### ISSUE TITLE
Feature proposal: `Session` can download from S3

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-python-sdk#1000]
Please fill out the form below.

### Describe the problem
sagemaker.session.Session has an `upload_data` method that allows users to upload a local file or directory to S3: https://github.com/aws/sagemaker-python-sdk/blob/6f3cf425e661fde79bbea1c855b4b298e1e4baa1/src/sagemaker/session.py#L137-L165

But there's no corresponding way to download files from using `Session` into a local directory. Training jobs put model artifacts in S3, and transform jobs put batch transform output in S3, and any job (or even an Endpoint) may output to S3 during its execution but right now, users have to use boto3 instead of `sagemaker_session`

### Proposal

Add `sagemaker.session.Session.download_data` with the following signature and behavior:

```python
def download_data(self, s3_uri, local_path):
    """Downloads data under an S3 prefix from an S3 URI into a local path or directory.

    Args:
        s3_uri (str): An S3 path. All objects under this prefix will be downloaded into the
          current directory.
        local_path (str): A local path. "." means the current directory. Directories will be
          created as needed.
    """
```

Thoughts / feedback on this proposal are welcome. Thanks!

**Comment by ChoiByungWook** [comment]
@andremoeller,

This looks good. Can you provide a small snippet/example of using the new method in a typical customer workflow? 

Thanks!

**Comment by andremoeller** [comment]
Sure:

Download a trained model. TF, for example, contains a TF SavedModel, which can be inspected for its signature.
```python
estimator.fit(..., wait=True)
# Downloads model.tar.gz into 'my/local/model_directory'
estimator.sagemaker_session.download_data(estimator.output_path, 'my/local/model_directory')
```

Download input and output from a transformed job and load it into a pandas DataFrame. This makes it easy to visualize model performance, do model evaluation, see how features affect, and combine input record indices with transform output (in case the model only gives predictions, and not record indices).
```python
def get_dataframe_from_csv_files(dir):
    csv_files = os.listdir(transform_out)
    dfs = (pd.read_csv(f) for f in all_files)
    return pd.concat(df_from_each_file, ignore_index=True)

transformer.transform(...)
transformer.wait()
# Downloads output from transformer's output path into 'transform_out'
transformer.sagemaker_session.download_data(transformer.output_path, 'transform_out')

# Read output into a pandas dataframe:
output df = get_dataframe_from_csv_files('transform_out')

# Download and read input into a pandas dataframe:
transformer.sagemaker_session.download_data('s3://input-bucket/csv/data', 'transform_in')
input_df = pd.read_csv('transform_in')

# Create one pandas DataFrame with input and output:
combined_df = pd.concat([input_df, output_df], axis=1) 
```

**Comment by laurenyu** [comment]
there is now an `S3Downloader` object that provides this functionality.
