### ISSUE TITLE
Performance issue regarding Sagemaker Estimator.deploy()

### ISSUE THREAD

**Issue by UniSabina** [aws/sagemaker-python-sdk#1006]
## System Information
- Python Version: 3.6
- CPU or GPU: CPU
- Python SDK Version: Anaconda

 ## Describe the problem
I'm quite new to the SageMaker algorithms and estimators so please bear with me.
I'm running a script very similar to this example script for DeepAR
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/deepar_electricity/DeepAR-Electricity.ipynb 
And want to start more than hundred of such training + prediction jobs.
The cell
```
predictor = estimator.deploy(
    initial_instance_count=1,
    instance_type='ml.m4.xlarge',
    predictor_cls=DeepARPredictor)
```
takes up 70% (~8.5min) of the time of the overall training and predicting job (~12min). Is there a possibility to reduce that time? What is the reason for this deploy job taking so long? 

Thanks!

**Comment by ChoiByungWook** [comment]
Hello @UniSabina,

Apologies on the slow experience.

I'll reach out to the team that handles the hosting platform and let them comment.

**Comment by amundv** [comment]
I'm also interested in this

**Comment by lexxx233** [comment]
Any update on this?

**Comment by rishabh1212** [comment]
Hii @ChoiByungWook,
Any update on this?

**Comment by nrapanos** [comment]
Is there any update on this? I'm experiencing a similar issue.

**Comment by dsow86** [comment]
Any update about this issue? I am still having the same problem, the model deployment take too long.

**Comment by zlufy90** [comment]
It is too slow for training and deploying model via SageMaker Studio. I just tested with Iris dataset. 
I do not think SageMaker is a good solution for us, at least until now, because of speed
