### ISSUE TITLE
Unable to update existing endpoint with newly trained model

### ISSUE THREAD

**Issue by OktayGardener** [aws/sagemaker-python-sdk#101]
Hello!

I am investigating the Sagemaker API for use in production (without notebooks). I am able to train a model, create an endpoint and delete the endpoint without any problems with the API. 

However, in a very common situation where I have a newly trained model on new data, I would like to be able to update/change the model that is currently serving in the specified endpoint and not have to update other services. In production, I would like to update the model serving without any downtime. 

Currently when I try to do this operation, simply train a new model and deploy to an endpoint using `deploy` with:

```
    def deploy(self):
        self.estimator.deploy(
                initial_instance_count=1000,
                instance_type=ml.c4.xlarge,
                endpoint_name="iris"
            )
```
I get the following error:
`botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateEndpoint operation: Cannot create already existing endpoint "arn:aws:sagemaker:eu-west-1:166488713907:endpoint/iris".`

Am I missing something here? Do I have to / can I do this operation manually with the boto3 api instead?

Thank you

**Comment by winstonaws** [comment]
Unfortunately, the feature for allowing you to update existing endpoints directly with .deploy is still on our backlog. We'll look again at its prioritization. In the meantime, you can try the workaround described in this issue: https://github.com/aws/sagemaker-python-sdk/issues/58

**Comment by ChoiByungWook** [comment]
This feature was added within this PR: #606. Updating the endpoint can be done by specifying update_endpoint to be True within the deploy method, usage case can be found here : [example](https://github.com/aws/sagemaker-python-sdk/blob/master/README.rst#using-estimators)

**Comment by ygcao** [comment]
@ChoiByungWook what is the availability impact for the in-place updating? And the example link is looking broken. Thanks!

**Comment by itsderek23** [comment]
I'm still seeing this error w/1.55.0 when trying to deploy a PyTorch Model:

```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateEndpointConfig operation: Cannot create already existing endpoint configuration
```

Example code:

```
pytorch_model = PyTorchModel(
        model_data = env.setting('model_data_path'),
        name = env.setting('model_name'),
        framework_version = '1.4.0',
        role = env.setting("aws_role"),
        env = {"DEPLOY_ENV": env.current_env()},
        entry_point = 'deploy/sagemaker/serve.py')

predictor = pytorch_model.deploy(
        instance_type = env.setting('instance_type'),
        update_endpoint = True,
        initial_instance_count = 1)
```

**Comment by laurenyu** [comment]
can you try specifying `endpoint_name` to be something else in the `deploy` call?

**Comment by itsderek23** [comment]
Hi @laurenyu - seems like I get the same error including a new `endpoint_name` in the call:

```py
predictor = pytorch_model.deploy(
        endpoint_name = env.setting('model_name')+"-1",
        instance_type = env.setting('instance_type'),
        update_endpoint = True,
        initial_instance_count = 1)
```

**Comment by laurenyu** [comment]
could you open a new issue in this repo? (sorry for the inconvenience, but it'll help with our internal tracking and making sure we respond)

**Comment by bkvsy** [comment]
update_endpoint is not working for me. It takes the name of the existing **model**, not the name of the **endpoint**.

`print('Endpoint name: {}'.format(rcf_inference.endpoint))
>>> Endpoint name: randomcutforest-2020-07-14-09-03-01-965`

My newest model name is 'randomcutforest-2020-07-14-10-18-45-146' though.

Error after new deployment:
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-31-9a97002d14ba> in <module>
     14     initial_instance_count=1,
     15     instance_type='ml.m5.xlarge',
---> 16     update_endpoint=True
     17 )
     18 rcf_inference.content_type = 'text/csv'

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, use_compiled_model, update_endpoint, wait, model_name, kms_key, data_capture_config, tags, **kwargs)
    718             wait=wait,
    719             kms_key=kms_key,
--> 720             data_capture_config=data_capture_config,
    721         )
    722 

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, update_endpoint, tags, kms_key, wait, data_capture_config)
    506             )
    507             self.sagemaker_session.update_endpoint(
--> 508                 self.endpoint_name, endpoint_config_name, wait=wait
    509             )
    510         else:

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/session.py in update_endpoint(self, endpoint_name, endpoint_config_name, wait)
   2443             raise ValueError(
   2444                 "Endpoint with name '{}' does not exist; please use an "
-> 2445                 "existing endpoint name".format(endpoint_name)
   2446             )
   2447 

ValueError: Endpoint with name 'randomcutforest-2020-07-14-10-18-45-146' does not exist; please use an existing endpoint name`

**Comment by hubtub2** [comment]
Still not working on my side. Same error as the original bug report, even when using update_endpoint = true. Did anyone open a new issue?
