### ISSUE TITLE
write_sparse_tensor_to_spmatrix

### ISSUE THREAD

**Issue by Jomonsugi** [aws/sagemaker-python-sdk#1023]
### System Information
- **Factorization Machine**:

I am successfully using the function `write_spmatrix_to_sparse_tensor` to transform my data from a sparse matrix to the recordio format expected by Sagemaker's factorization machine implementation. 

Example:
```
def write_recordio(array, y, prefix, f):
    # Convert to record protobuf
    buf = io.BytesIO()
    smac.write_spmatrix_to_sparse_tensor(array=array, file=buf, labels=y)
    buf.seek(0)
    
    fname = os.path.join(prefix, f)
    boto3.Session().resource('s3').Bucket('bucket').Object(fname).upload_fileobj(buf)
```
An example of `array` which are features:
```
  (0, 990290)	1.0
  (0, 1266265)	1.0
  (1, 560338)	1.0
  (1, 1266181)	1.0
  (2, 182872)	1.0
  (2, 1266205)	1.0
.................................
```
An example of `y` which is my target:
`[1. 2. 1. ... 3. 1. 5.]`

`write_spmatrix_to_sparse_tensor` does the job. After training my model, I then use Batch Transform to receive a `.out` file with many outputs of type `<class 'record_pb2.Record'>`
An example of one input and associated output record:
input:
```
features {
  key: "values"
  value {
    float32_tensor {
      values: 1.0
      values: 1.0
      keys: 990290
      keys: 1266265
      shape: 1266394
    }
  }
}
label {
  key: "values"
  value {
    float32_tensor {
      values: 1.0
    }
  }
}
```

output:
```
label {
  key: "score"
  value {
    float32_tensor {
      values: 1.5246734619140625
    }
  }
}
```

So now I have a file I originally wrote using `write_spmatrix_to_sparse_tensor` and an output from  `transformer.transform` and I would like the function `write_sparse_tensor_to_spmatrix` to exist for both of these files (my original recordio file used for training and the output `.out` file). I personally need to get back to my original parquet format as my data pull pipeline is parquet -> pandas -> sparse_matrix -> recordio and I need to reverse that process for evaluation and eventually deployment, but no matter what the use case it seems that users would frequently want to work back to their original format from both their input to the model and the output of batch transform and `write_sparse_tensor_to_spmatrix` would accomplish the task.

**Comment by laurenyu** [comment]
hi @Jomonsugi, just to make sure I'm understanding you correctly - are you looking for a way to have your batch transform results include the input as well? if so, I think this might work for you: https://aws.amazon.com/blogs/machine-learning/associating-prediction-results-with-input-data-using-amazon-sagemaker-batch-transform/

**Comment by Jomonsugi** [comment]
@laurenyu Thank you for pointing me to this tool. Although that is not the functionality I was asking for, it might be able to get me where I'd like to go which is back to my original format before converting to RecordIO for training. Factorization Machines require RecordIO for training and thus I continued with that format for inference passing `'application/x-recordio-protobuf'` to both the `accept` and `context_type` arguments when using batch transform. If I understand the functionality of batch transform, **when associating input to inference**, RecordIO is not supported. Are you suggesting I 1. train the model with RecordIO as is mandatory, then 2. for inference, pass data formatted as json (`'application/json'`) to both the `accept` and `context_type` statements when doing batch transform so I can associate input to inference? It is my understanding these arguments demand the same data type when using batch transform. Correct?

 If that is the suggested work flow, I could do that, however it forces me to format my input for batch transform into a different format than the model trained on (RecordIO). It would be most convenient if I could batch transform with `'application/x-recordio-protobuf'` as the `context_type`  and `'application/json'` to `accept`. 

What I was asking for originally is the ability to convert the output in RecordIO from batch transform back to the numpy sparse matrix format I started with before training, which is quite a different functionality than what is outlined above, however if I can get my batch transform results to include my input as you have suggested that should do the trick.

**Comment by laurenyu** [comment]
@Jomonsugi thanks for the clarification - I misread your original post then. I don't think we have any utility functions for converting from RecordIO back to a sparse matrix. My only suggestion there would be to look at the [code for `write_spmatrix_to_sparse_tensor`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/amazon/common.py#L166-L212) and see if you can do the opposite. I have opened an item for this in our internal backlog, which we're always reprioritizing based on feedback.

As for the potential workaround by associating transform inputs, I'm going to reach out to the team that owns the Factorization Machines algorithm to see if they have any advice. If there were a way to pass the inference data as JSON to be able to associate the outputs with the input, then it sounds like there's a way to make that workaround work.

**Comment by Jomonsugi** [comment]
Thanks for your response @laurenyu. So as not to conflate the feature request with the question, I would like to summarize for clarity.

**Feature request**
Because Sagemaker's factorization machine implementation requires RecordIO for training and there is a convenience function written to a sparse matrix into the required format I believe the following would be useful:
1. allow the same RecordIO format used in training to be used in batch transform where the output can include the associated input
2. a function that then reverses `write_spmatrix_to_sparse_tensor`, taking the output of batch transform and converting it back to sparse matrix format

**Question**
However, based on your input it seems like it might be possible that I do not need the above functionality if batch transform has the capability I need. This is where I would appreciate a response from the team that owns the Factorization Machines algorithm. Although I trained with RecordIO, if I can:
1. pass JSON to batch transform for both input and output on my trained model
2. associate the input with output as you suggested
I should be able to convert that output to my desired format (in fact this might make the batch transform step even easier for me since the format of my data for prediction starts with a Spark data frame which is easily converted into JSON).

**Comment by Jomonsugi** [comment]
@laurenyu Do you have any feedback for my question above yet? I am still struggling to successfully batch transform data using my trained FM model where the output includes associated data from my input. A best practice and an example of batch transform with a trained FM model would be useful. Because I will eventually want to convert my output to a spark data frame, 'application/jsonlines' would be most convenient, but I am eager to be given any batch transform example that successfully maps input data to inference on an FM model.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
