### ISSUE TITLE
Support for mxnet 1.5.0

### ISSUE THREAD

**Issue by mont-blanc** [aws/sagemaker-python-sdk#1047]
Reference: 0411635954

Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: MXNet 
- **Framework Version**: 1.5.0
- **Python Version**: 3.6.6
- **CPU or GPU**: GPU
- **Python SDK Version**: 1.38.4
- **Are you using a custom image**: No

### Describe the problem
mxnet 1.5.0 was released and sespecially supports more recent versions of numpy (=1.16.0)
https://github.com/apache/incubator-mxnet/releases/tag/1.5.0

It seems to be still unsupported by sagemaker yet though: https://github.com/aws/sagemaker-python-sdk#mxnet-sagemaker-estimators

Do you have an ETA on when it will be supported?

**Comment by yuanzhua** [comment]
Hello,

Thank you for reaching out. We are aware of the release of MXNet 1.5.0. Team is actively planning and working on the support. Unfortunately, we do not have an ETA to share at the moment.

**Comment by eric-haibin-lin** [comment]
Any update on this?

**Comment by ChuyangDeng** [comment]
Hi @eric-haibin-lin,

We do not have an ETA yet.

**Comment by leezu** [comment]
When do expect to announce ETA?

**Comment by leezu** [comment]
Some of the Gluon toolkits (https://github.com/aws/sagemaker-mxnet-container/issues/111) require recent version of MXNet. These issues may align

**Comment by surajkota** [comment]
Hi @mont-blanc @leezu @eric-haibin-lin , MXNet-1.6.0rc0 was released earlier this month with an upgraded numpy version>1.17, please let us know if it works for you and if this issue can be resolved.

We do not have an ETA for 1.5.0 yet.

**Comment by leezu** [comment]
MXNet 1.6.0rc0 contains release critical bugs. Please update to rc1.

**Comment by surajkota** [comment]
rc1 is not available yet and we do not have an ETA for 1.6.0 release at the moment

**Comment by saimidu** [comment]
MXNet 1.6.0 is supported on SageMaker: https://github.com/aws/sagemaker-python-sdk#mxnet-sagemaker-estimators
The version of MXNet used is up to date with https://github.com/apache/incubator-mxnet/releases/tag/1.6.0

**Comment by mont-blanc** [comment]
Excellent thanks a lot!
