### ISSUE TITLE
Import Tensorflow hub into AWS SageMaker

### ISSUE THREAD

**Issue by rv-ltran** [aws/sagemaker-python-sdk#1049]
How do I import tensorflow hub into AWS Sagemaker? I did the following comds, and receive the errors. I opened a conda-python3 jupyter notebook

I am looking to use this tensorflow hub module: https://tfhub.dev/google/universal-sentence-encoder/1

![1](https://user-images.githubusercontent.com/49695537/65244574-e148e800-dab8-11e9-805c-a9ebf3ade8f9.png)
![2](https://user-images.githubusercontent.com/49695537/65244575-e148e800-dab8-11e9-8a06-b8640f068dc1.png)
![3](https://user-images.githubusercontent.com/49695537/65244576-e1e17e80-dab8-11e9-8d53-6da8665e5d7f.png)

**Comment by ZhangHan** [comment]
conda_python3 doesn't have tensorflow installed. Please try the tensorflow_python3 notebook instead.

**Comment by ChoiByungWook** [comment]
Hello @rv-ltran,

Were you able to resolve your issue?

**Comment by rv-ltran** [comment]
Hi, I encounter another problem today with tensorflow version. It seems there was some forced change yesterday on tensorflow version. How do I make sure that I am importing tensorflow 1.14? 
I used '!pip install -U "tensorflow==1.14", then 'import tensorflow as tf'. However, version 2.1.0-dev20191010 was imported. See attached file.
![Screen Shot 2019-10-11 at 10 30 11 AM](https://user-images.githubusercontent.com/49695537/66659854-325c7f80-ec12-11e9-8c39-c3d596754425.png)

**Comment by neelamgehlot** [comment]
@rv-ltran 

SageMaker Notebook Instances already has tensorflow version 1.14.0 installed, could you restart your Notebook Instances so that all packages get refreshed.

Let us know if you are still facing any issue even after restarting the Notebook Instance.

**Comment by rv-ltran** [comment]
Thank you, restarting the Notebook instance works!

**Comment by ChoiByungWook** [comment]
Closing the issue, as it looks like @rv-ltran was able to resolve their issue.

Please reopen or open a new issue if you run into anymore problems.

Thanks!
