### ISSUE TITLE
Support for pytorch cli 

### ISSUE THREAD

**Issue by hyche** [aws/sagemaker-python-sdk#1068]
Please fill out the form below.

### System Information
- **Framework**: Pytorch
- **Framework Version**: 1.0, 1.1, 1.2
- **Python Version**: 3.6, 3.7
- **CPU or GPU**: both
- **Python SDK Version**: latest
- **Are you using a custom image**: No

### Describe the problem
Current sagemaker cli doesn't support Pytorch (only MxNet and Tensorflow are supported), any plan to support this ? I don't mind to contribute though.

**Comment by mvsusp** [comment]
Hi @hyche , unfortunately we don't have plans to support PyTorch in the CLI. Any contributions are welcome.

**Comment by laurenyu** [comment]
closing in preparation for #1476. we do have plans to release a revamped CLI in the future, and that will certainly include support for PyTorch.
