### ISSUE TITLE
List of docker containers

### ISSUE THREAD

**Issue by eric-haibin-lin** [aws/sagemaker-python-sdk#1077]
It's a bit hard to find the list of docker containers used by sagemaker sdk. 

Use case: 
I want to use the SDK but with a few additional dependencies (e.g. [gluonnlp](http://gluon-nlp.mxnet.io/)) on top of the container. 
I had to do `docker ps` to figure out that `763104351884.dkr.ecr.us-east-1.amazonaws.com/mxnet-inference:1.4.1-cpu-py3` is used when I deploy with `MXNetModel.deploy`, then I created a Dockerfile with 
```
FROM 763104351884.dkr.ecr.us-east-1.amazonaws.com/mxnet-inference:1.4.1-cpu-py3
RUN pip install ....
```
to add the extra dependencies, so that I can avoid building the `mxnet-inference` container from scratch. 
Would you consider putting a list of pre-built containers somewhere for users to search, when they need to just add extra dependencies on top of the existing ones?

**Comment by ChuyangDeng** [comment]
Hi @eric-haibin-lin,

Sorry for the confusion. Here's a list of framework containers and the corresponding accounts that you can use to quickly find out the docker image uri: https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html

**Comment by eric-haibin-lin** [comment]
Thank you very much! I missed that from the website.
