### ISSUE TITLE
np.int is int64 on many platforms, so why is np.int here ascribed int32 type?

### ISSUE THREAD

**Issue by jharrang** [aws/sagemaker-python-sdk#1079]
https://github.com/aws/sagemaker-python-sdk/blob/5bba5959a44116322ce99c23ecd158a2db999870/src/sagemaker/amazon/common.py#L281

Notably, this line causes code to fail if an expressly int32 type array is passed in to `write_numpy_to_dense_tensor()`, which seems wrong. Can someone help me understand the seeming type mismatch here?

Edit: Sorry, missed that np.int was platform-dependent per the docs: https://docs.scipy.org/doc/numpy-1.17.0/user/basics.types.html. That said, passing in an explicitly np.int32 array should probably be supported as well.

**Comment by ChuyangDeng** [comment]
Hi @jharrang, thanks for using SageMaker! This line of code was introduced 2 years ago and hasn't been changed since then. Since this is a small change, please feel to submit a PR and we will review it.

**Comment by ChoiByungWook** [comment]
Hello @jharrang,

What is the best way to support an explicitly passed np.int32 array?

What should we return for the `_resolve_type` function?

Thanks!

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
