### ISSUE TITLE
Edit neo docs to include currently supported target family

### ISSUE THREAD

**Issue by w601sxs** [aws/sagemaker-python-sdk#1088]
Reference: 0413599314

Current docs Should be updated to include:
'sbe_c', 'rk3399', 'deeplens', 'jetson_tx2', 'ml_c5', 'ml_p2', 'ml_m4', 'rasp3b', 'jetson_tx1', 'jetson_nano', 'ml_c4', 'ml_p3', 'rk3288', 'ml_m5'

for compile model API

Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Neo
- **Framework Version**:
- **Python Version**:2
- **CPU or GPU**:CPU
- **Python SDK Version**:
- **Are you using a custom image**:

### Describe the problem
Describe the problem or feature request clearly here.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by IvyBazan** [comment]
The documentation has been updated to link to the full list of available images: 
https://sagemaker.readthedocs.io/en/stable/api/inference/model.html#sagemaker.model.Model.compile
