### ISSUE TITLE
Add Tensorboard API to Pytorch

### ISSUE THREAD

**Issue by tanguycdls** [aws/sagemaker-python-sdk#1090]
Reference: MLFW-2707

Tensorboard API is attached to the tensorflow SDK while in reality it could work for Pytorch as well. We would need to make estimator not required in the api:
https://github.com/aws/sagemaker-python-sdk/blob/0e97997c88101b7f5603f0a8657e6f6a94d2784e/src/sagemaker/tensorflow/estimator.py#L56
and pass the path to the logdir we would write to in the local filesystem.

**Comment by ChoiByungWook** [comment]
Hello @tanguycdls,

Thank you for the awesome suggestion. I'll add this into our backlog, which we are always reprioritizing based on customer feedback.

Thanks!

**Comment by mmhealey1** [comment]
This would be so useful! I would value this feature immensely to improving my workflow and efficiency.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
