### ISSUE TITLE
How to obtain meta-information from bath transform job requests?

### ISSUE THREAD

**Issue by velociraptor111** [aws/sagemaker-python-sdk#1095]
I am running a batch transform job where it reads a bunch of images from an S3 repository.
Here is what my deployment code looks like 
```python
sagemaker_model = MXNetModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/yolo_object_person_detector.tar.gz',
                             role = role, 
                             entry_point = 'entry_point.py',
                             py_version='py3',
                             framework_version='1.4.1',
                            sagemaker_session = sagemaker_session)
transformer = sagemaker_model.transformer(instance_count=1, instance_type='ml.m4.xlarge', output_path=batch_output)
transformer.transform(data=batch_input, content_type='application/x-image')
```

How I can get information such as the image name on my entry_point file during runtime? I'm guessing this information is somewhat sent in the POST request to the model server however the input_data seems to be the stripped out version of the POST request, only containing bytes which holds the image values.

This is what the skeleton of my entry_point file looks like.
```python
def input_fn(input_data, content_type):
   ...
   if content_type == 'application/x-image':
        pil_object = Image.open(io.BytesIO(input_data))
        print(pil_object.filename) #RETURNS EMPTY
        np_img = np.array(pil_object)
        np_img = np_img[...,:3]
        mx_img = mx.nd.array(np_img)
        return data.transforms.presets.ssd.transform_test(mx_img,512)[0]
```

### EDIT
I need the image name because it contains a unique string identifier which will allow me to make a request to a different S3 storage storing certain meta-information required to make the current prediction.

Also, after further investigating and printing input_data in the input_fn , I am pretty sure that the built-in internal encoding function to convert images to bytes looks something like this, when it is reading the png files from S3 bucket and converting them to bytes to be sent as a HTTP request.
```python
with open("tennis.png", "rb") as image:
  f = image.read()
  b = bytearray(f)
```

Does this mean that the information like image name will be lost? How is it possible then to extract the image name?

**Comment by velociraptor111** [comment]
@ChoiByungWook any thoughts ?

**Comment by laurenyu** [comment]
hi @velociraptor111, unfortunately I don't think there's an out-of-the-box way to do this. I think you would need to find a way to encode the image name as part of your input.
