### ISSUE TITLE
How to increase maximum return size from Sagemaker batch transform

### ISSUE THREAD

**Issue by velociraptor111** [aws/sagemaker-python-sdk#1096]
As a result of another issue, I need to return a JSON which contains an image and also the prediction results. This would mean that the returning result from entry_point is a large JSON string. 

This is what my transform function looks like in entry_point:
```python
def transform_fn(model, request_body, content_type, accept_type):
    # Input Function    
    pil_object = Image.open(io.BytesIO(request_body))
    np_img = np.array(pil_object)
    np_img = np_img[...,:3]
    mx_img = mx.nd.array(np_img)
    x,img = data.transforms.presets.ssd.transform_test(mx_img,512)
    
    # Predict Function
    output = model(x)

    # Output Function
    return_list = []
    for list_element in output:
        return_list.append(list_element.asnumpy().tolist())

    return json.dumps({"image":img.tostring().decode('latin1'),"prediction": return_list})
```

As expected, I am running into some errors 
```
io.netty.handler.codec.CorruptedFrameException: Message size exceed limit: 6572143
```

Is it possible to increase the size of the return object?

**Comment by laurenyu** [comment]
sorry for the slow response here too. can you post the full stacktrace?

**Comment by ldong87** [comment]
I'm interested in this issue too. I'm trying to return a 768 dimensional vector for each record but got the same error. I already set max_payload to 1.

**Comment by laurenyu** [comment]
@ldong87 can you open a new issue?

**Comment by ldong87** [comment]
> @ldong87 can you open a new issue?

Thanks for the quick reply. Here is the new issue: https://github.com/aws/sagemaker-python-sdk/issues/1882
