### ISSUE TITLE
Batch Transform reading input from OUTPUT source BUG

### ISSUE THREAD

**Issue by velociraptor111** [aws/sagemaker-python-sdk#1106]
I'm facing this extremely weird issue where the batch transform job **Sometimes reads input FROM output destination**.

This is how I am using batch transform:
```python
import sagemaker
from sagemaker.mxnet.model import MXNetModel
from sagemaker import get_execution_role

sagemaker_session = sagemaker.Session()
bucket = sagemaker_session.default_bucket()
role = get_execution_role()

batch_input = 's3://{}/test_output'.format(bucket) 
batch_output = 's3://{}/test_output_pose'.format(bucket) 

sagemaker_model = MXNetModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/simple_pose_resnet50_v1d.tar.gz',
                             role = role, 
                             entry_point = 'entry_point_pose.py',
                             py_version='py3',
                             framework_version='1.4.1',
                            sagemaker_session = sagemaker_session)

transformer = sagemaker_model.transformer(instance_count=1, instance_type='ml.m4.xlarge', output_path=batch_output)

transformer.transform(data=batch_input, content_type='application/json')

transformer.wait()
```

I have 6 different simple text file located in my S3 bucket input where they have content like this:
```
{"bucket_id": "f7e03aee-492b-44aa-9a06-c4680a7c6432"}
```

This is what my entry_point file looks like 
```python
def transform_fn(model, request_body, content_type, accept_type):
    print("Inside transform function")
    print(request_body)    
    print(type(request_body))
    ...
```

I noticed from my error logs on CloudWatch that the function is being invoked 24 times. Whereas I only have 6 files in my batch_input location. EVEN more weirdly, 18 out of those 24 calls contain input where it was reading the JSON file from my OUTPUT location.

How do I fix this?

**EDIT**
It may also be worth noting that in my transform function I am downloading an S3 file like so.
```python
client_s3 = boto3.client(
                        's3',
                         aws_access_key_id='xxx'
                         ,aws_secret_access_key='xxx'
    )

..
with open(temporary_file_name_img, 'wb') as data:
        client_s3.download_fileobj(bucket_name, file_name, data)
```

I am not sure if this could somehow impact the server model running in the backend.

**Comment by laurenyu** [comment]
Does the problem persist if you use a value for `batch_output` where `batch_input` is not a substring of `batch_output`? According to the documentation:

>  Amazon SageMaker uses all objects with the specified key name prefix for batch transform.

Since S3 doesn't have a notion of a directory, my guess is that "test_output_pose" matches against the prefix "test_output".

If changing the S3 locations isn't possible, maybe try using a manifest file instead?

reference: https://docs.aws.amazon.com/sagemaker/latest/dg/API_TransformS3DataSource.html

**Comment by velociraptor111** [comment]
Thanks for the answer.

I can confirm that this works.
