### ISSUE TITLE
PyTorch 1.2 support

### ISSUE THREAD

**Issue by ksanjeevan** [aws/sagemaker-python-sdk#1111]
I'm finding some conflicting documentation on what PyTorch versions are supported. Is 1.2.0 on of them? I says so [here](https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/pytorch#sagemaker-pytorch-docker-containers) but I can't find anywhere what the ECR image name is, i.e. `<>dkr.ecr.<>.amazonaws.com/sagemaker-pytorch:1.1.0-cpu-py3` changing just the version doesn't seem to work.

@ChoiByungWook

**Comment by laurenyu** [comment]
Starting with PyTorch 1.2, the URIs have changed:
* training: `763104351884.dkr.ecr.<region>.amazonaws.com/pytorch-training:1.2.0-cpu-py3`
* serving: `763104351884.dkr.ecr.<region>.amazonaws.com/pytorch-inference:1.2.0-cpu-py3`

(replace "cpu" and "py3" as appropriate)

reference: https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-containers-frameworks-deep-learning.html

**Comment by ksanjeevan** [comment]
Oh great, thanks @laurenyu! Just a quick question, what's the difference between the training image and the inference one? We are currently using the same image for both cases and was curious about the distinction...

**Comment by laurenyu** [comment]
the training image is used for training a model (SageMaker Training and Hyperparameter Tuning Jobs) while the inference one is used for making predictions with your model (SageMaker Endpoints and Batch Transform Jobs). Version 1.2 was the beginning of using two different images for PyTorch; the previous PyTorch images had both sets of functionality in a single image.

**Comment by ksanjeevan** [comment]
Right, but are there any major package differences between the two? We're using the sagemaker python sdk for training and inference, will deploying models for inference with the training image cause any problems?

**Comment by laurenyu** [comment]
Ah, I see what you're asking. Here are the source files if you want to take a look yourself:
* training: https://github.com/aws/sagemaker-pytorch-container
* inference: https://github.com/aws/sagemaker-pytorch-serving-container

Each image, in addition to some dependencies, will respond differently to the Docker commands used by SageMaker. In particular, the training image responds to "train" and will set up for distributed training before calling the entry script (as a runnable script).

The inference image, on the other hand, responds to "serve" and will start up a model server before calling the serving functions in the entry script (`model_fn`, etc.) to serve predictions.

**Comment by ksanjeevan** [comment]
Gotcha! Yeah that's what I was looking for. Thanks for the quick responses!
