### ISSUE TITLE
Support for bleeding edge versions of Tensorflow

### ISSUE THREAD

**Issue by durandg12** [aws/sagemaker-python-sdk#1115]
Hi,

I am thinking about using SageMaker for research purposes and I need to use the latest tools released with the last version of TF.

Yet, TensorFlow 2.0.0 has been released [more than 1 month ago](https://github.com/tensorflow/tensorflow/releases/tag/v2.0.0) and it seems that there is still no support for it. 

So I wonder : what is the timeframe of AWS for releasing the newer versions of the most popular Deep Learning frameworks?

Knowing that the delay can be as long as a month makes me worry about using SageMaker at all.

As a side note (I don't need it, but it should also be noted), TensorFlow 1.15.0 has been released [20 days ago](https://github.com/tensorflow/tensorflow/releases/tag/v1.15.0) and Pytorch 1.3.0 has been released [nearly one month ago](https://github.com/pytorch/pytorch/releases/tag/v1.3.0) and they also seem missing from the supported frameworks.

**Comment by anankira** [comment]
Thank you for your interest ! We plan to add support for Pytorch 1.3. Stay tuned!

**Comment by la-cruche** [comment]
@durandg12 in the meantime you can also create a container with the dependencies of your choice? the `sagemaker-containers` package features a demo of how to create a TF2.0 container https://github.com/aws/sagemaker-containers#creating-a-container-using-sagemaker-containers

**Comment by durandg12** [comment]
I am already doing that, given that I can't do otherwise with SageMaker.

As a side note, the example in the link you provided uses tf2.0.0-alpha0 instead of tf2.0.0.

**Comment by surajkota** [comment]
@durandg12, Thank you for using Sagemaker
Tensorflow-1.15 and Pytorch-1.3 were released earlier this month. Tensorflow-2.0 containers have also been released today.

**Comment by durandg12** [comment]
@surajkota thank you. May I ask why:

- no Dockerfile for TF 2.0.0 can be found at [https://github.com/aws/sagemaker-tensorflow-container/tree/master/docker](https://github.com/aws/sagemaker-tensorflow-container/tree/master/docker) ?
- the version of tensorflow used in the notebook of a SageMaker notebook instance used with the conda_tensorflow_p36 kernel is still TF 1.14.0 ?

Do I have to open new issues on this ? Especially since upgrading to TF 2.0.0 is not possible from the notebook, running `! pip install -U tensorflow` throws
```
Requirement already up-to-date: tensorflow in /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages (1.14.0)
```
