### ISSUE TITLE
Can't pip install sagemaker on OSX / Anaconda: ERROR: Cannot uninstall 'PyYAML'

### ISSUE THREAD

**Issue by marianokamp** [aws/sagemaker-python-sdk#1117]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: None
- **Framework Version**: None
- **Python Version**: 3.7 / Conda 4.7.12
- **CPU or GPU**: CPU
- **Python SDK Version**: latest
- **Are you using a custom image**: No

### Describe the problem
Cannot use/install the SageMaker SDK locally on OSX Mojave (10.14.6). 

### Minimal repro / logs
See below steps to reproduce, starting from a clean install of Anaconda on a Mac that I just redid to start from a clean slate. I also created a clean conda environment to make it easy to reproduce this issue.

- **Exact command to reproduce**:

conda create -y -n sm_test python=3.7 anaconda
conda activate sm_test
jupyter notebook

# In the browser then:

(New Notebook (Python3))

!pip install sagemaker
# Ends in: 
[..]
**ERROR**: jupyterlab-server 1.0.6 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.
Installing collected packages: invoke, pynacl, bcrypt, paramiko, fabric, jmespath, python-dateutil, botocore, s3transfer, boto3, protobuf, jsonschema, PyYAML, cached-property, texttable, idna, requests, docker-pycreds, websocket-client, docker, docopt, dockerpty, docker-compose, protobuf3-to-dict, sagemaker
  Found existing installation: python-dateutil 2.8.1
    Uninstalling python-dateutil-2.8.1:
      Successfully uninstalled python-dateutil-2.8.1
  Found existing installation: jsonschema 3.1.1
    Uninstalling jsonschema-3.1.1:
      Successfully uninstalled jsonschema-3.1.1
  Found existing installation: PyYAML 5.1.2
**ERROR:** Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

# As you can see there are two errors. The earlier one can be resolved by doing the steps from below, but the second one (PyYAML) remains.

!pip install -U botocore
!pip install sagemaker

# Still leaves me with this:

Installing collected packages: protobuf3-to-dict, idna, requests, websocket-client, PyYAML, docopt, cached-property, dockerpty, texttable, docker-pycreds, docker, docker-compose, sagemaker
  Found existing installation: idna 2.8
    Uninstalling idna-2.8:
      Successfully uninstalled idna-2.8
  Found existing installation: requests 2.22.0
    Uninstalling requests-2.22.0:
      Successfully uninstalled requests-2.22.0
  Found existing installation: PyYAML 5.1.2
**ERROR**: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by marianokamp** [comment]
FWIW I also tried with a clean Python on OSX, but got a similar error:

`mkamp@xxx  ~  pip install sagemaker
Collecting sagemaker
Requirement already satisfied: scipy>=0.19.0 in ./opt/anaconda3/lib/python3.7/site-packages (from sagemaker) (1.3.1)
Collecting requests<2.21,>=2.20.0 (from sagemaker)
  Using cached https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl
Requirement already satisfied: urllib3<1.25,>=1.21 in ./opt/anaconda3/lib/python3.7/site-packages (from sagemaker) (1.24.2)
Collecting protobuf>=3.1 (from sagemaker)
  Using cached https://files.pythonhosted.org/packages/a5/c6/a8b6a74ab1e165f0aaa673a46f5c895af8780976880c98934ae82060356d/protobuf-3.10.0-cp37-cp37m-macosx_10_9_intel.whl
Collecting boto3>=1.9.213 (from sagemaker)
  Downloading https://files.pythonhosted.org/packages/c0/c6/aa0670205b43a98029a2886d3a16155a48d6c91a5f477e7554c739da963e/boto3-1.10.16-py2.py3-none-any.whl (128kB)
     |████████████████████████████████| 133kB 297kB/s
Requirement already satisfied: numpy>=1.9.0 in ./opt/anaconda3/lib/python3.7/site-packages (from sagemaker) (1.17.2)
Collecting fabric>=2.0 (from sagemaker)
  Using cached https://files.pythonhosted.org/packages/d7/cb/47feeb00dae857f0fbd1153a61e902e54ed77ccdc578b371a514a3959a19/fabric-2.5.0-py2.py3-none-any.whl
Collecting protobuf3-to-dict>=0.1.5 (from sagemaker)
Collecting docker-compose>=1.23.0 (from sagemaker)
  Using cached https://files.pythonhosted.org/packages/dd/e6/1521d1dfd9c0da1d1863b18e592d91c3df222e55f258b9876fa1e59bc4b5/docker_compose-1.24.1-py2.py3-none-any.whl
Collecting idna<2.8,>=2.5 (from requests<2.21,>=2.20.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/4b/2a/0276479a4b3caeb8a8c1af2f8e4355746a97fab05a372e4a2c6a6b876165/idna-2.7-py2.py3-none-any.whl
Requirement already satisfied: certifi>=2017.4.17 in ./opt/anaconda3/lib/python3.7/site-packages (from requests<2.21,>=2.20.0->sagemaker) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./opt/anaconda3/lib/python3.7/site-packages (from requests<2.21,>=2.20.0->sagemaker) (3.0.4)
Requirement already satisfied: six>=1.9 in ./opt/anaconda3/lib/python3.7/site-packages (from protobuf>=3.1->sagemaker) (1.12.0)
Requirement already satisfied: setuptools in ./opt/anaconda3/lib/python3.7/site-packages (from protobuf>=3.1->sagemaker) (41.4.0)
Collecting s3transfer<0.3.0,>=0.2.0 (from boto3>=1.9.213->sagemaker)
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1 (from boto3>=1.9.213->sagemaker)
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting botocore<1.14.0,>=1.13.16 (from boto3>=1.9.213->sagemaker)
  Downloading https://files.pythonhosted.org/packages/f4/00/4516c82f36f6b53053b0e28513cb673f462c5b969a9e7bb5e51b5627fe08/botocore-1.13.16-py2.py3-none-any.whl (5.4MB)
     |████████████████████████████████| 5.4MB 5.8MB/s
Collecting paramiko>=2.4 (from fabric>=2.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/4b/80/74dace9e48b0ef923633dfb5e48798f58a168e4734bca8ecfaf839ba051a/paramiko-2.6.0-py2.py3-none-any.whl
Collecting invoke<2.0,>=1.3 (from fabric>=2.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/d9/7c/68e99f659749dbf3349ce72e2e9b581f644b8482121d92ab604145ad01ac/invoke-1.3.0-py3-none-any.whl
Collecting websocket-client<1.0,>=0.32.0 (from docker-compose>=1.23.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl
Collecting dockerpty<0.5,>=0.4.1 (from docker-compose>=1.23.0->sagemaker)
Collecting jsonschema<3,>=2.5.1 (from docker-compose>=1.23.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/77/de/47e35a97b2b05c2fadbec67d44cfcdcd09b8086951b331d82de90d2912da/jsonschema-2.6.0-py2.py3-none-any.whl
Collecting PyYAML<4.3,>=3.10 (from docker-compose>=1.23.0->sagemaker)
Collecting texttable<0.10,>=0.9.0 (from docker-compose>=1.23.0->sagemaker)
Collecting docopt<0.7,>=0.6.1 (from docker-compose>=1.23.0->sagemaker)
Collecting docker[ssh]<4.0,>=3.7.0 (from docker-compose>=1.23.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/09/da/7cc7ecdcd01145e9924a8ccbe9c1baf3a362fc75d4cb150676eb5231ea60/docker-3.7.3-py2.py3-none-any.whl
Collecting cached-property<2,>=1.2.0 (from docker-compose>=1.23.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/3b/86/85c1be2e8db9e13ef9a350aecd6dea292bd612fa288c2f40d035bb750ded/cached_property-1.5.1-py2.py3-none-any.whl
Requirement already satisfied: python-dateutil<2.8.1,>=2.1; python_version >= "2.7" in ./opt/anaconda3/lib/python3.7/site-packages (from botocore<1.14.0,>=1.13.16->boto3>=1.9.213->sagemaker) (2.8.0)
Requirement already satisfied: docutils<0.16,>=0.10 in ./opt/anaconda3/lib/python3.7/site-packages (from botocore<1.14.0,>=1.13.16->boto3>=1.9.213->sagemaker) (0.15.2)
Collecting bcrypt>=3.1.3 (from paramiko>=2.4->fabric>=2.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/62/20/4c94f3f8dfc6b8720c8bc903ce2951ec6397ad864e3a64b4abdced014514/bcrypt-3.1.7-cp34-abi3-macosx_10_6_intel.whl
Requirement already satisfied: cryptography>=2.5 in ./opt/anaconda3/lib/python3.7/site-packages (from paramiko>=2.4->fabric>=2.0->sagemaker) (2.7)
Collecting pynacl>=1.0.1 (from paramiko>=2.4->fabric>=2.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/cd/c9/4d6deea9d900345b1243cc3e6265110697fae5e594689cfa1ba34e0ef4a8/PyNaCl-1.3.0-cp34-abi3-macosx_10_6_intel.whl
Collecting docker-pycreds>=0.4.0 (from docker[ssh]<4.0,>=3.7.0->docker-compose>=1.23.0->sagemaker)
  Using cached https://files.pythonhosted.org/packages/f5/e8/f6bd1eee09314e7e6dee49cbe2c5e22314ccdb38db16c9fc72d2fa80d054/docker_pycreds-0.4.0-py2.py3-none-any.whl
Requirement already satisfied: cffi>=1.1 in ./opt/anaconda3/lib/python3.7/site-packages (from bcrypt>=3.1.3->paramiko>=2.4->fabric>=2.0->sagemaker) (1.12.3)
Requirement already satisfied: asn1crypto>=0.21.0 in ./opt/anaconda3/lib/python3.7/site-packages (from cryptography>=2.5->paramiko>=2.4->fabric>=2.0->sagemaker) (1.0.1)
Requirement already satisfied: pycparser in ./opt/anaconda3/lib/python3.7/site-packages (from cffi>=1.1->bcrypt>=3.1.3->paramiko>=2.4->fabric>=2.0->sagemaker) (2.19)
ERROR: jupyterlab-server 1.0.6 has requirement jsonschema>=3.0.1, but you'll have jsonschema 2.6.0 which is incompatible.
Installing collected packages: idna, requests, protobuf, jmespath, botocore, s3transfer, boto3, bcrypt, pynacl, paramiko, invoke, fabric, protobuf3-to-dict, websocket-client, dockerpty, jsonschema, PyYAML, texttable, docopt, docker-pycreds, docker, cached-property, docker-compose, sagemaker
  Found existing installation: idna 2.8
    Uninstalling idna-2.8:
      Successfully uninstalled idna-2.8
  Found existing installation: requests 2.22.0
    Uninstalling requests-2.22.0:
      Successfully uninstalled requests-2.22.0
  Found existing installation: jsonschema 3.0.2
    Uninstalling jsonschema-3.0.2:
      Successfully uninstalled jsonschema-3.0.2
  Found existing installation: PyYAML 5.1.2
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.`

**Comment by laurenyu** [comment]
Sorry for the slow response here. The error message comes from pip 10, which won't uninstall distutills projects, unlike previous versions of pip: https://github.com/pypa/pip/issues/5247

Workarounds include:
* using `--ignore-installed` with the pip install command
* doing a `conda remove PyYAML` before launching the notebook
* manually removing PyYAML from site-packages

**Comment by marianokamp** [comment]
Hey Lauren.

Thanks. This was quite rocky for me. At the end it worked for to remove the site-packages and then use the following in a Jupyter Notebook using a Python 3 kernel to install the sagemaker libraries and friends.

~/opt/anaconda3/envs/sm_test/lib/python3.7/site-packages> rm -rf PyYAML-3.13.dist-info

!pip install sagemaker -U pandas botocore boto3 awscli 'jsonschema==2.5.1'

Thanks for your help.

I am not dead set on using conda. If you have a better suggestion for a Mac user I am happy to explore that alternative route.

**Comment by laurenyu** [comment]
glad you were able to make it work! Personally, I use virtualenv (also on Mojave 10.14.6), but I haven't used conda enough to be able to properly compare the two.
