### ISSUE TITLE
Deploy method doesn't work if "tags" attribute is supplied

### ISSUE THREAD

**Issue by svpino** [aws/sagemaker-python-sdk#1120]
Please fill out the form below.

### System Information
- sagemaker lib version 1.43.4.post1
- Using object detection sample notebook.

### Describe the problem
When supplying the `tags` attribute to the deploy function of a model, an error is displayed.

Here is the relevant code:
```
object_detector = od_model.deploy(
    initial_instance_count = 1, 
    instance_type = 'ml.m4.xlarge'
    tags = [{
        "TagName": "TagValue"
    }])
```

Error message:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-63-da1a1683e6f2> in <module>()
      3     instance_type = 'ml.m4.xlarge',
      4     tags = [{
----> 5         "TagName": "TagValue"
      6     }])
      7 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, accelerator_type, endpoint_name, use_compiled_model, update_endpoint, wait, model_name, kms_key, **kwargs)
    549         else:
    550             kwargs["model_kms_key"] = self.output_kms_key
--> 551             model = self.create_model(**kwargs)
    552         model.name = model_name
    553         return model.deploy(

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in create_model(self, role, image, predictor_cls, serializer, deserializer, content_type, accept, vpc_config_override, **kwargs)
   1176             predictor_cls=predictor_cls,
   1177             enable_network_isolation=self.enable_network_isolation(),
-> 1178             **kwargs
   1179         )
   1180 

TypeError: __init__() got an unexpected keyword argument 'tags'
```

**Comment by ChoiByungWook** [comment]
Hello @svpino,

Apologies for the late response.

Thank you for bringing this issue up to us.

I will first attempt to reproduce the error that you are seeing and will report ASAP.

Thank you!

**Comment by ChoiByungWook** [comment]
I was able to reproduce the issue. Seems like the issue is that `tags` is being supported in the deploy method through `kwargs`, which will run into problems depending on the implementation of the create_model function. To mitigate this, I will add a keyword argument for `tags`, which is similar to the `deploy` method for our `Model` class.

**Comment by ChoiByungWook** [comment]
The change has been released. Please reopen if there are any other issues! Thanks!
