### ISSUE TITLE
Question: is is possible to specify the variant_name when we deploy a Model

### ISSUE THREAD

**Issue by anotinelg** [aws/sagemaker-python-sdk#1122]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: mxnet
- **Framework Version**:
1.42.1.dev0
- **Python Version**:
- **CPU or GPU**:
- **Python SDK Version**:
- **Are you using a custom image**:

### Describe the problem
I need to specify the variant_name when I deploy a model:

in sagemaker/models.py, there is no possibility to specify the variant_name. the default AllTraffic will be used!
```
class Model(object):
   def deploy(
        self,
        initial_instance_count,
        instance_type,
        accelerator_type=None,
        endpoint_name=None,
        update_endpoint=False,
        tags=None,
        kms_key=None,
        wait=True,
    ):
    ...
    self._create_sagemaker_model(instance_type, accelerator_type, tags)
        production_variant = sagemaker.production_variant(
            self.name, instance_type, initial_instance_count, accelerator_type=accelerator_type
        )
    ...
```

It would not be too much trouble adding an input to the deploy:

```
 def deploy(
        self,
        initial_instance_count,
        instance_type,
        accelerator_type=None,
        endpoint_name=None,
        variant_name="AllTraffic"
        update_endpoint=False,
        tags=None,
        kms_key=None,
        wait=True,
    ):
```

in the same way, would it be possible to parametric the weight of the new model (especially if it is an update process

**Comment by anotinelg** [comment]
Would it be an acceptable PullRequest?

**Comment by laurenyu** [comment]
sorry for the slow response. if you want to submit a pull request, go for it!

**Comment by akrishna1995** [comment]
Closing based on the comment above. Please feel free to reopen if there are any more feedback. Thanks
