### ISSUE TITLE
Question: updating endpoint with scaling policy

### ISSUE THREAD

**Issue by anotinelg** [aws/sagemaker-python-sdk#1123]
Reference: MLFW-2728

Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
- **Framework Version**:
1.4.2.dev0
- **Python Version**:
- **CPU or GPU**:
- **Python SDK Version**:
- **Are you using a custom image**:

### Describe the problem
I need to update endpoint which are currently in production with scaling policy on. I need to follow the best guidelines from AWS: https://docs.aws.amazon.com/sagemaker/latest/dg/endpoint-auto-scaling-considerations.html

The MXNetModel.deploy function can not handle that case. Is it something in Roadmap, or does a PR would be accepted for that?

**Comment by ChuyangDeng** [comment]
Hi @anotinelg, thanks for using SageMaker.

Our `Model` class dose not support update endpoint with `deploy()` method, but our `Estimator` class does.

Is it possible for you to `attach` the completed training job and update the endpoint through estimator's `deploy()` method?

attach: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1590

deploy: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L474

**Comment by ChoiByungWook** [comment]
Hello @anotinelg,

Apologies for the late response.

Unfortunately, support for using auto scaling policies in SageMaker isn't supported in the Python SDK. I have created a backlog item to track this. Our backlog is constantly reprioritized based on customer feedback.

While not ideal, it is possible to utilize boto3 to support updating endpoints with scaling policy. This can be seen here: https://docs.aws.amazon.com/sagemaker/latest/dg/endpoint-auto-scaling-add-policy.html#endpoint-auto-scaling-add-code

Please let me know if there is anything I can clarify.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
