### ISSUE TITLE
No KMS Key support 

### ISSUE THREAD

**Issue by samlovestech** [aws/sagemaker-python-sdk#1124]
Reference: MLFW-2727

https://github.com/aws/sagemaker-python-sdk/blob/3d82d8f75bc841bc7f31097208854e1c76fc8330/src/sagemaker/model.py#L779

If the SageMaker bucket requires KMS key for all putObjects, this framework entry_point will not be ALLOWED to push to this bucket.

**Comment by ChoiByungWook** [comment]
Hello @Seninus,

Apologies for the late response.

Thank you for bringing this to our attention. I have created an internal ticket in our backlog, which is always reprioritized based on customer feedback. I will speak with the team on how to prioritize for this.

Thanks!

Apologies

**Comment by ChoiByungWook** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/2005

**Comment by akrishna1995** [comment]
Thanks for raising this issue! It has been addressed in this [PR](https://github.com/aws/sagemaker-python-sdk/pull/3784) and all PySDK versions >=v2.151.0 now support KMS key for Model registration.
