### ISSUE TITLE
GPU utilization is always zero when doing inference

### ISSUE THREAD

**Issue by Andreachen0707** [aws/sagemaker-python-sdk#1127]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: tensorflow
- **Framework Version**: 1.14
- **Python Version**: 3
- **CPU or GPU**: GPU
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem
Describe the problem or feature request clearly here.
I'm deploying my pre-trained model through endpoint using the pre-built image for tensorflow inference: 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:1.14-gpu. Since the inference time is longer than my expectation, I check the log and find the gpu utilization is almost always zero when doing inference when sometime it would jump to 1.3%. Is there some way to identify whether the container is using GPU or not? GPU memory usage stays around 97% which I think is tensorflow pre-alloc.

Model I'm using: SSD-inception
Instance I'm using: g4dn.xlarge

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

<img width="1563" alt="Screen Shot 2019-11-19 at 2 24 18 PM" src="https://user-images.githubusercontent.com/27985923/69187658-49777280-0ad8-11ea-894d-2a50df9cade9.png">

- **Exact command to reproduce**:

**Comment by Andreachen0707** [comment]
Sorry for the confusion. It is supposed to be around 0% given I'm doing single image inference.

**Comment by Andreachen0707** [comment]
> Sorry for the confusion. It is supposed to be around 0% given I'm doing single image inference.

Well, turns out it should not be true. I did tests through notebook instance with p2.xlarge. When continuously make predictions, the gpu util does go up, up to 50% at least. It is still weird why deploying through endpoint it lost the gpu utilization. Could there be any setting I'm missing when deploy an endpoint? I was following the example notebook in sagemaker to deploy.

**Comment by ChuyangDeng** [comment]
> > Sorry for the confusion. It is supposed to be around 0% given I'm doing single image inference.
> 
> Well, turns out it should not be true. I did tests through notebook instance with p2.xlarge. When continuously make predictions, the gpu util does go up, up to 50% at least. It is still weird why deploying through endpoint it lost the gpu utilization. Could there be any setting I'm missing when deploy an endpoint? I was following the example notebook in sagemaker to deploy.

What do you mean by "through notebook instance" and "deploying through endpoint"?

If "deploying through endpoint" means using your own code, can you share more details so we can re-produce and debug?

**Comment by Andreachen0707** [comment]
Hi Chuyang,
Thank you for getting back to me.
So 'through notebook instance' -> TensorFlow serving has a command line that allows using localhost to deploy. 
'deploying through endpoint' -> using sagemaker host endpoint and sagemaker prebuilt tensorflow-inference-gpu docker image.
I guess my question should be, would there be a better way to monitor endpoint GPU utilization, other than using cloudwatch?

**Comment by ChuyangDeng** [comment]
Hi @Andreachen0707, if you do not want to use CloudWatch, you can try NVIDIA System Management Interface (https://developer.nvidia.com/nvidia-system-management-interface) to monitor your GPU utilization.

**Comment by satishlokkoju** [comment]
@Andreachen0707  How did you go about solving this issue ?  I am using 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:**1.13**-gpu base image and GPUUtilization is **always** zero.

**Comment by Andreachen0707** [comment]
> @Andreachen0707 How did you go about solving this issue ? I am using 763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-inference:**1.13**-gpu base image and GPUUtilization is **always** zero.

Hi @satishlokkoju , my problem turned out to be a little bit different. I was making inference on one image at a time, which is the reason why the GPU utilization is always low. If you do batch processing, there should be a noticeable difference. Also, one thing that could affect the plot is the period you are monitoring. When I was monitoring the GPU utilization locally, I was using 0.2s period, which means it will be more accurate. However, AWS cloudwatch has a minimum of 1 second and somehow even if I change it to 1 second I'm still seeing a period of 1min. If you do have GPU locally, I suggest you do some test locally first and compare the performance, so you have a rough guess in mind. As long as you see it is using GPU(i.e. speedwise it is using GPU or it shows it has connected to GPU in the log), it should be fine.

**Comment by costefan** [comment]
still having an issue with that, 
I have an endpoint, image is custom, tf-gpu 1.14, 
Gpu memory is full (pre allocation) 
But still gpu usage when doing inference is 0

The same configuration on cpu-only machine works fine (having tf 1.14) 
what are the necessary dependencies from this base image? 
I mean,I have cuda image, everything looks good, pretty-much the same image works on google cloud

**Comment by LiJell** [comment]
> still having an issue with that, I have an endpoint, image is custom, tf-gpu 1.14, Gpu memory is full (pre allocation) But still gpu usage when doing inference is 0
> 
> The same configuration on cpu-only machine works fine (having tf 1.14) what are the necessary dependencies from this base image? I mean,I have cuda image, everything looks good, pretty-much the same image works on google cloud

did you solve the problem? I do have a same problem. Moreover, GPU memory always be increased as every request.

**Comment by ChristosCh00** [comment]
same here.
any solutions?
