### ISSUE TITLE
Bert Model Error. While invoking the Endpoint.

### ISSUE THREAD

**Issue by hegebharat** [aws/sagemaker-python-sdk#1132]
### System Information
- **Framework (e.g. TensorFlow) 
- **Framework Version**: 1.15.0
- **Python Version**:3.5
- **CPU or GPU**: CPU
- **Python SDK Version**:
- **Are you using a custom image**:

### Describe the problem
I trained the bert model  in the SageMaker. Also I have created the endpoint. But when try to predict using endpoint is is throwing ModelError as mentioned below.
My model requires multiple inputs.
Input to  the model is of form
{
        'input_ids': np.array(input_ids).reshape(-1, max_seq_length).tolist(),
        'input_mask': np.array(input_mask).reshape(-1, max_seq_length).tolist(),
  
        'segment_ids': np.array(segment_ids).reshape(-1, max_seq_length).tolist(),
  }

But when I pass this input to the endpoint config , it is throwing error.
Code is as follows::
bert.fit(inputs)
bert_predictor = bert.deploy(initial_instance_count=1, instance_type='ml.t2.large')
bert_predictor.predict(data)

where data is a dict.
data={
        'input_ids': np.array(input_ids).reshape(-1, max_seq_length).tolist(),
        'input_mask': np.array(input_mask).reshape(-1, max_seq_length).tolist(),
        'segment_ids': np.array(segment_ids).reshape(-1, max_seq_length).tolist(),
    }

### Minimal repro / logs
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from model with message "{ "error": "Failed to process element: 0 of 'instances' list. JSON object: {\n    \"input_ids\": [\n        [\n            101,\n            1290,\n            21146,\n            7777,\n            14298,\n            6334,\n            7409,\n            2723,\n            1110,\n            1126,\n            7808,\n            3903,\n            2848,\n            15644,\n            16219,\n            3677,\n            1105,\n            1144,\n            1136,\n            1151,\n            2628,\n            1114,\n            170,\n            19515,\n            117,\n            1122,\n            1110,\n            1103,\n            6349,\n            137,\n            3850,\n            109,\n            1111,\n            137,\n            14255,\n            1181,\n            109,\n            1219,\n            10203,\n            119,\n            102,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0\n        ]\n    ],\n    \"input_mask\": [\n        [\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            1,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0\n        ]\n    ],\n    \"segment_ids\": [\n        [\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0,\n            0\n        ]\n    ]\n} must only have keys: input_ids,input_mask,is_real_example,label_ids,segment_ids" }". See https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=/aws/sagemaker/Endpoints/tensorflow-training-2019-11-22-16-08-44-177 in account 922643591083 for more information.

**Comment by ChuyangDeng** [comment]
Hi @hegebharat, thanks for using SageMaker!

From the error message, I think the model you deployed is expecting inference request as something like the following instead of your input data:

{
    "instances": [...]
}

And here's some guidance on how to pre-process your input data: https://github.com/aws/sagemaker-tensorflow-serving-container/blob/master/README.md#prepost-processing
