### ISSUE TITLE
Multi-Model endpoints

### ISSUE THREAD

**Issue by ssp573** [aws/sagemaker-python-sdk#1149]
Reference: 0420761780

I can see a pull request for hosting multiple models on the same endpoint here - https://github.com/aws/sagemaker-python-sdk/pull/1144
When will this be available to deploy multiple PyTorch models?

**Comment by ChoiByungWook** [comment]
Hello @ssp573,

Currently there is no ETA for when this will be available for PyTorch models. I'll provide an update when it becomes available.

Thanks!

**Comment by ssp573** [comment]
Thanks. In that case, what is the best way to do the same now. I have 4 BERT models I am trying to deploy on one ml.m5.2xlarge instance. Currently, I am returning a dictionary of models from the model_fn instead of returning one model. I am running into memory utilization problems as the request rate is also quite high. Any pointers would be helpful.

**Comment by ahnate** [comment]
+1

@ssp573 Did you find a solution?

**Comment by ssp573** [comment]
> +1
> 
> @ssp573 Did you find a solution?

Check this [https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/multi_model_bring_your_own/multi_model_endpoint_bring_your_own.ipynb](url)
