### ISSUE TITLE
Allow specifying default S3 bucket for a given SageMaker Session

### ISSUE THREAD

**Issue by elvinx** [aws/sagemaker-python-sdk#1165]
One of the issues we face with the SDK over and over again in controlled environments is where we are not allowed to create S3 buckets, the SDK tries to create and use one based on the following  convention:
`sagemaker-{region}-{AWS account ID}`

Cases where we face this issue:
 - Code location using Tensorflow/Pytorch script mode
 - Code location for Data Processing Jobs
 - Default output directories for created models, and etc.

What's even worse, in all of the above cases those variables are optional and the SDK tries to use the default bucket which we are not able to create.

As a user, I would like to be able to specify my default S3 bucket for a given session so I stop hitting this issue all the time.

Proposed solution:
Allow specifying a default_bucket during the creation of a Session

```code
class Session(object):  # pylint: disable=too-many-public-methods
    def __init__(self, boto_session=None, sagemaker_client=None, sagemaker_runtime_client=None, default_bucket=None):
```

**Comment by ajaykarpur** [comment]
Hi @elvinx, thanks for providing details about your use case and a proposed solution. We'll look into this and get back to you shortly.

**Comment by knakad** [comment]
Hi Elvin!

Thanks for reaching out with your pain point!
I went ahead and implemented this in https://github.com/aws/sagemaker-python-sdk/pull/1168

It'll get pushed to PyPI the next time we release, which is estimated at early next week, but may be as early as today. As always, dates are subject to change based on unexpected issues, and these are just estimates.

(Officially still OOO, so I may be slow to respond to follow-ups)

Hope that helps!
Karim

**Comment by andremoeller** [comment]
Hey @elvinx ,

This change to allow setting the `default_bucket` through a `Session` has been released: https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.47.0

Just as with https://github.com/aws/sagemaker-python-sdk/issues/1163, you can install this newest release into a notebook instance by:

1. Running !pip install -U --user sagemaker
2. Restarting the kernel.

I'm closing this issue. Please feel free to reach out or reopen this if you run into issues. Thanks!

**Comment by elvinx** [comment]
@andremoeller thank you for the quick fix!
I am afraid this feature introduced a bug :/ And now by default the SDK tries to create the bucket
 - I upgraded to SageMaker 1.47 
 - Run below lines of code
```python
import sagemaker
role = sagemaker.get_execution_role()
```
 - I get the below error 
`ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied`

<img width="865" alt="Screen Shot 2019-12-16 at 2 22 24 PM" src="https://user-images.githubusercontent.com/8008982/70910195-7fdcda80-200f-11ea-83a5-b0045858a377.png">
