### ISSUE TITLE
Bug in v1.47.0 after allowing default bucket to be specified by the user

### ISSUE THREAD

**Issue by elvinx** [aws/sagemaker-python-sdk#1174]
@andremoeller thank you for the quick fix!
I am afraid this feature (https://github.com/aws/sagemaker-python-sdk/pull/1168) introduced a bug :/ And now by default the SDK tries to create the bucket all the time
 - I upgraded to SageMaker 1.47 
 - Run below lines of code
```python
import sagemaker
role = sagemaker.get_execution_role()
```
 - I get the below error 
`ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied`

<img width="865" alt="Screen Shot 2019-12-16 at 2 22 24 PM" src="https://user-images.githubusercontent.com/8008982/70910195-7fdcda80-200f-11ea-83a5-b0045858a377.png">

https://github.com/aws/sagemaker-python-sdk/issues/1165

**Comment by andremoeller** [comment]
@elvinx 

Thanks for reporting this! We're looking into this now.

**Comment by knakad** [comment]
While we push a revert out, I believe a workaround is to specify the session with the custom bucket name as part of the session you pass in to .get_execution_role().

i.e.:
```
my_session = Session(..., default_bucket="my_custom_bucket")
role = sagemaker.get_execution_role(sagemaker_session=my_session)
```

Alternatively, you can also downgrade to a previous version to unblock yourself.

In the meantime, we're working on a version of this fix that doesn't create the bucket on init.

**Comment by ajaykarpur** [comment]
Hi @elvinx, we've merged in the fix for this bug. We'll have a release out soon.

**Comment by ajaykarpur** [comment]
The bugfix has been released. Please feel free to reach out if you have any further questions.
