### ISSUE TITLE
How to train on SageMaker and deploy on Nvidia Jetson boards?

### ISSUE THREAD

**Issue by mhaboali** [aws/sagemaker-python-sdk#1178]
Recently, we have decided to use AWS SageMaker to train our models, but after studying its documentation, I didn't find how to deploy the trained model on a local machine. Our local machines are mainly Nvidia Jetson boards.

Is it possible? If yes, could you explain to us how can we do it?

Your help will be much appreciated!

Mohammad.

**Comment by nadiaya** [comment]
You can deploy the model as if you have trained it locally.

At the end of the training you get a trained model saved to your s3 bucket.
There is nothing SageMaker specific about the model, e.g. after training PyTorch/Tensorflow/MXNet/etc. you just get a regular PyTorch/Tensorflow/MXNet/etc. model.

**Comment by mhaboali** [comment]
Thanks for your reply, 

Ok, I got this part, but I'm wondering about the steps to run this trained model on the local board. 

And, should I set up or install other dependencies? If yes, please give me an example.

Thanks for your support!

**Comment by nadiaya** [comment]
It really depends on your model and/or framework, as well as on whether you need to process prediction requests at all or just simply run evaluation on some data. I would direct you to the frameworks documentation on how to host model locally.

You can also check out our open sourced serving containers to see how we set hosting and what libraries we use to process prediction requests:
https://github.com/aws/sagemaker-mxnet-serving-container
https://github.com/aws/sagemaker-pytorch-serving-container
https://github.com/aws/sagemaker-tensorflow-serving-container

**Comment by mhaboali** [comment]
Ok, The links sound very useful for me.

Thanks so much for your help!
