### ISSUE TITLE
Sagemaker training job throws an error "OSError: [Errno 9] Bad file descriptor"

### ISSUE THREAD

**Issue by eljur** [aws/sagemaker-python-sdk#1202]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: PyTorch
- **Framework Version**: 1.2.0
- **Python Version**: 3.6.5
- **CPU or GPU**: GPU
- **Python SDK Version**: latest
- **Are you using a custom image**: SageMaker conda_pytorch_p36

Hello,

I am trying to train a Pytorch model with Sagemaker endpoint. Data processing is done with  torchvision.datasets.ImageFolder. When it tries to access training data it throws an error:
"OSError: [Errno 9] Bad file descriptor"

Interestingly, yesterday night there was a different error message at the same place: 
"TypeError: scandir: illegal type for path parameter"

This is what I run:

import sagemaker

sagemaker_session = sagemaker.Session()
bucket = sagemaker_session.default_bucket()
prefix = 'dogImages/train'
role = sagemaker.get_execution_role()

input_data = sagemaker_session.upload_data(path='/home/ec2-user/SageMaker/data/dogImages/train', bucket=bucket, key_prefix=prefix)

which produces:
's3://sagemaker-us-west-2-686454818424/dogImages/train'
This bucket is public currently.

File structure in that folder is according to ImageFolder spec:
        root/class_x/xxx.ext
        root/class_x/xxy.ext
        root/class_x/xxz.ext

This is the code to start a training job:

from sagemaker.pytorch import PyTorch

estimator = PyTorch(entry_point="train.py",
                    source_dir="train",
                    role=role,
                    framework_version='0.4.0',
                    train_instance_count=1,
                    train_instance_type='ml.p2.xlarge',
                    hyperparameters={
                        'epochs': 20
                    })

This is a full training log:

2019-12-31 19:23:05 Starting - Starting the training job...
2019-12-31 19:23:07 Starting - Launching requested ML instances......
2019-12-31 19:24:10 Starting - Preparing the instances for training......
2019-12-31 19:25:17 Downloading - Downloading input data......
2019-12-31 19:26:32 Training - Downloading the training image...
2019-12-31 19:27:05 Uploading - Uploading generated training model
2019-12-31 19:27:05 Failed - Training job failed
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
2019-12-31 19:26:53,868 sagemaker-containers INFO     Imported framework sagemaker_pytorch_container.training
2019-12-31 19:26:53,895 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.
2019-12-31 19:26:53,899 sagemaker_pytorch_container.training INFO     Invoking user training script.
2019-12-31 19:26:54,170 sagemaker-containers INFO     Module train does not provide a setup.py. 
Generating setup.py
2019-12-31 19:26:54,171 sagemaker-containers INFO     Generating setup.cfg
2019-12-31 19:26:54,171 sagemaker-containers INFO     Generating MANIFEST.in
2019-12-31 19:26:54,171 sagemaker-containers INFO     Installing module with the following command:
/usr/bin/python -m pip install -U . -r requirements.txt
Processing /opt/ml/code
Building wheels for collected packages: train
  Running setup.py bdist_wheel for train: started
  Running setup.py bdist_wheel for train: finished with status 'done'
  Stored in directory: /tmp/pip-ephem-wheel-cache-ppu3rux6/wheels/35/24/16/37574d11bf9bde50616c67372a334f94fa8356bc7164af8ca3
Successfully built train
Installing collected packages: train
Successfully installed train-1.0.0
You are using pip version 18.1, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
2019-12-31 19:26:55,642 sagemaker-containers INFO     Invoking user script

Training Env:

{
    "current_host": "algo-1",
    "model_dir": "/opt/ml/model",
    "channel_input_dirs": {
        "training": "/opt/ml/input/data/training"
    },
    "input_config_dir": "/opt/ml/input/config",
    "hosts": [
        "algo-1"
    ],
    "user_entry_point": "train.py",
    "module_dir": "s3://sagemaker-us-west-2-686454818424/sagemaker-pytorch-2019-12-31-19-23-05-049/source/sourcedir.tar.gz",
    "input_data_config": {
        "training": {
            "RecordWrapperType": "None",
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated"
        }
    },
    "network_interface_name": "eth0",
    "job_name": "sagemaker-pytorch-2019-12-31-19-23-05-049",
    "input_dir": "/opt/ml/input",
    "output_dir": "/opt/ml/output",
    "num_cpus": 4,
    "output_data_dir": "/opt/ml/output/data",
    "hyperparameters": {
        "epochs": 20
    },
    "additional_framework_parameters": {},
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "framework_module": "sagemaker_pytorch_container.training:main",
    "module_name": "train",
    "num_gpus": 1,
    "resource_config": {
        "current_host": "algo-1",
        "hosts": [
            "algo-1"
        ],
        "network_interface_name": "eth0"
    },
    "log_level": 20
}

Environment variables:

SM_CHANNELS=["training"]
SM_MODEL_DIR=/opt/ml/model
SM_OUTPUT_DIR=/opt/ml/output
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_USER_ARGS=["--epochs","20"]
SM_INPUT_DIR=/opt/ml/input
SM_NETWORK_INTERFACE_NAME=eth0
SM_RESOURCE_CONFIG={"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"}
SM_TRAINING_ENV={"additional_framework_parameters":{},"channel_input_dirs":{"training":"/opt/ml/input/data/training"},"current_host":"algo-1","framework_module":"sagemaker_pytorch_container.training:main","hosts":["algo-1"],"hyperparameters":{"epochs":20},"input_config_dir":"/opt/ml/input/config","input_data_config":{"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","job_name":"sagemaker-pytorch-2019-12-31-19-23-05-049","log_level":20,"model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-west-2-686454818424/sagemaker-pytorch-2019-12-31-19-23-05-049/source/sourcedir.tar.gz","module_name":"train","network_interface_name":"eth0","num_cpus":4,"num_gpus":1,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1"],"network_interface_name":"eth0"},"user_entry_point":"train.py"}
SM_INPUT_DATA_CONFIG={"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_HOSTS=["algo-1"]
SM_CHANNEL_TRAINING=/opt/ml/input/data/training
SM_HPS={"epochs":20}
SM_NUM_GPUS=1
SM_USER_ENTRY_POINT=train.py
SM_HP_EPOCHS=20
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_MODULE_NAME=train
SM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main
SM_MODULE_DIR=s3://sagemaker-us-west-2-686454818424/sagemaker-pytorch-2019-12-31-19-23-05-049/source/sourcedir.tar.gz
SM_CURRENT_HOST=algo-1
PYTHONPATH=/usr/local/bin:/usr/lib/python35.zip:/usr/lib/python3.5:/usr/lib/python3.5/plat-x86_64-linux-gnu:/usr/lib/python3.5/lib-dynload:/usr/local/lib/python3.5/dist-packages:/usr/lib/python3/dist-packages
SM_NUM_CPUS=4
SM_FRAMEWORK_PARAMS={}
SM_LOG_LEVEL=20

Invoking script with the following command:

/usr/bin/python -m train --epochs 20

Using device cuda.
2019-12-31 19:26:56,700 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/bin/python -m train --epochs 20"
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/ml/code/train.py", line 152, in <module>
    train_loader = _get_train_data_loader(args.batch_size, args.data_dir, args.num_workers, args.pin_memory)
  File "/opt/ml/code/train.py", line 68, in _get_train_data_loader
    transform=transform)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 178, in __init__
    target_transform=target_transform)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 75, in __init__
    classes, class_to_idx = find_classes(root)
  File "/usr/local/lib/python3.5/dist-packages/torchvision/datasets/folder.py", line 23, in find_classes
    classes = [d for d in os.listdir(dir) if os.path.isdir(os.path.join(dir, d))]
OSError: [Errno 9] Bad file descriptor

I also attached content of my train folder for reference (Archive 2.zip). Thank you!
[Archive 2.zip](https://github.com/aws/sagemaker-python-sdk/files/4013567/Archive.2.zip)

**Comment by nadiaya** [comment]
Based on the stack trace the error seems to be coming from the user script and not from sagemaker library. Do you get the same error when running user script locally? 

Also the pytorch version (framework_version='0.4.0',) used is outdated and we would recommend switching to a newer version (the latest supported in SageMaker version is 1.3.1).

**Comment by eljur** [comment]
Thank you looking into it! 
I can run it successfully in local mode (Sagemaker notebook) with relative path.
