### ISSUE TITLE
Why can't run S3FS on custom SM image as SM doesn't run docker image with privilege 

### ISSUE THREAD

**Issue by bimhud** [aws/sagemaker-python-sdk#1214]
Please fill out the form below.

### System Information
- **Python Version**: 3.7
- **CPU or GPU**: both
- **Are you using a custom image**: yes

### Describe the problem
I create a custom image to support training a large number of models on multiple instances. To do this, I choose S3FS to provisioning a share S3 location for all instances.
When running this docker image outside Sagemaker, I have to use either  ``--privileged `` or ``--cap-add SYS_ADMIN --device /dev/fuse``  param on ``docker run`` to enable more privilege for the container. This is fine to make the image to run on multiple EC2 instance writing out models on that share location.

When moving that image to run on Sagemaker, by default, SM doesn't run the image with extras permission, hence, the S3FS failed on Sagegmaker as the SM doesn't provide a permission to provisioning /dev/fuse to load ``fuse`` module 

https://stackoverflow.com/questions/59638097/why-cant-run-s3fs-on-custom-sm-image-as-sm-doesnt-run-docker-image-with-privil

**Comment by laurenyu** [comment]
We've reached out to the relevant team. Thanks for using SageMaker!

**Comment by dickren123** [comment]
@bimhud facing the same issue, do you have some ideas or workaround?

**Comment by srikanthchandika** [comment]
Facing the same issue. did someone tried any workarounds or got any solution?

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using “aws s3 sync” manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using “aws s3 sync” manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using “aws s3 sync” manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using “aws s3 sync” manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using “aws s3 sync” manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using aws s3 sync manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using aws s3 sync manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using aws s3 sync manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using aws s3 sync manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using aws s3 sync manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
Unfortunately, I have to sync back and forward using `aws s3 sync` manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
I have to sync back and forward using `aws s3 sync` manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.

**Comment by bimhud** [comment]
I have to sync back and forward using `aws s3 sync` manually in my usecase. It’s not the ideal solution but it’s good enough to deal with my problem.
