### ISSUE TITLE
ValueError in docs should be ClientError for Estimator.delete_endpoint

### ISSUE THREAD

**Issue by Hari-Nagarajan** [aws/sagemaker-python-sdk#1238]
### Describe the problem
The documentation states that ```Estimator.delete_endpoint``` raises ```ValueError``` if the endpoint does not exist, but it actually raises ```botocore.exceptions.ClientError``` when the endpoint does not exist.

See: https://github.com/aws/sagemaker-python-sdk/blob/bf48fb1219bd8ea22e78a913bfa091e544c57cc3/src/sagemaker/estimator.py#L795-L802

**Comment by ajaykarpur** [comment]
@Hari-Nagarajan, thanks for bringing this to our attention. Fixed in https://github.com/aws/sagemaker-python-sdk/pull/1241.
