### ISSUE TITLE
Calling predict with the predictor we got back from deploy

### ISSUE THREAD

**Issue by Firas-Ben-Hassan** [aws/sagemaker-python-sdk#125]
Hello Sagemaker Community, 

I get this error when I try to run this command in Sagemaker Notebook : "print(predictor.predict("the password is 15jdgvd "))" 

The error : 
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-114-5828681b8210> in <module>()
      8 
      9 
---> 10 print(predictor.predict("the password is 15jdgvd "))

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data)
     72         """
     73         if self.serializer is not None:
---> 74             data = self.serializer(data)
     75 
     76         request_args = {

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/predictor.py in __call__(self, data)
    247             return _json_serialize_from_buffer(data)
    248 
--> 249         raise ValueError("Unable to handle input format: {}".format(type(data)))
    250 
    251 

ValueError: Unable to handle input format: <class 'str'>

**Comment by yangaws** [comment]
Hi,

From the error message, the json serializer in predictor.py is invoked. So if that's the correct serializer you want to use, then you cannot serialize the data from a string as the error message indicated. What you can serialize with this json serializer is: numpy array, list, dict, file and buffer.

I cannot see what you are trying to do just by this code. If you provide us more info(what estimator, model, etc), we may have suggestions on data type you should use.

Thanks

**Comment by yangaws** [comment]
Thanks for your info @PFE-Passau 

Now we have better ideas of the problem here. We should support string serialization in built in json serializer. We have already put this in backlog and I will mark this issue as a feature request.

For a short-term solution to your problem, I recommend you to implement a simple serializer for now. And you can also contribute it to us. Our json serializer codes are here:

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/predictor.py#L221

Thanks

**Comment by PFE-Passau** [comment]
Thanks @yangaws, 

Done!

**Comment by PFE-Passau** [comment]
Hi @yangaws , 

I get another error when I try to convert the input to bytes format via predictor.predict(bytes format) 

odelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.</p>
". See https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logEventViewer:group=/aws/sagemaker/Endpoints/sagemaker-all-2018-04-11-12-00-21-560 in account 180856571690 for more information.

**Comment by mohanasudhan** [comment]
@Firas-Ben-Hassan predictor.predict has evolved over the years and we currently support StringSerializer [class StringSerializer(SimpleBaseSerializer):. ](https://github.com/aws/sagemaker-python-sdk/blob/45166bedb564fd30ca1d658b005c4457d719f6d9/src/sagemaker/base_serializers.py#L404)

Additionally, we have released a new class to simplify the deployment with automated wiring of serializer with release of ModelBuilder (https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-modelbuilder-creation.html)

Happy to help if it is still an issue.

**Comment by mohanasudhan** [comment]
We are closing this issue as we currently lack sufficient information to proceed. Please feel free to reopen the issue if you can provide more details.
