### ISSUE TITLE
Broken link to sagemaker.automl Doc

### ISSUE THREAD

**Issue by nealrp** [aws/sagemaker-python-sdk#1276]
**Describe the bug**
Broken link in page https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/automl/README.rst

"For more information about AutoML parameters, please refer to: https://sagemaker.readthedocs.io/en/stable/sagemaker.automl.html"

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

Go to "For more information about AutoML parameters, please refer to: https://sagemaker.readthedocs.io/en/stable/sagemaker.automl.html"

**Expected behavior**
Working link

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by knakad** [comment]
Thanks for bringing this to our attention!
For now, the links are actually:
* https://sagemaker.readthedocs.io/en/stable/automl.html
* https://sagemaker.readthedocs.io/en/stable/automl.html#sagemaker.automl.candidate_estimator.CandidateEstimator

I went ahead and fixed this in our documentation. The readthedocs page will be updated on the next release, scheduled for Wednesday morning =)

**Comment by nealrp** [comment]
Thanks!
