### ISSUE TITLE
Incorrect name of env variable SM_CHANNEL_TRAIN in pytorch documentation

### ISSUE THREAD

**Issue by mharvan** [aws/sagemaker-python-sdk#1292]
**What did you find confusing? Please describe.**
The documentation https://sagemaker.readthedocs.io/en/stable/using_pytorch.html specifies the environment variable SM_CHANNEL_TRAIN. This variable was not present and I had to use the variable SM_CHANNEL_TRAINING instead.

**Describe how documentation can be improved**

Could you please clarify which variable is correct?

If the variable name changed, could you please clarify in which version of sagemaker and/or pytorch it changed?

**Additional context**
Relevant code snippet from sagemaker estiamtor entry point (train.py):
```python
    parser.add_argument('--data-dir', type=str, default=os.environ['SM_CHANNEL_TRAINING'])
```

This is the case with with framework_version 1.3.1 but other versions might also be affected.
Code snippet showing how I created the sagemaker estimator:
```python
from sagemaker.pytorch import PyTorch

estimator = PyTorch(entry_point="train.py",
                    source_dir="source_pytorch",
                    role=role,
                    #framework_version='0.4.0',
                    #framework_version='1.0',
                    framework_version='1.3.1',
                    train_instance_count=1,
                    #train_instance_type='ml.p2.xlarge',
                    #train_instance_type='ml.m4.xlarge',
                    #train_instance_type='local_gpu',
                    train_instance_type='local',
                    hyperparameters={
                        'epochs': 10,
                        'batch-size': 4,
                        'hidden_dim': 40,
                        'input_features': 3,
                        'output_dim': 1
                    })
```

**Comment by laurenyu** [comment]
The name of that environment variable is dependent on the name of the channel [emphasis mine]:

> Suppose that two input channels, **‘train’ and ‘test’**, were used in the call to the PyTorch estimator’s fit method, the following will be set, following the format “SM_CHANNEL_[channel_name]”:
>
>   * SM_CHANNEL_TRAIN: A string representing the path to the directory containing data in the ‘train’ channel
>   * SM_CHANNEL_TEST: Same as above, but for the ‘test’ channel.

I can see how this might not have been clear, though, so thanks for reaching out!

**Comment by mharvan** [comment]
Thanks, after changing to 'train' in call to fit() I get SM_CHANNEL_TRAIN.
