### ISSUE TITLE
The link is not working

### ISSUE THREAD

**Issue by pingsutw** [aws/sagemaker-python-sdk#1318]
The links https://sagemaker.readthedocs.io/en/stable/using_xgboost.html in README seems not work

**Comment by knakad** [comment]
Thanks for reaching out!

To unblock yourself in the short-term, please take a look at https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost.html .

Interesting timing, we actually have an active project adding XGBoost documentation. That work is almost done. Expect the links to point to some new docs soon!

**Comment by pingsutw** [comment]
@knakad Thanks for the reply, and looking forward the new docs about XGBoost

**Comment by martinRenou** [comment]
Closing as resolved. Thank you!
