### ISSUE TITLE
The processing feature does not allow use of encrypt_inter_container_traffic parameter

### ISSUE THREAD

**Issue by bhavik161** [aws/sagemaker-python-sdk#1320]
The SageMaker processing feature  sagemaker.processing.Processor and sagemaker.processing.ScriptProcessor does now allow use of encrypt_inter_container_traffic parameter.
This parameter is available in sagemaker estimator.  We have a requirement where we can not use the processor feature if it does not allow encrypting inter container traffic

**Comment by andremoeller** [comment]
Hi @bhavik161 ,

SageMaker Processing doesn't currently have this feature, and we can't provide an ETA, but we're always reprioritizing our roadmap based on customer input. Thank you!

**Comment by laurenyu** [comment]
this is now in progress: https://github.com/aws/sagemaker-python-sdk/pull/1431

**Comment by laurenyu** [comment]
This feature is now available as of v1.58.1.
