### ISSUE TITLE
TypeError callling tuner.best_estimator(best_training_job=best_job_name)

### ISSUE THREAD

**Issue by jfelectron** [aws/sagemaker-python-sdk#1322]
**Describe the bug**

Fetching best estimator from Tuner by name raises TypeError

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

1) Create XGBoost Estimator.  
2) Create HyperparameterTuner with Extimator
3) After HPO finishes try to get best_estmator from tuner:
           best_job_name = self.tuner.best_training_job()
            best_estimator = self.tuner.best_estimator(best_training_job=best_job_name)

**Expected behavior**

Estimator is retrieved. 

**Screenshots or logs**
2020-03-03T20:58:52.397Z best_estimator = self.tuner.best_estimator(best_training_job=best_job_name)
2020-03-03T20:58:52.397Z best_estimator = self.tuner.best_estimator(best_training_job=best_job_name)
 File "/usr/local/lib/python3.7/site-packages/sagemaker/tuner.py", line 776, in best_estimator
 2020-03-03T20:58:52.398Z training_job_name=best_training_job["TrainingJobName"],
 2020-03-03T20:58:52.398Z TypeError: string indices must be integers

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: current
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by knakad** [comment]
Hi Jonathan!

Thanks for reaching out!
I updated the docstring on this method to be clearer. You need to pass in a python dict object containing a couple keys: https://github.com/aws/sagemaker-python-sdk/pull/1331
I added an Example to the docstring as well to make it easier.

Hope that helps!

**Comment by knakad** [comment]
( https://sagemaker.readthedocs.io/en/stable/tuner.html will be updated on the next release, scheduled for Monday morning US Pacific time )
