### ISSUE TITLE
Expose better JsonSerde for endpoint invocation

### ISSUE THREAD

**Issue by ehsanmok** [aws/sagemaker-python-sdk#1351]
**Is your feature request related to a problem? Please describe.**

Currently`json_serializer` is based on a hidden class [_JsonSerializer](https://github.com/aws/sagemaker-python-sdk/blob/4d05b8ebb344377dbe473b28da45898e709d66d0/src/sagemaker/predictor.py#L513) (same for `json_deserialize`) and that doesn't allow the users to define their own custom json serde via extending `json.JSONEncoder` and `json.JSONDecoder`. For certain applications that the json request has many fields of various types using the current implementation makes the request handling very manual in `transform_fn` which is not scalable.

**Comment by laurenyu** [comment]
@ehsanmok sorry for the delay in response here

if the default JSON serializer and deserializer don't work for you, you can define your own, and then set your predictor to use your custom classes: 

```python
predictor.serializer = custom_json_serializer
predictor.deserializer = custom_json_deserializer
```

hope that helps!

**Comment by ehsanmok** [comment]
@laurenyu that won't work, bc `_JsonSerializer` accepts no argument and `__call__` method is very specific whereas python `json.JSONEncoder` accepts arguments. Probably would be better to wrap `JSONEncoder` and making it callable. Something that conforms with normal python interface would be useful.

**Comment by laurenyu** [comment]
sorry if I wasn't clear. what I meant is that you can write your own classes that are completely separate from `_JsonSerializer` and `_JsonDeserializer`, e.g.

```python
class _CustomJsonSerializer(object):

    def __init__(self):
        self.content_type = "application/json"

    def __call__(self, data):
        # use json.JSONEncoder here

custom_json_serializer = _CustomJsonSerializer()
```

and then configure your predictor to use your own class:

```python
predictor.serializer = custom_json_serializer
```

**Comment by ehsanmok** [comment]
Sure, but that doesn't solve the lack of proper abstraction issue. I meant something like

```python
class BaseJsonSerializer:
    def __init__(self):
        self.context_type = "application/json"
    def __call__(self, data):
        raise NotImplementedError
```

then any custom serializer would inherit from it and becomes visibly callable.

**Comment by laurenyu** [comment]
I can see where you're coming from, and will leave this open as a feature request.

In the meantime, your options are to either write your own class from scratch, or have it inherit `_JsonSerializer` (and ignore that it's private)

**Comment by bveeramani** [comment]
Hi @ehsanmok, just wanted to let you know that we’ve improved the abstraction of serializers and deserializers in v2 of the SageMaker Python SDK (#1668). Thank you for your feedback on the SerDe interface.
