### ISSUE TITLE
Support using local S3 instance (e.g. minio)

### ISSUE THREAD

**Issue by larsll** [aws/sagemaker-python-sdk#1358]
**Is your feature request related to a problem? Please describe.**
We are working on setting up local/offline DeepRacer training; using Sagemaker and Robomaker. This means having a local S3 instance (using minio) to host the files.

**Describe the solution you'd like**
It should be possible to configure the S3 Endpoint URL to point to a specific local URL/port. Current proposal is to allow to pass a pre-configured s3Client into an Estimator on creation.

**Describe alternatives you've considered**
An alternative would be to store the required configuration in the Sagemaker Local Session. It would nevertheless require changes to all areas of code where a new s3Client is created.

**Comment by laurenyu** [comment]
Thanks again for submitting #1359! Did it address your issue (or is there more you're looking for with this)?

**Comment by larsll** [comment]
Yes - this can be closed. #1359 solved this issue -- we no longer need a fork to support local S3 instances (e.g. minio).
