### ISSUE TITLE
Error message during tensorflow fit with instance_type='local'

### ISSUE THREAD

**Issue by jsaedtler** [aws/sagemaker-python-sdk#136]
When starting a local training with a "local" instance_type an error message is shown:

```
Pulling algo-1-H0U3U (520713654638.dkr.ecr.eu-central-1.amazonaws.com/sagemaker-tensorflow:1.6-cpu-py2)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.
```

Here's the code I use to start the training:
```
    estimator = TensorFlow(
        entry_point='model_with_fx_keras.py',
        source_dir='v20180404/',
        role='SageMakerFullAccess',
        training_steps=50000,
        evaluation_steps=10,
        hyperparameters={'learning_rate': 1e-03},
        train_instance_count=1,
        train_instance_type='local',
        base_job_name='model-v20180404')

    estimator.fit(
        TRAING_DATA_BUCKET,
        run_tensorboard_locally=True)
```

Remote training with an usual ml instance works as expected.

**Comment by jsaedtler** [comment]
What I found out:

I was using the aws profile based credentials, which have set the region to eu-central-1:

```
region=eu-central-1
```

And I had an additional environment variable for AWS_REGION: 

```
export AWS_REGION='eu-west-1'
```

This made sagemaker use eu-west-1 for remote training, but It tried to pull the docker image from eu-central-1. Setting the region in the aws profile to 

```
region=eu-west-1 
```

worked.

It would be great if the remote training and the local training behave similar regarding the use of the region configuration from the profile and the environment variables.

**Comment by iquintero** [comment]
Hi @jsaedtler 

thanks for trying out local mode! I will troubleshoot this and update when I know what is causing the problem.

**Comment by iquintero** [comment]
Hi again @jsaedtler 

I have figure this out. Boto (and in general the other AWS SDKS) expect the region to be set as AWS_DEFAULT_REGION instead of AWS_REGION

I confirmed that the sagemaker-python-sdk behaves the same way in both local mode and remote traininig. I will go ahead and close this issue feel free to open if there is something else you want to add. I am going to work on your other issue now :)
