### ISSUE TITLE
StackOverflow: TrainingJobAnalytics returns only one timestamp for inbuilt xgboost

### ISSUE THREAD

**Issue by danabens** [aws/sagemaker-python-sdk#1361]
**Describe the bug**
https://stackoverflow.com/questions/59202898/amazon-sagemaker-trainingjobanalytics-returns-only-one-timestamp-for-inbuilt-xg

**Comment by laurenyu** [comment]
closing this issue as a duplicate since there's already some correspondence on the StackOverflow question

**Comment by ilanaklo** [comment]
was this issue resolved? I have a similar problem and there is no correspondance in the stackoverflow link

**Comment by laurenyu** [comment]
@ilanaklo feel free to open a new issue in this repository and include your code for starting your training job as well as any relevant logs/errors

**Comment by yoandinkov** [comment]
Debugged a bit similar scenario, wrote my notes in SO. https://stackoverflow.com/a/69785558/1626392
