### ISSUE TITLE
Adding argument `model_dir` to PyTorch Estimator

### ISSUE THREAD

**Issue by henghuiz** [aws/sagemaker-python-sdk#1386]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I submit the Pytorch Training job, it will automatically create an folder in the root folder in my S3 bucket for source files.

**Describe the solution you'd like**
It would be great to have an `model_dir` argument in PyTorch Estimator, similar to `model_dir` argument in [Tensorflow Estimator](https://github.com/aws/sagemaker-python-sdk/blob/660a23074ba1bff937416797163ee297b1390acd/src/sagemaker/tensorflow/estimator.py#L216).

**Additional context**
I really like the experiment when I use Tensorflow in Sagemaker. And I wish Pytorch Estimator can have a similar function so that the source, output and checkpoint can be placed under the same folder. Or alternatively, some argument that I can direct the zip file of the source code so that it will not mess up the S3 bucket.

**Comment by nadiaya** [comment]
The source code logic under question is not specific to the PyTorch framework and is the same for all frameworks.

`model_dir` parameter was added to support [a special TF checkpointing functionality during distributed training](https://sagemaker.readthedocs.io/en/stable/using_tf.html#prepare-a-script-mode-training-script) that is not needed for PyTorch.

Could you give us an example of how you would use it in PyTorch?

You can set [code_location](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1474-L1478) and [output_path](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L130-L134) parameters in all supported frameworks and use [model checkpoints logic](https://docs.aws.amazon.com/sagemaker/latest/dg/model-checkpoints.html) provided by SageMaker Training.

Could you elaborate on the use case for the source, output and checkpoint being placed under the same folder? An example of how you are using PyTorch checkpoints in that case would be greatly appreciated.
