### ISSUE TITLE
[Request] SKLearnProcessor no image_uri support

### ISSUE THREAD

**Issue by bmaingret** [aws/sagemaker-python-sdk#1400]
Hi,

Why not  allow for custom image for training and modeling and not for preprocessing ?

Allowing only for 0.20.0 which dates from 2018 (https://scikit-learn.org/0.20/whats_new.html#version-0-20-0) is starting to get limiting IMHO.

I can understand the effort required to support newer version but why not then allow for custom images as it is done for estimator.SKLearn ?

Thank you

https://github.com/aws/sagemaker-python-sdk/blob/9127d602ae8874c322a6dcf5eef8735918ec60ed/src/sagemaker/sklearn/processing.py#L100

**Comment by knakad** [comment]
Hi Baptiste!

We don't currently have an SKLearn image above 0.20.0, but I've reached out to the team responsible to prioritize that process.

That being said, you can definitely still provide your own image in the higher-level class called "ScriptProcessor", which has all the existing functionality that SKLearnProcessor has, but allows a user-defined image_uri =)

For more information, feel free to take a look at https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker_processing/scikit_learn_data_processing_and_model_evaluation/scikit_learn_data_processing_and_model_evaluation.ipynb

Let me know if there's anything else I can help with!

**Comment by bmaingret** [comment]
> That being said, you can definitely still provide your own image in the higher-level class called "ScriptProcessor", which has all the existing functionality that SKLearnProcessor has, but allows a user-defined image_uri =)

Hi,

That's exactly what I eventually did and it worked seamlessly. Thanks.

BTW, I think it is on its way:
https://github.com/aws/sagemaker-scikit-learn-container/pull/36

Baptiste

**Comment by martinRenou** [comment]
Sklearn >0.20 can be used now. Closing for triage.
