### ISSUE TITLE
RuntimeError in training a model of resnet152 using transfer learning on Pytorch: "models cannot register a hook on a tensor that doesn't require gradient"

### ISSUE THREAD

**Issue by FurkanArslan** [aws/sagemaker-python-sdk#1401]
**Describe the bug**
I am struggling with a strange error in my transfer learning model on Pytorch. The pytorch estimator is giving RuntimeError: cannot register a hook on a tensor that doesn't require gradient error both on GPU and CPU sagemaker instances. I cannot find any solution for this error.

While searching google, I saw a thread about the same error in the Pytorch forum. I am wondering if the problem is about the estimator is trying to register a hook for parts that don't require grad in the Resnet model?

https://discuss.pytorch.org/t/register-hook-throwing-an-error-during-model-eval/65432

**To reproduce**
The code lines of my notebook instance are below: 

```
import sagemaker
import os

from sagemaker.pytorch import PyTorch

sagemaker_session = sagemaker.Session()

# Define IAM role
role = sagemaker.get_execution_role()

bucket = 'shoe-dataset'
prefix = 'sagemaker/singleColor'

data_location = 's3://{}/{}'.format(bucket, prefix)
!pygmentize run_aws.py

estimator = PyTorch(entry_point='run_aws.py',
                    source_dir='.',
                    role=role,
                    framework_version='1.4.0',
                    train_instance_count=1,
                    train_instance_type='ml.p2.xlarge')

estimator.fit({
    'train': os.path.join(data_location, 'train'), 
    'test': os.path.join(data_location, 'test')
})
```

**Expected behavior**
Running resnet152 transfer learning train smoothly in Sagemaker

**Screenshots or logs**
```
Traceback (most recent call last):
  File "run_aws.py", line 159, in 
    _train(parser.parse_args())
  File "run_aws.py", line 116, in _train
    log_interval=log_interval
  File "/opt/ml/code/trainer.py", line 25, in fit
    train_loss, metrics = train_epoch(train_loader, model, loss_fn, optimizer, cuda, log_interval, metrics)
  File "/opt/ml/code/trainer.py", line 61, in train_epoch
    outputs = model(*data)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 531, in _call_
    hook.register_hook(self)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 194, in register_hook
    self.register_module(module)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 227, in register_module
    self._backward_apply(module)
  File "/opt/conda/lib/python3.6/site-packages/smdebug/pytorch/hook.py", line 186, in _backward_apply
    param.register_hook(self.backward_hook(pname))
  File "/opt/conda/lib/python3.6/site-packages/torch/tensor.py", line 227, in register_hook
    raise RuntimeError("cannot register a hook on a tensor that "
RuntimeError: cannot register a hook on a tensor that doesn't require gradient
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: lastest
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Pytorch
- **Framework version**: 1.4
- **Python version**: 3.6
- **CPU or GPU**: GPU
- **Custom Docker image (Y/N)**: N

**Additional context**

run_aws.py code is here: 
https://github.com/FurkanArslan/deep-shoe-implementation/blob/master/run_aws.py

Here is the actual code that gives an error when forwarding the resnet152 model: (line 61):
https://github.com/FurkanArslan/deep-shoe-implementation/blob/master/trainer.py

**Comment by ChuyangDeng** [comment]
Hi @FurkanArslan, apologies for the late response.

The ``Estimator`` class will enable debugger hook by default (https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1686)

To disable the debugger functionality please set ``debugger_hook_config`` to False: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L98
