### ISSUE TITLE
Specify location for repacked model data

### ISSUE THREAD

**Issue by harusametime** [aws/sagemaker-python-sdk#1402]
**Is your feature request related to a problem? Please describe.**
When users are not allowed to create S3 bucket, they need to specify S3 bucket that they can access. For training, we can set `output_path` in estimator for specifying location for storing source code and a trained model.

However, calling estimator.deploy() repacks the source code and the trained model, and tries to upload to default bucket, named `sagemaker-<region name>-<account_id>`. If a user is not allowed to access the S3 bucket, SageMaker fails to deploy.

Reading [model.py#L852](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model.py#L852), we need to overwrite `model.bucket`. Actually, the following code works, but is not easy for users.
```
model = estimator.create_model()
model.bucket = "accessible-bucket-name"
predictor = model.deploy(...)
```
**Describe the solution you'd like**
- For estimator, `output_path` should be used for repacked model data. A user need not to specify the accessible bucket name again.
- For create_model() or model.deploy(), an argument to specify a location for repacked model would be convenient.

**Comment by knakad** [comment]
Hi Masaki!

We actually received this as a feature request already in https://github.com/aws/sagemaker-python-sdk/issues/1258 and I added new functionality to support this use-case =)

There are two ways you can change your code to resolve this:
* (Recommended) Created your session as follows, by specifying the default_bucket that already exists (if it doesn't exist, sagemaker-python-sdk will attempt to create it for you):
```
sagemaker_session = sagemaker.session.Session(default_bucket='my-bucket')
```
* You can override the bucket location for this specific issue by specifying the code_location in the estimator.

Hope that helps!!

Reopen and reach out if you're still having trouble :)
