### ISSUE TITLE
CSV Problem with Scientific Notation

### ISSUE THREAD

**Issue by hantianz** [aws/sagemaker-python-sdk#141]
When I tried to train an xgboost model, I used a csv file without header line that is output of an all number pandas data-frame but got error: Alphabet found in the header line. 
Then after a while I realized that it was because there is scientific notation in the csv file, e.g., 1e-10
It would be better if it can automatically convert scientific notation to a number. Also this problem is hard to debug, because I am sure that my csv file only contains numbers but the error basically says you have non-numbers.

Best,
Hantian

**Comment by iquintero** [comment]
HI @hantianz  thanks for using SageMaker and pointing this out.

We look at  all enhancement / feature requests and consider them as part of our backlog and are constantly looking at our prioirities. I agree providing a better error message or even just converting it would be great! 

We will keep this issue open to track it.

**Comment by trungleduc** [comment]
Closing as it's not related to the SDK, please feel free to re-open if needed.
