### ISSUE TITLE
Fix link

### ISSUE THREAD

**Issue by IvyBazan** [aws/sagemaker-python-sdk#1411]
**What did you find confusing? Please describe.**
The doc link for https://sagemaker.readthedocs.io/en/stable/sagemaker.workflow.airflow.html doesn't follow the naming convention of other docs pages.

**Describe how documentation can be improved**
Reformat the link to https://sagemaker.readthedocs.io/en/stable/sagemaker_workflow_airflow.html

**Comment by laurenyu** [comment]
hi there, if you look at https://github.com/aws/sagemaker-python-sdk/tree/master/doc, you'll see that there are in fact quite a few files that follow the convention of `sagemaker.` prefixing the file name. I believe the intent is for them to correspond to the `src` directory structure.
