### ISSUE TITLE
[NON-PY-SDK] pandas version issue with MXNet 1.6 environment

### ISSUE THREAD

**Issue by ehsanmok** [aws/sagemaker-python-sdk#1428]
**Describe the bug**
The `mxnet_p36` env seems to enforce `pandas==0.24` somehow which makes using [awslabs/gluonts](https://github.com/awslabs/gluon-ts) (pip installed from **master**) to fail (with and without upgrading pip) because GluonTS requires [`pandas~=1.0`](https://github.com/awslabs/gluon-ts/blob/master/requirements/requirements.txt#L4)

```
ContextualVersionConflict: (pandas 0.24.2 (/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages), Requirement.parse('pandas~=1.0'), {'gluonts'})
```

**To reproduce**
Run this in a notebook cell in `mxnet_p36` env

```
%%bash
if [[ `python -m pip freeze | grep enum34` ]]; then
    python -m pip uninstall -y enum34
fi
python -m pip install --upgrade -q sagemaker
python -m pip install -q git+https://github.com/awslabs/gluon-ts@master
```

Also it seems pandas requirement was not specified anywhere for MXNet [here](https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/mxnet).

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 1.55.4
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: MXNet
- **Framework version**: 1.6
- **Python version**: python3.6
- **CPU or GPU**: Both
- **Custom Docker image (Y/N)**: N

**Comment by laurenyu** [comment]
sorry for the delayed response here - just to clarify, you're referring to the `mxnet_p36` environment in a SageMaker Notebook Instance, right? (just want to make sure I route this to the correct team)

**Comment by ehsanmok** [comment]
Yes, that's right.

**Comment by laurenyu** [comment]
gotcha, thanks for the clarification. I'm going to pass this along to the team that owns Notebook Instances to see if they have any insight. thanks for your patience!

**Comment by neelamgehlot** [comment]
Hi @ehsanmok ,

We have deployed the newer version of pandas. This change will be deployed to all regions in coming week. 

In the meantime, you can update the version of pandas using `conda update pandas` in mxnet_p36 environment to unblock yourself. 

Please re-open this issue if you still didn't get `>1.0` version of pandas by end of next week.

Thanks,
Neelam
