### ISSUE TITLE
AlgorithmError: ExecuteUserScriptError: Command "/usr/bin/python script.py --model_dir s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model" bug

### ISSUE THREAD

**Issue by aksaravu** [aws/sagemaker-python-sdk#1442]
Hi Guys,

I've deployed a Machine Learning model on AWS Sagemaker. But I'm facing issues in my code and it is not getting successfully deployed.

**To reproduce**
1.Create a Jupyter Instance and create the two files(one .ipynb file & a .py file)
2. Copy/Paste the code in the my .ipynb file and run it.
I have two files in my Jupyter Instance created in AWS:
1. BuildingDeepLearningModelsUsingTensorflow.ipynb
2. script.py

The code for '**script.py**' is :
---------------------------------------------------------------------------------------------------------
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf
import os
import json
import argparse
from tensorflow.python.platform import tf_logging
import logging as lg
import sys as sys

def cnn_mode_fn(features, labels, mode):
    input_layer = tf.reshape(features["x"], [-1, 28, 28, 1])
    
    conv1 = tf.layers.conv2d(
        inputs=input_layer,
        filters = 32,
        kernel_size=[5, 5],
        padding = 'same',
        activation=tf.nn.relu)
    
    pool1 = tf.layers.max_pooling2d(inputs=conv1, pool_size=[2, 2], strides=2)
    
    conv2 = tf.layers.conv2d(
        inputs=pool1,
        filters = 64,
        kernel_size=[5, 5],
        padding = 'same',
        activation=tf.nn.relu)
    
    pool2 = tf.layers.max_pooling2d(inputs=conv2, pool_size=[2, 2], strides=2)
    
    pool2_flat = tf.reshape(pool2, [-1, 7 * 7 * 64])
    
    dense = tf.layers.dense(inputs=pool2_flat, units=1024, activation=tf.nn.relu)
    dropout = tf.layers.dropout(
        inputs=dense, rate=0.4, training=mode == tf.estimator.ModeKeys.TRAIN)
    
    logits = tf.layers.dense(inputs=dropout, units=10)
    
    predictions = {
        "classes":tf.argmax(input=logits, axis=1),
        "probabilities":tf.nn.softmax(logits, name="softmax_tensor")
    }
    
    if mode == tf.estimator.ModeKeys.PREDICT:
        return tf.estimator.EstimatorSpec(mode=mode, predictions = predictions)
    
    loss = tf.losses.sparse_softmax_cross_entropy(labels=labels, logits=logits)
    
    if mode == tf.estimator.ModeKeys.TRAIN: 
        optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.001)
        train_op = optimizer.minimize(
        loss=loss,
        global_step = tf.train.get_global_step())
        
        return tf.estimator.EstimatorSpec(mode=mode, loss=loss, train_op=train_op)
    
        eval_metric_ops = {
            "accuracy":tf.metrics.accuracy(
                labels=labels, predictions = predictions["classes"])}
    return tf.estimator.EstimatorSpec(
        mode=mode, loss=loss, eval_metric_ops=eval_metric_ops)
    

def _load_training_data(base_dir):
    x_train = np.load(os.path.join(base_dir, 'train_data.npy'))
    y_train = np.load(os.path.join(base_dir, 'train_labels.npy'))
    return x_train, y_train

def _load_testing_data(base_dir):
    x_test = np.load(os.path.join(base_dir, 'eval_data.npy'))
    y_test = np.load(os.path.join(base_dir, 'eval_labels.npy'))
    return x_test, y_test

def _parse_args():
    parser = argparse.ArgumentParser()   
    parser.add_argument('--model_dir', type=str)
    parser.add_argument('--sm-model-dir', type=str, default=os.environ.get("SM_MODEL_DIR"))
    parser.add_argument('--train', type=str, default=os.environ.get("SM_CHANNEL_TRAINING"))
    parser.add_argument('--hosts', type=list, default=json.loads(os.environ.get("SM_HOSTS")))
    parser.add_argument('--current-host', type=str, default=os.environ.get("SM_CURRENT_HOST"))    
    
    return parser.parse_known_args()

def serving_input_fn():
    inputs = {'x': tf.placeholder(tf.float32, [None, 784])}
    return tf.estimator.export.ServingInputReceiver(inputs,inputs)

if __name__ == '__main__':
    args, unknown = _parse_args()
    
    train_data, train_labels = _load_training_data(args.train)
    eval_data, eval_labels = _load_testing_data(args.train)
    
    mnist_classifier = tf.estimator.Estimator(
        model_fn = cnn_mode_fn, model_dir=args.model_dir)
    
    tensors_to_log = {"probabilities" : "softmax_tensor"}
    logging_hook = tf.train.LoggingTensorHook(
        tensors=tensors_to_log, every_n_iter=50)
    
    train_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x":train_data},
        y=train_labels,
        batch_size=100,
        num_epochs=None,
        shuffle=True)
    
    eval_input_fn = tf.estimator.inputs.numpy_input_fn(
        x={"x":eval_data},
        y=eval_labels,
        num_epochs=1,
        shuffle=false)
    
    train_spec = tf.estimator.TrainSpec(train_input_fn, max_steps=20000)
    eval_spec = tf.estimator.EvalSpec(eval_input_fn)
    tf.estimator.train_and_evaluate(mnist_classifier, train_spec, eval_spec)
    
    if args.current_host == args.hosts[0]:
        mnist_classifier.export_savedmodel(args.sm_model_dir, serving_input_fn)   
---------------------------------------------------------------------------------------------------------
And the code for BuildingDeepLearningModelsUsingTensorflow.ipynb is:
---------------------------------------------------------------------------
import os
import sagemaker
from sagemaker import get_execution_role

sagemaker_session = sagemaker.Session()
role = get_execution_role()

region = sagemaker_session.boto_session.region_name

training_url = 's3://sagemaker-sample-data-{}/tensorflow/mnist'.format(region)

from sagemaker.tensorflow import TensorFlow

mnist_estimator = TensorFlow(entry_point='script.py',
                             role=role,
                             train_instance_count=2,
                             train_instance_type = 'ml.m4.4xlarge',
                             framework_version='1.12',
                             py_version = 'py3',
                             distributions = {'parameter_server':{'enabled':True}})
mnist_estimator.fit(training_url)

--------------------------------------------------------------------------------------
**Expected behavior**
When you run the last statement of fit in 'BuildingDeepLearningModelsUsingTensorflow.ipynb' that is 'mnist_estimator.fit(training_url)'
It is going to print out an error like this:

<img width="901" alt="Capture1" src="https://user-images.githubusercontent.com/64312366/80280061-361fa180-871f-11ea-8c50-a73374df9f60.PNG">
<img width="697" alt="Capture" src="https://user-images.githubusercontent.com/64312366/80280062-39b32880-871f-11ea-972b-569a898ea774.PNG">

This is the complete output:
-----------------------------------------------------------------------------------------------------------
2020-04-25 11:33:56 Starting - Starting the training job...
2020-04-25 11:33:58 Starting - Launching requested ML instances......
2020-04-25 11:35:22 Starting - Preparing the instances for training......
2020-04-25 11:36:27 Downloading - Downloading input data
2020-04-25 11:36:27 Training - Downloading the training image...
2020-04-25 11:36:54 Uploading - Uploading generated training model
2020-04-25 11:36:54 Failed - Training job failed
2020-04-25 11:36:45,260 sagemaker-containers INFO     Imported framework sagemaker_tensorflow_container.training
2020-04-25 11:36:45,265 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-25 11:36:45,469 sagemaker_tensorflow_container.training INFO     Running distributed training job with parameter servers
2020-04-25 11:36:45,469 sagemaker_tensorflow_container.training INFO     Launching parameter server process
2020-04-25 11:36:45,469 sagemaker_tensorflow_container.training INFO     Running distributed training job with parameter servers
2020-04-25 11:36:45,575 sagemaker_tensorflow_container.training INFO     Launching worker process
2020-04-25 11:36:45,678 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-25 11:36:45,696 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-25 11:36:45,709 sagemaker-containers INFO     Invoking user script

Training Env:

{
    "additional_framework_parameters": {
        "sagemaker_parameter_server_enabled": true
    },
    "channel_input_dirs": {
        "training": "/opt/ml/input/data/training"
    },
    "current_host": "algo-1",
    "framework_module": "sagemaker_tensorflow_container.training:main",
    "hosts": [
        "algo-1",
        "algo-2"
    ],
    "hyperparameters": {
        "model_dir": "s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "training": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "is_master": true,
    "job_name": "sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/source/sourcedir.tar.gz",
    "module_name": "script",
    "network_interface_name": "eth0",
    "num_cpus": 16,
    "num_gpus": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-1",
        "hosts": [
            "algo-1",
            "algo-2"
        ],
        "network_interface_name": "eth0"
    },
    "user_entry_point": "script.py"
}

Environment variables:

SM_HOSTS=["algo-1","algo-2"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"model_dir":"s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"}
SM_USER_ENTRY_POINT=script.py
SM_FRAMEWORK_PARAMS={"sagemaker_parameter_server_enabled":true}
SM_RESOURCE_CONFIG={"current_host":"algo-1","hosts":["algo-1","algo-2"],"network_interface_name":"eth0"}
SM_INPUT_DATA_CONFIG={"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["training"]
SM_CURRENT_HOST=algo-1
SM_MODULE_NAME=script
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_tensorflow_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=16
SM_NUM_GPUS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{"sagemaker_parameter_server_enabled":true},"channel_input_dirs":{"training":"/opt/ml/input/data/training"},"current_host":"algo-1","framework_module":"sagemaker_tensorflow_container.training:main","hosts":["algo-1","algo-2"],"hyperparameters":{"model_dir":"s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":true,"job_name":"sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/source/sourcedir.tar.gz","module_name":"script","network_interface_name":"eth0","num_cpus":16,"num_gpus":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-1","hosts":["algo-1","algo-2"],"network_interface_name":"eth0"},"user_entry_point":"script.py"}
SM_USER_ARGS=["--model_dir","s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAINING=/opt/ml/input/data/training
SM_HP_MODEL_DIR=s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model
TF_CONFIG={"cluster": {"master": ["algo-1:2222"], "ps": ["algo-1:2223", "algo-2:2223"], "worker": ["algo-2:2222"]}, "environment": "cloud", "task": {"index": 0, "type": "master"}}
PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages

Invoking script with the following command:

/usr/bin/python script.py --model_dir s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model

Traceback (most recent call last):
  File "script.py", line 116, in <module>
    shuffle=false)
NameError: name 'false' is not defined
2020-04-25 11:36:47,247 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/bin/python script.py --model_dir s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"
2020-04-25 11:36:45,124 sagemaker-containers INFO     Imported framework sagemaker_tensorflow_container.training
2020-04-25 11:36:45,130 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-25 11:36:45,369 sagemaker_tensorflow_container.training INFO     Running distributed training job with parameter servers
2020-04-25 11:36:45,369 sagemaker_tensorflow_container.training INFO     Launching parameter server process
2020-04-25 11:36:45,369 sagemaker_tensorflow_container.training INFO     Running distributed training job with parameter servers
2020-04-25 11:36:45,484 sagemaker_tensorflow_container.training INFO     Launching worker process
2020-04-25 11:36:45,583 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-25 11:36:45,601 sagemaker-containers INFO     No GPUs detected (normal if no gpus installed)
2020-04-25 11:36:45,615 sagemaker-containers INFO     Invoking user script

Training Env:

{
    "additional_framework_parameters": {
        "sagemaker_parameter_server_enabled": true
    },
    "channel_input_dirs": {
        "training": "/opt/ml/input/data/training"
    },
    "current_host": "algo-2",
    "framework_module": "sagemaker_tensorflow_container.training:main",
    "hosts": [
        "algo-1",
        "algo-2"
    ],
    "hyperparameters": {
        "model_dir": "s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"
    },
    "input_config_dir": "/opt/ml/input/config",
    "input_data_config": {
        "training": {
            "TrainingInputMode": "File",
            "S3DistributionType": "FullyReplicated",
            "RecordWrapperType": "None"
        }
    },
    "input_dir": "/opt/ml/input",
    "is_master": false,
    "job_name": "sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421",
    "log_level": 20,
    "master_hostname": "algo-1",
    "model_dir": "/opt/ml/model",
    "module_dir": "s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/source/sourcedir.tar.gz",
    "module_name": "script",
    "network_interface_name": "eth0",
    "num_cpus": 16,
    "num_gpus": 0,
    "output_data_dir": "/opt/ml/output/data",
    "output_dir": "/opt/ml/output",
    "output_intermediate_dir": "/opt/ml/output/intermediate",
    "resource_config": {
        "current_host": "algo-2",
        "hosts": [
            "algo-1",
            "algo-2"
        ],
        "network_interface_name": "eth0"
    },
    "user_entry_point": "script.py"
}

Environment variables:

SM_HOSTS=["algo-1","algo-2"]
SM_NETWORK_INTERFACE_NAME=eth0
SM_HPS={"model_dir":"s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"}
SM_USER_ENTRY_POINT=script.py
SM_FRAMEWORK_PARAMS={"sagemaker_parameter_server_enabled":true}
SM_RESOURCE_CONFIG={"current_host":"algo-2","hosts":["algo-1","algo-2"],"network_interface_name":"eth0"}
SM_INPUT_DATA_CONFIG={"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}}
SM_OUTPUT_DATA_DIR=/opt/ml/output/data
SM_CHANNELS=["training"]
SM_CURRENT_HOST=algo-2
SM_MODULE_NAME=script
SM_LOG_LEVEL=20
SM_FRAMEWORK_MODULE=sagemaker_tensorflow_container.training:main
SM_INPUT_DIR=/opt/ml/input
SM_INPUT_CONFIG_DIR=/opt/ml/input/config
SM_OUTPUT_DIR=/opt/ml/output
SM_NUM_CPUS=16
SM_NUM_GPUS=0
SM_MODEL_DIR=/opt/ml/model
SM_MODULE_DIR=s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/source/sourcedir.tar.gz
SM_TRAINING_ENV={"additional_framework_parameters":{"sagemaker_parameter_server_enabled":true},"channel_input_dirs":{"training":"/opt/ml/input/data/training"},"current_host":"algo-2","framework_module":"sagemaker_tensorflow_container.training:main","hosts":["algo-1","algo-2"],"hyperparameters":{"model_dir":"s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"},"input_config_dir":"/opt/ml/input/config","input_data_config":{"training":{"RecordWrapperType":"None","S3DistributionType":"FullyReplicated","TrainingInputMode":"File"}},"input_dir":"/opt/ml/input","is_master":false,"job_name":"sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421","log_level":20,"master_hostname":"algo-1","model_dir":"/opt/ml/model","module_dir":"s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/source/sourcedir.tar.gz","module_name":"script","network_interface_name":"eth0","num_cpus":16,"num_gpus":0,"output_data_dir":"/opt/ml/output/data","output_dir":"/opt/ml/output","output_intermediate_dir":"/opt/ml/output/intermediate","resource_config":{"current_host":"algo-2","hosts":["algo-1","algo-2"],"network_interface_name":"eth0"},"user_entry_point":"script.py"}
SM_USER_ARGS=["--model_dir","s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"]
SM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate
SM_CHANNEL_TRAINING=/opt/ml/input/data/training
SM_HP_MODEL_DIR=s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model
TF_CONFIG={"cluster": {"master": ["algo-1:2222"], "ps": ["algo-1:2223", "algo-2:2223"], "worker": ["algo-2:2222"]}, "environment": "cloud", "task": {"index": 0, "type": "worker"}}
PYTHONPATH=/opt/ml/code:/usr/local/bin:/usr/lib/python36.zip:/usr/lib/python3.6:/usr/lib/python3.6/lib-dynload:/usr/local/lib/python3.6/dist-packages:/usr/lib/python3/dist-packages

Invoking script with the following command:

/usr/bin/python script.py --model_dir s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model

Traceback (most recent call last):
  File "script.py", line 116, in <module>
    shuffle=false)
NameError: name 'false' is not defined
2020-04-25 11:36:47,193 sagemaker-containers ERROR    ExecuteUserScriptError:
Command "/usr/bin/python script.py --model_dir s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-7-9634efdd0d05> in <module>()
----> 1 mnist_estimator.fit(training_url)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config, run_tensorboard_locally)
    477                 tensorboard.join()
    478         else:
--> 479             fit_super()
    480 
    481     @classmethod

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    456 
    457         def fit_super():
--> 458             super(TensorFlow, self).fit(inputs, wait, logs, job_name, experiment_config)
    459 
    460         if run_tensorboard_locally and wait is False:

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    475         self.jobs.append(self.latest_training_job)
    476         if wait:
--> 477             self.latest_training_job.wait(logs=logs)
    478 
    479     def _compilation_job_name(self):

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1087         # If logs are requested, call logs_for_jobs.
   1088         if logs != "None":
-> 1089             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1090         else:
   1091             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3042 
   3043         if wait:
-> 3044             self._check_job_status(job_name, description, "TrainingJobStatus")
   3045             if dot:
   3046                 print()

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2636                 ),
   2637                 allowed_statuses=["Completed", "Stopped"],
-> 2638                 actual_status=status,
   2639             )
   2640 

UnexpectedStatusException: Error for Training job sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421: Failed. Reason: AlgorithmError: ExecuteUserScriptError:
Command "/usr/bin/python script.py --model_dir s3://sagemaker-us-east-2-390127998428/sagemaker-tensorflow-scriptmode-2020-04-25-11-33-55-421/model"

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Comment by aksaravu** [comment]
Please copy and paste the entire code in script.py and BuildingDeepLearningModelsUsingTensorflow.ipynb despite partial highlighting and seperations above.

**Comment by aksaravu** [comment]
An also this error is with regards to not being able to create a training job.

**Comment by Electric-Dragon** [comment]
Is there a solution to this issue?
