### ISSUE TITLE
Using universal-sentence-encoder-multilingual will fail on SageMaker's endpoint

### ISSUE THREAD

**Issue by promisenxu** [aws/sagemaker-python-sdk#1450]
**Describe the bug**
When trying to invoke the endpoint that's built with the universal-sentence-encoder-multilingual-large pre-trained TensorFlow model, the following error is thrown:

> ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (404) from model with message "{ "error": "[_Derived_]{{function_node __inference_signature_wrapper_227768}} {{function_node __inference_signature_wrapper_227768}} Op type not registered \'SentencepieceOp\' in binary running on model.aws.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.\n\t [[{{node StatefulPartitionedCall}}]]\n\t [[StatefulPartitionedCall]]" }".

**To reproduce**
I'm running the following code in a Jupyter Notebook on SageMaker, running conda_tensorflow_p36

```
from sagemaker import get_execution_role
import sagemaker

role = get_execution_role()

from sagemaker.tensorflow.serving import Model, Predictor

sagemaker_model = Model(
    model_data = 's3://mys3bucket/model/universal-sentence-encoder.tar.gz',
    role = role,
    framework_version='2.0.1'
)

predictor = sagemaker_model.deploy(
    initial_instance_count=1, 
    instance_type='ml.t2.medium', 
    endpoint_name="test3"
)

input = ['I am a good guy.', 'I am a bad guy, very bad.']
output = predictor.predict(input)
```

**Expected behavior**
The endpoint to run properly and the resulted embedding vector is returned.

**Screenshots or logs**
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (404) from model with message "{ "error": "[_Derived_]{{function_node __inference_signature_wrapper_227768}} {{function_node __inference_signature_wrapper_227768}} Op type not registered \'SentencepieceOp\' in binary running on model.aws.local. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.\n\t [[{{node StatefulPartitionedCall}}]]\n\t [[StatefulPartitionedCall]]" }".

**Additional context**
1 - The universal-sentence-encoder.tar.gz is a compressed file I made from the model downloaded at the [Tensorflow Hub](https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3). The folder structure is:
- universal-sentence-encoders
  - universal-sentence-encoder-multilingual-large
    - 00000001
       saved_model.pb
       - variables
       |  variables.index
       |  variables.data-00000-of-00001
       - assets  # empty folder

2 - According to the [Tensorflow Hub page](https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3), the tensorflow-text library is required when using the model in Python. Would this be the reason why we have a bug?

**Comment by Kesin1** [comment]
I'm having the same issue and I try to figure out how this could be done. My guess is that it's because the SentencepieceOp is missing in the sagemaker-tensorflow-sagemaker container. 

These are related issues inside the tensorflow/serving repo:
[https://github.com/tensorflow/serving/issues/1490](https://github.com/tensorflow/serving/issues/1490)
[https://github.com/google/sentencepiece/issues/325](https://github.com/google/sentencepiece/issues/325)

**Comment by promisenxu** [comment]
@Kesin1 Thanks for the links! They are very helpful and informative, and unfortunately, well above my current level of knowledge to actually implement. Let me learn more about Tensorflow and see if I could eventually make it work (or maybe AWS will update the SageMaker container first).

**Comment by Kesin1** [comment]
Right now, it is implemented in the release candidate 1 and 2 of the next release of tensorflow-serving, so my guess is, that it will be available in tf-serving 2.2 and therefore will be integrated in an sagemaker-tensorflow-serving container as well eventually.

**Comment by nadiaya** [comment]
The latest official tensorflow-serving version we support is 2.1. We do not release images for release candidate versions.
As @Kesin1 mentioned we will add support for  tf-serving 2.2 soon after it is officially released.

Since the original question seems to be answered I am going to close the issue.

**Comment by singularity014** [comment]
Hello, I recently tried performing same thing as mentioned in the subject,  for multilingual USE3 

model. predictor = sagemaker_model.deploy(
    initial_instance_count=1, 
    instance_type='ml.t2.medium', 
    endpoint_name="muse3endpoint"
)

However, this part, takes too long ....in fact I waited for more than 15 mins for it. Could you please let me know if there is any solution to this?

Thank you

**Comment by Kesin1** [comment]
> The latest official tensorflow-serving version we support is 2.1. We do not release images for release candidate versions.
> As @Kesin1 mentioned we will add support for tf-serving 2.2 soon after it is officially released.
> 
> Since the original question seems to be answered I am going to close the issue.

Hella @nadiaya, is there anything in the making for the 2.2 version of tensorflow-serving now?
