### ISSUE TITLE
sagemaker.tensorflow.serving.Model does not seem to use `entry_point` and `source_dir`

### ISSUE THREAD

**Issue by cfregly** [aws/sagemaker-python-sdk#1451]
I am forced to use a hard-coded filename `inference.py` and a hard-code directory called `code`.

I thought `entry_point` and `source_dir` override the `code/inference.py` default?  is this not the case?

```
from sagemaker.tensorflow.serving import Model

batch_model = Model(entry_point='batch_inference.py',
                                      source_dir='src_batch_inference',
                                      model_data='s3://{}/{}/output/model.tar.gz'.format(bucket, training_job_name),
                                      role=role,
                                      framework_version='2.1.0',
                                      env=batch_env)
```

**Comment by ajaykarpur** [comment]
Hi Chris, I'm looking at the code for `tensorflow.serving.Model` and it looks like `source_dir` is being passed up to `sagemaker.model.FrameworkModel` via `kwargs`.

Can you please provide a stack trace for the error you're running into when using `source_dir`, your system information (including the Python SDK version), and any other relevant information for us to reproduce this issue?

**Comment by cfregly** [comment]
No stack trace.  It’s just not using the entry_point and source_dir that I’m passing.

I will try again here in a bit.

**Comment by cfregly** [comment]
@ajaykarpur 

thanks fo the response.

`sagemaker==1.56.1`
`tensorflow==2.1.0`

ok, so i've tried every combination of `entry_point` and `source_dir` and it appears that `entry_point` must equal `inference.py`, however `source_dir` can vary.

if i change `entry_point` to something other than `inference.py` (ie. `inference2.py`), the batch transformer does not seem to pick up my code.

perhaps an issue when copying to the image?  i've seen similar issues related to `entry_point` and `source_dir` in other parts of the SDK.  just a thought.

**Comment by cfregly** [comment]
More code:

```
batch_predictor = batch_model.transformer(instance_count=1,
                                          strategy='MultiRecord', # SingleRecord is orders of magnitude slower                          
                                          instance_type='ml.c5.18xlarge',
                                          accept='text/csv',
                                          assemble_with='Line',
                                          max_payload=1, # This is in Megabytes (not number of records)
                                          env=batch_env)
```

```
batch_predictor.transform(data=predict_csv_s3_uri,
                          split_type='Line',
                          compression_type='Gzip',
                          content_type='text/csv',
                          experiment_config=None,
                          wait=False)
```

**Comment by cfregly** [comment]
any update?  I have a workaround (to just change the `source_dir`) , but wondering if the intended API should allow both `source_dir` and `entry_point` to be specified?

**Comment by ChuyangDeng** [comment]
Hi @cfregly, sorry for the late reponse. Yes, the ``entry_point`` must be names as ``inference.py`` for ``sagemaker.tensorflow.serving``.

For more information about this feature, please refer to: https://github.com/aws/sagemaker-tensorflow-serving-container#prepost-processing
