### ISSUE TITLE
sagemaker.estimator not creating s3 output unless local

### ISSUE THREAD

**Issue by neonguru** [aws/sagemaker-python-sdk#1452]
On a local jupyter notebook I run the following two cells with no problem, except no files are written to S3. And the s3 bucket allows public access. I expected model and output tar files. If I change the instance_type in the second cell to 'local', then the s3 files are written:

```python
import boto3

client = boto3.client('sts')
account = client.get_caller_identity()['Account']

my_session = boto3.session.Session()
region = my_session.region_name

image = 'sagemaker-one'

# ecrimage = '{}:latest'.format(image)
ecrimage = '{}.dkr.ecr.{}.amazonaws.com/{}:latest'.format(account, region, image)

bucket = 'sagemaker-us-east-2-XXXXXXXXXXXX'

key = f"{image}-output-one"

s3_output_location = 's3://{}/{}'.format(bucket, key)

print(ecrimage, key)
```

output:
```
XXXXXXXXXXXX.dkr.ecr.us-east-2.amazonaws.com/sagemaker-one:latest sagemaker-one-output-one
```
and next cell:

```python
from sagemaker.estimator import Estimator

role = "arn:aws:iam::XXXXXXXXXXXX:role/service-role/AmazonSageMaker-ExecutionRole-20200411T182787"

hyperparameters = {'years': '2018 2019', 'valyears': '2020', 'run': 'run-one'}

instance_type = 'ml.m4.xlarge'

estimator = Estimator(role=role,
                      train_instance_count=1,
                      train_instance_type=instance_type,
                      image_name=ecrimage,
                      output_path=s3_output_location,
                      hyperparameters=hyperparameters)

estimator.fit()
```

output:
```
2020-05-04 18:10:40 Starting - Starting the training job...
2020-05-04 18:10:42 Starting - Launching requested ML instances...
2020-05-04 18:11:43 Starting - Preparing the instances for training......
2020-05-04 18:12:36 Downloading - Downloading input data
2020-05-04 18:12:36 Training - Downloading the training image........Training complete.

2020-05-04 18:14:08 Uploading - Uploading generated training model
2020-05-04 18:14:08 Completed - Training job completed
Training seconds: 98
Billable seconds: 98
```
But no output to S3. Now change the instance_type in the second cell to 'local' with no other changes and get this output and it DOES write to s3:
```
Creating tmpjzav88c0_algo-1-y35xl_1 ... 
Attaching to tmpjzav88c0_algo-1-y35xl_12mdone
algo-1-y35xl_1  | Training complete.
tmpjzav88c0_algo-1-y35xl_1 exited with code 0
Aborting on container exit...
===== Job Complete =====
```
Same container local vs ecs with different results. How to get output to s3 on ecs?

So this was on local windows machine, but I also tried the exact same cell 1 and 2 code above on a sagemaker notebook (conda_pytorch_36 kernel) and it still does not write to s3. Here is the sagemaker notebook training output:

```
2020-05-05 15:32:57 Starting - Starting the training job...
2020-05-05 15:32:58 Starting - Launching requested ML instances......
2020-05-05 15:33:58 Starting - Preparing the instances for training...
2020-05-05 15:34:44 Downloading - Downloading input data
2020-05-05 15:34:44 Training - Downloading the training image........Training complete.

2020-05-05 15:36:13 Uploading - Uploading generated training model
2020-05-05 15:36:13 Completed - Training job completed
Training seconds: 95
Billable seconds: 95
```

change instance_type to 'local' and it DOES write to s3 with this output on the above sagemaker notebook:

```
Creating tmpk2yjucio_algo-1-wnp0a_1 ... 
Attaching to tmpk2yjucio_algo-1-wnp0a_12mdone
algo-1-wnp0a_1  | Training complete.
tmpk2yjucio_algo-1-wnp0a_1 exited with code 0
Aborting on container exit...
===== Job Complete =====
```

**Comment by nadiaya** [comment]
Do you save anything under ```"/opt/ml/model"``` directory during the training?

**Comment by neonguru** [comment]
I have something in /opt/ml/output. Let me try /opt/ml/model. I'll let you know...

Thanks

**Comment by neonguru** [comment]
Thanks for the feedback @nadiaya 

for some reason, running from local jupyter notebook on an ml.m4.xlarge train_instance_type now (before it was fine) gives an error saying my region is invalid:

ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: Invalid DNS suffix 'amazonaws.com' for region 'us-east-2' in training image. Please provide the valid <region>.<dns-suffix>: 'us-west-2.amazonaws.com'

image_name is correct. us-east-2 is where my ecr image is, us-west-2 is my default region. Side question: how do I overcome this error?

But if I run on a sagemaker notebook it now succeeds in writing the model folder to s3 but does not write the output folder. Perhaps because I did not write a failure file?

**Comment by ChuyangDeng** [comment]
Hi @neonguru, for the region error, I believe it's because you are trying to pull the image from us-east-2 while your service/code is running in us-west-2.

You could either running your application on an instance in us-east-2, or copy your image to another ECR in us-west-2.

**Comment by neonguru** [comment]
Hi @ChuyangDeng 
I am doing this on a local jupyter instance, how do I run my jupyter instance on us-east-2? I tried a docker login to us-east-2 but get the same error.

All my ecr images are on us-east-2 as is my sagemaker notebook from which I am using it's role.

This was working just fine before local and I really haven't changed anything.

**Comment by neonguru** [comment]
Nevermind, I started my jupyter notebook from a cmd box right after aws configure set region us-east-2. Now it works.

I will close this issue since I am able to put my output in the model folder.
Feel free to reopen if you think it should copy the output folder like the docs say it does.
