### ISSUE TITLE
Create a script to aid with migrating from v1.x to v2.0

### ISSUE THREAD

**Issue by laurenyu** [aws/sagemaker-python-sdk#1478]
To go along with the breaking changes proposed in https://github.com/aws/sagemaker-python-sdk/issues/1459, we should provide a script that makes it easier to update one's code. For example, TensorFlow did this [for upgrading to TF 2.0](https://www.tensorflow.org/guide/upgrade) ([source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py)).

**Comment by Olamyy** [comment]
Hi @laurenyu , would love to contribute to this feature. Are external contributors allowed in the migration? If yes, how can I help?

**Comment by laurenyu** [comment]
@Olamyy yes! I've just posted a PR (#1492) to start laying some ground work. Take a look, comment with suggestions for refactoring, renaming, etc.

after that, I think the next steps would include:
* setting up some tests
* class(es) for reading source files and feeding the code into the `ASTTransformer` class, and dumping the results into a new file
* the CLI interface (see [TensorFlow's](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py) for an example)
* some of the other options that TF's script has, such as [handling directories](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py#L77-L86), [printing a report of the changes](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py#L114-L120), etc.

anything of the above jump out as something you'd like to pick up?

**Comment by Olamyy** [comment]
I went through the ASTTransformer PR and it seems fine to me. 
I want to try and move on to setting up tests.
Should these tests be ASTTransformer related or general v2 migration tests?

**Comment by laurenyu** [comment]
@Olamyy just for the `ASTTransformer` and code related to this migration script

**Comment by laurenyu** [comment]
@Olamyy have you had a chance to try working on things here?

**Comment by Olamyy** [comment]
Hi @laurenyu , I currently have a setup here https://github.com/Olamyy/sagemaker-python-sdk/tree/v2-compability-tests/tests/unit/v2 where I plan to write the tests. I've been able to write a simple function to test the output of the ASTTransformer. [here](https://github.com/Olamyy/sagemaker-python-sdk/blob/v2-compability-tests/tests/unit/v2/test_transformer.py). However, i'm honestly not sure what other thing to test. Could you provide some tips on how you'll go about this for me? This would help me decide what tests I need to write and which are not important.

**Comment by laurenyu** [comment]
@Olamyy what you've got is good; I didn't have too much in mind at the time because, you're right, there's not a lot of code in `ASTTransformer`. I think I'd also add a test case where there shouldn't be any change with the code.

The other thing is that we use pytest rather than unittest. I added some tests last week for my more recent changes, so that can help with seeing how some of the unit tests in this repo are written: https://github.com/aws/sagemaker-python-sdk/tree/zwei/tests/unit/sagemaker/cli/compatibility/v2

**Comment by Olamyy** [comment]
Hi @laurenyu , I made a PR with the tests here https://github.com/aws/sagemaker-python-sdk/pull/1555 . 
Please, let me know if there's any fix I need to add.

**Comment by laurenyu** [comment]
as we're nearing the release of v2.0, noting what's left:

* more end-to-end tests, like what was started in #1555.
* some of the other options that TF's script has, such as [handling directories](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py#L77-L86), [printing a report of the changes](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/compatibility/tf_upgrade_v2_main.py#L114-L120), etc.

**Comment by knikure** [comment]
Closing this issue as we no longer need to track the migration from v1 to v2. This Milestone has been already achieved and this looks like a stale issue.
