### ISSUE TITLE
.pd model deployment error, no SavedModel bundles found!

### ISSUE THREAD

**Issue by Xixiong-Guo** [aws/sagemaker-python-sdk#1484]
**Describe the bug**

I am trying to deploy a saved tensorflow+Keras model (saved in .pd and uploaded to S3 together with variables folder), and followed the instruction 
"https://sagemaker.readthedocs.io/en/stable/using_tf.html#deploying-directly-from-model-artifacts" to deploy the predictor, and error comes up

**My code:**

import tarfile
with tarfile.open('model.tar.gz', mode='w:gz') as archive:
    archive.add('export', recursive=True)

import sagemaker
sagemaker_session = sagemaker.Session()
inputs = sagemaker_session.upload_data(path='model.tar.gz', key_prefix='model')

%%time
from sagemaker.tensorflow.serving import Model

model = Model(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz', role= role)
predictor = model.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

**Error**:
UnexpectedStatusException: Error hosting endpoint sagemaker-tensorflow-serving-2020-05-10-01-59-22-414: Failed. Reason:  The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint..

I checked the CloudWatch and said:

INFO:__main__:starting services
Traceback (most recent call last):
  File "/sagemaker/serve.py", line 377, in <module>
    ServiceManager().start()
  File "/sagemaker/serve.py", line 331, in start
    self._create_tfs_config()
  File "/sagemaker/serve.py", line 91, in _create_tfs_config
    raise ValueError('no SavedModel bundles found!')
ValueError: no SavedModel bundles found!

Any thoughts? Thanks a lot!

**Comment by Xixiong-Guo** [comment]
solved!
As the model should be stored in a sub-directory such as ./export/1/.

**Comment by Tanmay-Kant** [comment]
@Xixiong-Guo Was this the line you edited? `model = Model(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz', role= role)`
What was the exact change you made?

**Comment by markandrew8435** [comment]
> @Xixiong-Guo Was this the line you edited? `model = Model(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz', role= role)` What was the exact change you made?

@Xixiong-Guo please reply to this comment
