### ISSUE TITLE
Debugging in local mode

### ISSUE THREAD

**Issue by jackwellsxyz** [aws/sagemaker-python-sdk#1489]
**What did you find confusing? Please describe.**
I'm trying to debug my sagemaker.sklearn.estimator.SKLearn() model in local mode. I've been able to create a script and requirements.txt file, and load data off my hard drive (although the local Docker container seems to choke on not having enough memory if the data is big - this in itself might be something worth adding to the docs). 

My main problem is - is there an easy way to recreate what the SKLearn.fit() command is doing behind the scenes (i.e. what is the docker-compose command) so that I can attach an IDE to it to debug? I had been running into a problem with my Sagemaker script--it worked fine when tested locally through PyCharm, but not when it was run out of the docker container instantiated through SKLearn.fit(). 

I tracked down to an old version of scikit-learn that the SM container uses (0.20 instead of 0.22), so when I upgraded it worked. This was a difficult issue to track down because I had to add a bunch of logging/print statements to figure out why it's crashing, and rerun the docker instantiation (SKLearn.fit({train: xxx}) and hope it gives me more useful errors.

**Comment by ChuyangDeng** [comment]
Hi @jackwellsxyz , unfortunately we do not have use cases attaching an IDE for debugging. However we do support SageMaker Debugger (though not in local mode) if you are interested: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/debugger.py

And some examples to use the debugger: https://github.com/awslabs/amazon-sagemaker-examples/tree/master/sagemaker-debugger

As for the scikit-learn version, looks like the latest framework version supported is 0.20 (https://github.com/aws/sagemaker-scikit-learn-container/tree/master/docker/0.20.0)

I will let our teammate from to update you with plans to upgrade scikit-learn version to 0.22

**Comment by edwardjkim** [comment]
Please note that SageMaker Debugger is only available for deep learning containers and XGBoost. scikit-learn currently does not support Debugger.

The scikit-learn container team is currently actively working on releasing an upgraded scikit-learn container. However, please note that scikit-learn [version 0.23](https://scikit-learn.org/stable/whats_new/v0.23.html) was just released, so it is likely that the next version of container will have version 0.23, not 0.22.

**Comment by jackwellsxyz** [comment]
Thanks @ChuyangDeng and @edwardjkim for considering. I might make it a feature request then, since I personally would find this a very helpful feature. In fact, even if there's more insight into how I can create the docker-compose script and container so I can launch it, that would be excellent. Also great to hear about the scikit-learn 0.23 support, that would be very helpful.

**Comment by edwardjkim** [comment]
@jackwellsxyz Sorry I forgot to address your question on docker. The scikit-learn container is open source https://github.com/aws/sagemaker-scikit-learn-container, so you can modify it as you see fit and use it as a staring point for your [bring-your-own container](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms.html).
