### ISSUE TITLE
ContextualVersionConflict Error

### ISSUE THREAD

**Issue by manojprabhakar90** [aws/sagemaker-python-sdk#1543]
I am using gluonts framework for doing forecasting. While trying to import loaddataset and listdataset, I am getting ContextualVersionConflict error.  

!pip install gluonts

The code was working till last month. now it seems to be not working. 

pandas.__version__  - 1.0.4

---------------------------------------------------------------------------
ContextualVersionConflict                 Traceback (most recent call last)
<ipython-input-11-2adfe439405c> in <module>
----> 1 from gluonts.dataset.common import load_datasets, ListDataset
      2 from gluonts.dataset.field_names import FieldName
      3 
      4 if submission == True:
      5     train_target_values = [ts for ts in series_tot]

/opt/conda/lib/python3.6/site-packages/gluonts/__init__.py in <module>
     21 
     22 try:
---> 23     __version__ = get_distribution(__name__).version
     24 except DistributionNotFound:
     25     __version__ = "0.0.0-unknown"

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py in get_distribution(dist)
    480         dist = Requirement.parse(dist)
    481     if isinstance(dist, Requirement):
--> 482         dist = get_provider(dist)
    483     if not isinstance(dist, Distribution):
    484         raise TypeError("Expected string, Requirement, or Distribution", dist)

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py in get_provider(moduleOrReq)
    356     """Return an IResourceProvider for the named module or requirement"""
    357     if isinstance(moduleOrReq, Requirement):
--> 358         return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
    359     try:
    360         module = sys.modules[moduleOrReq]

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py in require(self, *requirements)
    899         included, even if they were already activated in this working set.
    900         """
--> 901         needed = self.resolve(parse_requirements(requirements))
    902 
    903         for dist in needed:

/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    790                 # Oops, the "best" so far conflicts with a dependency
    791                 dependent_req = required_by[req]
--> 792                 raise VersionConflict(dist, req).with_context(dependent_req)
    793 
    794             # push the new requirements onto the stack

ContextualVersionConflict: (pandas 0.25.3 (/opt/conda/lib/python3.6/site-packages), Requirement.parse('pandas~=1.0'), {'gluonts'})
**System information**
A description of your system. Please provide:
- MXNET
- Kaggle

**Comment by nadiaya** [comment]
Do you get this error on a SageMaker Notebook instance?

**Comment by manojprabhakar90** [comment]
Yeah not in sagemaker.. May be if it can be tagged to personal system, that would be great.
