### ISSUE TITLE
s3Uploader destination clarification

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#1564]
**What did you find confusing? Please describe.**

Whereas the old [Session.upload_data doc](https://sagemaker.readthedocs.io/en/stable/api/utility/session.html#sagemaker.session.Session.upload_data) was very explicit about `key_prefix` being a prefix to which the **base filename from local** would be added, the new [S3Uploader.upload doc](https://sagemaker.readthedocs.io/en/stable/api/utility/s3.html#sagemaker.s3.S3Uploader.upload) makes `desired_s3_uri` sound like the complete URI which should be created by the request.

Having tried it out and accidentally created `data/train.csv/train.csv` in my bucket, it seems like it's still just a prefix.

**Describe how documentation can be improved**

Clearly indicate that `S3Uploader.upload`'s `desired_s3_uri` is a prefix to which the local filename will be added - like the old `Session.upload_data` docs did.

**Additional context**

***Please also note*** that after refactoring to use S3Uploader I'm *still seeing the below deprecation warning* on SDK v1.60.0... I guess one uses the other under the hood and that's not intentional?

```python
sagemaker.s3.S3Uploader.upload("data/train.csv", f"s3://{bucket_name}/data/train.csv")
```
```
'upload_data' method will be deprecated in favor of 'S3Uploader' class (https://sagemaker.readthedocs.io/en/stable/s3.html#sagemaker.s3.S3Uploader) in SageMaker Python SDK v2.
```

**Comment by laurenyu** [comment]
fixed in https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.63.0
