### ISSUE TITLE
Broken PyTorch() doc link to supported PyTorch framework versions

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#1565]
**What did you find confusing? Please describe.**

Broken link at [sagemaker.pytorch.estimator.PyTorch()](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html#sagemaker.pytorch.estimator.PyTorch) `framework_version` param:

> * **framework_version** (str) – PyTorch version you want to use for executing your model training code. List of supported versions https://github.com/aws/sagemaker-python-sdk#pytorch-sagemaker-estimators. If not specified, this will default to 0.4.

This section no longer appears to exist on the target page.

**Describe how documentation can be improved**

Update with a current link to list of supported PyTorch versions

**Additional context**

None

**Comment by laurenyu** [comment]
fixed in https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.63.0
