### ISSUE TITLE
Difference between ScriptProcessor vs Processor

### ISSUE THREAD

**Issue by mdrmuhaimin** [aws/sagemaker-python-sdk#1569]
From [Sagemaker python SDK][1] I have seen two API, [ScriptProcessor][2] and [Processor][3]. It seems like we can achieve the same goals using either of them, the only difference I noticed ScriptProcessor support docker `command` parameter on the other hand Processor support docker `entrypoint` parameter. 

Is there any other difference amongst them? Can we improve the documentation to define when to use which?

  [1]: https://sagemaker.readthedocs.io/en/stable/index.html
  [2]: https://sagemaker.readthedocs.io/en/stable/api/training/processing.html#sagemaker.processing.ScriptProcessor
  [3]: https://sagemaker.readthedocs.io/en/stable/api/training/processing.html#sagemaker.processing.Processor

**Comment by ChuyangDeng** [comment]
Hi @mdrmuhaimi n, from what I understand, the key difference between `Processor` and `ScriptProcessor` is that `ScriptProcessor` takes a `code` parameter that allows you to process data and evaluate model: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/processing.py#L354

Here's some instruction to use `ScriptProcessor`

**Comment by laurenyu** [comment]
I've opened a PR to try and help: #1600. As Chuyang said, the `ScriptProcessor`'s `code` parameter allows you to provide a script to be run as part of the Processing Job.

Docs: https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_processing.html

**Comment by laurenyu** [comment]
doc changes have been released in https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.65.1. feel free to reopen if you have further questions.
