### ISSUE TITLE
Add describe_hyper_parameter_tuning_job() to the SageMaker Session class

### ISSUE THREAD

**Issue by alex23lemm** [aws/sagemaker-python-sdk#1589]
**Is your feature request related to a problem? Please describe.**
A SageMaker Session object comes with the following methods which allow me to retrieve the status of training, batch transform, processing and AutoML jobs: `describe_training_job()`, `describe_transform_job()`, `describe_processing_job()`,  `describe_auto_ml_job()`. Examples:

``` python
import sagemaker

session = sagemaker.Session()
session.describe_training_job("[YOUR_JOB_NAME]")["TrainingJobStatus"]
session.describe_transform_job("[YOUR_JOB_NAME]")["TransformJobStatus"]
session.describe_processing_job("[YOUR_JOB_NAME]")["ProcessingJobStatus"]
session.describe_auto_ml_job("[YOUR_JOB_NAME]")["AutoMLJobStatus"]
```
However, if I like to get the status of a hyperparameter tuning job **in the same workflow**, I need to use one of the following two options:

**Option 1**: Use the following two lines of code

``` python
tuning_job_results = sagemaker.HyperparameterTuningJobAnalytics("[YOUR_JOB_NAME]")
tuning_job_results.description()["HyperParameterTuningJobStatus"]
```

**Option 2**: Create an extra low-level SageMaker client using boto3:

``` python
import boto3

sm = boto3.client("sagemaker")
sm.describe_hyper_parameter_tuning_job(HyperParameterTuningJobName = "[YOUR_JOB_NAME]")["HyperParameterTuningJobStatus"]
```

**Describe the solution you'd like**
Even though the above options work, it could become much more concise and smoother by adding a `describe_hyper_parameter_tuning_job()` method to the SageMaker Session class. This would harmonize the family of `describe_[...]_job()` functions.

**Comment by laurenyu** [comment]
#1594 has been merged. should get released later today

**Comment by laurenyu** [comment]
released in https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.65.0
