### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by metrizable** [aws/sagemaker-python-sdk#1592]
**Is your feature request related to a problem? Please describe.**

Python 3.8.0 was final released [Oct 2019](https://www.python.org/dev/peps/pep-0569/#schedule) and has several useful language features. Users of the SageMaker Python SDK may prefer to develop in 3.8. Offering Python 3.8 as a supported version will lower friction to adoption of this package.

**Describe the solution you'd like**

Supporting Python 3.8 includes:

* Introduce py38 as tox env and upgrade dependencies
* Add py38 as a build target in CI/CD
* Include py38 support in buildspecs
* Declare Python 3.8 support in setup.py
* Release package as supporting Python 3.8 to the Python Package Index

**Describe alternatives you've considered**

n/a

**Additional context**

**Comment by nectario** [comment]
How do I enable Python 3.8 version if I use the generic Estimator?
