### ISSUE TITLE
Can't deploy model to t3 instance types

### ISSUE THREAD

**Issue by thomelane** [aws/sagemaker-python-sdk#1623]
**Describe the bug**

Can't deploy model to t3 instance types. Just hit validation errors.

**To reproduce**
```
model.deploy(
    endpoint_name=explainer_name,
    instance_type='ml.t3.medium',
    initial_instance_count=1
)
```

**Expected behavior**

Would expect the endpoint to deploy successfully on ml.t3.medium instance.

**Screenshots or logs**

```
ClientError: An error occurred (ValidationException) when calling the CreateEndpointConfig operation: 1 validation error detected: Value 'ml.t3.medium' at 'productionVariants.1.member.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [ml.r5d.12xlarge, ml.r5.12xlarge, ml.p2.xlarge, ml.m5.4xlarge, ml.m4.16xlarge, ml.r5d.24xlarge, ml.r5.24xlarge, ml.p3.16xlarge, ml.m5d.xlarge, ml.m5.large, ml.t2.xlarge, ml.p2.16xlarge, ml.m5d.12xlarge, ml.inf1.2xlarge, ml.m5d.24xlarge, ml.c4.2xlarge, ml.c5.2xlarge, ml.c4.4xlarge, ml.inf1.6xlarge, ml.c5d.2xlarge, ml.c5.4xlarge, ml.g4dn.xlarge, ml.g4dn.12xlarge, ml.c5d.4xlarge, ml.g4dn.2xlarge, ml.c4.8xlarge, ml.c4.large, ml.c5d.xlarge, ml.c5.large, ml.g4dn.4xlarge, ml.c5.9xlarge, ml.g4dn.16xlarge, ml.c5d.large, ml.c5.xlarge, ml.c5d.9xlarge, ml.c4.xlarge, ml.inf1.xlarge, ml.g4dn.8xlarge, ml.inf1.24xlarge, ml.m5d.2xlarge, ml.t2.2xlarge, ml.c5d.18xlarge, ml.m5d.4xlarge, ml.t2.medium, ml.c5.18xlarge, ml.r5d.2xlarge, ml.r5.2xlarge, ml.p3.2xlarge, ml.m5d.large, ml.m5.xlarge, ml.m4.10xlarge, ml.t2.large, ml.r5d.4xlarge, ml.r5.4xlarge, ml.m5.12xlarge, ml.m4.xlarge, ml.m5.24xlarge, ml.m4.2xlarge, ml.p2.8xlarge, ml.m5.2xlarge, ml.r5d.xlarge, ml.r5d.large, ml.r5.xlarge, ml.r5.large, ml.p3.8xlarge, ml.m4.4xlarge]
```

**System information**

A description of your system. Please provide:
- **SageMaker Python SDK version**: 1.55.4
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SKLearn
- **Framework version**: 
- **Python version**: 3
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Y

**Additional context**

**Comment by ajaykarpur** [comment]
Hi @thomelane, sorry for the confusion here. If you go to the [Amazon SageMaker Pricing](https://aws.amazon.com/sagemaker/pricing/) page, scroll down to your region, and then expand the `Model Deployment` section, you'll see the list of supported instance types for model deployment. I don't see `ml.t3.medium` listed among these instance types. Please try one of the listed instance types and let us know if you run into any issues.

**Comment by UsamaEjaz0** [comment]
I tried with `ml.t2.medium` as it was available in my region and it worked.

**Comment by richardkmichael** [comment]
On the SageMaker Pricing page, the up-thread mentioned `Model Deployment` section now appears to be named `Real-Time Inference`.
