### ISSUE TITLE
get_image_uri should return latest version of XGBoost by default instead of a previous version

### ISSUE THREAD

**Issue by asimjalis** [aws/sagemaker-python-sdk#1643]
**Describe the bug**
`get_image_uri(region, 'xgboost')` returns a previous version of XGBoost instead of the latest version. When the version is not explicitly specified the default behavior should be to return the latest.

**To reproduce**
Code:
```python
import boto3
from sagemaker.amazon.amazon_estimator import get_image_uri
get_image_uri(boto3.Session().region_name, 'xgboost')
```
Output:
```
'433757028032.dkr.ecr.us-west-2.amazonaws.com/xgboost:1'
```
Error:
```
WARNING:root:There is a more up to date SageMaker XGBoost image. To use the newer image, please set 'repo_version'='1.0-1'. For example:
	get_image_uri(region, 'xgboost', '1.0-1').
```

**Expected behavior**
No warning should occur. 

**Screenshots or logs**
Error:
```
WARNING:root:There is a more up to date SageMaker XGBoost image. To use the newer image, please set 'repo_version'='1.0-1'. For example:
	get_image_uri(region, 'xgboost', '1.0-1').
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: sagemaker 1.66.0    
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: XGBoost
- **Framework version**: 1.0-1
- **Python version**: '3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) \n[GCC 7.2.0]'
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
Using SageMaker notebook instance with `conda_python3` kernel.

**Comment by ajaykarpur** [comment]
@asimjalis Thanks for bringing this to our attention. We are redesigning the functionality to get the image URI in Python SDK v2, so we'll look into modifying the default behavior there: https://github.com/aws/sagemaker-python-sdk/issues/1464

**Comment by davidbrochart** [comment]
@asimjalis since #1464 was merged, did you have a chance to try with SageMaker Python SDK v2 and see if your issue is fixed?

**Comment by asimjalis** [comment]
Appreciate the ping @davidbrochart. I just tested it and the issue is resolved.

**Comment by asimjalis** [comment]
Closing issue.
