### ISSUE TITLE
AlgorithmEstimator does not allow passing some arguments used in EstimatorBase

### ISSUE THREAD

**Issue by saulbein** [aws/sagemaker-python-sdk#1658]
**Describe the feature you'd like**
Some optional arguments (in my case, `train_use_spot_instances` specifically) are not passed from `AlgorithmEstimator` to it's base class, which means that those features can not be used with the convenience class. 

**How would this feature be used? Please describe.**
Same as before, but allowing for extra options.

**Describe alternatives you've considered**
Not using the `AlgorithmEstimator` class, which is inconvenient when I am using my own created algorithms. `Estimator` class has the capability needed, but that will use the docker image rather than the algorithm set in SageMaker. 

**Additional context**
This would not require a breaking change, since the current API assumes default values for the missing options. If the defaults are preserved, this would allow for specifying them and existing user code would still work same as before.

**Comment by metrizable** [comment]
@saulbein Thanks for filing the issue. Good call out. Typically, exposing `**kwargs` as [here](https://github.com/aws/sagemaker-python-sdk/blob/v1.67.1/src/sagemaker/algorithm.py#L56) implies these arguments would be passed on to the base class, but, in this case, [they are not](https://github.com/aws/sagemaker-python-sdk/blob/v1.67.1/src/sagemaker/algorithm.py#L128-L129).

The least invasive solution, as you suggest, is to add the `train_use_spot_instances` and `train_max_wait` (which should also be set, if `train_use_spot_instances` is provided) with default values to the constructor and pass them onto the base.

**Comment by saulbein** [comment]
Assuming this is done, based on #1672
