### ISSUE TITLE
how to provide predictor the endpoint name?

### ISSUE THREAD

**Issue by yolanda0202** [aws/sagemaker-python-sdk#166]
Hi
I have the model in the existing endpoint, and I know if I want to apply this model to the new data, I need to create a Predictor object and provide it the endpoint name.
So here is the question...
How to provide the endpoint name? Could you show me the query I can use? 
 I tried
kmeans_predictor = predictor("kmeans-2018-05-02-16-48-42-652")
but doesn't work.

Thank you!

**Comment by laurenyu** [comment]
I see. In that case, you should be able to use the `RealTimePredictor` class: https://sagemaker.readthedocs.io/en/latest/predictors.html

**Comment by yolanda0202** [comment]
![capture](https://user-images.githubusercontent.com/12420463/39545011-0e3f4a3c-4e0d-11e8-93b2-c260377a2c89.PNG)
Got the error. Anything else I need to set up?

**Comment by laurenyu** [comment]
the `class` keyword in Python is for defining a new [class](https://www.learnpython.org/en/Classes_and_Objects). The error you're seeing indicates that there's an issue with how the words are being used.

Instead, you want to import the class, and then initialize the class:
```python
from sagemaker.predictor import RealTimePredictor

predictor = RealTimePredictor('kmeans-2018-05-02-16-48-42-652')
```

does that make sense?

**Comment by yolanda0202** [comment]
@laurenyu Thank you so much for your explanation! Now I got another bug.

When I'm in the notebook of training the model, it works for me to predict with the pred_set dataset, whose format is exactly as same as the training dataset

kmeans_predictor = kmeans.deploy(initial_instance_count=1,
                                 instance_type='ml.m4.xlarge')

result = kmeans_predictor.predict(pred_set)



But when I called the endpoint in another notebook and trying to predict with the same pred_set dataset

from sagemaker.predictor import RealTimePredictor
predictor = RealTimePredictor('kmeans-2018-05-02-16-48-42-652')
predictor.predict(pred_set)

I got
ParamValidationError: Parameter validation failed:
Invalid type for parameter Body, value: [[  6.   0.   1.   1.  20.]
 [ 12.   0.   7.   1.  13.]
 [  1.   0.   1.   1.   0.]
 ...
 [  9.   0.   1.   1.  26.]
 [ 10.   0.   2.   1.  19.]
 [283.   0. 112.  93.   0.]], type: <class 'numpy.ndarray'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object

**Comment by laurenyu** [comment]
That is because the `RealTimePredictor` doesn't default to a specific content type, while the dataset you're using is a numpy array. You can pass a serializer and deserializer to allow the Predictor to handle numpy arrays.

I probably should've suggested this first instead of the more general case, but you probably can also just use the `KMeansPredictor` class: https://sagemaker.readthedocs.io/en/latest/kmeans.html#sagemaker.KMeansPredictor

**Comment by yolanda0202** [comment]
problem solved! really appreciate your help! @laurenyu

**Comment by laurenyu** [comment]
good to hear, @yolanda0202 - happy to help!

**Comment by githubhnw** [comment]
Hello. I have a similar issue. I'm using a HyperParameterTuner for a Linear Learner model from Sagemaker. And I train it on data stored as record set in S3. When I call predict on a numpy ndarray of test data it gives me the same error as @yolanda0202 . I tried setting the content_type of the RealTimePredictor to 'application/x-recordio-protobuf' and use the test set stored as record set in S3 but it has an error related to batch_size from the logs. My issue is: what serialize and/or deserializer, content_type and accept arguments should be when training and wanting to predict on record sets ? Regards
