### ISSUE TITLE
Error: HTTP content length exceeded 5246976 bytes

### ISSUE THREAD

**Issue by yolanda0202** [aws/sagemaker-python-sdk#171]
I got this error when I using the model sitting in the endpoint to predict with a new data set.  Appreciate if anyone can tell me how to fix it.

ClientError: An error occurred (413) when calling the InvokeEndpoint operation: HTTP content length exceeded 5246976 bytes.

**Comment by laurenyu** [comment]
Hi @yolanda0202, at what point during prediction is this error occurring? Can you provide a stacktrace and any other info you think might be useful?

**Comment by andremoeller** [comment]
Hi @yolanda0202 ,

This means you're sending over 5MB of data in your predictor. There's a 5MB limit with InvokeEndpoint. Would it be possible to send a more compact representation of your data?

**Comment by winstonaws** [comment]
As Andre said, this limit is part of the InvokeEndpoint API itself, so it's likely to be a hard limit for the foreseeable future. https://docs.aws.amazon.com/sagemaker/latest/dg/API_runtime_InvokeEndpoint.html

Resolving this.

**Comment by rhkaz** [comment]
Hi there,

I am using Rstudio with sagemaker. However, I also get the following error as well. I read your comments for the 5MB limit. I have 1 million rows. Does this mean I can not use sagemaker for predictions for large dataset?

> library(stringr)
> predictions <- model_endpoint$predict(test_sample)
 Show Traceback
 
 Rerun with Debug
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ClientError: An error occurred (413) when calling the InvokeEndpoint operation: HTTP content length exceeded 5246976 bytes. 

Thanks in advance !!!

**Comment by jesterhazy** [comment]
Hi!  Thanks for using SageMaker!

The 5MB per request limit was removed from SageMaker earlier this year. You can definitely post individual inference requests that contain more than 5MB. Whether that is the right thing to do to get the best performance will depend on your model. If your 1 million rows are distinct inputs and you want to get a separate prediction for each of them, then posting them in a single request is probably not the best approach -- consider splitting them into smaller batches and making a separate request (possibly in parallel) for each batch. The inference code you deploy to the SageMaker endpoint will need to be written to handle whatever batch size you intend to send to it.

For inference over a large number of items, you may also want to look at [SageMaker Batch Transform](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-batch.html). It will read an input file from S3, transform each item in it using your trained model, and then write all the results to a new S3 file.

**Comment by araitats** [comment]
This happened to me when I modified one of these tensorflow samples and bring in slightly larger images than those in samples (e.g. (1,299,299,3)). 
The following method is just a way-around and may not be the best practice. When an float array is serialized to json/string, the byte size dramatically increases. 

```
 # - This works
data = np.random.randn(1, 299, 299, 3)
predictor2.predict({'image':np.around(data, decimals = 12)}) 

 # - This does not work. 
data = np.random.randn(1, 299, 299, 3)
predictor1.predict({'image':data}) 

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-13-afd656626da4> in <module>()
      4 # The inputs key 'inputs_input' matches the Keras InputLayer name
      5 #predictor.predict({'image_input':data})
----> 6 predictor1.predict({'image':data})
      7 #predictor.predict(data)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/sagemaker/predictor.py in predict(self, data, initial_args)
     76 
     77         request_args = self._create_request_args(data, initial_args)
---> 78         response = self.sagemaker_session.sagemaker_runtime_client.invoke_endpoint(**request_args)
     79         return self._handle_response(response)
     80 

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    318                     "%s() only accepts keyword arguments." % py_operation_name)
    319             # The "self" in this scope is referring to the BaseClient.
--> 320             return self._make_api_call(operation_name, kwargs)
    321 
    322         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    621             error_code = parsed_response.get("Error", {}).get("Code")
    622             error_class = self.exceptions.from_code(error_code)
--> 623             raise error_class(parsed_response, operation_name)
    624         else:
    625             return parsed_response

ClientError: An error occurred (413) when calling the InvokeEndpoint operation: HTTP content length exceeded 5246976 bytes.
```
