### ISSUE TITLE
[Undocumented behavior] `save_checkpoints_secs` defaults to 300, preventing `save_checkpoints_steps` from being used without workaround in TF Estimator

### ISSUE THREAD

**Issue by zmjjmz** [aws/sagemaker-python-sdk#175]
This is a fairly small thing, so I'm skipping the form:

So I've been trying to reproduce a separate issue both in and out of Sagemaker and to do so it's a lot more convenient to save checkpoints as a function of training step rather than as a function of the wall clock timer so as to get consistent results across machines. To do so, you can set `save_checkpoints_steps` in the `RunConfig` that you pass to the `Estimator`. 

However, you cannot set both `save_checkpoints_steps` and `save_checkpoints_secs`. The container [defaults](https://github.com/aws/sagemaker-tensorflow-containers/blob/6feb8162e5dd20c99907dc0a3f1eae823034d3d2/src/tf_container/trainer.py#L60) `save_checkpoints_secs=300`, which is not clear from the documentation. As a result, if you pass `save_checkpoints_steps` with nothing else specified, it will error out, which is a confusing experience. 

There's a rather trivial workaround to this which is to explicitly set `save_checkpoints_secs=None` in the hyperparameters that you send, but it's not clear from the documentation that this is what needs to be done. If the documentation could be amended to reflect that, it'd likely save future users the trouble of diagnosing this themselves.

Alternatively, the container could do something to determine that if `save_checkpoints_steps` is set but `save_checkpoints_secs` is unspecified, it should leave it as `None` rather than the default value.

Thanks!

**Comment by yangaws** [comment]
Hi @zmjjmz ,

Thanks for bringing this.

I will put a feature request mark here and create task in our backlog for:

1, Add validation if both save_checkpoints_steps and save_checkpoints_secs are both set

2, Update documentation to be more clear on best practice of this case

**Comment by laurenyu** [comment]
this issue is for TF "legacy mode," which we've stopped updating releases for. (this is true of both the containers and the relevant docs.)
