### ISSUE TITLE
API restricted to only serve on '/invocations'

### ISSUE THREAD

**Issue by OktayGardener** [aws/sagemaker-python-sdk#176]
### System Information
- Vanilla Python
- 2.7.14
- 2.7.14
- CPU
- 2.7.14
- Yes

### Describe the problem
Whenever I deploy an endpoint, I am restricted in BYO Model and otherwise to adhere to a single endpoint '/invocations'. It would be great to be able to have as many endpoints as you'd like, with the possibility to add what endpoint I want to query in my container as a parameter.

https://docs.aws.amazon.com/sagemaker/latest/dg/API_runtime_InvokeEndpoint.html

Locally, I am able to curl whatever endpoint I'd like with the proper ngix conf, am I able to do this through AWS with access keys as well? In that case, how?

**Comment by andremoeller** [comment]
Hi @OktayGardener ,

I'm not sure if there are currently any plans to add additional endpoints to the hosting model schema. Could you describe how you'd be able to use this feature in more detail?

As for curling endpoints, this post explains how, but it's recommended to use the InvokeEndpoint API call: https://engineering.upside.com/digging-into-aws-sagemaker-first-look-90975d80cd87

Thanks!

**Comment by OktayGardener** [comment]
For example, we have a recommendation model being able to serve different purposes, and we would love to have /user, ..., /item endpoints to make things easy for us with the parsing. It seems like this would be possible if you used `curl`, but otherwise, not really.

**Comment by winstonaws** [comment]
To clarify, currently there is no way to have the request hit a different url from /invocations.

Given that this is a core part of the contract for the InvokeEndpoint API, it's not something SageMaker can change lightly. We'd be interested in hearing your feedback when considering future changes, though. 

Is there a big difference between having the request hit a different url, compared to having your server use the model name parameter in deciding which model to use?

**Comment by winstonaws** [comment]
Yea, given the overloading of "endpoint", let me see if we're on the same page -

Your goal is to have one SageMaker endpoint to be able to serve multiple types of requests, right? So in your example, if it were a regular HTTP request, you could either make the request /user?id=5 or /item?id=5. That makes sense to me.

I can talk to the Hosting team to see how they feel about supporting this feature in the longer term, but that change is unlikely to happen quickly, as AWS service APIs are expensive to change.

My suggestion to unblock yourself in the meantime is to instead do something like:

/invocations?type=user&id=5

Does that work for you? Or is the problem that the client needs to make the request in the /user?id=5 format?

**Comment by nadiaya** [comment]
@OktayGardener 

I am going to close this issue due to inactivity. If you still have questions, please re-open it.
