### ISSUE TITLE
Content gap: Documentation for the Built-in algorithms is incomplete

### ISSUE THREAD

**Issue by mchoi8739** [aws/sagemaker-python-sdk#1779]
**What did you find confusing? Please describe.**

I had a look at our current docs and found gaps in the Algorithm documentations between the [AWS dev guide](https://docs.aws.amazon.com/sagemaker/latest/dg/algos.html) and [readthedocs.io](https://sagemaker.readthedocs.io/en/stable/algorithms/index.html).

The AWS dev guide lists all algos that are officially released (left column below), but some of them are not documented in readthedocs.io (right column below).

AWS dev guide | pySDK in First-Party Algorithms
-- | --
BlazingText |  (missing)
DeepAR Forecasting |  (missing)
Factorization Machines | FactorizationMachines
Image Classification Algorithm |  (missing)
IP Insights | IP Insights
K-Means Algorithm | K-means
K-Nearest Neighbors (k-NN) Algorithm | K-Nearest Neighbors
Latent Dirichlet Allocation (LDA) | LDA
Linear learner algorithm | LinearLearner
Neural Topic Model (NTM) Algorithm | NTM
Object2Vec | Object2Vec
Object Detection Algorithm |  (missing)
Principal Component Analysis (PCA) Algorithm | PCA
Random Cut Forest (RCF) Algorithm | Random Cut Forest
Semantic Segmentation |  (missing)
Sequence to Sequence (seq2seq) |  (missing)
XGBoost | XGBoost (is under the Framework node)

In case of XGBoost, I suggest to list it with the other algos and provide a link to the exisiting XGBoost in the Framework node with a short explanation of why XGBoost is under Frameworks.

**Describe how documentation can be improved**

* Add the 6 missing algorithms to the readthedoc.io 1p algorithm section.
* Add XGBoost to the 1p algorithm section as well, and link to the existing XGBoost documentation under the Frameworks node.

**Comment by IvyBazan** [comment]
List of Built-in algorithms in pySDK documentation includes all algorithms in the AWS dev guide
