### ISSUE TITLE
Document support of inference_response_keys on AutoML.deploy()

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#1797]
**What did you find confusing? Please describe.**

[AutoML.create_model()](https://sagemaker.readthedocs.io/en/stable/api/training/automl.html#sagemaker.automl.automl.AutoML.create_model) supports an `inference_response_keys` parameter which controls what kind of results the created model produces: e.g. Label, top label confidence and/or all confidences for multiclass classification.

[AutoML.deploy() doc](https://sagemaker.readthedocs.io/en/stable/api/training/automl.html#sagemaker.automl.automl.AutoML.deploy) does not mention the `inference_response_keys` parameter or any default behaviour of additional kwargs...

...However, it is possible to pass `inference_response_keys` in and the created endpoint will respond as specified.

**Describe how documentation can be improved**

Best would be to explicitly support this argument, because it's important for how the results of the model will be consumed as it significantly changes the API contract.

Documentation could also be improved to indicate what parent/downstream methods unlisted kwargs will be sent to.

**Additional context**

N/A

**Comment by ChuyangDeng** [comment]
Hi @athewsey , I think ``AutoML.deploy()`` does have a docstring regarding ``inference_response_keys``, is this what you are looking for? https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/automl/automl.py#L397

**Comment by athewsey** [comment]
Thanks @ChuyangDeng - Agreed this is now present on the [AutoML.deploy() doc](https://sagemaker.readthedocs.io/en/stable/api/training/automl.html#sagemaker.automl.automl.AutoML.deploy) as I originally linked: I assume the `stable` tag just updated or something since I saw it!

Docs look fine on this feature, so happy to close.
