### ISSUE TITLE
`sagemaker.session.s3_input` or `sagemaker.inputs.s3_input`?

### ISSUE THREAD

**Issue by dz902** [aws/sagemaker-python-sdk#1798]
**What did you find confusing? Please describe.**
`sagemaker.session.s3_input()` or `sagemaker.inputs.s3_input()`?

While I found no code using the latter, it is the only document entry. `s3_input` is not listed in the Session page where I would expect it.

**Describe how documentation can be improved**
I'm not sure whether this is a convention of Python docs but it is confusing. If it is to be used as `sagemaker.session.s3_input()` then it should be documented as such.

I also found the use of `sess = sagemaker.Session()` but in the docs it is `sagemaker.session.Session()`.

To save another issue, I also found `from sagemaker.amazon.amazon_estimator import get_image_uri` in official examples but that function was not documented.

These are quite confusing for SageMaker new comers. Hope these can be fixed somehow.

Thanks!

**Comment by ajaykarpur** [comment]
Thanks for bringing this to our attention, @dz902. We're actually planning on [consolidating and renaming this functionality](https://github.com/aws/sagemaker-python-sdk/blob/e774fcf37e943bb91f9c2668019f20f0f325c6da/src/sagemaker/inputs.py#L83-L85) in [Python SDK v2](https://github.com/aws/sagemaker-python-sdk/issues/1459), which will be released soon.

Please let us know if you'd like any additional information or clarification.
