### ISSUE TITLE
**kwargs from HyperparameterTuner class fit method doesn't work.

### ISSUE THREAD

**Issue by BrenoVC** [aws/sagemaker-python-sdk#1804]
**Describe the bug**
The HyperparameterTuner class has a fit method that accepts **kwargs with additional arguments to pass for training, but when I give arguments like "experiment_config", "wait or "logs" they are ignored and my training jobs initialized by this tuner don't receive them in their fit method. However these arguments are defined on EstimatorBase.fit() method.

**To reproduce**
Try to give other arguments to fit method of HyperparameterTuner class, as "wait" or "experiment_config" and you will see that they are ignored when this method is called.

**Expected behavior**
I would expect that these arguments would be given to the other fit method that is defined in EstimatorBase class.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: stable.
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Scikit-learn.
- **Framework version**: 0.23-1
- **Python version**: 3.7
- **CPU or GPU**: Using Amazon sagemaker instance 'ml.m5.xlarge'.
- **Custom Docker image (Y/N)**: N

**Additional context**
None.

**Comment by ChuyangDeng** [comment]
Hi @BrenoVC, a hyperparameter tuning job is essentially this: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateHyperParameterTuningJob.html, which does not accept ALL the parameters that training job receive (e.g. ExperimentConfig: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html)

However, the hyperparameter tuner's ``fit()`` function does accept ``wait`` (https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tuner.py#L372)

**Comment by BrenoVC** [comment]
I was checking the source code and you are right. I was confused because the documentation gives us an idea that you can give to fit function other arguments to be used in the training job and this would be a good improvement, but it's not the case now.

It would be useful to have experiment configs in all training jobs initialized by the tuning job, so we could have track of them inside the sagemaker studio using the experiment tab.

Thank you for the explanation.
