### ISSUE TITLE
Add ContainerArguments to sagemaker.estimator.Estimator

### ISSUE THREAD

**Issue by tchaton** [aws/sagemaker-python-sdk#1837]
**Describe the feature you'd like**
A clear and concise description of the functionality you want.

Allow to pass arguments to ContainerEntrypoint for sagemaker.estimator.Estimator as ContainerArguments similar to ScriptProcessor

ContainerEntrypoint should be flexible enough to enable several arguments parser to be applied such as argparse or Hydra https://github.com/facebookresearch/hydra. I guess the simplest would be the pass arguments as a single string and to concatenate with train or serve ContainerEntrypoint.

**How would this feature be used? Please describe.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

```python
estimator = sagemaker.estimator.Estimator(image,
                       role, 
                        1,
                       'ml.c4.2xlarge',
                       output_path="s3://{}/output".format(sess.default_bucket()),
                       sagemaker_session=sess,
                       container_entrypoint={
                            "train":"+model_name=my_model --my_dataset=my_dataset ",
                            "serve":"+model_weight_selection=miou"
                        }
)
```

**Describe alternatives you've considered**

Currently, I am using sed to overrides default missing arguments from hydra conf yaml file when building the docker image.

**Additional context**

**Comment by dudulasry** [comment]
Is there an update regarding this functionality? I also need this feature

**Comment by zhazhn** [comment]
why not response? this feature should be provided.

**Comment by celsofranssa** [comment]
> Is there an update regarding this functionality? I also need this feature.

Hello @zhazhn, do you find a workaround? 
This sagemaker team seems not to care about the community.

**Comment by celsofranssa** [comment]
> **Describe the feature you'd like** A clear and concise description of the functionality you want.
> 
> Allow to pass arguments to ContainerEntrypoint for sagemaker.estimator.Estimator as ContainerArguments similar to ScriptProcessor
> 
> ContainerEntrypoint should be flexible enough to enable several arguments parser to be applied such as argparse or Hydra https://github.com/facebookresearch/hydra. I guess the simplest would be the pass arguments as a single string and to concatenate with train or serve ContainerEntrypoint.
> 
> **How would this feature be used? Please describe.** A clear and concise description of the use case for this feature. Please provide an example, if possible.
> 
> ```python
> estimator = sagemaker.estimator.Estimator(image,
>                        role, 
>                         1,
>                        'ml.c4.2xlarge',
>                        output_path="s3://{}/output".format(sess.default_bucket()),
>                        sagemaker_session=sess,
>                        container_entrypoint={
>                             "train":"+model_name=my_model --my_dataset=my_dataset ",
>                             "serve":"+model_weight_selection=miou"
>                         }
> )
> ```
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> Currently, I am using sed to overrides default missing arguments from hydra conf yaml file when building the docker image.
> 
> **Additional context** Add any other context or screenshots about the feature request here.

Hello @tchaton, do you find a workaround?
This sagemaker team seems not to care about the community's needs.

**Comment by celsofranssa** [comment]
@metrizable, any update on this?

**Comment by celsofranssa** [comment]
@martinRenou, any update on this?

**Comment by akrishna1995** [comment]
We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.

**Comment by ouj** [comment]
What a bummer. I was planning to start using Hydra to manage the config files. There is just so many irritating things around sagemaker, I should just look for an alternative.

**Comment by tikr7** [comment]
I wanted to pass arguments into the Estimator. The way I found is:
```
estimator = Estimator(...
                      container_entry_point=["/usr/bin/python3"],
                      container_arguments=["/opt/ml/code/training.py", "--instances", "test,test"]
```

Maybe it helps somebody.

**Comment by charleswilmot** [comment]
So what is the best practice as of 2024?

**Comment by ouj** [comment]
the best practice as of 2024 is NOT to use SageMaker.

**Comment by ahmednmourad** [comment]
A workaround that I found out we can use `hyperparameters` which gets passed to the entrypoint as arguments.

For example:
```python
estimator = Estimator(
        ............
        entry_point="train.py",

        # This will not work
        # container_arguments=[
        #     "--input-dir",
        #     "/opt/ml/input/data/train",
        #     "--input-file",
        #     "test.parquet",
        # ],

        # Will translate into `/usr/local/bin/python3 train.py --input-dir /opt/ml/input/data/train --input-file test.parquet`
        hyperparameters={
            "input-dir": "/opt/ml/input/data/train",
            "input-file": "test.parquet"
        },
)
```

One downside is that hyperparameters has a limit of 256 characters [SageMaker API HyperParameters](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html#sagemaker-CreateTrainingJob-request-HyperParameters), but for my case it was enough. Hope that helps someone!
