### ISSUE TITLE
add output_path to Processor

### ISSUE THREAD

**Issue by ajaykarpur** [aws/sagemaker-python-sdk#1892]
**Describe the feature you'd like**
`output_path` should be added to the `Processor` class so that users can specify a custom bucket with encryption for output.

**How would this feature be used? Please describe.**
This would be used when users do not have the ability to use the default bucket and wish to use a custom bucket instead.

**Comment by ChuyangDeng** [comment]
We also want to add `kms_key` option to the `run` method so that user code could be uploaded to S3 with encryption.

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/processing.py#L405
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/s3.py#L73

**Comment by ChuyangDeng** [comment]
It looks like customized s3 output paths for outputs option is already supported: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/processing.py#L116

This parameter `outputs` accepts a list of path strings or `ProcessingOutput` objects that will later get added into the ProcessingJob request arguments together with the `output_kms_key`: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/processing.py#L685-L689

And we have tests for it: https://github.com/aws/sagemaker-python-sdk/blob/master/tests/unit/test_processing.py#L168

**Comment by chris-moov** [comment]
Is there a way to specify a specific folder within the default bucket provided by the SageMaker `Session`?

**Comment by davidbrochart** [comment]
@chris-moov it looks like it is possible, since a `ProcessingOutput` [destination](https://sagemaker.readthedocs.io/en/stable/api/training/processing.html#sagemaker.processing.ProcessingOutput) can be of the form: `s3://<default-bucket-name>/<job-name>/output/<output-name>`.
If you think this issue is fixed, could you please close it?

**Comment by akrishna1995** [comment]
Closing based on @davidbrochart comment. Please feel free to reopen if the issue still persists
