### ISSUE TITLE
sagemaker.image_uris.retrieve for custom docker images in ecr (no framework)

### ISSUE THREAD

**Issue by walter-hernandez** [aws/sagemaker-python-sdk#1902]
**What did you find confusing? Please describe.**
The call [`sagemaker.amazon.amazon_estimator.get_image_uri` was migrated to `sagemaker.image_uris.retrieve` ](https://github.com/aws/sagemaker-python-sdk/issues/1464). There is no information about how to make the calls to get the image url of a custom docker image in ecr that was created using Sagemaker .

**Describe how documentation can be improved**
How do you make the call to get the uri of custom docker image using the library sagemaker-training? This docker image is not using any of the prebuilt frameworks.

**Additional context**
Before you just did:
`container_image_uri = get_image_uri(repo_name, repo_region, repo_version)`

The above was specially useful when you were bringing your own custom docker images that were not using a framework in particular.

Kind regards,

Walter

**Comment by ChuyangDeng** [comment]
Hi @walter-hernandez, the `image_uris.retrieve()` does not support customized docker images. `image_uris` will only retrieve prebuilt images listed here: https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/image_uri_config

If you wish to use customized images, please use `image_uri` parameter in your `estimator` or `model` constructors:
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L1483
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model.py#L36

**Comment by walter-hernandez** [comment]
Thank you for your quick answer!

I was using `get_image_uri ` as an automatic way to get the container url in ecr to pass to the estimator, but for what I see, it is not possible to do so anymore with the way that `image_uris.retrieve()` works

**Comment by walter-hernandez** [comment]
I am closing this issue. I am leaving a solution here if someone comes in the future into this thread with the same issue, a solution to get the container ecr uri is to do:
`'{0}.dkr.ecr.{1}.amazonaws.com/{2}:{3}'.format(account_id, region_name, ecr_repository_name, version)`
