### ISSUE TITLE
Error while creating a new container image

### ISSUE THREAD

**Issue by 11elangelm** [aws/sagemaker-python-sdk#1906]
**Describe the bug**
Error on a sagemaker instance while creating a new container. 

**To reproduce**
%%sh
# The name of our algorithm
algorithm_name=sagemaker-python
set -eu # stop if anything fails
account=$(aws sts get-caller-identity --query Account --output text)
# Get the region defined in the current configuration (default to us-west-2 if none defined)
region=$(aws configure get region)
region=${region:-us-east-2}
fullname="${account}.dkr.ecr.${region}.amazonaws.com/${algorithm_name}:latest"
# If the repository doesn't exist in ECR, create it.
aws ecr describe-repositories --repository-names "${algorithm_name}" > /dev/null 2>&1
if [ $? -ne 0 ]
then
    aws ecr create-repository --repository-name "${algorithm_name}" > /dev/null
fi
# Get the login command from ECR and execute it directly
$(aws ecr get-login --region ${region} --no-include-email)
# Build the docker image locally with the image name and then push it to ECR
# with the full name.
docker build  -t ${algorithm_name} . ***this line returns '' returned non-zero exit status 1.
docker tag ${algorithm_name} ${fullname}
docker push ${fullname}

**Expected behavior**
This should create the docker image in my ecr repository.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.
![image](https://user-images.githubusercontent.com/8346056/93536734-fd1ede00-f906-11ea-82c0-2bb0c7f80ddc.png)

**System information**
Conda_python 3. Python. 

**Additional context**
I'm following this link
https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/pipe_bring_your_own/pipe_bring_your_own.ipynb

**Comment by icywang86rui** [comment]
@11elangelm I think the problem is that the user you are running as is not the owner of the directory where you are running the docker commands from. I would switch to a different directory or create a new one to try again.

It's not clear to me that how are you running this code. Did you just run it on a ec2-instance or in a SageMaker notebook?
