### ISSUE TITLE
docs build fail on Sphinx v3.2.1

### ISSUE THREAD

**Issue by aaronmarkham** [aws/sagemaker-python-sdk#1912]
**Describe the bug**

```
Warning, treated as error:
/home/ubuntu/anaconda3/envs/sagemaker/lib/python3.7/site-packages/sagemaker/amazon/linear_learner.py:docstring of sagemaker.LinearLearner:184:Field list ends without a blank line; unexpected unindent.
```

**To reproduce**
Setup an env w/ the latest Sphinx (3.2.1) and build the docs.

**Comment by icywang86rui** [comment]
There seem to be a bug in Sphinx 3.2.1 that causes this - https://github.com/sphinx-doc/sphinx/issues/8190
It should be fixed in 3.3.

**Comment by metrizable** [comment]
This is also a little surprising, given that the `sphinx` tox target creates an isolated environment and [installs](https://github.com/aws/sagemaker-python-sdk/blob/v2.14.0/tox.ini#L107) its [requirements, including specifying `sphinx==3.1.1`](https://github.com/aws/sagemaker-python-sdk/blob/v2.14.0/doc/requirements.txt#L1).

@aaronmarkham Can you describe how you are building the docs? Is it being done outside of a `tox` env?

**Comment by icywang86rui** [comment]
It seems like there is nothing actionable here for us other than waiting for 3.3 to be released. Resolving. @aaronmarkham feel free to reopen if you need to upgrade to v3.2.1 now.
