### ISSUE TITLE
Make the link to the base class under **kwargs clickable to easily surface additional parameters that can be passed to the derived class.

### ISSUE THREAD

**Issue by kamwang-aws** [aws/sagemaker-python-sdk#1924]
**What did you find confusing? Please describe.**
Most of the time, it is Not clear enough what additional parameters can be passed to the derived class. For example kwargs here https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/pytorch/model.py#L109 . Thus, some users are not aware that sagemaker_session can be passed as a parameter to sagemaker.pytorch.model.PyTorchModel to specify a default bucket. This would prevent users from running into the common error of "access denid while creating a bucket" when a session is not passed and SageMaker attempt to create a new one.

**Describe how documentation can be improved**
While the Tip says that one can find additional parameters for initializing this class at the bases FrameworkModel and Model, it would be better to make reference to the base classes (FrameworkModel and Model) directly clickable from kwargs like we do it here https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/pytorch/model.py#L115

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by metrizable** [comment]
@kamwang-aws 

Thanks for your suggestion. PR [1942](https://github.com/aws/sagemaker-python-sdk/pull/1942) should address the docs improvement.
