### ISSUE TITLE
"distribution" parameter should be "distributions"

### ISSUE THREAD

**Issue by DubiousLatchkey** [aws/sagemaker-python-sdk#1925]
There are code typos in the page about adapting your local tensorflow script.  In the sections about distributed training, the "distribution" parameter is referenced as the way to enable distributed training.  This is a typo, as each instance of "distribution" should be "distributions".

https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/using_tf.html#distributed-training

**Comment by icywang86rui** [comment]
We have released breaking change in V2 to rename the argument - 
https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.md#breaking-changes-1

Closing the issue. Feel free to reopen if you have any questions.
