### ISSUE TITLE
Broken link in Documentation

### ISSUE THREAD

**Issue by LiutongZhou** [aws/sagemaker-python-sdk#1931]
The link for [Bringing your own estimator for hyperparameter tuning](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/hyperparameter_tuning/r_bring_your_own/hpo_r_bring_your_own.ipynb) in the [overview page](https://github.com/aws/sagemaker-python-sdk/blob/f99e48f93e6788281c240ff31f69eb331bd71de2/doc/overview.rst) of the documentation leads to a **page not found**· 

Please update the link.

**Comment by metrizable** [comment]
@LiutongZhou Thanks for reporting the broken link in the documentation.

The [linked PR](https://github.com/aws/sagemaker-python-sdk/pull/1940) should address the issue.
