### ISSUE TITLE
Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.

### ISSUE THREAD

**Issue by sumankamilya** [aws/sagemaker-python-sdk#1968]
2020-10-23 12:04:45 Starting - Starting the training job...
2020-10-23 12:04:48 Starting - Launching requested ML instances......
2020-10-23 12:06:01 Starting - Preparing the instances for training......
2020-10-23 12:06:59 Downloading - Downloading input data.........
2020-10-23 12:08:36 Training - Downloading the training image.........
2020-10-23 12:09:56 Failed - Training job failed
..
---------------------------------------------------------------------------
UnexpectedStatusException                 Traceback (most recent call last)
<ipython-input-25-e218a06ec66b> in <module>
----> 1 model.fit(inputs=data_channels, logs=True)

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name, experiment_config)
    497         self.jobs.append(self.latest_training_job)
    498         if wait:
--> 499             self.latest_training_job.wait(logs=logs)
    500 
    501     def _compilation_job_name(self):

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in wait(self, logs)
   1137         # If logs are requested, call logs_for_jobs.
   1138         if logs != "None":
-> 1139             self.sagemaker_session.logs_for_job(self.job_name, wait=True, log_type=logs)
   1140         else:
   1141             self.sagemaker_session.wait_for_job(self.job_name)

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/sagemaker/session.py in logs_for_job(self, job_name, wait, poll, log_type)
   3075 
   3076         if wait:
-> 3077             self._check_job_status(job_name, description, "TrainingJobStatus")
   3078             if dot:
   3079                 print()

~/anaconda3/envs/amazonei_mxnet_p36/lib/python3.6/site-packages/sagemaker/session.py in _check_job_status(self, job, desc, status_key_name)
   2669                 ),
   2670                 allowed_statuses=["Completed", "Stopped"],
-> 2671                 actual_status=status,
   2672             )
   2673 

UnexpectedStatusException: Error for Training job object-detection-2020-10-23-12-04-45-594: Failed. Reason: ClientError: Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.

**Comment by icywang86rui** [comment]
@sumankamilya 
Which version of sagemaker SDK are you using? 
Could you show me the code you use to start the training job?

**Comment by kilsenp** [comment]
@sumankamilya Could you solve it?
