### ISSUE TITLE
Intermittent broken pipe error while waiting for endpoint

### ISSUE THREAD

**Issue by pinaraws** [aws/sagemaker-python-sdk#1978]
**Describe the bug**
Intermittent broken pipe error seen while waiting for endpoint.

**To reproduce**
Create an endpoint and wait.

**Expected behavior**
Wait should return with no error.

**Screenshots or logs**
```
    self.__sagemaker_session.wait_for_endpoint(self.__endpoint_name)
  File "/root/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sagemaker/session.py", line 2876, in wait_for_endpoint
    desc = _wait_until(lambda: _deploy_done(self.sagemaker_client, endpoint), poll)
  File "/root/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sagemaker/session.py", line 3789, in _wait_until
    result = callable_fn()
  File "/root/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sagemaker/session.py", line 2876, in <lambda>
    desc = _wait_until(lambda: _deploy_done(self.sagemaker_client, endpoint), poll)
  File "/root/.pyenv/versions/3.7.7/lib/python3.7/site-packages/sagemaker/session.py", line 3772, in _deploy_done
    print(hosting_status_codes.get(status, "?"), end="")
BrokenPipeError: [Errno 32] Broken pipe
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.5.5
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.7.7
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by ChoiByungWook** [comment]
Hello @pinaraws,

Thanks for bringing this to our attention!

Can you please provide a minimal repro for this?

Is this a consistent issue still?

Thanks!

**Comment by pinaraws** [comment]
We have not encountered this again in the last couple of months. You may close the issue. Thanks for taking a look.
