### ISSUE TITLE
Enable type checking on PR builds

### ISSUE THREAD

**Issue by ahsan-z-khan** [aws/sagemaker-python-sdk#1982]
**Describe the feature you'd like**
Enable type checking  PR builds. `mypy` type checker is not enabled on the PR builds.
https://github.com/aws/sagemaker-python-sdk/blob/master/tox.ini#L133

**How would this feature be used? Please describe.**
It will enable static type checking on the code during PR builds.

**Additional context**
This needs to be enables during PR builds
```
[testenv:typing]
deps = mypy
commands =
    mypy src/sagemaker

```

**Comment by liujiaorr** [comment]
Any update if feature request has been processed or still in needed?

**Comment by liujiaorr** [comment]
Check has been added, close the issue
