### ISSUE TITLE
Setup spelling check

### ISSUE THREAD

**Issue by ahsan-z-khan** [aws/sagemaker-python-sdk#1983]
**Describe the feature you'd like**
Would like to setup spelling check

**How would this feature be used? Please describe.**
It will help check the spelling on the documentations

**Additional context**
This test needs to be added
```
[testenv:spelling]
skipdist = true
skip_install = true
deps =
    pyenchant
    pylint
commands =
    python -m pylint --rcfile=.pylintrc --disable all --enable spelling --spelling-dict en_US src/sagemaker/{posargs}
```

**Comment by martinRenou** [comment]
This has been resolved: https://github.com/aws/sagemaker-python-sdk/blob/master/tox.ini#L100
