### ISSUE TITLE
sagemaker.image_uris.retrieve:  FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/image_uri_config/us-east-1.json'

### ISSUE THREAD

**Issue by cfregly** [aws/sagemaker-python-sdk#1985]
sagemaker==2.16.1 (latest as of this issue) and python3.6 in SageMaker Notebook Instances (not SM Studio):

```
container = sagemaker.image_uris.retrieve(region_name, "blazingtext", "latest")
```

FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/image_uri_config/us-east-1.json'

**Comment by Ayushi96** [comment]
I am facing the same issue! Any help ?

**Comment by ajaykarpur** [comment]
Your parameters are in the wrong order: https://sagemaker.readthedocs.io/en/stable/api/utility/image_uris.html#sagemaker.image_uris.retrieve

Change your code to the following and it should work:
```python
container = sagemaker.image_uris.retrieve("blazingtext", region_name, "latest")
```

Alternatively, you can use keyword arguments, like so:
```python
container = sagemaker.image_uris.retrieve(
    region=region_name,
    framework="blazingtext",
    version="latest")
```

**Comment by cfregly** [comment]
@ajaykarpur in specifying keyword args in my function invocation.  I never rely on the ordering of parameters for exactly this reason.

This should remain open unless I’m missing something.

**Comment by cfregly** [comment]
gotcha.  i was, indeed, missing something.  this is working.  thanks!

**Comment by pscsudal** [comment]
Thank you. I troubled same problem. :)

**Comment by qwe1256** [comment]
I have the same problem. Do you know how to fix it?

**Comment by kislayamourya201** [comment]
I have the same issue while getting xgboost model. Any one got the fix?
My code:
container=sagemaker.image_uris.retrieve("xgboost", region, "1.2-1",py_version=3.6)
print(container)

Output:FileNotFoundError: [Errno 2] No such file or directory: '/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker/image_uri_config/xgboost.json'
