### ISSUE TITLE
XGBoost Tutorial but with error

### ISSUE THREAD

**Issue by bilative** [aws/sagemaker-python-sdk#1986]
Hi,

I'm trying to adapt [this tutorial](https://aws.amazon.com/getting-started/hands-on/build-train-deploy-machine-learning-model-sagemaker/)  to my data. But when i try to fit my model, an error returns to me like this:

**2020-11-10 14:44:26 Starting - Starting the training job...**
**2020-11-10 14:44:29 Starting - Launching requested ML instances......**
**2020-11-10 14:45:33 Starting - Preparing the instances for training......**
**2020-11-10 14:46:37 Downloading - Downloading input data**
**2020-11-10 14:46:37 Training - Downloading the training image...**
**2020-11-10 14:47:24 Failed - Training job failed**
**Cannot pull algorithm container. Either the image does not exist or its permissions are incorrect.**

Now, things you could wanna now:
1. My data 10000x7 with headers,
2. My region is "eu-central-1", so i change/update my xgboost container info [from this ](https://docs.aws.amazon.com/sagemaker/latest/dg/sagemaker-algo-docker-registry-paths.html) like this:
**"eu-central-1:492215442770.dkr.ecr.eu-central-1.amazonaws.com/xgboost:latest"**
3. my sagemaker version is '1.72.1'
4. I log in as main user, so i think it is not about permission. I checked my role have fullaccess,
5. and i have some cridits, so i think i have no problem about limits.

So, i wonder what are you think about this. Where am i wrong? 

If you want any other information about my trials, i can show you everything. I wanna solve the sagemaker.

Thanks in advance

**Comment by ajaykarpur** [comment]
Hi @bilative, can you try upgrading the SageMaker Python SDK to the latest version?

```
pip install --upgrade sagemaker
```

**Comment by bilative** [comment]
Thank you i solved the problem thanks to you. But there is a question on my mind, this tutorial could be old version because in a step when i use "s3_input" there was a warning message like this: 

- 's3_input' class will be renamed to 'TrainingInput' in SageMaker Python SDK v2.

But it is not problem like you see.

Anyway, thank you again.

**Comment by martinRenou** [comment]
Closing as answered, thank you!
