### ISSUE TITLE
"Unable to local credentials" error is happening a lot inside SageMaker Notebooks

### ISSUE THREAD

**Issue by cfregly** [aws/sagemaker-python-sdk#1996]
![image](https://user-images.githubusercontent.com/1438064/99761274-8c34a780-2aaa-11eb-9e52-550d8b426a57.png)

**Comment by icywang86rui** [comment]
@cfregly 
* Are you running a specific example notebook? 
* Are you using sagemaker python sdk in your notebook? 
* Are you running notebook instances or studio?
* How did you setup your execution role for the notebook?

**Comment by cfregly** [comment]
It happens sporadically.  Classic SM notebook instances.  Any notebook.

Started happening more with sagemaker sdk 2.x.  Same code and IAM roles that we’ve been using for 1 year:  https://github.com/data-science-on-aws/workshop

Either a cell re-run or notebook kernel restart + Run All helps, but it’s very disruptive and unpredictable.

**Comment by cfregly** [comment]
any update?

**Comment by SameerJain901** [comment]
Even I am having similar issue(Tried restarting the kernel as well):
![image](https://user-images.githubusercontent.com/33768055/101327825-41ca6d80-3895-11eb-96cd-234f33ad7ef0.png)
