### ISSUE TITLE
[Feature Request] TensorRT installed by default into SageMaker notebooks

### ISSUE THREAD

**Issue by austinmw** [aws/sagemaker-python-sdk#1999]
**Describe the feature you'd like**
If there are no licensing issues, I'd love it if TensorRT was installed into SageMaker notebooks by default.

**How would this feature be used? Please describe.**
TensorRT is still quite a pain / time consuming to install. It'd be great if a version of it was installed into notebooks by default. Maybe this could be installed if a GPU instance type is selected.

**Comment by shreyapandit** [comment]
Hello Austin,
    
Thanks again for contacting us. Closing this issue since this request is unrelated to the SageMaker Python SDK.
     
Best regards,
Regards
