### ISSUE TITLE
Durability or github integration of jupyter notebook

### ISSUE THREAD

**Issue by richardxin** [aws/sagemaker-python-sdk#20]
I was very impressed with quality and rich functionalities of the first release of sagemaker. Great job!

I might have missed those features, but I would like to see improved durability of the sagemaker notebooks, i.e. the notebooks can be stored on S3, or even better github integration of the notebooks.

Thanks!

**Comment by iquintero** [comment]
Hi @richardxin 

Thanks for your interest in SageMaker! I will recommend you to post your suggestion in the AWS Forums where the Notebook team will be able to see it. [SageMaker Forums](https://forums.aws.amazon.com/forum.jspa?forumID=285&start=0)

I will close this issue for now as this feature request is not part of the python sdk itself.
