### ISSUE TITLE
The trained model can be deployed on the other platform without dependency of sagemaker or aws service?

### ISSUE THREAD

**Issue by giggle0312** [aws/sagemaker-python-sdk#200]
The output of the training model operation is model artifacts stored on S3 bucket, I did not find the path of docker image. Therefore, I want to ask a question that if the trained model can be deployed on the other platform without sagemaker or aws service,for example I download the artifacts and docker image to deploy on local environment?

**Comment by juliensimon** [comment]
Yes, you can download the model from S3 and use it anywhere else. 

For Docker images, only the Tensorflow and MXNet containers have been open sourced (you'll find them on Github) but you don't need them to use a model trained on SageMaker. You can use vanilla Tensorflow and MXNet.

**Comment by giggle0312** [comment]
@juliensimon Thank you very much. I find the model artifacts on the S3 bucket which can be download. But I unzip the model.tar.gz , I don't know how to use it for predict. Can you help give me a explanation about how to deply a trained model on local environment and use it to make some predicts with the local data?

**Comment by winstonaws** [comment]
Hi @giggle0312 - 

1. If you want to make a prediction locally using the docker image, the easiest way to do so is to use the SageMaker Python SDK's local mode - https://github.com/aws/sagemaker-python-sdk#sagemaker-python-sdk-overview (see the section labeled "Local Mode")

What this will do for you is download the appropriate image, set up the environment, and run the image as if it was on sagemaker.

2. As @juliensimon said, you can also take the model artifacts and use them natively in the framework that trained them. The specific code needed to do this would depend on whether you are using MXNet or TensorFlow, and what you did to train the models. It'd be possible to figure this out just from reading MXNet/TensorFlow documentation, but wouldn't be super simple, so hopefully option 1 works for you.

**Comment by giggle0312** [comment]
@winstonaws Thank you very much. I have a question that what is the difference and relation between `model artifacts` stored on s3 and `docer image` stored on EC2?

**Comment by winstonaws** [comment]
@giggle0312 

The recommended way to use SageMaker hosting is to build a docker image with the code and dependencies you need to make predictions using your model, but have the actual model data itself (the weights) stored in S3. 

When you create an SageMaker model to host in an endpoint, you specify both the image and the S3 location of the model data: https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateModel.html

When the endpoint is created, SageMaker will download the model data from S3 and make it available in the docker image in the local /opt/ml/model directory. The code in the docker image should know how to load the model data and make predictions.

**Comment by jesterhazy** [comment]
This issue has been closed due to inactivity. If you still have questions, please re-open it.

**Comment by nicolasmichaeleljamal** [comment]
Hello. As @kshitij-kant  pointed, is hosting Sagemaker models like DeepAR possible on premises using any open source software?

**Comment by mfkenson** [comment]
I have the same question actually after attending AWS summit. @nicolasmichaeleljamal 
@juliensimon Do you have any idea?

**Comment by NotSoShaby** [comment]
@winstonaws can you please elaborate on how to load `tar.gz` file that was created by sagemaker to MXNet/TensorFlow? I understand it changes, but even a simple example will be very helpful

**Comment by Serhiy-Shekhovtsov** [comment]
Also wondering about extracting core SageMaker models(like DeepAR). @jesterhazy how can someone reopen this issue?

**Comment by laurenyu** [comment]
@NotSoShaby here are some examples for MXNet/TFS:
* MXNet: https://github.com/aws/sagemaker-mxnet-serving-container/blob/master/src/sagemaker_mxnet_serving_container/default_inference_handler.py#L36-L68
* TFS: https://github.com/aws/sagemaker-tensorflow-serving-container/blob/master/container/sagemaker/proxy_client.py#L30-L62

@others for the DeepAR question, can you open a new issue? That'll help us track it and get it to the right team to answer your question.

**Comment by wangzhenj321** [comment]
@laurenyu 

I have trained a model artifact (`model.tar.gz` stored on S3) with the built-in algorithm **Semantic Segmentation** on AWS SageMaker. I want to download this model and make inference with `mxnet` and `gluon-cv` on my local PC. However, after downloading and unzipping this model file, I there are only three files as follows, but there is no json of reconstructing the network model.

- hyperparams.json
- model_algo-1
- model_best.params

And I can't see the detail of the image of the Semantic Segmentation algorithm about how the network is constructed.

**Comment by laurenyu** [comment]
@wangzhenj321 Apologies as I'm not super familiar with MXNet, but I'm guessing you might need to provide more information when loading the model. Can you create a new GitHub issue? It'll help us track your question and pass it along to the team that owns Semantic Segmentation.

**Comment by wangzhenj321** [comment]
@laurenyu 

Sorry for forgetting to update my status about the solution. After struggling for three days, I found the way to make inference on my local PC with the trained model from the built-in algorithm Semantic Segmentation.

```python
import mxnet as mx
from mxnet import image
from gluoncv.data.transforms.presets.segmentation import test_transform
import gluoncv

# use cpu
ctx = mx.cpu(0)

# load test image
img = image.imread('./img/IMG_4015.jpg')
img = test_transform(img, ctx)
img = img.astype('float32')

# reconstruct the PSP network model
model = gluoncv.model_zoo.PSPNet(2)

# load the trained model
model.load_parameters('./model/model_algo-1')

# make inference
output = model.predict(img)
predict = mx.nd.squeeze(mx.nd.argmax(output, 1)).asnumpy()
```

**Comment by JeongJaeSoon** [comment]
Hello @wangzhenj321 

I referred to your code and applied it to my `model_algo-1` and test image.
However, the error has occurred like this.

```bash
/Users/{username}/opt/anaconda3/lib/python3.8/site-packages/gluoncv/__init__.py:40: UserWarning: Both `mxnet==1.8.0` and `torch==1.9.1` are installed. You might encounter increased GPU memory footprint if both framework are used at the same time.
  warnings.warn(f'Both `mxnet=={mx.__version__}` and `torch=={torch.__version__}` are installed. '
self.crop_size 480
Traceback (most recent call last):
  File "test.py", line 62, in <module>
    model.load_parameters('./model/model_algo-1')
  File "/Users/{username}/opt/anaconda3/lib/python3.8/site-packages/mxnet/gluon/block.py", line 545, in load_parameters
    assert any(p in loaded for p in params_inv[param]), \
AssertionError: Parameter 'head.psp.conv1.0.weight' is missing in file './model/model_algo-1', which contains parameters: 'conv1.0.weight', 'conv1.1.gamma', 'conv1.1.beta', ..., 'auxlayer.block.1.running_mean', 'auxlayer.block.1.running_var', 'auxlayer.block.4.weight', 'auxlayer.block.4.bias'. Set allow_missing=True to ignore missing parameters.
```

Do you happen to see the same error as me or know a solution to it?

**Comment by wangzhenj321** [comment]
@JeongJaeSoon 

> Do you happen to see the same error as me or know a solution to it?

No, I have not seen the same error. But from the following your error message, how about set `allow_missing=True` in `model.load_parameters('./model/model_algo-1')`?

```bash
AssertionError: Parameter 'head.psp.conv1.0.weight' is missing in file './model/model_algo-1', which contains parameters: 'conv1.0.weight', 'conv1.1.gamma', 'conv1.1.beta', ..., 'auxlayer.block.1.running_mean', 'auxlayer.block.1.running_var', 'auxlayer.block.4.weight', 'auxlayer.block.4.bias'. Set allow_missing=True to ignore missing parameters.
```

**Comment by JeongJaeSoon** [comment]
@wangzhenj321 Thanks for your reply!!

I've tried setting `allot_missing=True` to like `model.load_parameters('./model/model_algo-1', allow_missing=True)`.
But, a similar error has occurred like this.

```bash
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    model.load_parameters('./model/model_algo-1', allow_missing=True)
  File "/Users/94soon/opt/anaconda3/lib/python3.8/site-packages/mxnet/gluon/block.py", line 556, in load_parameters
    params[name]._load_init(loaded[name], ctx, cast_dtype=cast_dtype, dtype_source=dtype_source)
  File "/Users/94soon/opt/anaconda3/lib/python3.8/site-packages/mxnet/gluon/parameter.py", line 278, in _load_init
    assert self_dim in (unknown_dim_size, data_dim), \
AssertionError: Failed loading Parameter 'pspnet0__psphead0_conv0_weight' from saved params: shape incompatible expected (512, 4096, 3, 3) vs saved (512, 2048, 3, 3)
```


So, in another way I check the keys of `model_algo-1` with this code.
##### Code
```python3
pca_model_params = mx.ndarray.load('./model/model_algo-1')
print(pca_model_params.keys())
```
##### Result
```bash
dict_keys(['conv1.0.weight', 'conv1.1.gamma', 'conv1.1.beta', 'conv1.1.running_mean', 'conv1.1.running_var', 'conv1.3.weight', 'conv1.4.gamma', 'conv1.4.beta', 'conv1.4.running_mean', 'conv1.4.running_var', 'conv1.6.weight', 'bn1.gamma', 'bn1.beta', 'bn1.running_mean', 'bn1.running_var', 'layer1.0.conv1.weight', 'layer1.0.bn1.gamma', 'layer1.0.bn1.beta',
```

I thought this error will be solved if I can find the way how to add `head.psp.` to `dict_keys`

I think finding a way to add `head.psp.` front `dict_keys` will solve this error.

**Comment by wangzhenj321** [comment]
@JeongJaeSoon 

I think you can continue your idea, and it may can fix the problem. I also checked the keys of my `model_algo-1`. Let me share the result with you.

```python
>>> pca_model_params = mx.ndarray.load('./model/model_algo-1')
>>> for key in pca_model_params.keys():
...     if key.startswith('head.psp'):
...             print(key)
... 
head.psp.conv4.1.running_var
head.psp.conv1.1.gamma
head.psp.conv2.1.running_mean
head.psp.conv3.1.gamma
head.psp.conv2.1.gamma
head.psp.conv1.1.running_var
head.psp.conv2.1.beta
head.psp.conv1.1.beta
head.psp.conv3.1.running_var
head.psp.conv4.1.running_mean
head.psp.conv2.0.weight
head.psp.conv4.0.weight
head.psp.conv3.0.weight
head.psp.conv2.1.running_var
head.psp.conv1.0.weight
head.psp.conv3.1.beta
head.psp.conv4.1.beta
head.psp.conv3.1.running_mean
head.psp.conv1.1.running_mean
head.psp.conv4.1.gamma
```

**Comment by wangzhenj321** [comment]
@JeongJaeSoon 

The following figure shows a part of important parameters of training job of SageMaker. It may be helpful.

![image](https://user-images.githubusercontent.com/16948646/141936249-e3d436f4-6a4d-42a5-8f62-ed8cf0d87cec.png)

**Comment by JeongJaeSoon** [comment]
@wangzhenj321 
Thanks for your advice and that will be helpful for me!
I will try again with reference to your data.
