### ISSUE TITLE
Permission error when passing `profile_name` to boto session

### ISSUE THREAD

**Issue by tomron** [aws/sagemaker-python-sdk#2004]
**Describe the bug**
When using sagemaker with profile name which is not the default and the default profile lacks permissions an error raise.
When changing the default profile to be the SageMaker role (and not passing `profile_name` to `boto.Session`) the code runs as expected. 

**To reproduce**
The following code creates an error depending on the missing permissions (based on [this](https://github.com/aws/amazon-sagemaker-examples/blob/master/introduction_to_amazon_algorithms/random_cut_forest/random_cut_forest.ipynb) notebook).

```
import boto3
import sagemaker
from sagemaker import RandomCutForest


session = boto3.Session(profile_name ="my_sagemaker_profile")
sagemaker_session = sagemaker.Session(boto_session=session)
execution_role = sagemaker.get_execution_role(sagemaker_session=sagemaker_session)

...
rcf.fit(rcf.record_set(taxi_data.value.to_numpy().reshape(-1, 1)))
```

Note that the value of `execution_role` is extracted correctly.

**Expected behavior**
Used the permissions of the given role.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.16.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: RCF
- **Framework version**:
- **Python version**: 3.7.9
- **CPU or GPU**: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
- **Custom Docker image (Y/N)**: N

**Additional context**
Running locally on mac os.

**Comment by liujiaorr** [comment]
Does the issue still exist?

**Comment by liujiaorr** [comment]
Close the issue now, feel free to open if there is any problem.
