### ISSUE TITLE
SM XGBoost documentation page out of sync with codebase (SDK v1)

### ISSUE THREAD

**Issue by warmlogic** [aws/sagemaker-python-sdk#2016]
**Describe the bug**

- The [public XGBoost Algorithm documentation page](https://docs.aws.amazon.com/sagemaker/latest/dg/xgboost.html) says XGBoost 1.2-1 is supported and an example is shown for SDK v1
- The latest version of SDK v1 (1.72.1) [pins the latest version of XGBoost to 1.0-1](https://github.com/aws/sagemaker-python-sdk/blob/v1.72.1/src/sagemaker/xgboost/defaults.py#L21)

**To reproduce**

To experience the error in SDK v1:
- Install the latest version of SageMaker SDK v1 (1.72.1)
- Run
  - `from sagemaker.amazon.amazon_estimator import get_image_uri`
  - `get_image_uri('us-west-2', 'xgboost', repo_version='1.2-1')`
- Receive the error: `ValueError: SageMaker XGBoost version 1.2-1 is not supported. Supported versions: 0.90-1, 0.90-2, 1.0-1`

**Expected behavior**

Either the documentation should say SDK v1 doesn't support XGBoost 1.2, or SDK v1 should be updated to support XGBoost 1.2

**Screenshots or logs**

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 1.72.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: XGBoost
- **Framework version**: 1.2-1
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

I know I should just upgrade to SDK v2... :) I'll try to get to that soon.

**Comment by ajaykarpur** [comment]
Thanks for bringing this to our attention! We don't plan to issue any more changes to v1; I suggest upgrading to v2. You can use this CLI tool to automatically upgrade your code and notebooks: https://sagemaker.readthedocs.io/en/stable/v2.html#automatically-upgrade-your-code
