### ISSUE TITLE
Metadata directory mount in local mode should be configurable

### ISSUE THREAD

**Issue by njgerner** [aws/sagemaker-python-sdk#2022]
**Describe the bug**
My issue stems from this commit which was included in the `v2.19.0` release:
https://github.com/aws/sagemaker-python-sdk/commit/e23e44e224dec09ccf08ded013d92944fd177561

An issue pops up in our CI process due to the mounting of `/opt/ml/metadata` which is not a directory locally available in most cases and results in the following error:

```
ERROR: for tmpygfxtiwh_algo-1-amfg2_1  Cannot start service algo-1-amfg2: Mounts denied:
The path /opt/ml/metadata is not shared from the host and is not known to Docker.
```

Docker by default does not have permissions to mount to `/opt/**` on most local machines. 

Ideally, this mount point would be configurable or mounted to the `model_dir`.

**Expected behavior**
Mount the metadata directory to the `model_dir` or allow support custom configuration. 

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.19.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Bring your own container
- **Framework version**: N/A
- **Python version**: 3.7.0
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Y

**Additional context**

**Comment by syalanurag1991** [comment]
I am facing the same issue. What's the workaround for this error as off now?

**Comment by njgerner** [comment]
> I am facing the same issue. What's the workaround for this error as off now?

Pin the install of sagemaker to be less than 2.19.0 (e.g. `sagemaker==2.18`)

**Comment by syalanurag1991** [comment]
Downdrading to version 2.18 worked. Thanks @njgerner
