### ISSUE TITLE
This project requires more permissions than AmazonSageMakerFullAccess gives it

### ISSUE THREAD

**Issue by tedivm** [aws/sagemaker-python-sdk#2027]
**Describe the bug**

Extremely basic code examples from the website don't work.

**To reproduce**
Create a new notebook with the following code:

```python
import boto3
import sagemaker
import sagemaker.session

sagemaker_session = sagemaker.session.Session()
role = sagemaker.get_execution_role()
```

Run it and get this error:

> Couldn't call 'get_role' to get Role ARN from role name ROLENAME to get Role path.

**Expected behavior**

Either the policy should be fixed, or the documentation should be upgraded to tell people what additional permissions they will need.

**Screenshots or logs**
![Screen Shot 2020-12-10 at 3 00 14 PM](https://user-images.githubusercontent.com/121709/101840158-72f6a800-3af8-11eb-9dff-bcca18375804.png)

**System information**
A description of your system. Please provide: Sagemaker Studio with no extra installs or changes.

**Additional context**

This problem has apparently come up before (#291 #305 #575). 

We are *not* using a local setup for this, but are running on Sagemaker directly.

**Comment by aaronmarkham** [comment]
Did you try granting permission for ``iam:GetRole``?

**Comment by tedivm** [comment]
We added "iam:GetRole", "iam:GetRolePolicy", "sts:GetCallerIdentity" and it worked.

**Comment by TEChopra1000** [comment]
@tedivm I'll resolve this issue as it appears that you have found a solution. Please reopen if needed.

**Comment by tedivm** [comment]
Well yeah I found a solution, but  you should probably fix the underlying problem- either in the documentation or in your policies themselves.

**Comment by tedivm** [comment]
You also don't allow people who aren't members of this project reopen tickets.

**Comment by TEChopra1000** [comment]
@tedivm good point and your right, my apologies! I didn't realize you weren't allowed to reopen it the ticket. I'll do so now.

**Comment by oonisim** [comment]
Apparently the issues has not been addressed yet? Please fix if it has not yet.

* [aws sagemaker - IAM permission to call get_role](https://stackoverflow.com/questions/68607118/aws-sagemaker-iam-permission-to-call-get-role)

**Comment by IvyBazan** [comment]
This prerequisite is currently identified in the following documentation:
https://docs.aws.amazon.com/sagemaker/latest/dg/gs-set-up.html
