### ISSUE TITLE
Update ProcessingInput / ProcessingOutput

### ISSUE THREAD

**Issue by owen-t** [aws/sagemaker-python-sdk#2028]
**Describe the feature you'd like**
- Bring ProcessingInput and ProcessingOutput up to date with API model. Specifically add support for FeatureGroup to ProcessingOutput. 

**How would this feature be used? Please describe.**
- Take advantage of new service features.

**Comment by aarsanjani** [comment]
Per above, We are trying to integrate Pipelines into and to leverage Feature Store:

**Describe the feature you'd like**
 the integration point between the pipeline processing step and the input into the Fstore is ambiguous: we don't know what parameter in   sagemaker. worklfow.steps.ProcessingStep we would use to write the output to the FeatureStore.

**Comment by aarsanjani** [comment]
Also allow the Next pipelines ProcessingStep to Ingest features as input from the  FeatureStore

**Comment by icywang86rui** [comment]
The PR is under review https://github.com/aws/sagemaker-python-sdk/pull/2031
