### ISSUE TITLE
Sagemaker Pipelines: CloudFormation support

### ISSUE THREAD

**Issue by elvinx** [aws/sagemaker-python-sdk#2033]
**Describe the feature you'd like**

I want to be able to deploy my SageMaker Workflows via CloudFormation templates

**How would this feature be used? Please describe.**
We would like to deploy our SageMaker workflows via CloudFormation following the Infrastructure as a Code principle using our own CI/CD setup.

Are there any plans on this? If yes when can we expect this feature to become available at the latest ?

**Comment by jerrypeng7773** [comment]
Hi Elvin, yes, you can create pipeline via CloudFormation resource type AWS::SageMaker::Pipeline. The public documentation will be available soon.

**Comment by elvinx** [comment]
> Hi Elvin, we already support that, you can create pipeline via CloudFormation resource type AWS::SageMaker::Pipeline. The public documentation will be available soon.

That's great! Thanks for the quick response.
