### ISSUE TITLE
[bug] v2.19+ breaks on local run due to mounting of non-existent metadata directory on MAC OSX

### ISSUE THREAD

**Issue by PiercingDan** [aws/sagemaker-python-sdk#2043]
On MAC OSX, mounting `/opt/ml/metadata:/opt/ml/metadata` fails during sagemaker local run docker-compose as `/opt/ml/metadata` is non-existent.

Commit that added this: 
https://github.com/aws/sagemaker-python-sdk/commit/e23e44e224dec09ccf08ded013d92944fd177561

**Comment by njgerner** [comment]
Yep, this looks like the same thing as #2022
