### ISSUE TITLE
Python SDK v2.20.0 throwing error `'application/octet-stream' not supported (caused by KeyError)` when sending json request to DeepAR endpoint

### ISSUE THREAD

**Issue by larkz** [aws/sagemaker-python-sdk#2046]
Previously, using SDK v 1.72.1, we are able to send correctly formatted json requests to an Existing Sagemaker DeepAr endpoint. The endpoint is generated using the function `endpoint_from_model_data`
```
endpoint_name = sagemaker_session.endpoint_from_model_data(
        model_s3_location={s3_path}, 
        image_uri='495149712605.dkr.ecr.eu-central-1.amazonaws.com/forecasting-deepar:latest'', 
        initial_instance_count=1, 
        instance_type='ml.m4.xlarge',
        role=role,
        name=model_endpoint_name
    )
```
We expect as we send json requests as specified in [by DeepAR inference format](https://docs.aws.amazon.com/sagemaker/latest/dg/deepar-in-formats.html) the endpoint will return predictions in json format. In SDK v 1.72.1, this is working.
```
predictor = sagemaker.RealTimePredictor(endpoint = endpoint_name, sagemaker_session=sagemaker_session, content_type = 'application/json')
req = "{JSON_DATA}"
predictor.predict(req)
```
However, after upgrading to v2.20.0, the same json request is throwing the error, 

```
ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (415) from model with message "Customer Error: Content-Type header value 'application/octet-stream' not supported (caused by KeyError)
```
I am thinking this is a bug with the json serialization. Are there any updates in the SDK to resolve the issue?

**Comment by ajaykarpur** [comment]
The `content_type` parameter is now a no-op in Predictor classes. Please specify content types in a serializer or deserializer class instead.

Documentation:
- https://sagemaker.readthedocs.io/en/stable/v2.html#content-type-and-accept-in-the-predictor-constructor
- https://sagemaker.readthedocs.io/en/stable/v2.html#pre-instantiated-serializer-and-deserializer-objects

**Comment by larkz** [comment]
Thank you @ajaykarpur, the issue was resolved by changing 
```
predictor = sagemaker.RealTimePredictor(endpoint = endpoint_name, sagemaker_session=sagemaker_session, content_type = 'application/json')

```
to
```
from sagemaker.predictor import json_serializer
predictor = sagemaker.predictor.RealTimePredictor(endpoint_name = endpoint_name, sagemaker_session=sagemaker_session, serializer=json_serializer)
```

**Comment by martinRenou** [comment]
Closing as answered. Feel free to continue the discussion if needed.
