### ISSUE TITLE
Enable Python 3.9 support

### ISSUE THREAD

**Issue by metrizable** [aws/sagemaker-python-sdk#2055]
**Describe the feature you'd like**

With [Python 3.9.1](https://www.python.org/downloads/release/python-391/), the first maintenance release of Python 3.9, out, more of the ecosystem has declared support for the Python version (e.g. [attrs](https://pypi.org/project/attrs/), [packaging](https://pypi.org/project/packaging/), etc.). Including support for Python 3.9 keeps the SageMaker Python SDK up-to-date.

**How would this feature be used? Please describe.**

As the last of the dependencies declare support for Python 3.9, anyone in a Python 3.9 environment could use the SageMaker Python SDK with confidence.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by ahsan-z-khan** [comment]
We have enabled Python 3.9 support to the SDK.
