### ISSUE TITLE
ProcessingInput takes Dataset Definition, but does not accept raw S3 definition

### ISSUE THREAD

**Issue by ericangelokim** [aws/sagemaker-python-sdk#2066]
https://github.com/aws/sagemaker-python-sdk/blob/01c6ee3a9ec1831e935e86df58cf70bc92ed1bbe/src/sagemaker/processing.py#L991

The new ProcessingInput implementation now takes dataset_definition as a parameter, but fails when S3 Dataset Definition is used:

```
ParamValidationError: Parameter validation failed:
Unknown parameter in ProcessingInputs[1].DatasetDefinition: "Typename", must be one of: AthenaDatasetDefinition, RedshiftDatasetDefinition, LocalPath, DataDistributionType, InputMode
Unknown parameter in ProcessingInputs[1].DatasetDefinition: "Datasetsourcetype", must be one of: AthenaDatasetDefinition, RedshiftDatasetDefinition, LocalPath, DataDistributionType, InputMode
Unknown parameter in ProcessingInputs[1].DatasetDefinition: "Name", must be one of: AthenaDatasetDefinition, RedshiftDatasetDefinition, LocalPath, DataDistributionType, InputMode
Unknown parameter in ProcessingInputs[1].DatasetDefinition: "S3Executioncontext", must be one of: AthenaDatasetDefinition, RedshiftDatasetDefinition, LocalPath, DataDistributionType, InputMode
```

This is inconvenient to use, as it requires different implementation for S3 inputs. Not entirely sure why this is implemented as such.

**Comment by marckarp** [comment]
If you want to use S3 as input to the Processing Job you should be setting *[s3_input](https://sagemaker.readthedocs.io/en/stable/api/training/processing.html#sagemaker.processing.ProcessingInput) (* [S3Input](https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.dataset_definition.inputs.S3Input)). 
If you are still facing an issue please provide a code snippet to reproduce the issue.
