### ISSUE TITLE
[Bug] sagemaker should not toggle global logging facilities

### ISSUE THREAD

**Issue by yifeim** [aws/sagemaker-python-sdk#2072]
After importing sagemaker, all my warning messages disappear. Here is a reproducible example:
```
import sagemaker, warnings # order does not matter
warnings.warn('this important warning message cannot be seen')
```

After some digging, I found this line of code to be particularly suspicious:

https://github.com/aws/sagemaker-python-sdk/blame/master/src/sagemaker/deprecations.py#L19

I was wondering if there is another way to achieve the desired effects without unexpected and potentially significant consequences. Thanks.

**Comment by icywang86rui** [comment]
We are already logging the same warning message here - https://github.com/aws/sagemaker-python-sdk/blame/master/src/sagemaker/deprecations.py#L33
Seems like it's not necessary to set this.

**Comment by icywang86rui** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/2085

**Comment by icywang86rui** [comment]
PR is merged. Closing the issue.
