### ISSUE TITLE
v2 guide incorrectly renames RecordSerializer and RecordDeserializer

### ISSUE THREAD

**Issue by aaronmarkham** [aws/sagemaker-python-sdk#2075]
https://sagemaker.readthedocs.io/en/stable/v2.html#serializer-and-deserializer-classes
This page incorrectly states the renaming of some serializers.

* "sagemaker.amazon.serializers.RecordSerializer" should read "sagemaker.amazon.common.RecordSerializer"
* "sagemaker.amazon.serializers.RecordDeserializer" should read "sagemaker.amazon.common.RecordDeserializer"

**Comment by icywang86rui** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/2078

**Comment by icywang86rui** [comment]
pr merged
