### ISSUE TITLE
Sagemaker Pipelines: Get information of pipeline when Pipeline object initialized as Existing pipelines

### ISSUE THREAD

**Issue by chik-taks** [aws/sagemaker-python-sdk#2094]
**Describe the feature you'd like**
When Pipeline object initialize and the pipeline name exists, add information of step and parameters into pipeline object.
```
>from sagemaker.workflow.pipeline import Pipeline
>pipeline = Pipeline(name='<existing-pipeline-name>')
>pipeline
Pipeline(name='<existing-pipeline-name>', parameters=[], steps=[], sagemaker_session=<sagemaker.session.Session object at xxxxxxx>)
```

**How would this feature be used? Please describe.**
1. Easily detect the pipeline name is existing or not.
2. Easy to understand how to execute existing pipeline.

**Comment by metrizable** [comment]
@chik-taks 

Thanks for using SageMaker! This is a great feature request. The semantics typically followed by other types, like `Estimator` instances, is `attach`. For consistency of experience in the SDK, something like the below seems appropriate:

```
from sagemaker.workflow.pipeline import Pipeline


pipeline = Pipeline.attach(name='<existing-pipeline-name>', sagemaker_session=<sagemaker.session.Session>)
```

**Comment by staubhp** [comment]
Related: https://github.com/aws/sagemaker-python-sdk/issues/2127

**Comment by ShwetaSingh801** [comment]
Hi @chik-taks, thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.” Let me know if you have any other questions. Best,Shweta
