### ISSUE TITLE
security feature for jupyter notebooks

### ISSUE THREAD

**Issue by richardxin** [aws/sagemaker-python-sdk#21]
how granular is jupyter notebooks security setting? for example, how can we have different user groups for different permissions (such as read/write/run and others)?

**Comment by iquintero** [comment]
Hi again @richardxin 

This is also a question that can be answered by our Notebook instances team. The best place to ask is the [SageMaker Forums](https://forums.aws.amazon.com/forum.jspa?forumID=285&start=0)

I will also close this issue as again this is not related to the sagemaker python sdk itself.
