### ISSUE TITLE
ModelPackageDescription missing from RegisterModelStep

### ISSUE THREAD

**Issue by owen-t** [aws/sagemaker-python-sdk#2104]
**Describe the feature you'd like**
The [RegisterModelStep](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/step_collections.py#L51) within the workflow module does not let a customer set the model package description. This is supported by the underlying DSL and is defined on the ModelPackage API [here](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateModelPackage.html).

**How would this feature be used? Please describe.**
Customers would use this in their pipelines to set the model package description on model registry entities they create.

**Describe alternatives you've considered**
There is no alternative, this is a feature of the service not supported by the SDK.

**Additional context**
None.

**Comment by ChoiByungWook** [comment]
Added in: https://github.com/aws/sagemaker-python-sdk/pull/2190
