### ISSUE TITLE
FeatureGroup ingest() function does not support NA.

### ISSUE THREAD

**Issue by alex-tang** [aws/sagemaker-python-sdk#2110]
**Describe the bug**
The FeatureGroup class's `ingest()` function does not support Pandas 'NA' values for Integral and Fractional types.

**To reproduce**
Create a pandas dataframe with integral, fractional, and string types (int, float, string). Add pandas NA values to some cells. Create a FeatureGroup instance and invoke the ingest() method.

See that the NA is being parsed as the string "NA" and provided to the SageMaker Feature Store PutRecord API, which is invalid.

**Expected behavior**
The pandas constant NA should be ignored for any feature type when generating a feature value for the record in the PutRecord API.

**Screenshots or logs**
N/A

**System information**
N/A

**Additional context**
N/A

**Comment by ChoiByungWook** [comment]
Released in https://pypi.org/project/sagemaker/2.25.2/.

Please reopen if you still seeing this issue.
