### ISSUE TITLE
FeatureGroup ingest function not utilizing all CPU cores

### ISSUE THREAD

**Issue by alex-tang** [aws/sagemaker-python-sdk#2111]
**Describe the feature you'd like**
Currently, the ingest function supports configuring the number of threads for parallelize ingestion. The current functionality does fully utilize machines with higher core counts (i.e. a single process is executing on a single CPU core).

The feature request is to support configuring the number of Processes for parallelizing ingestion, to increase CPU core utilization.

**How would this feature be used? Please describe.**
As a parameter in the ingest() API to specify the number of parallel processes.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by akrishna1995** [comment]
Hi @alex-tang - seems like the fix has been merged : https://github.com/aws/sagemaker-python-sdk/pull/2288.

Please feel free to reopen if there are any further feedback. Thank you
