### ISSUE TITLE
CreateModelStep doesn't use model name.

### ISSUE THREAD

**Issue by hughack** [aws/sagemaker-python-sdk#2122]
CreateModelStep doesn't seem to pass model names to the call to create the model.

E.g. if i have a CreateModelStep like this:

```python
CreateModelStep(
    name="CreateModel",
    model=Model(
        name=pipeline_parameters["model_name"],
        image_uri=image_uri,
        model_data=train_step.properties.ModelArtifacts.S3ModelArtifacts,
        role=role,
        sagemaker_session=sagemaker_session
    ),
    inputs=CreateModelInput(instance_type="ml.m5.large")
)
```

And call 

```python
pipeline.start(
    parameters=dict(
        ModelName="predictable-model-name"
    )
)
```

I expect the model to be created with the name `predictable-model-name`.

Actual behaviour is an auto-generated name.

https://github.com/aws/sagemaker-python-sdk/blob/e20193e51fb88b606e9d0529c8855384863606f7/src/sagemaker/workflow/steps.py#L184

**Comment by icywang86rui** [comment]
Pipeline created resources, eg training jobs, models etc, are given names generated by the pipeline execution to avoid name collision. Hope that answers your question. Closing the issue. Feel free to reopen if you have more questions.

**Comment by hughack** [comment]
Not sure i agree with it but if that's the design then that's the way it is i guess. Would be good to have it documented and maybe even print a warning that it is being dropped rather than silently dropping it.
