### ISSUE TITLE
RegisterModel step confusing

### ISSUE THREAD

**Issue by ruyyi0323** [aws/sagemaker-python-sdk#2124]
**What did you find confusing? Please describe.**
I don't know exactly the behavior of repacking, seems like it's copying only the entry point file out to the model.tar.gz rather than coping the whole source_dir, and it's auto-generated, not able to modify, not sure if I got the correct logic and what's behind the stage. 

**Describe how documentation can be improved**
Give some additional explanantion to this step

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by ChoiByungWook** [comment]
Hey @ruyyi0323,

Apologies on the late response.

Can you point us to any guide/documentation that you are following for going about for using RegisterModel?

> I don't know exactly the behavior of repacking, seems like it's copying only the entry point file out to the model.tar.gz rather than coping the whole source_dir, and it's auto-generated, not able to modify, not sure if I got the correct logic and what's behind the stage.

Not too sure if I'm understanding this correctly, but I assume repack refers to: https://github.com/aws/sagemaker-python-sdk/blob/c0f54d915089e6a8b45f944e4b568b638b5e62f1/src/sagemaker/utils.py#L362. I believe repack_model should be copying in source_dir into the model.tar.gz.

I believe repack_model will end up only be called when attempting to use our predefined Deep Learning Framework containers, as we have container side logic, that depends on userscripts and dependencies being within the model.tar.gz.

Let me know if there is anything I can clarify.

Thanks!

**Comment by ChoiByungWook** [comment]
For reference: https://github.com/aws/sagemaker-python-sdk/issues/2123
