### ISSUE TITLE
SM Pipelines RegisterModel step without Estimator object as input

### ISSUE THREAD

**Issue by giuseppeporcelli** [aws/sagemaker-python-sdk#2143]
**Describe the feature you'd like**
Allow registering models to SM model registry without providing an estimator object as input to the RegisterModel step (StepCollection).

**How would this feature be used? Please describe.**
When registering a model to SM model registry, the SDK currently requires to provide an Estimator instance as input to the constructor of the RegisterModel step.

The Estimator objects seems to be used to get the container image URI (if not passed in the constructor), the Session instance, and some other settings like the execution role and source_dir for the repack operation.

However, following this approach means that an Estimator instance has to be available to register a model, which is not always the case when a/ models are not trained using an Estimator (e.g. when using a processing job to fit a featurizer) b/ registering a model that was previously trained.

**Describe alternatives you've considered**
The workaround I have used is to define a "dummy" Estimator with the required parameters (tried to support the scenario a/ above), but this is not ideal as it is not clear what is the purpose of creating it.

**Additional context**
Can provide an example if needed.

**Comment by ahsan-z-khan** [comment]
Hi @giuseppeporcelli ,

Thank you for using SageMaker. Can provide an example?

Thanks

**Comment by giuseppeporcelli** [comment]
Hi @ahsan-z-khan,
sure. 

Please check this notebook: https://github.com/giuseppeporcelli/end-to-end-ml-sm/blob/master/07_workflow/07_workflow.ipynb (section Register Model Steps > Featurizer Model) and see how I register a model that was trained via a processing job. In that scenario, I'm using a dummy estimator as I didn't use SM training to train that model. It would be great if the register model step does not have dependencies on estimators.

**Comment by jerrypeng7773** [comment]
Did not hear this from other customers, close it for now, feel free to re-open @giuseppeporcelli

**Comment by suyashdb** [comment]
I have the same issue where we use one estimator for train step and another in register model. 

Can we register model with a diff estimator(the one not used for training)?

**Comment by bandhakavi** [comment]
I am trying to do the same thing - model registration should be allowed to happen in different scenarios - for example when a different team has trained a model on a non-aws platform (say using huggingface interface) but we want to use Sagemaker Model Registry as a centralized model store. Adding this comment to the thread to record the interest in such a feature.

> Did not hear this from other customers, close it for now, feel free to re-open @giuseppeporcelli
