### ISSUE TITLE
SM Pipelines ParameterInteger default value set to 0 is not generated in the JSON definition

### ISSUE THREAD

**Issue by giuseppeporcelli** [aws/sagemaker-python-sdk#2144]
**Describe the bug**
When creating a ParameterInteger whose default value is set to 0, the default value is not generated in the pipeline JSON definition.

**To reproduce**
Simply create a ParameterInteger with default value set to 0 similarly to the following one:

`ParameterInteger(name="silent", default_value=0)`

Then, generate the JSON definition and you will find:

`{'Name': 'silent', 'Type': 'Integer'},`

**Expected behavior**
The generated JSON definition should include the default value. Example:

`{'Name': 'silent', 'Type': 'Integer', 'DefaultValue': 0},`

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.24.5
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.7.6
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
N/A

**Comment by ChoiByungWook** [comment]
@giuseppeporcelli,

Apologies for the late response.

Thank you for bringing this issue to our attention.

For clarification, does this happen when attempting to create a SageMaker Pipeline with the following ParameterInteger?
```
ParameterInteger(name="silent", default_value=0)
```

**Comment by giuseppeporcelli** [comment]
@ChoiByungWook,
yes. When you create a pipeline with that ParameterInteger, the corresponding JSON definition does not include the default value. Thanks!

**Comment by ahsan-z-khan** [comment]
@melzareix Thank you for contributing to the issue.
