### ISSUE TITLE
Inquiry: model_monitoring/create_monitoring_schedule job frequency issue

### ISSUE THREAD

**Issue by zhangchi1** [aws/sagemaker-python-sdk#2177]
**Describe the feature you'd like**
Customized `Schedule_cron_expressio`, such as weekly, monthly, and per x days, etc.

**How would this feature be used? Please describe.**
I'd like to create sagemaker model monitoring schedule using this `create_monitoring_schedule` [Model Monitor API](https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_monitor.model_monitoring.DefaultModelMonitor.create_monitoring_schedule). One field is the cron expression that dictates the frequency that this job runs at. 
Firstly, I'm wondering if I can specify weekly or monthly, I would like to generate a weekly report?  It seems like currently it only supports hourly and daily, based on this [code](https://github.com/aws/sagemaker-python-sdk/blob/2a0cf1b1f4cb74802a2fdbb0f19c7f0761c3ff5b/src/sagemaker/model_monitor/cron_expression_generator.py#L21)?

Secondly, assume I select hourly in `create_monitoring_schedule`, does that mean Sagemaker will generate a report each hour by only using **the last hour captured data** from inference and compare it will my baseline statistics? Or it does a **cumulatively** report each hour? The description of `create_monitoring_schedule` [method](https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_monitor.model_monitoring.DefaultModelMonitor.create_monitoring_schedule) doesn't state that clearly? Maybe we could add more clarification context in the API documentation?

Really appreciated,

**Comment by nigenda-amazon** [comment]
You are correct, we will generate a report using only the last hour of captured data (or the last day if running a daily job).

It is furthermore correct that we only support hourly and daily at this time.

We appreciate the feedback, we will update the documentation to make this clearer.

**Comment by TremaMiguel** [comment]
Checking out the [ScheduleConfig](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ScheduleConfig.html) documentation, valid values are still at most daily. 

Supporting weekly, monthly or every x month values can be of great value if using `DataQualityMonitor` for Models where the ground truth period is longer.

Is there any way to request the development for weekly, monthly, every x months or the like to `ScheduleConfig` ?

**Comment by akrishna1995** [comment]
Thanks @TremaMiguel - I have added this as a feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
