### ISSUE TITLE
Endpoint Deploy issue

### ISSUE THREAD

**Issue by Abhicode5** [aws/sagemaker-python-sdk#2192]
i trained a custom model in tensorflow using prebuilt docker image 
763104351884.dkr.ecr.us-west-2.amazonaws.com/tensorflow-training:1.15.3-cpu-py3

I am able to train , and deploy the model as endpoint   . no issues .

But i tried to apply increment learning  --> take the already trained model, retrain it on new data, put the new model artifacts 
back and then deploy the new model as endpoint.

** I am able to resume training , but  endpoint.deploy is causing error**

** Fit the base estimator

```
ic = sagemaker.estimator.Estimator(training_image,
                                   role,
                                   train_instance_count=1,
                                   train_instance_type='ml.c4.xlarge',
                                   input_mode='File',
                                   output_path=s3_output_location,
                                   sagemaker_session=sess,
                                   hyperparameters=hyperparams)


train_data = sagemaker.inputs.s3_input(input_path, distribution='FullyReplicated',
                                         s3_data_type='S3Prefix')


data_channels = {'train': train_data}

ic.fit(inputs=data_channels, logs=True)

Print the location of the model data from previous training
print(ic.model_data)

Prepare model channel in addition to train and validation
model_data = sagemaker.session.s3_input(ic.model_data, distribution='FullyReplicated', 
                              s3_data_type='S3Prefix', content_type='application/x-sagemaker-model')

data_channels = {'train': train_data, 'model': model_data}


incr_ic = sagemaker.estimator.Estimator(training_image,
                                   role,
                                   train_instance_count=1,
                                   train_instance_type='ml.c4.xlarge',
                                   input_mode='File',
                                   output_path=s3_output_location,
                                   sagemaker_session=sess,
                                   hyperparameters=hyperparams,
                                         )
incr_ic.fit(inputs=data_channels, logs=True)

**ic_classifier = incr_ic.deploy(initial_instance_count = 1,
                                          instance_type = 'ml.t2.medium')**     ###Causes error`**

Error  Cloudwatch:     **exec: "serve": executable file not found in $PATH**. 
```
Note : ** I am using the prebuilt docker image so i guess i cannot alter the docker file content**

**Comment by ChoiByungWook** [comment]
Hey @Abhicode5,

Based on the code above, it looks like you're using the Estimator class to handle your training. The image you provided is for training only. For inference you will need to use an inference image: https://github.com/aws/deep-learning-containers/blob/master/available_images.md#general-framework-containers.

You would need to change your image to be an inference image after calling fit() by setting image_uri in your Estimator to your inference image.

You can also use the [TensorFlow estimator](https://github.com/aws/sagemaker-python-sdk/blob/3dd4373a61a8c2c7d98181b931b5729a8eeccc0a/src/sagemaker/tensorflow/estimator.py#L33) defined in the Python SDK, if you don't want to keep specifying the training and inference image directly.

For notebook examples please see any TensorFlow notebooks in: https://github.com/aws/amazon-sagemaker-examples/tree/master/sagemaker-python-sdk

**Comment by Abhicode5** [comment]
Hi @ChoiByungWook  ! Thank you So much for helping . 
** I have used another approach , by deploying endpoint directly from model artifacts**. 
** I am not sure though if my approach is right or not. So could you please guide me ? My goal is to achieve incremental learning**.

suppose i have done initial deployment of endpoint (trained & deployed).

# now on new incoming data . I directly take previous saved model and resume training on new Data

`

icr = sagemaker.estimator.Estimator(training_image,
                                   role,
                                   train_instance_count=1,
                                   train_instance_type='ml.c4.xlarge',
                                   input_mode='File',
                                   output_path=s3_output_location,
                                   sagemaker_session=sess,
                                   hyperparameters=hyperparams)

input_path ='s3:/.path to training data./train.csv';
train_data = sagemaker.inputs.s3_input(input_path, distribution='FullyReplicated',
                                         s3_data_type='S3Prefix')
data_channels = {'train': train_data, 'model': model_data}   ##### load already trained model

icr.fit(inputs=data_channels, logs=True)

` 

# Then new model artifacts get saved to bucket . Use model artifacts to deploy directly

`
from sagemaker.tensorflow.serving import Model
model_data ='s3://path to model data/output/model.tar.gz'
model = Model(model_data=model_data, role=role, framework_version=tf.__version__)
predictor = model.deploy(initial_instance_count=1, instance_type='ml.c4.xlarge')
`

** Is my approach correct? . Is the deployed model as end point & saved model in s3 bucket - an incremental model 
 previously trained + trained on new Data ? 
 **

**Comment by ChoiByungWook** [comment]
Hey @Abhicode5,

That approach works fine.

The class defined in `sagemaker.tensorflow.serving import Model` points to a tensorflow-inference ECR image defined in: https://github.com/aws/deep-learning-containers/blob/master/available_images.md#general-framework-containers, so your endpoint should work properly, assuming your model is compatible with TensorFlow serving.

**Comment by Abhicode5** [comment]
@ChoiByungWook  Thanks for such a quick reply.

I had one more question 
What is the pytorch equivalent of  -- sagemaker.tensorflow.serving import Model

Thanks

**Comment by ChoiByungWook** [comment]
> @ChoiByungWook Thanks for such a quick reply.
> 
> I had one more question
> What is the pytorch equivalent of -- sagemaker.tensorflow.serving import Model
> 
> Thanks

Hey @Abhicode5,

No problem.

The PyTorch equivalent would be: https://github.com/aws/sagemaker-python-sdk/blob/3dd4373a61a8c2c7d98181b931b5729a8eeccc0a/src/sagemaker/pytorch/model.py#L72

from sagemaker.pytorch.model import PyTorchModel
