### ISSUE TITLE
Model persists when endpoint deploys fails at 'createEndpoint'

### ISSUE THREAD

**Issue by evakravi** [aws/sagemaker-python-sdk#2194]
I'm a software engineer at AWS that is experiencing this bug in SageMaker Studio (JumpStart). My alias is @evakravi

**Describe the bug**
If you attempt to deploy a model and are successful in a) uploading the script/deps to s3, (b) creating a model, (c) creating an endpoint config, but d) FAIL to create the endpoint (which could happen if an account does not have GPU instances allocated), then if you attempt to re-deploy the same model with parameters such that the endpoint creation succeeds, the deployment will still fail. 

**To reproduce**
Deploy a model on a disallowed instance type, then deploy the identical model to a permitted instance type. 

**Expected behavior**
The deployment to an allowed instance type should be successful, but it ends up failing.  

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.21.0
- **Python version**: Python 3.7.10
- **CPU or GPU**: SageMaker Studio Jupyter Server
- **Custom Docker image (Y/N)**: SageMaker Studio Jupyter Server

**Additional context**
While this issue is related to SageMaker JumpStart ModelHub, the sagemaker api issue can be reproduced outside of SageMaker Studio.

**Comment by ChoiByungWook** [comment]
What is the exact error/stacktrace are you seeing when you deploy for the second time?

From my understanding it sounds like you're running a similar issue shown in: https://github.com/aws/sagemaker-python-sdk/issues/1470?

**Comment by ChoiByungWook** [comment]
```
Something went wrong
We encountered an error while preparing to deploy your endpoint. You can get more details below.
operation deploy failed: An error occurred (ResourceLimitExceeded) when calling the CreateEndpoint operation: The account-level service limit 'ml.g4dn.xlarge for endpoint usage' is 0 Instances, with current utilization of 0 Instances and a request delta of 1 Instances. Please contact AWS support to request an increase for this limit.
```

**Comment by ChoiByungWook** [comment]
It looks like we check to see if there is an existing endpoint_config: https://github.com/aws/sagemaker-python-sdk/blob/3a1f0b365f8f46a00a33e444f136826b4a7d56ff/src/sagemaker/session.py#L3443

Are you using the same name in your code for your deployments?

**Comment by marckarp** [comment]
There is not enough in the information provided to reproduce/classify this as a bug. Do you have a code snippets/notebook to reproduce the issue?
