### ISSUE TITLE
Workflow ProcessingStep run arguments

### ISSUE THREAD

**Issue by jaggaer-mtrninic** [aws/sagemaker-python-sdk#2197]
**Describe the feature you'd like**
ProcessingStep at the moment as per my knowledge doesn't cover all the arguments that run function of concrete Processor has. 
Feature would be ability to pass in an run arguments for concrete processor from the ProcessingStep object.

**How would this feature be used? Please describe.**
For example PySparkProcessor has a submit_jars argument but this can not be passed to ProcessingStep as part of the pipeline. 
It would be nice if there could be a run arguments for ProcessingStep where we could client pass the arguments of concrete Procesor.

**Describe alternatives you've considered**
For PySpark processor and submit jars only solution in my mind is to rewrite the code in Scala and make an uber jar with all jars required for the job.

**Comment by jerrypeng7773** [comment]
https://github.com/aws/sagemaker-python-sdk/issues/2857

**Comment by jerrypeng7773** [comment]
Reprinted from the answer for #2857 

@jaggaer-mtrninic We recently released a SDK change to support this. 

```
from sagemaker.workflow.pipeline_context import PipelineSession

session = PipelineSession()

processor = FrameworkProcessor(...)

step_args = processor.run(inputs=..., source_dir="...")

step_sklearn = ProcessingStep(
    name="MyProcessingStep",
    step_args=step_args,
)
```

In summary, we introduced the `PipelineSession`. This special session does not trigger a processing job immediately when you call `processor.run` , instead, it captures the request arguments required to run a processing job, and delegate it to the processing step to start the job later during pipeline execution. 

This works for estimator, transformer, and tuner too.

You should be able to use this with the latest sdk release 2.89.0

**Comment by jerrypeng7773** [comment]
close for now, feel free to re-open if you have any other concern.
