### ISSUE TITLE
Hyperparameter won't be changed for different executions

### ISSUE THREAD

**Issue by ruyyi0323** [aws/sagemaker-python-sdk#2200]
**Describe the bug**
Changing hyperparameter for the estimator doesn't work

**To reproduce**
I am creating an estimator and hyperparameters in this way
```
# ... define other parameters

    train_epochs=ParameterInteger(
        name="TrainEpochs", 
        default_value=5,
    )
    train_batch_size=ParameterInteger(
        name="TrainBatchSize", 
        default_value=256,
    )
    early_stop_tolerance=ParameterInteger(
        name="EarlyStopPatience", 
        default_value=10,
    )

# ... define other steps

salary_estimator = Estimator(
        entry_point='train.py',
        source_dir=os.path.join(code_dir, "src.tar.gz"), # this should be just "source" for your code
        role=role,
        image_uri="763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.3.1-gpu-py37-cu110-ubuntu18.04",
        instance_count=1,
        instance_type=training_instance_type,
        output_path = get_projection_s3_dir(experiment_dir, "model"),
        sagemaker_session=sagemaker_session,
        container_log_level=10, # 10 debug 20 info 30 warning 40 error
        volume_size=160,
        base_job_name=f"{base_job_prefix}-model-train"
    )
    salary_estimator.set_hyperparameters(
        epcohs=train_epochs,
        batch_size=train_batch_size,
        early_stop_patience=early_stop_tolerance
    )
``` 
if I run the experiment in this way
```
exec_params = dict(
    ...
    TrainEpochs=3,
)
```
In training, it would still use 5 as its training epochs, by further checking the definition of pipeline, I found
![image](https://user-images.githubusercontent.com/31749673/110577198-2ab74800-8130-11eb-9f3c-93c97dd1c6d3.png)
Rather than fetching the parameter, seems like estimator is purely using the default value of it

Also, I tried to use the `TensorFlow` estimator object, it won't work either

**Expected behavior**
The estimator seems should get the parameter value rather than set it using the default value.

**Screenshots or logs**
See above

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.23.5
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Tensorflow
- **Framework version**: ..
- **Python version**: 3.7
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N
- (Same as SageMaker Studio Data-Science Environment)

**Additional context**
@ChoiByungWook 
I am using this as reference to create my own stuff https://github.com/data-science-on-aws/workshop/blob/7f3449de54c908c97d58d784f0a1050531d9b7ad/10_pipeline/01_Create_SageMaker_Pipeline_BERT_Reviews.ipynb

**Comment by ruyyi0323** [comment]
hello?

**Comment by ruyyi0323** [comment]
hello.....

**Comment by olivermeyer** [comment]
I'm observing the same issue with `sagemaker==2.72.0`. It seems to be a broader issue than just the hyperparameters though, because I also cannot use parameter values for other estimator parameters (e.g. `output_path`).

My workaround is to pass an environment parameter (prod, staging, etc) and derive these values from it (`if environment = 'prod' then epochs = 5`. Not ideal though because I'd like to be able to change these on the fly.
