### ISSUE TITLE
Add cron schedule option to sagemaker pipelines

### ISSUE THREAD

**Issue by akshjain83** [aws/sagemaker-python-sdk#2205]
**Describe the feature you'd like**
As a pipeline developer, I would like ability to define cron schedule on sagemaker pipelines so that we could run workflows on a cadence

**How would this feature be used? Please describe.**
Currently the pipeline doesn't offer the scheduling feature, with this feature we would be able to automatically execute pipeline and avoid the need to manually start or explicitly call execution on the pipeline object. This is a very typical use case for ML workflows and should be a core feature to empower pipelines for orchestration

**Describe alternatives you've considered**
AWS SageMaker recommends Airflow, SG Pipeline, Kubernetes and Step functions as recommended options for orchestration. While we could use Airflow or step function ( cloudwatch) to define schedule, I think it will defeat the purpose of listing pipeline as an alternative to Airflow / Step functions for orchestration.

**Additional context**

**Comment by danabens** [comment]
Hi Akshay thanks for your feature request. We have no plans to add this functionality at this time. The orchestration solutions you mention would work - really anything that can call the [StartPipelineExecution API](https://docs.aws.amazon.com/cli/latest/reference/sagemaker/start-pipeline-execution.html).
