### ISSUE TITLE
Pass in environment variables for Estimator training job 

### ISSUE THREAD

**Issue by PiercingDan** [aws/sagemaker-python-sdk#2207]
**Describe the feature you'd like**
I want to pass in an environment variable for Estimator like for Transformer(env=...) https://sagemaker.readthedocs.io/en/stable/api/inference/transformer.html#sagemaker.transformer.Transformer

**How would this feature be used? Please describe.*
I want to pass in information to my sagemaker container during runtime

**Describe alternatives you've considered**
I'm forced to encode it as 'hyperparameters' to pass in the info

**Additional context**
N/A

**Comment by anirudhgangwal** [comment]
+1 this would be helpful. We would like to pass pip configuration as environment so that 3rd party libraries are downloaded from AWS CodeArtifact instead of PyPi.

**Comment by PiercingDan** [comment]
From #2218 , looks like this is available in the native boto3 call CreateTrainingJob under Environment. Waiting for sagemaker-python-sdk support for this interface.

https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateTrainingJob.html

**Comment by PiercingDan** [comment]
Thanks for adding this to the boto3 call in #2218 , is it possible to also add support for passing in environment variables for local jobs? That would be really helpful

**Comment by ssmall41** [comment]
As far as I can tell, #2218 should add support to the sagemaker python sdk for environment variables, but that seems to not be the case almost a year later with version 2.72.3. The API supports an argument `environment`, but the values passed are not defined in the container.

**Comment by usamec** [comment]
> As far as I can tell, #2218 should add support to the sagemaker python sdk for environment variables, but that seems to not be the case almost a year later with version 2.72.3. The API supports an argument `environment`, but the values passed are not defined in the container.

I have exactly same problem.
It can be easily confirmed by running training script, which just output os.environ content.

**Comment by ssmall41** [comment]
I figured out that passing environment variables DOES work for me, except in local mode. I made an issue to address this. #2930

**Comment by mufaddal-rohawala** [comment]
Keeping https://github.com/aws/sagemaker-python-sdk/issues/2930 open to track Env Var Support in Local Mode. Closing this one.
