### ISSUE TITLE
Can't describe() latest TransformJob

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#2208]
**Describe the bug**

`sagemaker.transformer._TransformJob` does not implement inherited abstract method `describe()` from `sagemaker.job._Job`.

This prevents users from easily fetching the details of a transformer's most recent job - as they might be used to doing for estimators and training jobs... Necessitating workarounds via Boto3 or similar.

At the least, it should surely raise a NotImplemented error as an abstract method?

**To reproduce**

1. Create a `Transformer` and use it to run a transform job
2. Try to query `desc = transformer.latest_transform_job.describe()`
3. Observe no logs/diagnostics/errors, and `desc = None`

**Expected behavior**

Consistent behaviour with `estimator.latest_training_job.describe()`: Return a job description

**Screenshots or logs**

N/A

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: Tested in 2.25.2, but checked still exists in current `master`
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: Python 3 (Data Science) kernel on SMStudio
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

Users can currently work around this via e.g:

```python
import boto3
smclient = boto3.client("sagemaker")

desc = smclient.describe_transform_job(TransformJobName=transformer.latest_transform_job.name)
```

**Comment by akrishna1995** [comment]
Thanks. We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
