### ISSUE TITLE
Add ability to schedule model monitor using a custom containers

### ISSUE THREAD

**Issue by vinayhanumaiah** [aws/sagemaker-python-sdk#2210]
**Describe the feature you'd like**
As a user I should be able to schedule model monitor using a custom container using SageMaker SDK.

**How would this feature be used? Please describe.**
If a user wants to bring in their custom drift detection algorithm, they would build a custom container. They would use SageMaker SDK's [method](https://sagemaker.readthedocs.io/en/stable/api/utility/session.html?highlight=create_monitoring_schedule#sagemaker.session.Session.create_monitoring_schedule) to launch custom container. They specify the image name and image arguments. That would need adding a method parameter that would accept a dict (refer to Boto3 [API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_monitoring_schedule) for how they do it).

**Describe alternatives you've considered**
I have used Boto3 [API](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.create_monitoring_schedule) to schedule model monitor job with customer container (parameter: 'MonitoringAppSpecification': {
                'ImageUri': String}}).

**Additional context**

**Comment by nigenda-amazon** [comment]
Actually you would use the [ModelMonitor](https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_monitor.model_monitoring.ModelMonitor) class, and then call `create_monitoring_schedule`.

However, the `ModelMonitor` class doesn't work if you want a custom model quality job, as model quality requires merging with ground truth which is only done for [ModelQualityMonitor](https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_monitor.model_monitoring.ModelMonitor) and `ModelBiasMonitor`.

Hence we either need a new `ModelMonitor` base class to support such use cases, or to add the parameter to `ModelQualityMonitor`

**Comment by nigenda-amazon** [comment]
I will keep this open to track adding custom container support for model quality monitoring.

**Comment by naveen-marthala** [comment]
@nigenda-amazon please make sagemaker-model-monitor-analyzer docker image public. it's been really hard for me to debug problems i had scheduling model quality monitoring jobs. ref: https://stackoverflow.com/questions/69252444/cannot-access-and-pull-pre-built-sagemaker-model-monitor-analyzer-docker-images

**Comment by naveen-marthala** [comment]
some reasons for why I would like to use custom containers for monitoring jobs:
1. currently you only support CSV output types. everything my models or endpoints return has been BASE64 encoded. so, i would like to be able to deal with them myself.
2. in data quality jobs, to be able to change the function used to calculate similarity in distribution of continuous columns. currently it is kolmogrov-smirnov test.
3. i would like to be able to monitor the quality of models that predict multiple labels.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
