### ISSUE TITLE
accelerator_type does not work with TensorFlowModel

### ISSUE THREAD

**Issue by scott2b** [aws/sagemaker-python-sdk#2212]
**Describe the bug**
According to the docs here: https://sagemaker.readthedocs.io/en/stable/frameworks/tensorflow/using_tf.html#deploying-directly-from-model-artifacts, once should be able to specify the accelerator_type for a TensorFlowModel. However, for both tensorflow 2.3 and 2.4 this throws a variation of the following error:

AttributeError: The TensorFlow version 2.4 doesn't support EIA.

**To reproduce**
Create a TensorFlowModel and deploy with accelerator_type specified as an ml.eiax.xx class instance.

**Expected behavior**
A model and endpoint are created which are configured to use elastic inference.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: sagemaker==2.29.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Tensorflow
- **Framework version**:  2.3 - 2.4.1
- **Python version**: 3.8.6
- **CPU or GPU**: ml.g4dn.xlarge specified as instance type, however also tried with m class instances
- **Custom Docker image (Y/N)**: N

**Comment by scott2b** [comment]
Digging into the code, it would appear that 2.0 is the highest supported Tensorflow version for elastic inference, which is perplexing and frustrating to say the least. It would be helpful if this information were in the docs. Nowhere can I find this documented either in the Sagemaker SDK docs, or in any of the online documentation for Sagemaker in general. More helpful would be a roadmap or statement regarding plans to implement EIA for newer versions of Tensorflow.

**Comment by martinRenou** [comment]
It seems this was fixed with https://github.com/aws/sagemaker-python-sdk/pull/2242 in March 2021
