### ISSUE TITLE
Unable to lookup dns from private hosted dns zone in route 53

### ISSUE THREAD

**Issue by brinley** [aws/sagemaker-python-sdk#2216]
**Describe the bug**
After creating a SageMaker model using the model API (https://sagemaker.readthedocs.io/en/stable/api/inference/model.html) with a custom container and initiating a new batch transform job, my custom container is unable to resolve privately hosted local domain names from route 53.

According to the docs, SageMaker API accepts a vpc_config parameter which only accepts SecurityGroupIds and Subnets but not a VPC id.

However according to 
https://docs.aws.amazon.com/vpc/latest/userguide/vpc-dns.html#vpc-dns-updating DNS resolution needs to be enabled on the VPC itself.

Replicating the same SecurityGroupIds and Subnets do not enable local dns lookups to work.

Creating a public dns for that local AWS resource works.

**To reproduce**
- Create a privately hosted dns in route 53
- Add a dns record pointing to an existing internal service such as an RDS db
- Create a custom SageMaker container that connects to that AWS resource via a local domain name
- Create a new SageMaker model with that container with appropriate vpc_config that allows access to the AWS resource
- Create and run a batch transform with this new SageMaker model.
- Logs will show it is unable to resolve the local dns.

**Expected behavior**
I'm not familiar with how VPCs work under the hood, so perhaps you need to add support in vpc_config to accept a vpc id.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: latest
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**: 
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**: Y

**Comment by davidBernardWefox** [comment]
Do you solve the issue ? (I have the similar issue try to access a private internal service from a Training Job)

**Comment by brinley** [comment]
> Do you solve the issue ? (I have the similar issue try to access a private internal service from a Training Job)

Not really, I worked around the issue by using a publicly resolvable dns name

**Comment by davidBernardWefox** [comment]
In fact my issue was that the python api of Estimators and Model are not consistent:
- for Estimators (and inherited classes Framework,…), add to the constructor: `subnets` and `security_group_ids`
- for Model (and inherited classes FrameworkModel,…), add to the constructor: `vpc_config`

When set "properly",
- the custom VPC settings are visible into the Web Management Console of the job (Network section)
- the job is able to access private hostname (defined in route53, and associated to the VPC)

For the subnets, I used private subnet with a nat in the route table, that why the resolution is made.

**Comment by marckarp** [comment]
This is does not appear to be an SDK issue. Issue is related to VPC config set up. The ENI that is launched when you provide a VPC config has a private IP address in the specified subnet.

**Comment by akrishna1995** [comment]
Closing as per comment above. Please feel free to reopen if the issue still persists.
