### ISSUE TITLE
PyTorch estimator support for py_version 3.8

### ISSUE THREAD

**Issue by dorringel** [aws/sagemaker-python-sdk#2221]
**Describe the feature you'd like**
PyTorch estimator support for py_version 3.8

**How would this feature be used? Please describe.**
Currently the Sagemaker Python SDK supports Python 3.8, but the PyTorch Estimator ([this](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html#sagemaker.pytorch.estimator.PyTorch)) Only supports Python 3.6 or earlier:

`py_version (str) – Python version you want to use for executing your model training code. One of ‘py2’ or ‘py3’. Defaults to None. Required unless image_uri is provided.`

**Describe alternatives you've considered**
Creating a pre-build image

**Comment by ahsan-z-khan** [comment]
Hi @dorringel ,

Thanks for using SageMaker SDK. We have added Python 3.8 support since PyTorch 1.9.0

- Ahsan
