### ISSUE TITLE
'code' argument is marked as optional on ProcessingStep

### ISSUE THREAD

**Issue by staubhp** [aws/sagemaker-python-sdk#2237]
**Describe the bug**
The [code argument is marked as optional on the ProcessingStep class](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/steps.py#L320) but not providing this will throw `code None url scheme b'' is not recognized. Please pass a file path or S3 url` when the pipeline definition is generated.

This argument is marked as required on the ScriptProcessor which the ProcessingStep is mirrored from.

**To reproduce**
```
from sagemaker.processing import ProcessingInput, ProcessingOutput
from sagemaker.workflow.steps import ProcessingStep
from sagemaker.workflow.pipeline import Pipeline
    
step_process = ProcessingStep(
    name="AbaloneProcess",
    processor=sklearn_processor,
    inputs=[
      ProcessingInput(source=input_data, destination="/opt/ml/processing/input"),  
    ],
    outputs=[
        ProcessingOutput(output_name="train", source="/opt/ml/processing/train"),
        ProcessingOutput(output_name="validation", source="/opt/ml/processing/validation"),
        ProcessingOutput(output_name="test", source="/opt/ml/processing/test")
    ],
    code=None,
)

pipeline_name = f"AbalonePipeline"
pipeline = Pipeline(
    name=pipeline_name,
    steps=[step_process],
)

pipeline.definition()
```

**Expected behavior**
The ProcessingStep constructor should match the ScriptProcessor `run()` method and require the `code` argument.

**Comment by jerrypeng7773** [comment]
Now, as we support the step construction with `step_args`.
