### ISSUE TITLE
error with hyperparameters tuning

### ISSUE THREAD

**Issue by guilloufre** [aws/sagemaker-python-sdk#224]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Factorization Machine
- **Framework Version**: 
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.4.1
- **Are you using a custom image**:

### Describe the problem
Hello,
I tried to use the newly released hyperparameters tuning described on the aws blog, but some error was thrown, when I launch the following command:
`tuner.fit({'train': records_train, 'test': records_val})`

This is the error:

```
Traceback (most recent call last):

  File "<ipython-input-20-9c3ba798ac1a>", line 1, in <module>
    tuner.fit({'train': s3_train_data, 'test': s3_val_data})

  File "/usr/local/lib/python2.7/dist-packages/sagemaker/tuner.py", line 144, in fit
    self.estimator._prepare_for_training(job_name)

  File "/usr/local/lib/python2.7/dist-packages/sagemaker/amazon/amazon_estimator.py", line 117, in _prepare_for_training
    feature_dim = records.feature_dim

AttributeError: 'NoneType' object has no attribute 'feature_dim'
```

Both records_train and records_val are RecordSet objects. For example, this is records_train:
`(<class 'sagemaker.amazon.amazon_estimator.RecordSet'>, {'s3_data_type': 'S3Prefix', 'feature_dim': 2229, 'num_records': 7923, 'channel': 'train', 's3_data': 's3://###############'})`

The training of the Factorization machine works if I launch:
`fm_estimator.fit(records_train, mini_batch_size = 1000)`
I also tried by providing direct links to s3 instead of RecordSet object with
`tuner.fit({'train': s3_train_data, 'test': s3_val_data})`
 like in the example on the blog, but it throws the same error. 

Thanks for helping me about this issue!

**Comment by laurenyu** [comment]
hi @guilloufre, thanks for trying out the new hyperparameter tuning feature!

The error is because you need to pass a list with the `RecordSet` objects instead of a dict to `fit()`. (the channel names are already specified in the `RecordSet` class, so no need to write them again.)

**Comment by guilloufre** [comment]
Thanks, it was actually easy! :)

**Comment by phschimm** [comment]
When using the `record_set()` method referenced [here](https://sagemaker.readthedocs.io/en/stable/algorithms/randomcutforest.html#sagemaker.RandomCutForest.record_set), the created `RecordSet` does not use the required `S3DataDistributionType=FullyReplicated` but instead uses `ShardedByS3Key`.

I'm trying to use the high level Python API to get metrics about my created models:

```python
from sagemaker import RandomCutForest
from sagemaker.tuner import HyperparameterTuner, IntegerParameter

rcf = RandomCutForest(..., eval_metrics=['accuracy', 'precision_recall_fscore'])

train_set = rcf.record_set(features,
                           channel='train')

test_set = rcf.record_set(features,
                          labels=labels,
                          channel='test')

tuner = HyperparameterTuner(estimator=rcf,
                            objective_metric_name='test:f1',
                            hyperparameter_ranges={'num_samples_per_tree': IntegerParameter(32, 512),
                                                   'num_trees': IntegerParameter(50, 1000)},
                            max_jobs=1,
                            max_parallel_jobs=1)

tuner.fit([train_set, test_set])
```

When I execute this code, I get the following error in the AWS SageMaker console:

> Failure reason
> ClientError: Unable to initialize the algorithm. Failed to validate input data configuration. (caused by ValidationError) Caused by: 'ShardedByS3Key' is not one of ['FullyReplicated'] Failed validating 'enum' in schema['properties']['test']['properties']['S3DistributionType']: {'enum': ['FullyReplicated'], 'type': 'string'} On instance['test']['S3DistributionType']: 'ShardedByS3Key'

Is there a manual way to create a `RecordSet` that has the correct `S3DataDistributionType`?
