### ISSUE TITLE
Missing APIs for sagemaker.model_metrics

### ISSUE THREAD

**Issue by juliensimon** [aws/sagemaker-python-sdk#2247]
MetricsSource and ModelMetrics are completely undocumented at the moment.

**Comment by IvyBazan** [comment]
These APIs are now documented:

https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_metrics.MetricsSource
https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_metrics.ModelMetrics
