### ISSUE TITLE
Scikit processing example - Client LogStream error #8

### ISSUE THREAD

**Issue by gerold-csendes-epam** [aws/sagemaker-python-sdk#2253]
**Describe the bug**
When running the the local scikit-learn processing [srcipt](https://github.com/aws-samples/amazon-sagemaker-local-mode/tree/main/scikit_learn_local_processing) on a notebook instance the training job finishes successfully but I get the following error (I substituted the user and and resource id-s with ....):
`ClientError: An error occurred (AccessDeniedException) when calling the DescribeLogStreams operation: User: ... is not authorized to perform: logs:DescribeLogStreams on resource: ... -group:/aws/sagemaker/ProcessingJobs:log-stream`

It seems like it is trying to write logs which is not really necessary in the local mode, is it? Maybe the issue is that I run the script on sagemaker? 

I originally posted the issue at the local example [repo](https://github.com/aws-samples/amazon-sagemaker-local-mode)

**To reproduce**
Run the aforementioned notebook.

**Screenshots or logs**
This is the last thing that gets outputted before the error:
```
405xfy7qlb-algo-1-xyh7a | Processing Complete
405xfy7qlb-algo-1-xyh7a exited with code 0
Aborting on container exit...
===== Job Complete =====
```
**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.31.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Sklearn 
- **Framework version**:  0.20.0
- **Python version**:  python3
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
I can get rid of the error by specifying `logs=False` argument.

**Comment by NeilJonkers** [comment]
I can reproduce this issue with **SKLearnProcessor** in local mode.
In Cloudtrail I can detect the DescribeLogStreams API call
