### ISSUE TITLE
Unexpected and dangerous behaviours with MXNet estimator's code uploading

### ISSUE THREAD

**Issue by humanzz** [aws/sagemaker-python-sdk#226]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: MXNet
- **Framework Version**: 1.1
- **Python Version**: 3
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.4.1
- **Are you using a custom image**: No

### Describe the problem
Using an MXNet estimator to fit a model and deploy it to an endpoint has the following problems:
1. **Duplicate source code upload**
    **deploy** unnecessarily re-uploads source code on a just-fit estimator to a different path
2. **Using custom s3 bucket for model artifacts and source code issues**
    a. code_location unnecessarily requires an s3 key prefix
    b. deploy ignores the training job name prefix leading to overwriting source code at the same location across different training jobs which is very dangerous
 
#### 1. Duplicate source code upload
Out of the box, using the example in README, to **fit** a model and **deploy** to an endpoint, the SDK uses an S3 bucket it creates to store both the fitting and deployment artifacts as follows

```
from sagemaker.mxnet import MXNet

# Configure an MXNet Estimator (no training happens yet)
mxnet_estimator = MXNet('train.py',
                                             source_dir='src',
                                             base_job_name='my-awesome-model'
                                             train_instance_type='ml.p2.xlarge',
                                             train_instance_count = 1)

# Starts a SageMaker training job and waits until completion.
mxnet_estimator.fit('s3://my_bucket/my_training_data/')
```
will create the following artifacts
- model artifact: s3://sagemaker-[AWS Region]-[AWS Account Id]/**my-awesome-model-[Timestamp]/output**/model.tar.gz
- source directory: s3://sagemaker-[AWS Region]-[AWS Account Id]/**my-awesome-model-[Timestamp]/source**/sourcedir.tar.gz

which is great because it does the following
- Keep everything in the same bucket
- Create a unique prefix for the training job
- Create the model.tar.gz and the sourcedir.tar.gz with output and source prefixes respectively

Moving to deploy from that just-fit estimator
```
# Deploys the model that was generated by fit() to a SageMaker Endpoint
mxnet_predictor = mxnet_estimator.deploy(initial_instance_count=1, instance_type='ml.p2.xlarge')
```

**re-uploads** the source code to
- s3://sagemaker-[AWS Region]-[AWS Account Id]/**my-awesome-model-[Timestamp]**/sourcedir.tar.gz (no source prefix)
and then moves to create Model, EndpointConfig and Endpoint using that just-uploaded source code.

This means that, the source code is uploaded twice
1. Once by fit to s3://sagemaker-[AWS Region]-[AWS Account Id]/**my-awesome-model-[Timestamp]/source**/sourcedir.tar.gz (used by Training Job)
2. Another time by deploy to s3://sagemaker-[AWS Region]-[AWS Account Id]/source/**my-awesome-model-[Timestamp]**/sourcedir.tar.gz (used by Model)

I understand where the issue comes from - MXNetModel is used by the MXNet estimator's deploy method and since MXNetModel also supports bring-your-own-model, it's uploading the source code.
I believe there should be 2 code paths; one for code already existing in S3 to be used by the estimator and one for the BYOM.
- https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/mxnet/estimator.py#L85
- https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/mxnet/model.py#L89

#### 2. Using custom s3 bucket for model artifacts and source code issues
Aiming to use my own S3 bucket for all generated artifacts, I changed the code to 
```
from sagemaker.mxnet import MXNet

# Configure an MXNet Estimator (no training happens yet)
mxnet_estimator = MXNet('train.py',
                                             source_dir='src',
                                             base_job_name='my-awesome-model'
                                             train_instance_type='ml.p2.xlarge',
                                             train_instance_count = 1,
                                             // NEW
                                             output_path=s3://my-awesome-bucket,
                                             // NEW - Notice how I had to also add /code
                                             code_location=s3://my-awesome-bucket/code)

# Starts a SageMaker training job and waits until completion.
mxnet_estimator.fit('s3://my_bucket/my_training_data/')

# Deploys the model that was generated by fit() to a SageMaker Endpoint
mxnet_predictor = mxnet_estimator.deploy(initial_instance_count=1, instance_type='ml.p2.xlarge')
```
##### a. code_location unnecessarily requires an s3 key prefix
I had to add the `/code` prefix to `code_location=s3://my-awesome-bucket/code` to satisfy https://github.com/aws/sagemaker-python-sdk/blob/7fea237768e257240820f499a616224b7901f23c/src/sagemaker/estimator.py#L574
Notice how this is different from using the default bucket in https://github.com/aws/sagemaker-python-sdk/blob/7fea237768e257240820f499a616224b7901f23c/src/sagemaker/estimator.py#L571 which does not require a key prefix.

Unnecessarily using the `/code` key prefix to satisfy code produces the following artifacts
- **fit**'s model artifact: s3://my-awesome-bucket/**my-awesome-model-[Timestamp]/output**/model.tar.gz
  This is fine.
- **fit**'s source code: s3://my-awesome-bucket/**code/my-awesome-model-[Timestamp]/source**/sourcedir.tar.gz
  This is fine-ish. Ideally, I want all the model artifacts to be prefixed by `my-awesome-model-[Timestamp]` but unfortunately `/code` has to come first
- **deploy**'s EXTREMELY DANGEROUS source code: s3://my-awesome-bucket/**code/source**/sourcedir.tar.gz
  Notice how this completely ignores the training job name. This means that if I train/deploy parallel jobs, there will be races and data loss.
##### b. deploy ignores the training job name prefix leading to overwriting source code at the same location across different training jobs which is very dangerous
See the last point above.

An **ugly** workaround for now until this is fixed is to do the following for deployment
```
mxnet_estimator.code_location = get_config(current_env, 'artifacts_s3_bucket') + '/' + m.latest_training_job.name

# Deploys the model that was generated by fit() to a SageMaker Endpoint
mxnet_predictor = mxnet_estimator.deploy(initial_instance_count=1, instance_type='ml.p2.xlarge')
```
which will at least properly namespace the fit's source code artifact as follows
- s3://my-awesome-bucket/**my-awesome-model-[Timestamp]**/sourcedir.tar.gz

**I believe all the above stems from following**
1. Stop requiring a key prefix for setting code_location (I might send a pull request for that if time permits)
2. Update the MXNetModel to have a code path taking into consideration it's coming from the MXNet's Estimator deploy (re-using the source artifacts)

**Comment by humanzz** [comment]
Sent a pull request https://github.com/aws/sagemaker-python-sdk/pull/227 for 2.a above.

**Comment by humanzz** [comment]
Sent https://github.com/aws/sagemaker-python-sdk/pull/228 that should help with 2.b above

**Comment by humanzz** [comment]
Sent #230 for 1 above.

**Comment by laurenyu** [comment]
#227, #228, and #230 have all been merged. Thanks for the wonderful contributions!
