### ISSUE TITLE
`run_baseline` API feature parity with `suggest_baseline`

### ISSUE THREAD

**Issue by nigenda-amazon** [aws/sagemaker-python-sdk#2274]
**Describe the feature you'd like**
A clear and concise description of the functionality you want.
[suggest_baseline](https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_monitor.model_monitoring.DefaultModelMonitor.suggest_baseline) API has some extra fields like `baseline_dataset` (which can be a plain string rather than always a `ProcessingInput`) and `dataset_format`.

Note the discrepancies versus [run_baseline](https://sagemaker.readthedocs.io/en/stable/api/inference/model_monitor.html#sagemaker.model_monitor.model_monitoring.ModelMonitor.run_baseline)

**How would this feature be used? Please describe.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

These extra fields are also useful for BYOC schedules, which are currently left out.

**Describe alternatives you've considered**

Boto APIs can be used to recreate the missing functionality, but are not as concise. Some of these are also translated to env variables in the backend, a mapping which is tricky to ensure correctness for.

**Additional context**

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
