### ISSUE TITLE
[Feature] Support local mode in rootless docker

### ISSUE THREAD

**Issue by elgalu** [aws/sagemaker-python-sdk#2276]
https://github.com/aws/sagemaker-python-sdk/blob/5348eda625b293469c532974988b52df6208a1e0/src/sagemaker/local/image.py#L91

Hi, it would be great if [rootless docker](https://docs.docker.com/engine/security/rootless/) is supported to run SageMaker in local mode, this way we don't need to allow root access to end users in restricted enterprise environments.

**Comment by cenkbircanoglu** [comment]
+1

**Comment by pduy** [comment]
+1

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
