### ISSUE TITLE
HyperparameterTuner does not support TuningJobCompletionCriteria supported by Create API

### ISSUE THREAD

**Issue by jerrypeng7773** [aws/sagemaker-python-sdk#2299]
**Describe the feature you'd like**
HyperparameterTuner does not support TuningJobCompletionCriteria as part of the HyperParameterTuningJobConfig, however, this parameter is supported by Create API.

**How would this feature be used? Please describe.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by akrishna1995** [comment]
Thanks @jerrypeng7773 - I see we are supported the param now: https://github.com/aws/sagemaker-python-sdk/blob/c797f2d54a6375993d1f4d8efd2fef52e81b3305/src/sagemaker/tuner.py#L612. Can you please confirm on your end too with the latest sagemaker ? Please feel free to reopen if the issue still persists. Thanks
