### ISSUE TITLE
HyperparameterTuner does not support TrainingJobDefinition[s]

### ISSUE THREAD

**Issue by jerrypeng7773** [aws/sagemaker-python-sdk#2300]
**Describe the feature you'd like**

currently, HyperparameterTuner only support one estimator, and this translates to a single TrainingJobDefinition when constructing the CreateHyperParameterTuningJobRequest. However, the CreateHyperParameterTuningJobRequest accepts TrainingJobDefinition[s] to run HPO job in multi-algo mode.   

**How would this feature be used? Please describe.**

This is supported in create API, so would be useful to support in python SDK level.

**Describe alternatives you've considered**

**Additional context**

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
