### ISSUE TITLE
sagemaker.workflow.step_collections.RegisterModel does not propagate the VPC config to repacker

### ISSUE THREAD

**Issue by yevgeniyilyin** [aws/sagemaker-python-sdk#2302]
**Describe the bug**
RegisterModel step is unable to use VPC config to access S3 buckets via VPC endpoints. The problem is in the internal implementation of _RepackModelStep. The SKLearn repacker does not use the VPC config from the original estimator: https://github.com/aws/sagemaker-python-sdk/blob/cdb633b3ab02398c3b77f5ecd2c03cdf41049c78/src/sagemaker/workflow/_utils.py#L88

**To reproduce**
Use VPC config setup for all pipeline steps to access S3 bucket via the VPC endpoint. The ProcessingStep and TrainingStep can use the VPC config (via Estimator and constructor parameters). RegisterModel step fails with AccessDenied exception because it does not use the specified VPC config.

**Expected behavior**
RegisterStep must use the provided VPC config and pass it to repacker

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**
This is a showstopper for a customer because all communication to S3 bucket must be done via an VPC endpoint.

**Comment by yevgeniyilyin** [comment]
See more discussion here: https://answers.amazon.com/questions/204072#204108

**Comment by staubhp** [comment]
Fixed with commit above
