### ISSUE TITLE
AWS Sagemaker p36 kernel issue

### ISSUE THREAD

**Issue by eviraj** [aws/sagemaker-python-sdk#2312]
**Describe the bug**
The current tensorflow version in the p36 kernel of AWS Sagemaker Notebook is 2.1.3. When I upgrade the tensorflow using pip3 install --upgrade tensorflow-gpu , its getting upgraded to 2.4.1 but the GPU is not being recognized. 
i.e. tf.config.list_physical_devices('gpu') is giving me [] 
Previously before upgrading , I was able to use the GPU.

Framework name : Tensorflow-gpu
2.1.3 current version , 2.4.1 upgraded version
GPU

**Comment by martinRenou** [comment]
As far as I understand, it may not be possible to update the tensorflow version this way?

Closing for triaging. Please reopen/continue the discussion if needed.
