### ISSUE TITLE
Client Error while doing model deployment using Sagemaker Studio notebook

### ISSUE THREAD

**Issue by sandipto-sanyal** [aws/sagemaker-python-sdk#2313]
**Describe the bug**
Client Error while performing model deployment using Sagemaker Studio notebook instance.

**To reproduce**
Following the documentation: https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-model-deployment.html, below is the step we are performing:
1. Trained a classification model XGBoost
2. Then tried deploying the model where I got the below error. This error appeared only in sagemaker studio notebook but not in actual sagemaker notebook.

**Code snippet**
import sagemaker
from sagemaker.serializers import CSVSerializer
predictor=model.deploy(
    initial_instance_count=1,
    instance_type='ml.t2.medium',
    serializer=CSVSerializer(),
    tags=tags
)

Model was fitted correctly and went into completion
**Expected behavior**
Expected behavior should be model should be deployed in an endpoint

**Screenshots or logs**
ClientError                               Traceback (most recent call last)
<ipython-input-50-13f7e6fe6631> in <module>
      4     initial_instance_count=1,
      5     instance_type='ml.t2.medium',
----> 6     serializer=CSVSerializer()
      7 )
/opt/conda/lib/python3.7/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, use_compiled_model, wait, model_name, kms_key, data_capture_config, tags, **kwargs)
    939             wait=wait,
    940             kms_key=kms_key,
--> 941             data_capture_config=data_capture_config,
    942         )
    943 
/opt/conda/lib/python3.7/site-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, **kwargs)
    783             kms_key=kms_key,
    784             wait=wait,
--> 785             data_capture_config_dict=data_capture_config_dict,
    786         )
    787 
/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in endpoint_from_production_variants(self, name, production_variants, tags, kms_key, wait, data_capture_config_dict)
   3465 
   3466             self.sagemaker_client.create_endpoint_config(**config_options)
-> 3467         return self.create_endpoint(endpoint_name=name, config_name=name, tags=tags, wait=wait)
   3468 
   3469     def expand_role(self, role):
/opt/conda/lib/python3.7/site-packages/sagemaker/session.py in create_endpoint(self, endpoint_name, config_name, tags, wait)
   2965 
   2966         self.sagemaker_client.create_endpoint(
-> 2967             EndpointName=endpoint_name, EndpointConfigName=config_name, Tags=tags
   2968         )
   2969         if wait:
/opt/conda/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)
/opt/conda/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             error_code = parsed_response.get("Error", {}).get("Code")
    675             error_class = self.exceptions.from_code(error_code)
--> 676             raise error_class(parsed_response, operation_name)
    677         else:
    678             return parsed_response
ClientError: An error occurred (ValidationException) when calling the CreateEndpoint operation: The provided tags "Tag(sagemaker:project-id, x-xxxxxxx),Tag(sagemaker:project-name, xxxxxxx),Tag(sagemaker:project-id, xxxxxx),Tag(sagemaker:project-name, xxxxxx)" must not have duplicate keys.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: Sagemaker Studio Python3 Data science Kernel Notebook
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: XGBoost, Linear-learn, KNN (same error for all) while deploying
- **Framework version** latest
- **Python version**: 3
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

**Comment by yehudacohen** [comment]
I've been running into the same issue here.

**Comment by yehudacohen** [comment]
Upon further investigation this is due to [this line of code](https://github.com/aws/sagemaker-python-sdk/blob/be8a19d98c3d6164f420d6c3ef39f354a6194c5b/src/sagemaker/_studio.py#L44) executing multiple times in [`model.deploy()` code](https://github.com/aws/sagemaker-python-sdk/blob/be8a19d98c3d6164f420d6c3ef39f354a6194c5b/src/sagemaker/model.py#L763): first when the model is created and second [when the model is deployed](https://github.com/aws/sagemaker-python-sdk/blob/be8a19d98c3d6164f420d6c3ef39f354a6194c5b/src/sagemaker/model.py#L763). I have a monkey patched fix that I'm compiling a pull request with.

**Comment by yehudacohen** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/2419
 
Looks like someone pushed a different fix to the same issue that got merged :(

**Comment by icywang86rui** [comment]
The fix has been merged and released. Resolving.
