### ISSUE TITLE
Pipeline parameters documentation has very less argument details

### ISSUE THREAD

**Issue by sandipto-sanyal** [aws/sagemaker-python-sdk#2314]
**What did you find confusing? Please describe.**
Document source: https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#parameters

They take an argument enum. Its a useful feature but is not mentioned anywhere in the document about the utility and data type it takes. Moreover neither documentation nor docstring mentions the limits of putting a maximum of 16 elements

**Describe how documentation can be improved**
Add the missing information

**Additional context**
Add any other context or screenshots about the documentation request here.

**Comment by sandipto-sanyal** [comment]
Same feedback given by me in one of the tickets. Its very time consuming to see the pipeline failing due to this limitation which should have been clearly documented

**Comment by jerrypeng7773** [comment]
we will have a more comprehensive documentations upcoming.
https://github.com/aws/sagemaker-python-sdk/pull/3081

**Comment by qidewenwhen** [comment]
Here's the more comprehensive document for Parameter:
- Parameter: https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html#pipeline-parameters
- Parameter limitation: https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html#limitations

This document also provides more description on other Pipeline SDK components.

**Comment by qidewenwhen** [comment]
Closing this issue. Feel free to reopen if you have any other questions.
