### ISSUE TITLE
output_path to set default code_location on Framework estimators

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#2325]
**Describe the feature you'd like**

To help keep the default bucket tidy with minimal notebook/user boilerplate, setting an `output_path` on a Framework Estimator should automatically set the `code_location`, if it's not provided.

Since both parameters automatically create a (matching) subfolder structure anyway (e.g. `output_path/job-name/output` and `code_location/job-name/source`), the artifacts should sit nicely together... And sharing a path by default would:

1. Improve transparency by making it more obvious where the code was uploaded, when users explore the job outputs in S3
2. Help users by making it easier to redirect *all* job artifacts from the SageMaker default bucket to their target location

**How would this feature be used? Please describe.**

If a user creates e.g.

```python
estimator = PyTorch(
    source_dir="src",
    entry_point="train.py",
    base_job_name="my-cool-model",
    output_path="s3://mybucket/training-jobs",
)
```

...Then in addition to storing training job **outputs** to e.g. `s3://mybucket/training-jobs/my-cool-model-2021-05-05-11-33-12-163/output`, the estimator would automatically **upload** the `sourcedir.tar.gz` to `s3://mybucket/training-jobs/my-cool-model-2021-05-05-11-33-12-163/source/`.

With the above code today, the `sourcedir.tar.gz` would still go to `s3://{SM Default Bucket}/my-cool-model-2021-05-05-11-33-12-163/source/`. The user would need to also separately specify the `code_location` parameter to push it to `mybucket` as well.

I'd argue that, because `job-name/output` subfolder structure is already created automatically, it's much more likely that a user setting the `output_path` would like their code delivered to that same working area as `job-name/source`, than explicitly wanting it in the SageMaker default bucket.

If a user **did** want to specify a separate location, they could still explicitly set the `code_location` parameter which could work as it does today.

**Describe alternatives you've considered**

I guess other options would be:

1. Preserve existing behaviour
2. Remove the code_location parameter altogether and *always* send the sourcedir to the same S3 location as the job outputs (might be even nicer/simpler, but a more breaking change!)

**Additional context**

I was just recently trying to tidy up my default bucket, and puzzled when things were still getting created there even though I'd used `output_path` in creating training jobs.

**Comment by mathcass** [comment]
I was just about to make a new issue when I found this one. 

> I'd argue that, because job-name/output subfolder structure is already created automatically, it's much more likely that a user setting the output_path would like their code delivered to that same working area as job-name/source, than explicitly wanting it in the SageMaker default bucket.

I'll give a ➕ to this statement. If I'm outputting the model to a specific bucket + prefix, I also want the source.tar.gz there too. Right now, I'm having to go ahead and run the following to achieve that behavior. It's not a pain, but it's more boilerplate code that seems like it should be the default implementation,

```
estimator = Estimator(
    ...
    output_path=MODELS_PATH,
    code_location=MODELS_PATH,
    ...
)
```

Changing the code at around this line would likely change this to what we want,

https://github.com/aws/sagemaker-python-sdk/blob/ae70340bb6ab6af4d2e4c09b64904b18d188c78e/src/sagemaker/estimator.py#L830

Original:
```
                if self.code_location is None:
                    code_bucket, _ = parse_s3_url(self.output_path)
                    code_s3_prefix = self._assign_s3_prefix()
                    kms_key = self.output_kms_key
```

Updated:
```
                if self.code_location is None:
                    code_bucket, key_prefix = parse_s3_url(self.output_path)
                    code_s3_prefix = self._assign_s3_prefix(key_prefix)
                    kms_key = self.output_kms_key
```

**Comment by akrishna1995** [comment]
Thanks for opening this issue. We have since supported SDK defaults : https://sagemaker.readthedocs.io/en/stable/overview.html#configuring-and-using-defaults-with-the-sagemaker-python-sdk 

Please let me know if this supports your use case. Feel free to reopen if there are any issues. Thank you
