### ISSUE TITLE
SageMaker Pipelines: unable to specify S3 URI (defined as output of a previous step) as TrainingStep input

### ISSUE THREAD

**Issue by giuseppeporcelli** [aws/sagemaker-python-sdk#2326]
**Describe the bug**
SageMaker Pipelines: unable to specify S3 URI defined as output of a previous step as `TrainingStep` input. The `inputs` parameter of a `TrainingStep` should support the same ways to provide inputs to an `Estimator`; this includes specifying directly a S3 URI. However, if the S3 URI has to be computed dynamically from the outputs of a previous step, an error is raised when getting the pipeline definition.

**To reproduce**
Create a pipeline with a processing step and a training step, and set the inputs parameter of the training step to the output S3 URI of the processing step.
Example:

```
TrainingStep(
inputs = step_process.properties.ProcessingOutputConfig.Outputs[
                "train"
            ].S3Output.S3Uri
...)
```

Try to get the pipeline definition and an error will be raised.

**Expected behavior**
Being able to provide inputs to a `TrainingStep` in the same way as for `Estimators`. The available options are implemented here:
https://github.com/aws/sagemaker-python-sdk/blob/ac25bfe3f25d811c0d838394969162b7fbf5faa7/src/sagemaker/job.py#L114

**Screenshots or logs**
No screenshots/logs.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.33.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.7
- **CPU or GPU**: N/A
- **Custom Docker image (Y/N)**: N

**Additional context**
N/A

**Comment by jerrypeng7773** [comment]
https://github.com/aws/sagemaker-python-sdk/blob/dev/tests/integ/test_workflow.py#L347

```
step_train = TrainingStep(
        ...
        inputs=TrainingInput(
            s3_data=step_process.properties.ProcessingOutputConfig.Outputs[
                "train_data"
            ].S3Output.S3Uri
        ),
    )
```

This should work. @giuseppeporcelli
