### ISSUE TITLE
Follow symbolic link when packing source and dependencies 

### ISSUE THREAD

**Issue by mhtrinhLIC** [aws/sagemaker-python-sdk#2337]
I am using sagemaker sdk to launch Training Job. I add my codes using `dependencies`. There are couple symbolic link in my code folder that point to common library that is not part of the training project. 

Currently source folder and dependencies packed as is: symbolic link as symbolic link. This mostly break as once extracted in the Docker image instance, the symbolic will likely point to non existing file.

Is it possible to pack the source code and dependencies with `realpath` ?

**Comment by martinRenou** [comment]
Fixed by https://github.com/aws/sagemaker-python-sdk/pull/2338
