### ISSUE TITLE
XGBoost Estimator cannot recognize "objective" parameter

### ISSUE THREAD

**Issue by hsl89** [aws/sagemaker-python-sdk#2340]
**Describe the bug**

**To reproduce**
Please take a look at cell 39 in this notebook

https://github.com/hsl89/sagemaker-notes/blob/master/xgboost/xgboost_customer_churn_studio.ipynb

The `hyperparemeter` sets `objective` to be "binary:logistic" but the training job complains that it cannot recognize the objective. 

Try to run the [](url)

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by rags1357** [comment]
Thank you for raising this to the PySDK team! We are closing this issue since it is no longer relevant. The code changes referenced in this issue were successfully included in a seperate PR and should not longer be a problem.
