### ISSUE TITLE
ImportError: Import by filename is not supported.

### ISSUE THREAD

**Issue by Shivakishore14** [aws/sagemaker-python-sdk#238]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow / Custom algorithm
- **Framework Version**: 1.4.1
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: - (Training via notebook from console)
- **Are you using a custom image**: no

### Describe the problem
I am trying to run sage maker with a custom algorithm by following https://docs.aws.amazon.com/sagemaker/latest/dg/tf-example1.html tutorial.

Here is the code last two cells that differ from the tutorial 
```
from sagemaker.tensorflow import TensorFlow

iris_estimator = TensorFlow(entry_point='/home/ec2-user/SageMaker/sagemaker.py',
                            role=role,
                            output_path=model_artifacts_location,
                            code_location=custom_code_upload_location,
                            train_instance_count=1,
                            train_instance_type='ml.c4.xlarge',
                            training_steps=1000,
                            evaluation_steps=100, source_dir="./", requirements_file="requirements.txt")
```
```
%%time
import boto3

train_data_location = 's3://sagemaker-<my bucket with train data>'

iris_estimator.fit(train_data_location)
```
While running .fit() i get a `ImportError: Import by filename is not supported.`
### Minimal repro / logs
```
2018-06-19 07:14:28,122 ERROR - container_support.training - uncaught exception during training: Import by filename is not supported.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/container_support/training.py", line 36, in start
    fw.train()
  File "/usr/local/lib/python2.7/dist-packages/tf_container/train_entry_point.py", line 143, in train
    customer_script = env.import_user_module()
  File "/usr/local/lib/python2.7/dist-packages/container_support/environment.py", line 101, in import_user_module
    user_module = importlib.import_module(script)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Import by filename is not supported.
```

**Comment by nadiaya** [comment]
You are providing source_dir as well as entry_point.
Does source_dir contain entry_point script?
Does the issue persists if you change entry_point path relative to the source_dir?

**Comment by Shivakishore14** [comment]
source dir contains the script `/home/ec2-user/SageMaker/sagemaker.py` along with other scripts that are used by `sagemaker.py`. (the working directory is `/home/ec2-user/SageMaker/`)
Two questions: 
1. shouldn't we provide `source_dir` and `entry_point` parameters ? if not how will sagemaker know the starting point to the application ?
2. is there any other file naming standards that I should stick to ?

**Comment by Shivakishore14** [comment]
changing the `entry_point='/home/ec2-user/SageMaker/sagemaker.py'` to `entry_point='sagemaker.py'` fixed this issue.
It seems we should use relative path to the `source_dir` for `entry_point`.
