### ISSUE TITLE
Pass locations of local files to an entry point

### ISSUE THREAD

**Issue by harusametime** [aws/sagemaker-python-sdk#240]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Chainer
- **Framework Version**: 4.0.0
- **Python Version**: 3.6.5
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.4.1
- **Are you using a custom image**: SageMaker chainer_p36

### Describe the problem
I am using SageMaker local mode for training the model with local files, which are put in:
Training data : `/home/ec2-user/SageMaker/pascal/train/`
Test data: `/home/ec2-user/SageMaker/pascal/test/`

Then I specify the locations of the files for running fit():
```
chainer_estimator = Chainer(entry_point='train.py',
                            source_dir="./",
                            role=role,
                            train_instance_count=1,
                            train_instance_type='local',
                            hyperparameters={'epochs': 10, 'batch-size': 64})
chainer_estimator.fit({'train': 'file:///home/ec2-user/SageMaker/pascal/train/', 
                          'test': 'file:///home/ec2-user/SageMaker/pascal/test/'})
```
However, the entry point reads files in `/opt/ml/input/train` though I specify the location in fit(). Because the entry point can receive the locations via arguments of `train` and `test`, we can rewrite the code as workaround like
```
chainer_estimator = Chainer(entry_point='train.py',
                            source_dir="./",
                            role=role,
                            train_instance_count=1,
                            train_instance_type='local',
                            hyperparameters={'epochs': 10, 'batch-size': 64
                               'train': '/home/ec2-user/SageMaker/pascal/train/',
                                'test': '/home/ec2-user/SageMaker/pascal/test/'})
chainer_estimator.fit({'train': 'file:///home/ec2-user/SageMaker/pascal/train/', 
                          'test': 'file:///home/ec2-user/SageMaker/pascal/test/'})
```
That works fines, but looks verbose. What is the best way to pass the locations of local files to the entry point?

**Comment by laurenyu** [comment]
hi @harusametime, can you explain a little more of your use case? Why do you want the training script to read from your local path directly?

The reason it reads from `opt/ml/input/train` is because this is the directory within the Docker container to which everything is copied. This is done because when you move from using local mode to training on SageMaker, SageMaker will not have access to your local files; instead, it needs to use the files that have been copied into the Docker container.

**Comment by harusametime** [comment]
@laurenyu 
Thanks to your answer, I have just realized I misunderstand the error message from the container. My code now works fine. As you answered, the local data is copied to  `/opt/ml/input/train` in the docker container, and the files are available for training.
