### ISSUE TITLE
ParameterBoolean is not serialziable.

### ISSUE THREAD

**Issue by Guillem96** [aws/sagemaker-python-sdk#2410]
https://github.com/aws/sagemaker-python-sdk/blob/012c4e8ce6fcf83eb82ccd8578f752ab0f713a62/src/sagemaker/workflow/parameters.py#L142

When using `sagemaker.worflow.parameters.ParameterBoolean` as an estimator hyperparameter the pipeline fails since it is not serializable.

```python
train_data = ParameterString(name="TrainData", 
                                               default_value="s3://...")

use_fast_tokenizer = ParameterBoolean(name="UseFastTokenzier", default_value=True)

hyperparameters = {
    # ...
    "use_fast_tokenizer": use_fast_tokenizer,
}

hf_estimator = HuggingFace(
    entry_point='train.py',
    source_dir='src',
    instance_type="...",
    instance_count=1,
    role="...",
    transformers_version='4.4',
    pytorch_version='1.6',
    py_version='py36',
    hyperparameters=hyperparameters
)

training_step = TrainingStep(name="Train",
                             estimator=hf_estimator,
                             inputs={"train": TrainingInput(s3_data=train_data)})

pipeline = Pipeline(
    name="name",
    parameters=[
        train_data,
        use_fast_tokenizer,
    ],
    steps=[training_step],
)

pipeline.upsert(role_arn=role)
```

The error:

```
TypeError: Object of type 'Parameter' is not JSON serializable
```

**Comment by melzareix** [comment]
Setting it using `estimator.set_hyperparameters` should work

**Comment by Guillem96** [comment]
Why? Does it make sense that one approach works while the other not?

**Comment by dpatro** [comment]
@Guillem96 I am looking into the issue. I am unable to reproduce what you have mentioned. I tried the test script you provided and I received the following error instead:

```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: Cannot assign property reference [Parameters.UseFastTokenzier] to argument of type [String].
```

* Can you please confirm that you are using the latest version of the SageMaker Python SDK?

**Comment by dpatro** [comment]
@Guillem96 I was trying to reproduce the issue using the script you have provided. I encountered the following error

`botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: Cannot assign property reference [Parameters.UseFastTokenzier] to argument of type [String].`

I was able to get past it by making the following change:

```
hyperparameters = {
    "use_fast_tokenizer": "True",
}
```

Reason: https://github.com/aws/sagemaker-python-sdk/blob/012c4e8ce6fcf83eb82ccd8578f752ab0f713a62/src/sagemaker/huggingface/estimator.py#L81-L86

After that, the script proceeded to completion without failure.

Can you confirm that you are using the latest version of the SDK? It might be possible that there was a bug in some earlier version but it is fixed.

**Comment by dpatro** [comment]
Update to my previous comment. If anyone is trying to reference to a pipeline parameter from a training step, the previous method does not work as it hard codes the parameter "use_fast_tokenizer" to True for the training step.

The original problem was because of type mismatch between the hyperparameters values and the defined pipeline parameters values. The hyperparameters expect the values to be Strings. So, by making the following update, the origninal code snippet works fine.

```
# original - is incompatible with the estimator's hyperparamters values
ParameterBoolean(name="UseFastTokenzier", default_value=True)

# updated - works
ParameterString(name="UseFastTokenzier", default_value="True")
```
