### ISSUE TITLE
S3Downloader.download with kms_key argument doesn't work.

### ISSUE THREAD

**Issue by sojiadeshina** [aws/sagemaker-python-sdk#2422]
**Describe the bug**
The `sagemaker.s3.S3Downloader.download` function results in a 

`botocore.exceptions.ClientError: An error occurred (400) when calling the HeadObject operation: Bad Request`

error when used a kms_key id is used.

This is because in this line: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/s3.py#L140. The extra args dictionary is the wrong format for passing in kms [key](url) for decryption. 

The counterpart upload operation is correct however: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/s3.py#L85. 

Removing the kms_key parameter resolves this as s3 will automatically attempt to decrypt any kms encrypted files.

**To reproduce**
Create a Customer managed key using kms.
Grant user/admin access to manage the key to a sagemaker role
Upload a file to S3 and encrypt using the key.
Attempt to download the file using sagemaker.s3.S3Downloader.download

**Expected behavior**

Passing in the correct kms_key in the kms_key parameter should not result in an error. 

kms_key paramater should either be removed from download or the extra args parameter dictionary for the s3 client should be fixed. 

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your prob
![Screen Shot 2021-05-31 at 1 35 15 PM](https://user-images.githubusercontent.com/10650702/120240368-3b4dfa80-c215-11eb-88a0-ea2c347010ad.png)
lem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by rags1357** [comment]
Thank you for raising this to the PySDK team! We are closing this issue since it is no longer relevant. The code changes referenced in this issue were succesfully included in a sperate PR and should not longer be a problem.
