### ISSUE TITLE
calling sagemaker_client.update_endpoint() does not update the endpoint config

### ISSUE THREAD

**Issue by wissambenhaddad** [aws/sagemaker-python-sdk#2431]
**Describe the bug**
As mentioned in the title, when I try to use the `update_endpoint()` function on an existing endpoint but with a new configuration and a new model, the endpoint is not updated in the dashboard, I can see the current configuration is the old one because I use a time based naming for each step.

**Comment by rags1357** [comment]
Not an actual issue anymore after SageMaker Python SDK 3.x you can now use the update_endpoint()
