### ISSUE TITLE
Can't Import Sagemaker

### ISSUE THREAD

**Issue by colts183281** [aws/sagemaker-python-sdk#2436]
When I try to import sagemaker I receive the error "Attribute Error: module 'botocore' has not attribute 'loaders'". I've made sure that botocore and sagemaker are both up-to-date but still nothing. I have also ran _from botocore import loaders_ and no error occured which tells me that botocore does contain the attribute loaders. Not sure what could be going on does anyone have an idea?

**Comment by ahsan-z-khan** [comment]
Hi @colts183281 ,

Thank you for using Amazon SageMaker. Can you provide the below information?

System information
A description of your system. Please provide:

SageMaker Python SDK version: 2.39.1
Framework name (eg. PyTorch) or algorithm (eg. KMeans):
Framework version: 
Python version: 
CPU or GPU:
Custom Docker image (Y/N):

**Comment by martinRenou** [comment]
Closing as probably outdated. Please feel free to reopen if needed.
