### ISSUE TITLE
Processing Inputs limit enforcement for Local Mode 

### ISSUE THREAD

**Issue by anirudhgangwal** [aws/sagemaker-python-sdk#2440]
**Describe the feature you'd like**
Raising a helpful error when using more than 10 inputs with Processing Jobs in local mode. 

**How would this feature be used? Please describe.**
Sagemaker Processing has a limit of 10 Inputs and the SDK raises an error when more inputs are passes:
`processingInputs' failed to satisfy constraint: Member must have length less than or equal to 10.` 

However, when developing in local mode, this restriction is not enforced and we are able to pass as many inputs as needed. This is not ideal as users develop in local mode only to realize they will have to refactor because of this constraint. 

**Describe alternatives you've considered**
Aim is to improve user experience. 

But for more than 10 inputs, we are considering using a Manifest file now.

**Additional context**
N/A

**Comment by sophiayue1116** [comment]
also encounter the same error, but not in a local mode. Any suggestion here?

**Comment by akrishna1995** [comment]
Hi @anirudhgangwal thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.
