### ISSUE TITLE
Cannot use SSH URL to point to a private GitHub repo containing a custom inference script when deploying a model

### ISSUE THREAD

**Issue by evanphilipsmith** [aws/sagemaker-python-sdk#2442]
[The SageMaker Python SDK docs](https://sagemaker.readthedocs.io/en/stable/api/inference/model.html#sagemaker.model.Model) imply that you can use your own `ssh/config` on a notebook instance
> For GitHub and other Git repos, when SSH URLs are provided, it doesn’t matter whether 2FA is enabled or disabled; you should either have no passphrase for the SSH key pairs, or have the ssh-agent configured so that you will not be prompted for SSH passphrase when you do ‘git clone’ command with SSH URLs.

But, the code for cloning repos with an SSH URL uses the `GIT_SSH` environment variable (to make sure that the user isn't prompted for credentials)
https://github.com/aws/sagemaker-python-sdk/blob/9f399cee16ccbad0134ecddf14b9f2846826334a/src/sagemaker/git_utils.py#L280-L287

[The documentation for git](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) says, however, that whatever `GIT_SSH` points to will override any `ssh/config` you have set up.
> `GIT_SSH`, if specified, is a program that is invoked **instead of** `ssh` when Git tries to connect to an SSH host. It is invoked like `$GIT_SSH [username@]host [-p <port>] <command>`. Note that this isn’t the easiest way to customize how `ssh` is invoked; it won’t support extra command-line parameters, so you’d have to write a wrapper script and set `GIT_SSH` to point to it. It’s probably easier just to use the `~/.ssh/config` file for that.

So this means that you can't clone a private repo using an SSH URL. The only way to clone it would be to use a GitHub Personal Access Token (PAT) and an HTTPS URL.

---

To reproduce, use this template code (having an `ssh/config` and a private key set up or not makes no difference in the output behavior):
```python
from sagemaker import get_execution_role
from sagemaker.pytorch.model import PyTorchModel

PyTorchModel(
    model_data=s3_uri_path_to_model_tar_gz,
    git_config={
        "repo": f"git@github.com:{repo_account_name}/{private_repo_name}.git",
        "branch": branch_name,
    },
    code_location=s3_uri_path_to_code_location,
    source_dir=path_to_src_in_github_repo,
    entry_point="inference.py",
    role=get_execution_role(),
    py_version="py3",
    framework_version="1.4"
)
```
Output (not a very helpful message, but that's a different issue :wink: )
```
CalledProcessError: Command '['git', 'clone', 'git@github.com:<org>/<repo>.git', '/tmp/tmp01e7i6rz']' returned non-zero exit status 128.
```

**Comment by timorkal** [comment]
Getting the same thing

**Comment by mgabilo** [comment]
https://github.com/mgabilo/sagemaker-python-sdk/commit/5a70c5d3b68b8d74863d0528b4aab40ebaade67c

**Comment by stkbailey** [comment]
I had to remove this code block entirely to get it to work, as shown in #3645
