### ISSUE TITLE
get_execution_role fails on Studio

### ISSUE THREAD

**Issue by harusametime** [aws/sagemaker-python-sdk#2443]
**Describe the bug**
Performing `get_execution_role` on SageMaker Studio raises `KeyError: 'UserSettings'` with SageMaker Python SDK >= 2.45.0. This does not happen on classic notebook instance and some Studio image with  SageMaker Python SDK <2.45.0; for example,`MXNet 1.6 Python 3.6 CPU` image uses version 2.28.0 as of June 12, and can perform `get_execution_role` successfully.

**To reproduce**
1. Create notebook using image with SageMaker Python SDK >= 2.45.0, such as `Data Science`.
2. Call get `get_execution_role`

**Expected behavior**
We can get role ARN without error.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

<img width="763" alt="スクリーンショット 2021-06-12 23 32 15" src="https://user-images.githubusercontent.com/10037251/121779621-94376e80-cbd7-11eb-92ff-2557f8343b9c.png">

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: >= 2.45.0.
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: 
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by cfregly** [comment]
This is also happening to me with `sagemaker==2.35.0` on SM Studio.

**Comment by aletheia** [comment]
Also happening on ```sagemaker == 2.41.0```

**Comment by cfregly** [comment]
this looks like it may have been addressed in 2.46.0+:  https://github.com/aws/sagemaker-python-sdk/commit/9f399cee16ccbad0134ecddf14b9f2846826334a

Please upgrade and see if this helps.

**Comment by harusametime** [comment]
Yes. I also confirmed the issue has gone in 2.46.0+. Let me close this issue.
