### ISSUE TITLE
Documentation link broken

### ISSUE THREAD

**Issue by johann-petrak** [aws/sagemaker-python-sdk#2444]
In page https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/using_pytorch.html#load-a-model

Text: "For more information on the default inference handler functions, please refer to: SageMaker PyTorch Default Inference Handler." has a link to
https://github.com/aws/sagemaker-pytorch-serving-container/blob/master/src/sagemaker_pytorch_serving_container/default_inference_handler.py

which does not exist and gives a 404

Should instead probably be:

https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/master/src/sagemaker_pytorch_serving_container/default_pytorch_inference_handler.py

**Comment by trungleduc** [comment]
Fixed by #2765
