### ISSUE TITLE
Sagemaker pipelines with script-mode Tensorflow + `source_dir`

### ISSUE THREAD

**Issue by stephenhunter-mdfwork** [aws/sagemaker-python-sdk#2472]
**What did you find confusing? Please describe.**
When running SageMaker Pipelines containing a script-mode Tensorflow training job, where the model script and a `requirements.txt` file are provided in a subfolder as specified by `source_dir`, I was able to run everything fine when starting a Pipeline run via the SageMaker Studio environment. However, when committing the code to the `main` branch of the project, the automated CI/CD in Codebuild fails to find the `source_dir` because it is not packaged. Not being a devops engineer, not having any CI/CD experience, and being a bit ignorant about how Python packages are built with setuptools, I did not know how to fix this and I could not find any documentation to point me in the right direction. Eventually I figured out how to fix it:

- Include an `__init__.py` in the `source_dir` folder so that the `source_dir` folder is packaged. This alone is not enough if a `requirements.txt` file is also provided, so the following step is also needed to include that.
- Change `setup.py` by adding a `package_data` argument to `setuptools.setup()` as below, where `src` is the `source_dir` provided in a subfolder of `my_pipeline`:

```
...
    packages=setuptools.find_packages(),
    include_package_data=True,
    package_data={"pipelines.my_pipeline.src": ["*.txt"]},
    python_requires=">=3.6",
    install_requires=required_packages,
    extras_require=extras,
...
```

The above makes sure that the `requirements.txt` file is packaged and thus found by the training job.

**Describe how documentation can be improved**
For people without DevOps experience, perhaps some more context in the template notebook of the generated SageMaker projects would be useful. Currently, when looking at the `pipelines` description in the `sagemaker-pipelines-project.ipynb` notebook, it says:

"

Your pipeline artifacts, which includes a pipeline module defining the required `get_pipeline` method that returns an instance of a SageMaker pipeline, a preprocessing script that is used in feature engineering, and a model evaluation script to measure the Mean Squared Error of the model that's trained by the pipeline:

```
|-- pipelines
|   |-- abalone
|   |   |-- evaluate.py
|   |   |-- __init__.py
|   |   |-- pipeline.py
|   |   `-- preprocess.py

```

"

Perhaps it would be valuable to just add a note here along the lines of:

"For additional subfolders with code and/or artifacts needed by your pipeline to be visible by pipeline jobs started in Codebuild, they need to be packaged correctly by the `setup.py` file. For example ... ",  etc.

**Additional context**
n/a

Thanks for looking at this issue. I appreciate any feedback :)

**Comment by jerrypeng7773** [comment]
@stephenhunter-mdfwork it would be great if you could share some code snippet

**Comment by stephenhunter-mdfwork** [comment]
@jerrypeng7773 unfortunately I can't share a snippet, but I think the main point is that additional files referred to by a training job, such as a `requirements.txt` file, need to be specifically included as per my post. 

To re-create this issue, you could create a new project in SageMaker Studio, choosing any of the templates that include model building. Then in the `-modelbuild` repo, alter the project to use a `sagemaker.tensorflow.TensorFlow` estimator, and provide a relevant working `model.py` for the `entry_point` argument as well as the `source_dir` where it is located. You will notice that if you have a `requirements.txt` file, it will be included if you run the pipeline from the `sagemaker-pipelines-project.ipynb` notebook. But, if you push your changes to the `main` branch, when the automated pipeline run via CodeBuild kicks off, your `requirements.txt` won't be included unless you change your `setup.py` as per my original post.

**Comment by jerrypeng7773** [comment]
I see, thanks for the clarification, I re-triaged this to training team.

**Comment by jerrypeng7773** [comment]
thanks for the feedback, we are addressing this now

**Comment by jerrypeng7773** [comment]
After second thought, this is more like the 1p project template packaging issue, I've reached out to our internal team. At the meanwhile, given this is open almost 1-year ago, can you please give it another try to see if it works? @stephenhunter-mdfwork

**Comment by jerrypeng7773** [comment]
Reached out to the 1p project team, they made a code change on their side to print out the resolution you listed above. Thanks for letting us know. Close this issue for now, feel free to re-open if you have any other concern.
