### ISSUE TITLE
Getting below error while creating a SageMaker pipeline AttributeError: 'NoneType' object has no attribute 's3_uri'

### ISSUE THREAD

**Issue by raveeshawasthi** [aws/sagemaker-python-sdk#2489]
AttributeError: 'NoneType' object has no attribute 's3_uri'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-28-e8e27d1b3dff> in <module>
----> 1 json.loads(pipeline.definition())

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/pipeline.py in definition(self)
    239     def definition(self) -> str:
    240         """Converts a request structure to string representation for workflow service calls."""
--> 241         request_dict = self.to_request()
    242         request_dict["PipelineExperimentConfig"] = interpolate(
    243             request_dict["PipelineExperimentConfig"]

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/pipeline.py in to_request(self)
     86             if self.pipeline_experiment_config is not None
     87             else None,
---> 88             "Steps": list_to_request(self.steps),
     89         }
     90 

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/utilities.py in list_to_request(entities)
     34     for entity in entities:
     35         if isinstance(entity, Entity):
---> 36             request_dicts.append(entity.to_request())
     37         elif isinstance(entity, StepCollection):
     38             request_dicts.extend(entity.request_dicts())

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/steps.py in to_request(self)
    422     def to_request(self) -> RequestType:
    423         """Get the request structure for workflow service calls."""
--> 424         request_dict = super(ProcessingStep, self).to_request()
    425         if self.cache_config:
    426             request_dict.update(self.cache_config.config)

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/steps.py in to_request(self)
     83             "Name": self.name,
     84             "Type": self.step_type.value,
---> 85             "Arguments": self.arguments,
     86         }
     87         if self.depends_on:

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/steps.py in arguments(self)
    404             inputs=self.inputs,
    405             outputs=self.outputs,
--> 406             code=self.code,
    407         )
    408 

/opt/conda/lib/python3.7/site-packages/sagemaker/processing.py in _normalize_args(self, job_name, arguments, inputs, outputs, code, kms_key)
    220 
    221         inputs_with_code = self._include_code_in_inputs(inputs, code, kms_key)
--> 222         normalized_inputs = self._normalize_inputs(inputs_with_code, kms_key)
    223         normalized_outputs = self._normalize_outputs(outputs)
    224         self.arguments = arguments

/opt/conda/lib/python3.7/site-packages/sagemaker/processing.py in _normalize_inputs(self, inputs, kms_key)
    295                     normalized_inputs.append(file_input)
    296                     continue
--> 297                 if isinstance(file_input.s3_input.s3_uri, (Parameter, Expression, Properties)):
    298                     normalized_inputs.append(file_input)
    299                     continue

AttributeError: 'NoneType' object has no attribute 's3_uri'

**Comment by raveeshawasthi** [comment]
I have full permission of S3 bucket  and sagemaker user has full access to S3

**Comment by jerrypeng7773** [comment]
> I have full permission of S3 bucket and sagemaker user has full access to S3

Hi, do you still seeing this issue, if so, can I have your code snippet constructing the steps and creating the pipeline?
