### ISSUE TITLE
how does custom algorithm access "train" channel's S3 uri and superparameter specified in "create training job" console?

### ISSUE THREAD

**Issue by richardxin** [aws/sagemaker-python-sdk#25]
I'm trying to use scikit_bring_your_own example to test own algorithm
What I'm trying to do:
1) run the sample sagemaker jupyter notenook scikit_bring_your_own.ipynb upto docker push ${fullname}
2) from SageMaker console, Jobs -> "Create New Job"
3) from algorithm dropdown, select Custom, and enter ECR uri created on step 1
4) Specify "train" channel with S3 path
Error was : No such file or directory: '/opt/ml/input/data/training'

https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/decision_trees/train#L21 has hard-coded path.  In my "train" python, how do I access "train" channel's S3 uri? Thanks

**Comment by tomfaulhaber** [comment]
Richard, 

The names of channels are entirely up to the algorithm and unrelated to the S3 URI of the data (which can change arbitrarily from run to run depending where you decide to put your data).

If you want a channel called "foo", there will be a directory called `/opt/ml/input/data/foo` with the copied data files (if you're using file mode, as we are in this example).

In this case, the algorithm specifies that it uses a channel called `training` (by which directory it looks in) so you can do one of two things:

1. When you invoke the algorithm from the console, change the "Channel name" field in the "Input data configuration" section from "train" to "training", or
2. You can change the channel name that the algorithm expects by changing [this line](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/container/decision_trees/train#L30) to `channel_name='train'`.

I hope that's clear and let us know if you have any more questions.
