### ISSUE TITLE
Redundant parameter for Tensorflow Estimator

### ISSUE THREAD

**Issue by vladhondru25** [aws/sagemaker-python-sdk#2507]
When using sagemaker.tensorflow.estimator.TensorFlow I have to mandatory provide entry_point parameter. However, I am also supplying my own custom Docker image which requires an ENTRYPOINT. I think the entry_point in the constructor of sagemaker.tensorflow.estimator.TensorFlow is redundant if you supply a custom Docker image.

**Comment by ahsan-z-khan** [comment]
Hi @vladhondru25 ,

Thanks for using Amazon SageMaker.

Can you give some example of your code?

**Comment by vladhondru25** [comment]
Sorry about that. Here are the two files of interest:

Dockerfile:
```
FROM tensorflow/tensorflow:latest-gpu-jupyter

RUN apt-get update
RUN apt-get install ffmpeg libsm6 libxext6  -y

COPY clean_yolov4/requirements-gpu.txt .
RUN pip3 install -r requirements-gpu.txt

RUN mkdir -p /opt/ml/input/data/train
RUN mkdir -p /opt/ml/input/data/eval
RUN mkdir -p /opt/ml/model
RUN mkdir -p /opt/ml/output

COPY /clean_yolov4/core /opt/ml/code/core
COPY /clean_yolov4/create_estimator.py /opt/ml/code

ENV PATH="/opt/ml/code:${PATH}"
ENV SM_MODEL_DIR="/opt/ml/model"
ENV SM_CHANNEL_TRAIN="/opt/ml/input/data/train/"
ENV SM_CHANNEL_EVAL="/opt/ml/input/data/eval"
ENV SM_CHANNEL_COMMON="/opt/ml/input/data/common/"

WORKDIR '/opt/ml/code'

ENTRYPOINT ["python", "create_estimator.py"]
```

and here is the file I am running:
```
import boto3
import logging
import sagemaker
import sagemaker.tensorflow as stf

import os
# # Let's use Amazon S3
# s3 = boto3.resource('s3')
# # Print out bucket names
# for bucket in s3.buckets.all():
#     print(bucket.name)

sagemaker_session = sagemaker.local.LocalSession()
sagemaker_session.config = {'local': {'local_code': True}}

role = 'SECRET_ROLE' #Modified due to security reasons

tf_estimator = stf.estimator.TensorFlow(
    # Framework
    entry_point=os.path.abspath(os.getcwd())+"/clean_yolov4/create_estimator.py",
    container_log_level=logging.DEBUG,
    # Estimator
    role=role,
    sagemaker_session=sagemaker_session,
    output_path="s3://deep-eye-dev/dev_temp/outputs",
    instance_count=1,
    instance_type="local",
    image_uri='deep-eye:latest'
)

tf_estimator.fit({
    'train': 's3://deep-eye-dev/dev_temp/val2',
    'common': 's3://deep-eye-dev/dev_temp/common',
    'eval': 's3://deep-eye-dev/dev_temp/val2'
})
```

`create_estimator.py` is the training script. As you can see, I have to mention it in both the Dockerfile (as an ENTRYPOINT) and in the Tensorflow Estimator (as parameter entry_point).

For any additional info, please do not hesitate to tell me.

**Comment by mufaddal-rohawala** [comment]
Hi [vladhondru25](https://github.com/vladhondru25), thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK.
 
We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.”
 
Let me know if you have any other questions.
