### ISSUE TITLE
Tensorflow Iris Example not working

### ISSUE THREAD

**Issue by UweBretschneider** [aws/sagemaker-python-sdk#251]
Please fill out the form below.

### System Information
- Tensorflow just like in IRIS example on github
- conda 3.6 with tensorflow
- 3.6
- ml.c4.xlarge

### Describe the problem
So, I try to reproduce the IRIS example with a custom dataset that is located on an s3 bucket. I successfully tested this example dataset with built-in AWS models and the sci-kit learn example with a custom image. Im pretty sure that the dataset is not the problem.

On my journey, I encountered several errors starting from deprecation warnings as the example still  uses training_set = tf.contrib.learn.datasets.base.load_csv_with_header() to ValueErrors with respect to the size of the shape of the tensor.

I don't even know how to start... :)

First, I tried to remove the hardcoding of the filename in iris_dnn_classifier.py. I replaced the hard coded filename with '' and supplied a full path as directory. As I mentioned that this didn't work, I changed it back to what the example suggest, even though I think this is really ugly...
Next, I got an error regarding a type conversion. My class value is 0/1 and the rest is float. I'm using not the Iris dataset by the way, I'm using the diabetes dataset with categorized variables.
It said something like int(10) cannot convert 2.0...

So, I thought it might thinks that this specific column should be the class value but it's actually a feature. I tried a dataset with the class value as last column, I tried a dataset with the class value as first column. I tried all shape values from 1 to 10 even though i have 8 + 1 columns... Nothing works and I don't understand from the error message what's the problem...

Is there any chance that the combination from python 2.7 and 3.6 just doesn't work??

### Minimal repro / logs
That's my iris_dnn_classifier.py:

```python
import numpy as np
import os
import tensorflow as tf

INPUT_TENSOR_NAME = 'inputs'


def estimator_fn(run_config, params):
    feature_columns = [tf.feature_column.numeric_column(INPUT_TENSOR_NAME, shape=[8])]
    return tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                      hidden_units=[2],
                                      n_classes=2,
                                      config=run_config)

def serving_input_fn(params):
    feature_spec = {INPUT_TENSOR_NAME: tf.FixedLenFeature(dtype=tf.float32, shape=[8])}
    return tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()


def train_input_fn(training_dir, params):
    """Returns input function that would feed the model during training"""
    return _generate_input_fn(training_dir, 'diabetes_train_prep.csv')


def eval_input_fn(training_dir, params):
    """Returns input function that would feed the model during evaluation"""
    return _generate_input_fn(training_dir, 'diabetes_train_prep.csv')


def _generate_input_fn(training_dir, training_filename):
    training_set = tf.contrib.learn.datasets.base.load_csv_with_header(
        filename=os.path.join(training_dir, training_filename),
        target_dtype=np.int,
        features_dtype=np.float32)

    return tf.estimator.inputs.numpy_input_fn(
        x={INPUT_TENSOR_NAME: np.array(training_set.data)},
        y=np.array(training_set.target),
        num_epochs=None,
        shuffle=True)()
```
----
That's the interesting part of the error:

```
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 691, in _get_features_and_labels_from_input_fn
    result = self._call_input_fn(input_fn, mode)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/estimator/estimator.py", line 798, in _call_input_fn
    return input_fn(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tf_container/trainer.py", line 117, in <lambda>
    train_input_fn = lambda: self.customer_script.train_input_fn(**invoke_args)
  File "/opt/ml/code/diabetes_dnn_classifier.py", line 22, in train_input_fn
    return _generate_input_fn(training_dir, 'diabetes_train_prep.csv')
  File "/opt/ml/code/diabetes_dnn_classifier.py", line 34, in _generate_input_fn
    features_dtype=np.float32)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 250, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 55, in load_csv_with_header
    n_features = int(header[1])
ValueError: invalid literal for int() with base 10: '2.0'
```

---
Update: I found out that the first line should be number of rows, number of features, class label A, class label B; but I still get an error

ValueError: could not broadcast input array from shape (8) into shape (2)

-----
That's 3 example lines from my data:

4, 2, 0, 1,,,,,
2.0,5.0,2.0,3.0,1.0,4.0,3.0,4.0,1
1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,0
3.0,6.0,2.0,1.0,1.0,2.0,3.0,3.0,1
1.0,1.0,2.0,1.0,2.0,3.0,1.0,1.0,0

Can anyone help me out, please? :)

**Comment by laurenyu** [comment]
hi @UweBretschneider, thanks for using SageMaker!

Your first row defines the number of features to be 2, but each row has 8 features. Can you try changing the 2 in the first line to 8?

**Comment by UweBretschneider** [comment]
Thank you, you were absolutely right. After all, it was my fault not getting the data format right. I'm setting up these notebooks for my colleagues and as I'm a Java programmer I'm not that familiar with tensorflow.

It seems that by convention the class value is always the last column and the first row has the above mentioned format. That would help alot if you might state that somewhere in the git readme, especially since that different from all the other examples.

But as I said, it was mainly my fault. So thanks alot for your fast response and help :) 👍

**Comment by laurenyu** [comment]
Glad that worked!
