### ISSUE TITLE
Use a custom inference script with HuggingFace model deployed directly from the Hub

### ISSUE THREAD

**Issue by joaopcm1996** [aws/sagemaker-python-sdk#2519]
This request regards the newly released HuggingFace Inference DLC.

I tested deploying a model directly from the HuggingFace Model Hub, but using my own custom inference script instead of defining an HF_TASK. I noticed that this is unsupported as of now, and the deployment ignores the provided `source_dir` and `entry_point`, using instead the default [predict function](https://github.com/aws/sagemaker-huggingface-inference-toolkit/blob/256717cbed1251d195968d07bbca9e3f7aa7c93a/src/sagemaker_huggingface_inference_toolkit/handler_service.py#L130) of the HF inference toolkit. 

This means there is no way to define input or output transformations, or even limit the parameters that can be passed to the model's Pipeline, which would be important details for advanced use of the DLC.   

[Here is a notebook where I replicated the error.](https://gist.github.com/joaopcm1996/97e8c14c935e26e9aad070e6fff890d4) 
 
Setup:
Notebook Instance: ml.m5.xlarge
Kernel: conda_pytorch_p36
SM SDK version: 2.48.2 

Thank you!

**Comment by vdantu** [comment]
@ahsan-z-khan ☝️ ☝️ : This must be fixed for HuggingFace containers.  

I think we should change [model.py](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model.py#L1057) 's `_upload_code` from . 
```
-        if repack and self.model_data is not None and self.entry_point is not None:
+        if repack and (self.model_data is not None or self.entry_point is not None):
```


In [utils.py](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L483) we should change `_extract_model` from

```
-    if model_uri.lower().startswith("s3://"):
-        local_model_path = os.path.join(tmp, "tar_file")
-        download_file_from_url(model_uri, local_model_path, sagemaker_session)
-    else:
-        local_model_path = model_uri.replace("file://", "")
-    with tarfile.open(name=local_model_path, mode="r:gz") as t:
-        t.extractall(path=tmp_model_dir)
+
+    if model_uri is not None: # <----- newly added check
+        if model_uri.lower().startswith("s3://"):
+            local_model_path = os.path.join(tmp, "tar_file")
+            download_file_from_url(model_uri, local_model_path, sagemaker_session)
+        else:
+            local_model_path = model_uri.replace("file://", "")
+        with tarfile.open(name=local_model_path, mode="r:gz") as t:
+            t.extractall(path=tmp_model_dir)

```

Not sure if we should change anything else.

**Comment by jeniyat** [comment]
Thanks for your suggestions.

**Comment by akrishna1995** [comment]
Thanks @joaopcm1996 and @arthur-st for this feedback. We have added this feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
