### ISSUE TITLE
Key error : SM_CHANNEL_TRAIN with custom docker container train

### ISSUE THREAD

**Issue by Samjith888** [aws/sagemaker-python-sdk#2521]
Build and pushed  a customized pytorch docker container , Getting the  following error while training 
![sgkey](https://user-images.githubusercontent.com/39676803/125762084-37922b3c-2edb-4080-800a-1be4986feea4.png)

train.py include the following parameters as mentioned in the docs.
```
    # # # Data, model, and output directories
    parser.add_argument('--output-data-dir', type=str, default=os.environ['SM_OUTPUT_DATA_DIR'])
    parser.add_argument('--model-dir',  type=str, default=os.environ['SM_MODEL_DIR'])
    parser.add_argument('--train, type=str,  default=os.environ['SM_CHANNEL_TRAIN])
    parser.add_argument('--val, type=str, default=os.environ['SM_CHANNEL_VAL])
```

When the `SM_OUTPUT_DATA_DIR` line commented out , getting same behavior error for the next line.

```

Esitmator and model.fit() are

output_path = "s3://xyz/sagemaker/result/"
train_path = "s3://xyz/sagemaker/dataset/train/"
val_path="s3://xyz/sagemaker/dataset/val/"

model = Estimator(
    role=role,
    instance_count=1,
    instance_type=instance_type,
    image_uri=ecr_image,
    hyperparameters=hyperparameters,
    sagemaker_session=sagemaker.Session(),
    output_path=output_path,
    use_spot_instances=False,
)


model.fit({"train": train_path, "val": val_path, wait=True)
```

Any suggestion or help will be appreciated

**Comment by mufaddal-rohawala** [comment]
Thanks for reaching out to AWS Sagemaker.

I think the issue is the missing single quote for Environment Variables at the end of the following lines:

```
parser.add_argument('--train, type=str,  default=os.environ['SM_CHANNEL_TRAIN])
parser.add_argument('--val, type=str, default=os.environ['SM_CHANNEL_VAL])
```

If you still have any issue please povide detailed reproduction steps for better troubleshooting experience.

**Comment by ozancaglayan** [comment]
Although the quotes are indeed missing, the actual error in the screenshot was about the env vars missing from the environment. I'm also seeing this with the `LocalMode`, environment is basically empty apart these two variables:
```python
     ¦   training_env_vars = {
 226     ¦   ¦   REGION_ENV_NAME: self.sagemaker_session.boto_region_name,
 227     ¦   ¦   TRAINING_JOB_NAME_ENV_NAME: job_name,
 228     ¦   }
```

Apparently the `SM_*` env vars are never exported. This creates a disparity between an actual non-local Sagemaker workflow and the development strategy with local mode. What is weird is that the source code of this repository does not include any reference to `SM_*` variables, they appear only in the documentation and tests. I'm wondering whether these variables are actually exported through some other layer in the pipelines/APIs.

Thanks!
