### ISSUE TITLE
feature: Custom handler for logging

### ISSUE THREAD

**Issue by marianobilli** [aws/sagemaker-python-sdk#2525]
**Describe the feature you'd like**
I would like to pass a custom handler to the logging fuction, such as python_logstash

**How would this feature be used? Please describe.**
The container would stream the logs directly to logstash allowing parsing/filtering/transformation and index selection.

**Describe alternatives you've considered**
Standard approach is to ship the stdout to cloudwatch, and then stream into elastic

**Comment by shreyapandit** [comment]
Hi Marian,

Thank you for your interest in the SageMaker Python SDK. We currently don't have a plan for extending our stack to include alternative logging platforms. We will keep the community posted if that changes in the future.

Regards,
Shreya
