### ISSUE TITLE
Capture metrics by default in the Hugging Face Estimator

### ISSUE THREAD

**Issue by la-cruche** [aws/sagemaker-python-sdk#2537]
**Describe the feature you'd like**
In order to capture metrics on a SageMaker Training job, one needs to write one regexp per metrics. Couldn't the SDK have those metrics already written instead? Some frameworks provide standard metrics, hence those regexp can be done once by the SDK team in the estimator, instead of being done by developers N times. This is for example the case of the [SM RL Estimator, that has regexp built into the object](https://github.com/aws/sagemaker-python-sdk/blob/a7f4637f21a3faf235c057e3791f0fdce89d2d3f/src/sagemaker/rl/estimator.py#L447.). Could we have built-in metrics for the Hugging Face Estimator as well? 

**How would this feature be used? Please describe.**
This would allow to capture Hugging Face-generated metrics without the need for an ad-hoc regexp.

**Describe alternatives you've considered**
Alternative is to have developer writes regexp, like [here](https://github.com/huggingface/notebooks/blob/master/sagemaker/06_sagemaker_metrics/sagemaker-notebook.ipynb). This is the default SageMaker expectation, yet it is verbose and difficult to get right for beginners.

**Comment by ahsan-z-khan** [comment]
Hi @la-cruche , 

I'm trying to understand the usage the metrics. Can you elaborate the use?

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
