### ISSUE TITLE
wait_for_endpoint should have a timeout value

### ISSUE THREAD

**Issue by larroy** [aws/sagemaker-python-sdk#2539]
**Describe the feature you'd like**

wait_for_endpoint can potentially hang up forever, this is rare but we have observed such case where the endpoint fails to come online.

https://sagemaker.readthedocs.io/en/stable/api/utility/session.html#sagemaker.session.Session.wait_for_endpoint

we would like to have wait_for_endpoint have a timeout value so it will return control to the program after a specified time interval.

**How would this feature be used? Please describe.**
as above

**Describe alternatives you've considered**
Using a signal handler to interrupt the wait? but it's clunky and not elegant.

**Additional context**

**Comment by akrishna1995** [comment]
Hi @larroy - Thanks for raising a PR for this feature request. Feel free to reopen the PR and our team can help review and merge it. Meanwhile I have added this feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
