### ISSUE TITLE
[DOC]sphinx_rtd_theme PackagesNotFoundError

### ISSUE THREAD

**Issue by IvyBazan** [aws/sagemaker-python-sdk#2540]
**Describe the bug**
Got the following error when attempting to build the docs locally. 

PackagesNotFoundError: The following packages are not available from current channels:

  - sphinx_rtd_theme=0.5.0

**To reproduce**
Run the following:
# conda
conda create -n sagemaker python=3.7
conda activate sagemaker
conda install sphinx=3.1.1 sphinx_rtd_theme=0.5.0

# pip
pip install -r doc/requirements.txt

**Expected behavior**
Expect the package to download and update.

**System information**
A description of your system. Please provide:
Trying to build through terminal on Mac running Mojave.

**Comment by martinRenou** [comment]
You may want to use the conda-forge channel when installing packages:

```
conda install sphinx=3.1.1 sphinx_rtd_theme=0.5.0 -c conda-forge
```
