### ISSUE TITLE
How to check logs of endpoint in local mode ?

### ISSUE THREAD

**Issue by Shivakishore14** [aws/sagemaker-python-sdk#255]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow/ Custom
- **Framework Version**: 1.4.1
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.5.0
- **Are you using a custom image**: no

### Describe the problem
I am trying debug a model locally, but for some reason the endpoint response is empty and the response status is 500. Is there any way i can check the logs of the local endpoint instance ?

**Comment by iquintero** [comment]
Hi @Shivakishore14 

When serving for local mode starts, all the stdout/stderr will go to your stdout. Are you not getting any log lines in stdout? Either you could redirect stdout to a file to look at later (I suggest using tee), or you could change the code in the pythonsdk to do something custom but I think its overkill at this point.

**Comment by Shivakishore14** [comment]
I am not getting any logs in stdout for the endpoint, But found a way to see the logs.
These endpoints run on a docker container container. so you can give `docker attach <container-id>` to attach to the container, here all the logs are printed to stdout.

**Comment by nadiaya** [comment]
Seems like problem was resolved. Closing this issue.
Please, feel free to reopen it if you still require our assistance.
