### ISSUE TITLE
Model Packages in console UI do not match model versions in SageMaker studio

### ISSUE THREAD

**Issue by ZenPylon** [aws/sagemaker-python-sdk#2568]
**Describe the bug**

When I register a model package via the SageMaker SDK, that model package shows up in SageMaker studio, but does not show up in the AWS SageMaker console UI.

**To reproduce**

Here's a representative code snippet:

```python

import boto3

from sagemaker import get_execution_role, session
from sagemaker.sklearn.model import SKLearnModel

s3_poc_bucket = 'our_s3_bucket
s3_path = 'our/s3/path'
model_filename = 'naive-bayes.tar.gz'

time_suffix = strftime("%Y-%m-%d-%H-%M-%S", gmtime())
model_group_name = 'fraud-detector'
base_model_name = 'fraud-detector-model'
new_model_name = '{}-{}'.format(base_model_name, time_suffix)

session = sagemaker.Session()
role = get_execution_role()

sklearn_model = SKLearnModel(
    name=new_model_name,
    model_data='s3://{}/{}/{}'.format(s3_poc_bucket, s3_path, model_filename),
    role=role,
    entry_point='naive-bayes-model.py',
    image_uri='246618743249.dkr.ecr.us-west-2.amazonaws.com/sagemaker-scikit-learn:0.23-1-cpu-py3',
    sagemaker_session=session)

# 4. Register the model in the model registry. This will create a new version of the model in the 'fraud-detector' model group
model_package = sklearn_model.register(
    content_types=['application/json'],
    response_types=['application/json'],
    inference_instances=['ml.m5.large'],
    transform_instances=['ml.m5.large'],
    model_package_group_name=model_group_name)
```

**Expected behavior**
I would expect this call to `register` to show a model package in the AWS SageMaker console UI.

**Screenshots or logs**
Here is the model package showing as expected in SageMaker studio (in this case, number 23):

<img width="1701" alt="Screen Shot 2021-08-09 at 8 40 19 AM" src="https://user-images.githubusercontent.com/1970004/128715795-99f7cbc8-5159-4ec8-826b-1673c14afc5e.png">

Here is the console UI, which does not show the model packages. The only model package that appears is one I created directly via the console UI.

<img width="1792" alt="Screen Shot 2021-08-09 at 8 41 05 AM" src="https://user-images.githubusercontent.com/1970004/128715841-04c118f9-3077-4acb-a91b-01f710d2a6f4.png">

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: `2.45.0`
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SKLearn
- **Framework version**: `sklearn.__version__`  =  `0.24.1`
- **Python version**: `3.6.13 | packaged by conda-forge`
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
It's possible that I'm misunderstanding how model packages and model versions relate but my understanding is that model packages effectively represent model versions, as indicated in this [doc](https://docs.aws.amazon.com/sagemaker/latest/dg/model-registry-version.html). For what it's worth, when I register the model package with the boto client rather than the python SDK (as shown in that doc), I get the same result.

Any help would be much appreciated. Thanks!

**Comment by shreyapandit** [comment]
Hi Zen, 

Thanks for reporting this issue. We will look into this on our end.

Regards,
Shreya

**Comment by morelen17** [comment]
@shreyapandit any updates here? Are these model packages (console UI vs Sagemaker Studio) even compatible and consistent? Or they're just different things with the same name? Could you please clarify since it's a bit confusing? ☹️

**Comment by mohanasudhan** [comment]
@ZenPylon SageMaker Studio has evolved over the year. Can you confirm that the issue still exists?

**Comment by ZenPylon** [comment]
Hi @mohanasudhan thanks for checking in! I'm unable to confirm, as I no longer have access to the AWS account where AWS Sagemaker was enabled.

**Comment by mohanasudhan** [comment]
Thanks for bringing the issue to our attention. We have created an internal ticket to track it, as it is not PySDK-related. For future reference, please use this tracking ticket - https://tt.amazon.com/P109747899
