### ISSUE TITLE
Error decoding a response from invoking a sageMaker endpoint

### ISSUE THREAD

**Issue by desmanda** [aws/sagemaker-python-sdk#2575]
I am invoking a sageMaker endpoint that returns an image from a tensorflow model using thecode below. I got a 200 response but I can't parse the predictions, the decoding of the response is throwing the following error: 
```UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 23: invalid start byte```
This is my actual code:

```
pose_array = np.empty([16,3])
images = [{"b64": read_from_url(url)} for url in urls]
input_data = [{''keypoints': pose_array, 'images':  list_of_images}]
body = json.dumps({"signature_name": "serving_default", "instances": input_data})
response = client.invoke_endpoint(
        EndpointName=endpoint_name,
        ContentType=''application/json',
        Body=body,
        Accept='Accept')
response = response.get("Body").read().decode()
```
the response can't be decoded, so I can't get the predictions

**Comment by BasilBeirouti** [comment]
hello, this looks like a boto3 issue not a sagemaker sdk issue. I would recommend opening an issue with the boto3 codebase [here](https://github.com/boto/boto3/issues)

**Comment by martinRenou** [comment]
Closing as should be transferred to boto3. Thank you!
