### ISSUE TITLE
S3 manifest file cannot be used for SageMaker Processing job defined by SageMaker Pipeline

### ISSUE THREAD

**Issue by xietao0221** [aws/sagemaker-python-sdk#2578]
**Describe the bug**
I am trying to use SageMaker Pipeline to define a Processing job whose inputs are s3 manifest files. Here is my ProcessingInput :
```
inputs=[
    ProcessingInput(
        input_name="raw_train_data",
        s3_input=S3Input(
            s3_uri="s3://watch-next-ml-ranker-prototype-data/20210717/data/manifest/train.manifest",
            local_path="/opt/ml/processing/raw_train",
            s3_data_type="ManifestFile",
        )),
    ProcessingInput(
        input_name="raw_test_data",
        s3_input=S3Input(
            s3_uri="s3://watch-next-ml-ranker-prototype-data/20210717/data/manifest/test.manifest",
            local_path="/opt/ml/processing/raw_test",
            s3_data_type="ManifestFile",
        ))
]
```
When I execute the SageMaker pipeline using Python SDK 2.51.0, an exception is thrown:
```
ClientError: Input raw_train_data missing one or more required fields for SageMaker-managed S3Input: "LocalPath", "S3DownloadMode", "S3InputMode"
```
But, it looks like the S3Input in the SageMaker Python SDK has no attribute of S3DownloadMode.
Do you know if it is a SDK bug, and how to fix this issue?

**To reproduce**
You can reproduce the issue using the above code in the Processing Job step. 

**Expected behavior**
The pipeline should be defined and executed without throwing exception. The S3 manifest file can be used for specifying the input data of Processing job. 

**Screenshots or logs**
It is provided in the above sections. 

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.51.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.8
- **CPU or GPU**: N/A
- **Custom Docker image (Y/N)**: N/A

**Additional context**

**Comment by jagimene** [comment]
Hi, do you manage to resolve this? There is any workarrond?

I think is hardcoded in https://github.com/aws/sagemaker-python-sdk/blob/7268e82d45b522424891ddd8267ad00ef0cffd23/src/sagemaker/processing.py#L1073

But the documents and the procedures let you chose even in the gui 
![image](https://user-images.githubusercontent.com/29465750/140524153-eb0c0053-49b6-4ccc-a75a-cd0a8bb5bcca.png)

When I tried in the web It gave me this error.
I have this error: Failure reason
ClientError: Failed to download data. 404 Not Found (404): Not Found

**Comment by xietao0221** [comment]
I am able to fix it by using the below code: 

```python
ProcessingInput(
    input_name="<input_name>",
    s3_input=S3Input(
        s3_uri="<s3_manifest_location>",
        local_path="<local_path>",
        s3_data_type="ManifestFile",
        s3_input_mode='File',
        s3_data_distribution_type="FullyReplicated"))
```

**Comment by jagimene** [comment]
> I am able to fix it by using the below code:
> 
> ```python
> ProcessingInput(
>     input_name="<input_name>",
>     s3_input=S3Input(
>         s3_uri="<s3_manifest_location>",
>         local_path="<local_path>",
>         s3_data_type="ManifestFile",
>         s3_input_mode='File',
>         s3_data_distribution_type="FullyReplicated"))
> ```

I'm still having the same error ClientError: Failed to download data. 404 Not Found (404): Not Found.

Can you share the manifest file, or an example?, I Think I have a problem with the file maybe.
Thanks

**Comment by xietao0221** [comment]
The manifest is like this: 
```
[
    {
        "prefix": "s3://<bucket>/"
    },
    "<key1>",
    "<key2>"
]
```

I think you put the wrong manifest location which causes 404.

**Comment by jagimene** [comment]
> The manifest is like this:
> 
> ```
> [
>     {
>         "prefix": "s3://<bucket>/"
>     },
>     "<key1>",
>     "<key2>"
> ]
> ```
> 
> The files will be copied to:
> 
> * local_path/bucket/key1
> * local_path/bucket/key2
> 
> Inside your processing job script, you can use this function to recursively list all input files.
> 
> ```
> def list_files(local_path):
>     files = []
>     for r, d, f in os.walk(location):
>         for file in f:
>             files.append(os.path.join(r, file))
>     return files
> ```

I will give it a try, The only difference I see in my manifest file is my prefix is larger, not only the bucket. but the example in the AWS documentation indicates that will work https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_S3DataSource.html#SageMaker-Type-S3DataSource-S3DataType
```
[  
    {  
        "prefix": "s3://<bucket>/folder1/folder2/"  
    },  
    "subfolder2.a/",  
    "subfolder2.b"  
]  
```

**Comment by st-nich** [comment]
@jagimene Were you able to make this work?

**Comment by jagimene** [comment]
> 

Hello, yes.
The tricky part was that when you use a manifest file, instead an s3 uri, you can only define it at files level, not "folders" outside the prefix.

For example.

`[  
    {  
        "prefix": "s3://<bucket>/folder1/folder2/"  
    },  
    "subfolder2.a/file1.txt",  
    "subfolder2.b/file2.txt"  
]  `

Hope it helps

**Comment by rsgrewal-aws** [comment]
Does this work for ShardByS3 or that limitation remains ?

**Comment by Jonathan995** [comment]
Hi,

Could anyone elaborate on the solution? @xietao0221 @jagimene @st-nich 
I still don't understand how you can specify several subfolders in a manifest file.
And if you can't, then I'm struggling to see the point of a manifest file.

Thank you very much
