### ISSUE TITLE
Predictions from locally-trained Fasttext model not matching predictions from same model on Sagemaker with Blazingtext prebuilt image

### ISSUE THREAD

**Issue by stephperk** [aws/sagemaker-python-sdk#2583]
**Describe the bug**

Hi -- I trained an unsupervised Fasttext model locally. I saved that model and used the Sagemaker Python SDK to deploy that model with the pre-built Blazingtext image. When I load that model and use `model.get_sentence_vector("my_string")` locally, I get different results than when I use `predictor.predict({"instances": ["my_string"]})`. 

I even tried re-downloading the same `model.tar.gz` file I uploaded to S3, load locally, and same result -- the local predictions still matched my original local predictions and did not match the deployed Sagemaker predictions. 

Is there anyone that could help me?

**To reproduce**
```python


import fasttext

# train model
model = fasttext.train_unsupervised("fasttext_training_input.txt", model='skipgram', dim=3)

# test out predictions
model.get_sentence_vector("my string")
# result is [0.399, 0.0965, -0.608]

model.save_model("model.bin")
```
```
tar -czvf model.tar.gz model.bin
```

```python
# deploy model on sagemaker
import sagemaker

sm_sess = sagemaker.Session()
boto_sess = boto3.Session()

bucket = sm_sess.default_bucket()
prefix = "fasttext/pretrained"
region_name = boto_sess.region_name
role = "arn:aws:iam::111111111:role/sagemaker-default-execution-role"

# get sagemaker prebuilt image
container = sagemaker.amazon.amazon_estimator.image_uris.retrieve("blazingtext", region_name, "latest")

# send model to S3 bucket
model_location = sm_sess.upload_data("model.tar.gz", bucket=bucket, key_prefix=prefix)



# deploy model and instantiate sagemaker.Predictor()

word_embed = sagemaker.Model(
    image_uri=container, model_data=model_location, role=role, sagemaker_session=sm_sess
)
word_embed.deploy(initial_instance_count=1, instance_type="ml.m5.xlarge")

from sagemaker.deserializers import JSONDeserializer
from sagemaker.serializers import JSONSerializer

predictor = sagemaker.Predictor(
    endpoint_name=word_embed.endpoint_name,
    sagemaker_session=sm_sess,
    serializer=JSONSerializer(),
    deserializer=JSONDeserializer(),
)


# test out predictor
predictor.predict({"instances": ["my string"]})
# returns [{"vector": [0.206, -0.101, -0.541], "word": "my string"}]

# note that the above prediction is not what we received locally

```

```
aws s3 cp s3://sagemaker-us-east-1-915124832670/fasttext/pretrained/model.tar.gz model_from_s3.tar.gz
tar -xzf model_from_s3.tar.gz
fasttext predict ./model_from_s3.bin input.txt
# this also produces the intended vector, [0.399, 0.0965, -0.608]
```

**Expected behavior**

What I expect to happen is that I get the same vector-- whether I am performing the prediction on sagemaker or locally. 

See [here](https://docs.aws.amazon.com/sagemaker/latest/dg/blazingtext.html): 

> For both supervised (text classification) and unsupervised (Word2Vec) modes, the binaries (*.bin) produced by BlazingText can be cross-consumed by fastText and vice versa. You can use binaries produced by BlazingText by fastText. Likewise, you can host the model binaries created with fastText using BlazingText.

**System information**

A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.54.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Blazingtext
- **Framework version**: Latest
- **Python version**: 3.8
- **CPU or GPU**: Not specified?
- **Custom Docker image (Y/N)**: N

**Additional context**

Really stumped on this one.

**Comment by rags1357** [comment]
Thank you for raising this to the PySDK team! We are closing this issue since it is no longer relevant. The code changes referenced in this issue were successfully included in a seperate PR and should not longer be a problem.
