### ISSUE TITLE
SageMaker Pipelines Lambda Step throwing AttributeError: LAMBDA when creating a step object

### ISSUE THREAD

**Issue by peter-resnick** [aws/sagemaker-python-sdk#2584]
**Describe the bug**
When using `sagemaker.workflow.lambda_step.LambdaStep`, an `AttributeError` is thrown upon instantiation of the step (i.e. `step_lambda = LambdaStep(name="my_lambda_step", lambda_func=Lambda(<lambda_arn>)`). 

This is occuring in SageMaker Studio Notebooks. 

**To reproduce**
```
from sagemaker.workflow.lambda_step import LambdaStep
from sagemaker.lambda_helper import Lambda

lambda_func = Lambda("arn:aws:lambda:us-west-2:<account>:function:<my_function>")

step_lambda = LambdaStep(
    name="my_lambda_step",
    lambda_func=lambda_func
)
```

**Expected behavior**
Would expect the object to be created successfully and able to include in SageMaker Pipeline objects

**Screenshots or logs**

Traceback as follows:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-309-114c837e2f69> in <module>
      3 step_lambda = LambdaStep(
      4     name="my_lambda_step",
----> 5     lambda_func=lambda_func
      6 )
      7 

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/lambda_step.py in __init__(self, name, lambda_func, inputs, outputs, cache_config, depends_on)
    102                 depends on
    103         """
--> 104         super(LambdaStep, self).__init__(name, StepTypeEnum.LAMBDA, depends_on)
    105         self.lambda_func = lambda_func
    106         self.outputs = outputs if outputs is not None else []

/opt/conda/lib/python3.7/enum.py in __getattr__(cls, name)
    352             return cls._member_map_[name]
    353         except KeyError:
--> 354             raise AttributeError(name) from None
    355 
    356     def __getitem__(cls, name):

AttributeError: LAMBDA
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.52.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/a
- **Framework version**: N/A
- **Python version**:  3.7.10
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
Attempting to create a SageMaker Pipeline that includes Lambda Steps but unable to create the initial step object to pass to the pipeline. It appears there is an issue with the `StepTypeEnum.LAMBDA` evaluation when creating the step, however the `StepTypeEnum` object does appear to have a LAMBDA attribute when evaluating the source code, so unsure exactly where the issue lies. 

The above example tries to construct an Lambda object by passing an already existing ARN to the constructor, but I have also tried defining a new lambda function in the Lambda object with 

```
LambdaStep(name="my_lambda_step", lambda_func=Lambda(function_name="my_lambda_function", execution_role_arn=<role_arn>, script="lambda.py", handler="lambda.lambda_handler"))
```

and the error response is the same as described above.

**Comment by staubhp** [comment]
I can't recreate this. The following cell executes without a problem:

```
from sagemaker.workflow.lambda_step import LambdaStep
from sagemaker.lambda_helper import Lambda

lambda_func = Lambda("arn:aws:lambda:us-west-2:<account_number>:function:MyFunction")

step_lambda = LambdaStep(
    name="my_lambda_step",
    lambda_func=lambda_func
)
```

The enum member it's referencing is [here](https://github.com/aws/sagemaker-python-sdk/blob/e87e9886803b122e1e92f2ede53b4dfe71c7b7d7/src/sagemaker/workflow/steps.py#L57)

Please try updating your SDK (`pip install sagemaker --upgrade`), restart your kernel and try instantiating the lambda step again.

Please reopen if the issue continues.
