### ISSUE TITLE
model.register() with ModelMetrics object and bias/explainability MetricsSources causes error

### ISSUE THREAD

**Issue by jasonnance** [aws/sagemaker-python-sdk#2588]
**Describe the bug**
The [ModelMetrics SDK object](https://github.com/aws/sagemaker-python-sdk/blob/0fb0822f64a97ad3cad8b366bd8cbf7f87501af3/src/sagemaker/model_metrics.py#L17) doesn't serialize to a valid [ModelMetrics](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ModelMetrics.html) API object if bias/explainability MetricsSources are passed to it.

**To reproduce**
Create a ModelMetrics object with bias/explainability params passed and create/register a model using it to create a ModelPackage:

```python
import sagemaker

mm = sagemaker.ModelMetrics(
    bias=MetricsSource(
        content_type='application/json',
        s3_uri="s3://...",
    ),
)

model = sagemaker.Model(...)
model.register(
    ...,
    model_metrics=mm,
)
```

**Expected behavior**
The ModelPackage is created successfully.

**Screenshots or logs**
botocore parameter validation returns the following error:

```
    return self.sagemaker_client.create_model_package(**request)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 677, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 725, in _convert_to_request_dict
    request_dict = self._serializer.serialize_to_request(
  File "/usr/local/lib/python3.9/site-packages/botocore/validate.py", line 319, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
botocore.exceptions.ParamValidationError: Parameter validation failed:
Unknown parameter in ModelMetrics.Bias: "ContentType", must be one of: Report
Unknown parameter in ModelMetrics.Bias: "S3Uri", must be one of: Report
Unknown parameter in ModelMetrics.Explainability: "ContentType", must be one of: Report
Unknown parameter in ModelMetrics.Explainability: "S3Uri", must be one of: Report
```
It looks like ModelMetrics just needs to nest the bias/explainability MetricsSources under a "Report" key when serializing them as dicts here: https://github.com/aws/sagemaker-python-sdk/blob/0fb0822f64a97ad3cad8b366bd8cbf7f87501af3/src/sagemaker/model_metrics.py#L66

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.52.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: n/a
- **Framework version**: n/a
- **Python version**: 3.9.6
- **CPU or GPU**: n/a
- **Custom Docker image (Y/N)**: Y

**Additional context**
N/A

**Comment by mufaddal-rohawala** [comment]
Thank you for opening this issue. Closing this issue since a fix was merged in pr#[2780](https://github.com/aws/sagemaker-python-sdk/pull/2780). Please feel free to reopen if you continue to see this issue with the latest sagemaker version.
