### ISSUE TITLE
__init__() got an unexpected keyword argument 'instance_count' when using Estimator

### ISSUE THREAD

**Issue by haochuaws** [aws/sagemaker-python-sdk#2590]
**Describe the bug**
When init estimator, its saying instance count is not one of the keywords

**To reproduce**
Run the default examples blazingtext_text_classification_dbpedia

**Expected behavior**
Expect to init the estimator
![Screen Shot 2021-08-23 at 12 49 59 PM](https://user-images.githubusercontent.com/89413121/130493531-b364f594-36d6-4ebd-ac90-2baca9b268c1.png)

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by jeniyat** [comment]
I could create the `bt_model` without any errors. Below is the code snippet. 


```
import sagemaker
from sagemaker import get_execution_role
import json
import boto3

sess = sagemaker.Session()

role = get_execution_role()
print(
    role
)  # This is the role that SageMaker would use to leverage AWS resources (S3, CloudWatch) on your behalf

bucket = sess.default_bucket()  # Replace with your own bucket name if needed
print(bucket)
prefix = "blazingtext/supervised"  # Replace with the prefix under which you want to store the data if needed
region_name = boto3.Session().region_name
container = sagemaker.amazon.amazon_estimator.get_image_uri(region_name, "blazingtext", "latest")

s3_output_location = "s3://{}/{}/output".format(bucket, prefix)

bt_model = sagemaker.estimator.Estimator(
    container,
    role,
    instance_count=1,
    instance_type="ml.c4.4xlarge",
    volume_size=30,
    max_run=360000,
    input_mode="File",
    output_path=s3_output_location,
    hyperparameters={
        "mode": "supervised",
        "epochs": 1,
        "min_count": 2,
        "learning_rate": 0.05,
        "vector_dim": 10,
        "early_stopping": True,
        "patience": 4,
        "min_epochs": 5,
        "word_ngrams": 2,
    },
)
```

Can you please provide more details?

**Comment by mufaddal-rohawala** [comment]
Thank you for opening this issue. Closing this issue as per the above comment. Please feel free to reopen if you continue to see this issue with the latest sagemaker version.
