### ISSUE TITLE
public.ecr.aws is not recognized as ecr URL

### ISSUE THREAD

**Issue by yitzchak-ben-ezra-ecoplant** [aws/sagemaker-python-sdk#2605]
I want to define a Processing Job with `ScriptProcessor` based on an image from `public.ecr.aws`, but I'm getting an error that this uri isn't from ecr:

> Invalid image URI public.ecr.aws/bitnami/python:3.9. Please provide a valid Amazon Elastic Container Registry path of the Docker image to run

my URI: `public.ecr.aws/bitnami/python:3.9`

I know I can create my image - push to my private ECR and use it, I just don't understand why is this necessary - instead of just pull from public ecr?

I see that the regex `ECR_URI_PATTERN` doesn't support this uri. Is it possible to change this?

**Comment by ahsan-z-khan** [comment]
Hi @yitzchak-ben-ezra-ecoplant,

Thank you for using Amazon SageMaker.

At this moment we don't support public.ecr images. We support creating your own images or using dlc images built by Amazon.
