### ISSUE TITLE
When do we support tensorflow >= 2.5 training images in the sdk?

### ISSUE THREAD

**Issue by jneuhauser** [aws/sagemaker-python-sdk#2648]
**Describe the feature you'd like**
When do we support tensorflow >= 2.5 training images in the sdk?
According to [available_images.md](https://github.com/aws/deep-learning-containers/blob/master/available_images.md) we should have at least images with tensorflow 2.5.0.

**Additional context**
If I use anything higher than 2.4.1 for the parameter `framework_version  `does throw the following exception:

```
estimator = sagemaker.tensorflow.TensorFlow(
    framework_version = '2.5.0',
    py_version = 'py37',
    ...
)
estimator.fit({'train': train_dataset_path_s3, 'valid': valid_dataset_path_s3})
```

`ValueError: Unsupported tensorflow version: 2.5.0. You may need to upgrade your SDK version (pip install -U sagemaker) for newer tensorflow versions. Supported tensorflow version(s): 1.10.0, 1.11.0, 1.12.0, 1.13.1, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 1.4.1, 1.5.0, 1.6.0, 1.7.0, 1.8.0, 1.9.0, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.3.2, 2.4.1, 1.10, 1.11, 1.12, 1.13, 1.14, 1.15, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.3, 2.4.
`

**Comment by jperuggia** [comment]
According to the containers supported in Sagemaker, we should also be able to use TF 2.6. The PR #2710 at one point had it in there, then that version was removed. Is there an ETA on when that will be supported?

**Comment by asmaier** [comment]
According to this list even containers with tensorflow 2.7 should be available for training and inference: 
https://github.com/aws/deep-learning-containers/blob/master/available_images.md
It would be nice if the SDK would support them also.

**Comment by ahsan-z-khan** [comment]
It has been added here #2710

**Comment by asmaier** [comment]
> It has been added here #2710

This adds support for Tensorflow 2.5 and 2.6. But what about tensorflow 2.7?
