### ISSUE TITLE
Model for Pipeline requires sagemaker_session argument, despite the docs

### ISSUE THREAD

**Issue by neilmcguigan** [aws/sagemaker-python-sdk#2651]
I tried creating a model and adding it to a pipeline, but there was an error

Adding sagemaker_session argument fixed it. 

The docs say it is not required

`sagemaker_session = sagemaker.session.Session()
model = Model(
    image_uri=image_uri,
    model_data=training_step.properties.ModelArtifacts.S3ModelArtifacts,
    role=role,
    sagemaker_session = sagemaker_session,
    name="model2" 
)`

**Comment by jerrypeng7773** [comment]
haven't heard back from @neilmcguigan for quite a while, closing this one now, feel free to re-open if you have any concern.
