### ISSUE TITLE
Processing job launching fails if the image name contains underscore

### ISSUE THREAD

**Issue by mrtj** [aws/sagemaker-python-sdk#2652]
**Describe the bug**
SageMaker processing job launching fails if image name contains underscore.

**To reproduce**
Launch a SageMaker Processing job with an image name containing underscore:
```python
    script_processor = ScriptProcessor(
        image_uri='1234567890.dkr.ecr.eu-west-1.amazonaws.com/my_project/my_image_with_underscores:latest',
        # ...
    )
    script_processor.run(
        # ...
    )
```

**Expected behavior**
The job starts correctly.

**Screenshots or logs**
Starting job fails with this this error:

`botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreateProcessingJob operation: 
1 validation error detected: Value 'my_image_with_underscores-2021-01-01-00-00-00-000' at 'processingJobName' 
failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9]){0,62}`

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.59.1
- **Python version**: 3.8
- **Custom Docker image (Y/N)**: Y

**Additional context**
[`base_name_from_image`](https://github.com/aws/sagemaker-python-sdk/blob/6a782d959050449afe9508710286a2fa117da06d/src/sagemaker/utils.py#L88) method in `utils.py` generates a job name that does not conform with the regex required by botocore.

**Comment by mufaddal-rohawala** [comment]
Hi [mrtj](https://github.com/mrtj), thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK.
 
We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.”
 
Let me know if you have any other questions.
