### ISSUE TITLE
Pytorch.fit() not working

### ISSUE THREAD

**Issue by LightToYang** [aws/sagemaker-python-sdk#2663]
**Describe the bug**

inputs are dirs to s3
```
from sagemaker.pytorch import PyTorch

estimator = PyTorch(entry_point='mnist.py',
                    role=role,
                    py_version='py3',
                    framework_version='1.8.0',
                    instance_count=2,
                    instance_type='ml.c5.2xlarge',
                    hyperparameters={
                        'epochs': 1,
                        'backend': 'gloo'
                    })
estimator.fit({'train': inputs, 'test': inputs})
```

dir still
```
"channel_input_dirs": {
        "test": "/opt/ml/input/data/test",
        "train": "/opt/ml/input/data/train"
    },
```
but not 
`s3:// .....`

And while directly set dataset dir  to `inputs s3:// .....`, dataset still not found with `torchvision.datasets.MNIST`

**System information**
A description of your system. Please provide:
- sagemaker version: 2.59.3.post0:
- PyTorch, MNIST tutorial:
- Python 3 (PyTorch 1.6 Python 3.6 GPU Optimized)

**Comment by mufaddal-rohawala** [comment]
Apologies for a late follow up on this issue. It seems like you are facing issues configuring S3 Inputs for a Pytorch Estimator. You can refer to following [example](https://github.com/aws/amazon-sagemaker-examples/blob/main/frameworks/pytorch/get_started_mnist_train.ipynb) for a helper to configure S3 input channels for Pytorch Estimator. Closing this issue for now, please feel free to reopen if you continue to see this issue with the latest sagemaker version.
