### ISSUE TITLE
TuningStep does not copy inputs to multi-estimator Tuner

### ISSUE THREAD

**Issue by neilmcguigan** [aws/sagemaker-python-sdk#2666]
**Describe the bug**
Create a Tuner. Create a TunerStep, and reference the tuner. The TunerStep inputs are used by the Tuner

Create a multi-estimator Tuner using HyperParameterTuner.create(). Create a TunerStep, and reference the tuner. The TunerStep inputs are NOT used by the tuners

**To reproduce**
Create a multi-estimator Tuner using HyperParameterTuner.create(). Create a TunerStep, and reference the tuner. The TunerStep inputs are NOT used by the tuners

**Expected behavior**
The tuner inputs are empty. I expect them to be filled with the TunerStep inputs

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: latest
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: linearlearner, knn, xgboost
- **Python version**: 3

**Comment by jerrypeng7773** [comment]
@neilmcguigan Hi there, it would be great if you could provide some code snippet, we do have some examples in our integration test about having `TuningStep` refers to a tuner with multiple estimators configured, and seems like its working. 

https://github.com/aws/sagemaker-python-sdk/blob/dev/tests/integ/test_workflow.py#L1400
