### ISSUE TITLE
Feature Store docs missing APIs

### ISSUE THREAD

**Issue by peter-resnick** [aws/sagemaker-python-sdk#2677]
**What did you find confusing? Please describe.**
The documentation does not include the `load_feature_definitions()` method for the `FeatureGroup` class

**Describe how documentation can be improved**
This method should be added to the docs

**Additional context**
example notebooks use this method, but do not provide great explanation as to its parameters and underlying function other than that it (as the name suggests) loads definitions.

**Comment by psnilesh** [comment]
Thank you for bringing this to our attention.  

It seems the method [is documented](https://github.com/aws/sagemaker-python-sdk/blob/5f8e53240e67c3b253bbaf9d3a2e12d3e2780cb9/src/sagemaker/feature_store/feature_group.py#L369) but it was deliberately [excluded from documentation](https://github.com/aws/sagemaker-python-sdk/blame/83460ab1ba85f0779dd326420913755d2d2cebc6/doc/api/prep_data/feature_store.rst). Given that its a public method, we need to remove the exclusion filter.

**Comment by athewsey** [comment]
Just been impacted by this too - Can we remove this exclusion yet please? It's an important method and currently mentioned 4 times on the amazon_sagemaker_featurestore.rst guidance page by my count... It was confusing & cost me time to find it wasn't listed when looking for details in the API doc itself.
