### ISSUE TITLE
Unable to set inter-container traffic encryption to True for default profiler processing job generated with training job

### ISSUE THREAD

**Issue by IamCarlMichael** [aws/sagemaker-python-sdk#2683]
**Describe the bug**
When the SageMaker training job estimator is created with the inter-container traffic encryption enabled as true, this same encryption flag, is not passed on to the underlying profiler processing job that is ran by default, when using the SageMaker built-in algorithms.

**To reproduce**
- Create an estimator with the inter-container traffic encryption enabled as True
- Run the .fit to create the training job.
- Check the default running profiler job, and under network, you will notice that the inter-container traffic encryption is still set to False.

**Expected behavior**
The processing job should also run with the inter-container traffic encryption set to True, if this was set on the training job estimator

**Screenshots or logs**
Not Applicable

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.59.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: xgboost
- **Framework version**: any
- **Python version**: 3.7
- **CPU or GPU**:  N.A.
- **Custom Docker image (Y/N)**: N

**Additional context**
Not Applicable
<img width="162" alt="Enable inter-container traffic encryption" src="https://user-images.githubusercontent.com/48624705/135784407-72d4e4e4-2838-4236-ac6c-833ff5880965.png">

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
