### ISSUE TITLE
Add option to pass list of arguments as hyperparameters instead of dict

### ISSUE THREAD

**Issue by nateraw** [aws/sagemaker-python-sdk#2689]
**Describe the feature you'd like**

Right now, you have to pass hyperparameters as a dict, with keys being the name of the flag and values being the explicitly defined value. That can be fine in many scenarios, but is very frustrating if you have a script that accepts argparse `action`s, as the hyperparameters you need to pass do not match the user experience of passing `store_true`-type flags.

**How would this feature be used? Please describe.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

I'd like the option to pass arguments as a list of strings (a la sys.argv). 

```python
estimator = HuggingFace(
    ...
    hyperparameters=['--output_dir', 'my_output_dir/', '--do_train', '--do_eval']
)
```

**Describe alternatives you've considered**

This could be a new kwarg for estimators called `arguments` instead, that way there's no collision between current `hyperparameters` kwarg.

**Additional context**

This enables you to build runners that can run right from the command line, avoiding any need to write python code.

```
python some_script.py --some_flag some_value --some_action_flag
```

...can be run via a wrapper you can put together if this feature is enabled. Here I call it `run_on_sagemaker`.

```
run_on_sagemaker some_script.py --some_flag some_value --some_action_flag
```

as opposed to what you'd have to do now, where you must explicitly define action flag values.

```
run_on_sagemaker some_script.py --some_flag some_value --some_action_flag True
```

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.

**Comment by tikr7** [comment]
I wanted to pass arguments into the Estimator. The way I found is:
```
estimator = Estimator(...
                      container_entry_point=["/usr/bin/python3"],
                      container_arguments=["/opt/ml/code/training.py", "--instances", "test,test"]
```

Maybe it helps somebody.
