### ISSUE TITLE
Sparse matrix to recordIO?

### ISSUE THREAD

**Issue by meownoid** [aws/sagemaker-python-sdk#27]
How can I write sparse matrix to binary format (for use in the factorization machines algorithm)? I found only the `write_numpy_to_dense_tensor` function.

**Comment by owen-t** [comment]
Hi Egor,

Yes, this is a great feature and something I've been thinking about. We're thinking of supporting types in scipy.sparse (e.g. csr, bsr). Would this work for you?

Thanks,

Owen.

**Comment by meownoid** [comment]
Yes, sure, it would be great to have the support of `scipy.sparse`.

**Comment by meownoid** [comment]
Tried to implement this in #28, have a look please.

**Comment by owen-t** [comment]
This has been merged, closing the issue.

**Comment by winstonaws** [comment]
Reopening - this has been merged, but has not been released to SageMaker Notebook Instances and pypi yet. Will start working on the releases later this week.

**Comment by laurenyu** [comment]
closing issue as it's now been released as part of version 1.0.2
