### ISSUE TITLE
The difference of creating training job with setting hyper parameters and creating hyper parameters tuning?

### ISSUE THREAD

**Issue by giggle0312** [aws/sagemaker-python-sdk#270]
1、When I  invoke built-in algorithm "linear-learner" to train a model , I can use ``` linear.sethyperparameter{} ``` to tune hyper parameters. But in the process, I did not define the arrangement of any hyper parameters, the algorithm can set the tuning range automatically? Because if I create a tuning hyper parameters job, it will require me to provide the range of some parameters to produce different combination of hyper parameters. Thus, can  you help me with a explanation that the difference of setting hyper-parameters in creating training job and creating tuning hyper parameters individually?

![image](https://user-images.githubusercontent.com/14227065/42102000-51137758-7bf7-11e8-8880-08ef0f76c07e.png)
![image](https://user-images.githubusercontent.com/14227065/42102018-5c0a7936-7bf7-11e8-91a6-f82139e933e2.png)

**Comment by uditbhatia** [comment]
Thanks for using sagemaker.

While creating a training job you can define only the static hyper parameters, i.e. none of them would be tuned. If you want to tune the hyper parameters you have to create a HyperParameterTuningJob, while creating that you will define the  ranges for parameters to be tuned, and in addition to that you can also define some hyper parameters as static. 

The following blog on Sagemaker automatic model tuning gives a good insight on how to tune hyper parameters at sagemaker: https://aws.amazon.com/blogs/aws/sagemaker-automatic-model-tuning/

Here are the api references giving a detailed explanation of above:
1. 	CreateTrainingJob: https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateTrainingJob.html
2.  CreateHyperParameterTuningJob: https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateHyperParameterTuningJob.html

Please let us know if this answers your questions and also if you have any other question.

**Comment by giggle0312** [comment]
@uditbhatia Thank you for your full explanation.

**Comment by iquintero** [comment]
Since this is answered, I am going to close this. Please re open if you have further questions.
