### ISSUE TITLE
Image Uri generation for Hugging Face is broken 

### ISSUE THREAD

**Issue by philschmid** [aws/sagemaker-python-sdk#2700]
**Describe the bug**
 i am getting an error saying
`UnexpectedStatusException: Error hosting endpoint huggingface-pytorch-inference-2021-10-13-08-17-14-036: Failed. Reason:  The image '763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.8.1-transformers4.10.2-gpu-py36-cu110-ubuntu18.04' does not exist..`

when using the following code
```python
huggingface_model = HuggingFaceModel(
	transformers_version='4.10.2',
	pytorch_version='1.8.1',
	py_version='py36',
	env=hub,
	role=role, 
)
```
Looking at the release here: https://github.com/aws/deep-learning-containers/releases/tag/v1.0-hf-4.10.2-pt-1.8.1-py36
I can see that the difference is cu110 to cu111

I looked at the image_uri_config and it correctly contains cu111 https://github.com/aws/sagemaker-python-sdk/blob/82f1ba771ff158a946b68be008aad627fdfb53e3/src/sagemaker/image_uri_config/huggingface.json#L569

It is the same for pytorch 1.9 and transformers 4.11. But there is also the ubuntu version wrong.

When using pytorch 1.9 and transformers 4.11 the sdk generates the following tag `1.9-transformers4.11-gpu-py38-cu110-ubuntu18.04`
but the correct one must include `cu111-ubuntu20.04`
 https://github.com/aws/sagemaker-python-sdk/blob/82f1ba771ff158a946b68be008aad627fdfb53e3/src/sagemaker/image_uri_config/huggingface.json#L775

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.62.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Hugging Face

cc @ahsan-z-khan

**Comment by TimbusCalin** [comment]
I trained a network (basic text-classifier distillbert) on my own laptop:

```
PT 1.12.0
PY 3.9
HF 4.21.0
```


I had to downgrade to these versions since this is what JNB outputs in the console (max versions displayed below).

```
# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
   model_data="s3://tfsaws/model.tar.gz",  # path to your trained sagemaker model
   role=role,# iam role with permissions to create an Endpoint
   transformers_version="4.17", # transformers version used
   pytorch_version="1.10.2", # pytorch version used
   py_version="py38", # python version of the DLC
)
```

Error (seems to reproduce again):

> ClientError: An error occurred (ValidationException) when calling the CreateModel operation: Requested image 763104351884.dkr.ecr.us-east-1.amazonaws.com/huggingface-pytorch-inference:1.10.2-transformers4.17-cpu-py38-ubuntu20.04 not found.

**Comment by VikParuchuri** [comment]
Since I found this issue when Googling - I'll leave the link to all of the deep learning container images [here](https://github.com/aws/deep-learning-containers/blob/master/available_images.md).  You can find the correct combinations of Python, transformers, and Pytorch versions there.

**Comment by llealgt** [comment]
I'm having a similar issue, I was trying to use settings from the original documentation https://docs.aws.amazon.com/sagemaker/latest/dg-ecr-paths/ecr-us-east-1.html but even the  default example from this page fails:

<img width="1076" alt="image" src="https://github.com/aws/sagemaker-python-sdk/assets/10162801/673cda95-d375-4950-9183-86fe04396382">

![unnamed](https://github.com/aws/sagemaker-python-sdk/assets/10162801/753ab505-9cd8-4ed8-9276-6dbd0837a74a)

It seems to me like the uri system for huggingface is broken or at least the documentation is outdated

**Comment by dayo777** [comment]
I also ran into this issue today. The solution is to check for the correct image uri on their official [https://github.com/aws/deep-learning-containers/blob/master/available_images.md#huggingface-inference-containers](github) page. 

AWS image uri list is outdated.
