### ISSUE TITLE
RegisterModel Step in Sagemaker Pipelines fails with multiple SKLearn models in a PipelineModel

### ISSUE THREAD

**Issue by chubzor** [aws/sagemaker-python-sdk#2701]
**Describe the bug**

While trying to register a PipelineModel consisting of:

1. SKLearn Feature Encoder
2. Linear Learner
3. SKLearn Calibration 

the pipeline upsert fails with the error of

> ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: Step name [sklearnRepackModel] is used multiple times.

offending line is:
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/step_collections.py#L179

In this case it is using sklearnRepackModel twice for models 1 and 3. using model_entity._framework_name that evaluates in sklearnRepackModel.

**To reproduce**
Create a PipelineModel with 2+ models created with custom entrypoint script and at least two are using SKLearn framework as a base. Add it to RegisterModel step, run upsert on pipeline with such a configuration.

**Expected behavior**
RegisterModel step runs normally and PipelineModel is registered

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: sagemaker==2.59.4
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SKLearnModel v 0.23-1
- **Framework version**:
- **Python version**: Python 3.7.10
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:  N

**Additional context**

I've tried to use a workaround wherein I defined the name differently but then the failure happens in this line which I'm not sure why is it needed and why it is replacing the model data.
Custom step: https://gist.github.com/chubzor/fb90246fb0ebbb93cfc2913facb62647
Error:

> ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: Property reference [Steps.feature_encodingRepackModel.ModelArtifacts.S3ModelArtifacts] references unknown step [feature_encodingRepackModel].

offending line: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/step_collections.py#L199

If I comment out the offending line the pipeline runs but the custom step is not registered in the pipeline and doesn't show in the DAG or runs in the execution. Like it doesn't exist at all.

**Comment by jerrypeng7773** [comment]
We have a upcoming PR (currently under review) to address this https://github.com/aws/sagemaker-python-sdk/pull/3076

Once its released you can do

```
from sagemaker.workflow.pipeline_context import PipelineSession
from sagemaker.pipeline import PipelineModel

session = PipelineSession()

model_1 = SKLearnModel(..., sagemaker_session=session)
model_2 = SKLearnModel(..., sagemaker_session=session)
model_3 = SKLearnModel(..., sagemaker_session=session)

pipeline_model = PipelineModel(models=[model_1, model_2, model_3], ...)

register_args = pipeline_model.register(...)

step_create_model = ModelStep(
   name="my-pipeline-model",
   step_args=register_args,
)
```

basically, we introduced a new special type of a session called `PipelineSession`. This special session does not register the model immediately when you call `model.register`, instead, it captures the request arguments required to register a model, and delegate it to the `ModelStep` to register the model later during pipeline execution.
