### ISSUE TITLE
RecordSet constructor requires num_examples parameter

### ISSUE THREAD

**Issue by philipgautier** [aws/sagemaker-python-sdk#271]
Please fill out the form below.

### Describe the problem
The constructor for RecordSet has a required parameter num_examples. This value to be unused/unnecessary, and should be removed.

**Comment by nadiaya** [comment]
@philipgautier,

Did you mean a different required parameter?

It doesn't look like RecordSet has `num_examples` parameter:
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/amazon/amazon_estimator.py#L188-L203

**Comment by philipgautier** [comment]
Sorry, meant num_records

**Comment by nadiaya** [comment]
From looking through the code we use it, for example, to calculate mini batch size:
https://github.com/aws/sagemaker-python-sdk/blob/502d6ebfcd698061cbdc1b369cb7ff449ff9db08/src/sagemaker/amazon/pca.py#L105-L119

Not sure it justifies it being a required parameter though.

**Comment by mohanasudhan** [comment]
@philipgautier  Thanks for your suggestion. Apologies for the delay in getting to this issue. Can you provide more detail on the rationale behind making num_records optional? 

The min_batch does depend on num_records as quoted before. I'm happy to work with you on the use case and if you have a quick PR, I would be happy to look at it.

**Comment by mohanasudhan** [comment]
We are closing this issue as we currently lack sufficient information to proceed. Please feel free to reopen the issue if you can provide more details.
