### ISSUE TITLE
Sagemaker don't take default bucket without "Create Bucket permission"

### ISSUE THREAD

**Issue by danielemocavini** [aws/sagemaker-python-sdk#2725]
https://github.com/aws/sagemaker-python-sdk/blob/67fa816494b1be7eb017f6f3bc8af2b88539f17e/src/sagemaker/session.py#L367

**Describe the bug:**
Sagemaker don't take default bucket if you don't have the "Create Bucket permission".
This is very limiting since i can't for example add configuration or jars at my PySparkProcessor run.

**To reproduce:**

sagemaker.Session(default_bucket=BUCKET).default_bucket()

and since i don't have the permission to create a new bucket i obtain

ClientError: An error occurred (AccessDenied) when calling the CreateBucket operation: Access Denied.

**Expected behavior:**

Reading at the code i found that Sagemaker always try to create a default bucket to check if default_bucket already exists, maybe should be great to find other way to check the default bucket if there is no permission to create bucket.

**Comment by giuseppeporcelli** [comment]
Any updates?

**Comment by mufaddal-rohawala** [comment]
Fixed in https://github.com/aws/sagemaker-python-sdk/pull/3165
