### ISSUE TITLE
Missing parameter in call to training_job_analytics

### ISSUE THREAD

**Issue by JonathanTaws** [aws/sagemaker-python-sdk#273]
Code to reproduce (any initialized estimator): 
`estimator.training_job_analytics`

https://github.com/aws/sagemaker-python-sdk/blob/864c653cfae62e9cbb1653ccf5648dc1bc246e65/src/sagemaker/estimator.py#L322

When trying to get the training job analytics using the training_job_analytics property of an estimator, I get the following error:

```
TypeError                                 Traceback (most recent call last)
<ipython-input-145-5976c283bde7> in <module>()
----> 1 estimator.training_job_analytics

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/sagemaker/estimator.py in training_job_analytics(self)
    325         if self._current_job_name is None:
    326             raise ValueError('Estimator is not associated with a TrainingJob')
--> 327         return TrainingJobAnalytics(self._current_job_name)
    328 
    329 

TypeError: __init__() missing 1 required positional argument: 'metric_names'
```

It seems like the TrainingJobAnalytics class is expectif the metric_names parameter, but this property method is not supplying it, and it should be a parameter as such:
`def training_job_analytics(self, metric_names)`

**Comment by nadiaya** [comment]
Thank you for reporting it! Marking as a bug.

**Comment by nadiaya** [comment]
Fix is merged.
