### ISSUE TITLE
Support on p4d A100 GPUs for inference

### ISSUE THREAD

**Issue by hackgoofer** [aws/sagemaker-python-sdk#2732]
**Describe the feature you'd like**
Support to use SageMaker on A100 GPUs for inference

**How would this feature be used? Please describe.**
This person from the blog post suggested A100 SageMaker support was being worked on end of last year 2020. Curious when will this feature be available?

Link to post here: https://aws.amazon.com/blogs/aws/new-gpu-equipped-ec2-p4-instances-for-machine-learning-hpc/

**Describe alternatives you've considered**
None

**Additional context**
Link: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_ProductionVariant.html#sagemaker-Type-ProductionVariant-InstanceType
<img width="1060" alt="Screen Shot 2021-10-26 at 3 12 32 PM" src="https://user-images.githubusercontent.com/1545487/138968416-3781645b-cfc9-4ac8-a8a4-03071a893748.png">

**Comment by mohanasudhan** [comment]
@hackgoofer SageMaker Inference currently support P4d instance type. Closing the issue.
