### ISSUE TITLE
Feature: Add new Hugging Face DLCs to Image config 

### ISSUE THREAD

**Issue by philschmid** [aws/sagemaker-python-sdk#2751]
# Add Release Image to Image config for the Hugging Face DLCs

## huggingface_pytorch

**Training**:
 -  PT 1.9 GPU, transformers==4.12

**inference**:
 -  PT 1.9 CPU, transformers==4.12
 -  PT 1.9 GPU, transformers==4.12
 
## huggingface_tensorflow

**Training**:
 -  TF 2.4 GPU, transformers==4.12
 -  TF 2.5 GPU, transformers==4.12

**inference**:
 -  TF 2.5 CPU, transformers==4.12
 -  TF 2.5 GPU, transformers==4.12

cc @ahsan-z-khan @arjkesh

**Comment by philschmid** [comment]
PR open #2752. 

The Release issue in the Deep Learning Container repository can be found here:
* https://github.com/aws/deep-learning-containers/issues/1475

**Comment by ahsan-z-khan** [comment]
@philschmid is there any due date on this?

**Comment by philschmid** [comment]
Yes, we need to have a SDK version support those images by Wednesday. I already opened the PR and made all required changes to the `mage_uri_config`
