### ISSUE TITLE
RegisterModel step fails when I provide 'entry_point' and 'source_dir' arguments to register a sklearn model as a part of SM Pipelines

### ISSUE THREAD

**Issue by krishnashanker-amt** [aws/sagemaker-python-sdk#2759]
**Describe the bug**
I have created a multi-step SM Pipeline that trains a sklearn model (xgb classifier from sklearn) using a custom training script as `entry_point` (that makes use of multiple custom supporting scripts provided via `source_dir`), and registers it post satisfactory evaluation results. 

When I provide the RegisterModel script with  `entry_point` and `source_dir` as additional parameters to indicate a custom script, the SM Pipeline fails at the RegisterRepackModel step as the repack step launches a container where the `SM_HP_SOURCE_DIR` environment variable is set to the location of the `source_dir` _on my local environment_ instead of packaging the `source_dir` from my local to a location on the container (usually `/opt/ml/code/`)

![image](https://user-images.githubusercontent.com/70163242/141372848-dc3e8299-4124-4f99-b65e-37688493cb1b.png)

The container obviously fails to find such a folder and the step fails

<img width="1491" alt="Screen Shot 2021-11-11 at 4 48 55 PM" src="https://user-images.githubusercontent.com/70163242/141373883-86be62ab-7c32-422d-8ea1-b173b23958ef.png">

**To reproduce**

- Create a sklearn estimator using a custom training script 

``` python
sklearn = SKLearn(
        entry_point = 'train.py',
        source_dir = code_location,
        framework_version = FRAMEWORK_VERSION,
        base_job_name=f"{base_job_prefix}/xgboost_train",
        instance_type=training_instance_type,
        role=role,
    output_path = model_path,
    hyperparameters = hyperparameters,
    metric_definitions=[
        {'Name': 'AUC-ROC', 'Regex': "AUC-ROC = ([0-9.]+).*$"}
    ], 
    )
```
- Create a TrainingStep in SM Pipeline using the estimator as input
- Create a RegisterModel step in SM Pipeline (from [this issue](https://github.com/aws/sagemaker-python-sdk/issues/2014), I found I can pass the additional parameters entry_point and source_dir to specify a custom inference script) 

``` python
step_register = RegisterModel(
        name="Register-Model",
        estimator=sklearn,
        model_data=step_train_model.properties.ModelArtifacts.S3ModelArtifacts,
        content_types=["application/json", "text/csv"],
        response_types=["application/json", "text/csv"],
        inference_instances=["ml.t2.medium", "ml.m5.xlarge"],
        transform_instances=["ml.m5.xlarge"],
        model_package_group_name=model_package_group_name,
        approval_status=model_approval_status,
        model_metrics=model_metrics,
        entry_point = 'train.py',
        source_dir = model_files_location
    )
```
- At this point, I've tried three different ways to provide a value for `source_dir`, all of them fail. 
1) `model_files_location` is a location on my local environment. That fails with the error shown in the issue description. 
2) `model_files_location` is a S3 bucket address where the code is packaged as a `tar.gz` file (same directory structure as a `sourcedir.tar.gz` file used by sklearn containers). Fails with the below error. 

<img width="815" alt="Screen Shot 2021-11-11 at 5 22 30 PM" src="https://user-images.githubusercontent.com/70163242/141377489-9803b428-0a3b-46c9-92ea-385c7dc5bc06.png">

- Combine the steps in a pipeline and execute it

**Expected behavior**

The RegisterModel takes care of re-packing the model with the custom training script and supporting scripts, but passes the wrong environment variable to the container. If the right environment variable can be passed, or if we can control the environment variables passed to a container, then endpoint should launch successfully. 

Ideally, the model package arn from RegisterModel step contains the inference and supporting scripts so that `serving.py` from a [sagemaker-scikit-learn-container](https://github.com/aws/sagemaker-scikit-learn-container/blob/master/src/sagemaker_sklearn_container/serving.py) can successfully find the `module_name` and launch a container that passes ping health checks. 

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.66.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SKLearn
- **Framework version**:  0.23-1
- **Python version**: 3.7.10
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

Based on the comments in[ link 1](https://github.com/aws/sagemaker-python-sdk/issues/2014) and [link 2](https://github.com/aws/sagemaker-python-sdk/issues/2123), I also tried building `/opt/ml/model/` with the following things during model training, so that they are stored as a part of the `model.tar.gz` file. 
```
./code/{both train and inference scripts}
./code/{other scripts}
./{model_assets}
./{other reference files}
```
 I tried skipping the `source_dir` and `entry_point` arguments in RegisterModel when I do this (so that the pipeline can at least run and create a registered model, otherwise it will not execute), but the container still fails to find my `train.py`. 

<img width="1356" alt="Screen Shot 2021-11-11 at 5 23 42 PM" src="https://user-images.githubusercontent.com/70163242/141377616-3a53bfbe-cfd8-404d-860f-f80a540ecc59.png">

**Comment by krishnashanker-amt** [comment]
Hello. Does anyone have a workaround for this problem?

**Comment by Othmane796** [comment]
Hi team (@ruyyi0323 , @ChoiByungWook),

Facing the same issue over here. Below are the system information on my side:

**System information**
A description of your system. Please provide:

**SageMaker Python SDK version:** 2.69.0
**Framework name (eg. PyTorch) or algorithm (eg. KMeans):** SKLearn
**Framework version:** 0.23-1
**Python version:** 3.7.10
**CPU or GPU:** CPU
**Custom Docker image (Y/N):** N


The training job created by the register step in order to repack the model is failing due to the container not able to find the contents of the source_dir. The "SM_HP_SOURCE_DIR" environment variable is set to the local directory during the build process (i.e: /home/sagemaker-user/project-name/model-build/..) instead of "/opt/ml/code".

**Things I have tried to debug**

1/ I cloned the training job (that repacks the model) and changed the hyperparameter "source_dir" to "/opt/ml/code" which results in the environment variable "SM_HP_SOURCE_DIR" having a value of "/opt/ml/code" and the container being able to find the code and executes successfully.

2/I updated the environment variables directly in the creation of the model object : 

```
    xgboost_model = XGBoostModel(
        model_data=training_step.properties.ModelArtifacts.S3ModelArtifacts,
        entry_point="inference.py",
        source_dir=os.path.join(BASE_DIR, "predict", "xgboost"),
        framework_version=xgboost_framework_version,
        py_version=xgboost_py_version,
        role=role,
        sagemaker_session=sagemaker_session,
        env={"SM_HP_SOURCE_DIR":"/opt/ml/code/", "ANOTHER_ENV_VAR":"hi"}
    )
```
However these were not taken into account when the repack training job was created and the job failed.

Is there a way to force the hyperparameters of the repack training job or this requires a fix within the sdk ? Thanks !

Othmane

**Comment by staubhp** [comment]
There is a [pending PR](https://github.com/aws/sagemaker-python-sdk/pull/2755) that fixes this issue. The repack_model script is referencing nonexistent directories that were flattened by the training job. There is no current workaround beyond reverting your SDK to a version prior to v2.62.0
