### ISSUE TITLE
Missing docs for TensorFlowProcessor

### ISSUE THREAD

**Issue by ksonbol** [aws/sagemaker-python-sdk#2763]
**What did you find confusing? Please describe.**
I did not find any documentation on the [TensorFlowProcessor](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/processing.py#L24) while docs exist for [SKLearn and Spark Processors](https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_processing.html#learn-more). Was it left out on purpose? Are there any stability issues I should be concerned about when using the TensorFlowProcessor?

**Describe how documentation can be improved**
API docs and possibly a tutorial could be added to the docs about using the TensorFlowProcessor. A warning could be added if it is not officially supported yet.

**Additional context**
I'd like to use the TensorFlowProcessor for creating TF Records as part of a data preparation/processing step.

<img width="401" alt="image" src="https://user-images.githubusercontent.com/3483662/142650984-abeebf95-3d8a-4cfa-ba7c-42fccba966fa.png">

**Comment by ksonbol** [comment]
I found this is already mentioned in this description of [this PR](https://github.com/aws/sagemaker-python-sdk/pull/2664)

**Comment by svpino** [comment]
It would be nice to have documentation for this class.

**Comment by martinRenou** [comment]
Thank you for opening an issue.

There is a bit of documentation here (at least, a small usage example) https://docs.aws.amazon.com/sagemaker/latest/dg/processing-job-frameworks-tensorflow.html. But it's true that the API documentation is missing.

**Comment by martinRenou** [comment]
This has been fixed by https://github.com/aws/sagemaker-python-sdk/pull/4152
