### ISSUE TITLE
Update links in sagemaker/image_uris.py

### ISSUE THREAD

**Issue by NouamaneTazi** [aws/sagemaker-python-sdk#2775]
This page is no longer available:
https://github.com/aws/sagemaker-python-sdk/blob/99f023e76a5db060907a796d4d8fee550f005844/src/sagemaker/image_uris.py#L55

It should probably be replaced with:
https://aws.amazon.com/sagemaker/pricing/

**Comment by ahsan-z-khan** [comment]
Updated link
