### ISSUE TITLE
Support model resources or Batch Transform jobs as input for scheduled Model Monitoring

### ISSUE THREAD

**Issue by adanRivas** [aws/sagemaker-python-sdk#2799]
**Describe the feature you'd like**
`ModelMonitor.create_monitoring_schedule()` takes only a model endpoint as input and would like to extend support for model resources as used in Batch Transform. Or create a new class that doesn't not require scheduling and is more compatible with Batch Transform job.

**How would this feature be used? Please describe.**
Extend the use case of Model Monitoring for batch inference jobs. 

**Describe alternative you've considered**
Create custom logic to monitor model performance on Batch Transform jobs.

**Comment by itsmesid12** [comment]
We can trigger monitoring job manually by converting our batch data into jsonline format and calling the sagemaker-model-monitoring-analyzer manually. You could check out the link attached for further details.

[https://github.com/marckarp/model-monitor-batch-transform](url)

**Comment by akrishna1995** [comment]
Closing this issue based on the comment above. Feel free to reopen if the issue persists. Thanks
