### ISSUE TITLE
repackModel could expose an output_path parameter

### ISSUE THREAD

**Issue by tuliocasagrande** [aws/sagemaker-python-sdk#2803]
**Describe the feature you'd like**
Right now, repackModel steps write to root of the default bucket. Here's one line from test code that we can verify that: https://github.com/aws/sagemaker-python-sdk/blob/f2fd42125df23e2baa1487bf58159554da055b61/tests/unit/sagemaker/workflow/test_utils.py#L143

It would be great if we could expose an `output_path` and perhaps also a `code_location` parameters to help us organize our S3 buckets.

**How would this feature be used? Please describe.**
The feature would be used to help us organize S3 buckets into namespaces/hierachy. For example, right now I organize my prefixes as:
```
s3://<myprojectbucket>/<base_job_prefix>/preprocess/...
s3://<myprojectbucket>/<base_job_prefix>/train/...
s3://<myprojectbucket>/<base_job_prefix>/evaluate/...
```
But since repackModel doesn't expose parameters to tune S3 outputs, I also end up some objects in the root, example:
```
s3://<myprojectbucket>/pipelines-<jobid-1>-sklearnRepackModel.../output/model.tar.gz
s3://<myprojectbucket>/pipelines-<jobid-2>-sklearnRepackModel.../output/model.tar.gz
s3://<myprojectbucket>/pipelines-<jobid-N>-sklearnRepackModel.../output/model.tar.gz
s3://<myprojectbucket>/sagemaker-scikit-learn-<timestamp-1>/source/sourcedir.tar.gz
s3://<myprojectbucket>/sagemaker-scikit-learn-<timestamp-2>/source/sourcedir.tar.gz
s3://<myprojectbucket>/sagemaker-scikit-learn-<timestamp-N>/source/sourcedir.tar.gz
```

**Describe alternatives you've considered**
I'd need some guidance to find all the correct places, but I can submit a PR with these changes:
1. [step_collections.RegisterModel](https://github.com/aws/sagemaker-python-sdk/blob/2beb91ece14707a3fa15d2dd8bd5c2de8d91e08c/src/sagemaker/workflow/step_collections.py#L56) and [step_collections.EstimatorTransformer](https://github.com/aws/sagemaker-python-sdk/blob/2beb91ece14707a3fa15d2dd8bd5c2de8d91e08c/src/sagemaker/workflow/step_collections.py#L244), add a new parameter called `repack_output_path`
2. On `_RepackModelStep()` calls ([L139](https://github.com/aws/sagemaker-python-sdk/blob/2beb91ece14707a3fa15d2dd8bd5c2de8d91e08c/src/sagemaker/workflow/step_collections.py#L139), [L183](https://github.com/aws/sagemaker-python-sdk/blob/2beb91ece14707a3fa15d2dd8bd5c2de8d91e08c/src/sagemaker/workflow/step_collections.py#L183), [L324](https://github.com/aws/sagemaker-python-sdk/blob/2beb91ece14707a3fa15d2dd8bd5c2de8d91e08c/src/sagemaker/workflow/step_collections.py#L324)), handover the parameter `repack_output_path=repack_output_path`.
3. Inside of `_RepackModelStep`, on the [`SKLearn()`](https://github.com/aws/sagemaker-python-sdk/blob/17fe93e457b3053014725e93f3bf1aac986f4d21/src/sagemaker/workflow/_utils.py#L157) call, add `output_path=repack_output_path` and `code_location=repack_output_path`.
4. Maybe another place I didn't identify.

I'd also need help to understand which unit tests would be needed, on `RegisterModel`, `EstimatorTransformer`, `_RepackModelStep`, or all of them.

Thanks for your review!

**Comment by jerrypeng7773** [comment]
@tuliocasagrande looks like your already unblocked yourself =) 

but for future reference, `RegisterModel` takes `kwargs`, and you will be able to pass `outpout_path` as a kwarg to it, and the repack model training job will use it as its `OutputDataConfig.S3Outputpath`.

Closing this issue, feel free to re-open if you have any other concern.
