### ISSUE TITLE
SKLearn jobs CLI output comes duplicated

### ISSUE THREAD

**Issue by danielmarostica** [aws/sagemaker-python-sdk#2811]
**Describe the bug**
When running jobs on SageMaker using AWS CLI, the output comes duplicated.

**To reproduce**
Start any job using CLI.

**Expected behavior**
To receive the necessary output only once.

**System information**
- **SageMaker Python SDK version**: lastest
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SKLearn
- **Framework version**: 0.23-1
- **Python version**: 3.9
![image](https://user-images.githubusercontent.com/3595998/147483263-666d2245-2ad9-403b-965b-84f504cb2045.png)

**Comment by akrishna1995** [comment]
Hi @danielmarostica - can you please confirm if this issue still exists with the latest sagemaker ?

**Comment by akrishna1995** [comment]
Closing this issue for now. Feel Free to re-open if the issue still exists. Thanks
