### ISSUE TITLE
ConditionEquals does not accept PrimitiveType "bool" in the left parameter

### ISSUE THREAD

**Issue by snnclsr** [aws/sagemaker-python-sdk#2843]
**Describe the bug**

ConditionEquals class accepts two parameters left and right. And according to documentation, it can be either ConditionValueType or PrimitiveType. When I pass two boolean parameters as True and True it throws the following exception. **AttributeError: 'bool' object has no attribute 'expr'**

**To reproduce**

```python
from sagemaker.workflow.conditions import ConditionEquals
from sagemaker.workflow.parameters import ParameterBoolean
bool_param = ParameterBoolean(name="bool_param", default_value=True)
# Produces the aforementioned error
cond_error = ConditionEquals(
    left=True,
    right=True
)
cond_fine = ConditionEquals(
    left=bool_param,
    right=True
)
print(cond_error.to_request())
>>> AttributeError: 'bool' object has no attribute 'expr'
print(cond_fine.to_request())
>>> {'Type': 'Equals', 'LeftValue': {'Get': 'Parameters.bool_param'}, 'RightValue': True}
```

**Expected behavior**
Since the documentation states that the parameter could be a primitive type, I would expect to pass a `True` as it is.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: '2.72.3'
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: None
- **Framework version**: None
- **Python version**: 3.8.8
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

I was using this operation while creating a new pipeline step but the code above can reproduce the same behaviour.

Here in the master branch: 
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/conditions.py#L82
for the right value `primitive_or_expr` function used. I believe the same thing applies to left value as well.

**Comment by jerrypeng7773** [comment]
@snnclsr thanks for the feedback, sorry for the confusion over the docstring, we actually expect the left value to be an expression. Otherwise, the condition comparison is not meaningful? =)

**Comment by snnclsr** [comment]
@jerrypeng7773 thanks for the answer. Why it does not make sense though? For example, I would like to read a parameter from let's say a config file, and depending on the value I would like to follow different branches in the pipeline. 

And apparently in this issue #2879 it is getting updated.

**Comment by navaj0** [comment]
This has been fixed: https://github.com/aws/sagemaker-python-sdk/pull/2886
