### ISSUE TITLE
Add .sageignore file + patch S3Uploader.upload()

### ISSUE THREAD

**Issue by elgalu** [aws/sagemaker-python-sdk#2875]
### Problem Statement
We have some personal secret files that are already in .gitignore however SageMaker will upload them to S3 in order to run a TrainingJob. Then everyone with access to S3 in the AWS can read those personal secrets.

### Proposed Solutions
Add support for either not uploading what is already listed in .gitignore or add a new .sageignore file specifically for SM. The SDK, probably S3Uploader.upload() should implement this.

### Describe alternatives you've considered
The only alternative now is to remove the files but this creates lots of manual work for the user.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
