### ISSUE TITLE
ConditionComparison fails if `left` is a primitive such as `float` or `int`

### ISSUE THREAD

**Issue by kevinnowland** [aws/sagemaker-python-sdk#2879]
**Describe the bug**

ConditionComparison fails if `left` is a primitive such as a `float` or `int`.

https://github.com/aws/sagemaker-python-sdk/blob/0a0b6e65288496ad33fd5ee34020665aced02156/src/sagemaker/workflow/conditions.py#L82

This line should be `"LeftValue": primitive_or_expr(self.left)` matching the line below it or, if current behavior is expected, then documentation should be updated and primitives should not be expected for `left`.

**To reproduce**

Create a ConditionGreatherThanOrEqualTo object and set both left and right to primitives such as 1.0 and 0.0.

**Expected behavior**

Primitives should not cause conditions to fail.

**Screenshots or logs**

This is a partial version of my code: 

<img width="597" alt="Screen Shot 2022-01-28 at 10 17 00 AM" src="https://user-images.githubusercontent.com/6806753/151573119-7d9af137-6095-4976-b901-00b4aff4a443.png">

This was the result when starting a pipeline:

<img width="860" alt="Screen Shot 2022-01-28 at 10 21 55 AM" src="https://user-images.githubusercontent.com/6806753/151573303-2832f606-49cf-4c28-8488-0c32cc33365c.png">

**System information**

Running `sagemaker==2.74.0` on `python==3.8.12` in a custom kernel image attached to SageMaker Studio.

**Additional context**

None.

**Comment by staubhp** [comment]
Good catch, the left value should allow primitives as well. See PR above

**Comment by navinsoni** [comment]
@kevinnowland We have merged the PR with the changes. Can you please check if it solves your issue.

**Comment by martinRenou** [comment]
Closing as https://github.com/aws/sagemaker-python-sdk/issues/2843 should have fixed it. Feel free to reopen if needed.
