### ISSUE TITLE
PipelineModel doesn't support serverless inference deployment

### ISSUE THREAD

**Issue by diegoxfx** [aws/sagemaker-python-sdk#2891]
**Describe the feature you'd like**
I'd like to deploy a serverless inference model by only using the `deploy()` function of the PipelineModel

**How would this feature be used? Please describe.**
This feature would be helpful to avoid creating the entire endpoint configuration manually just to create a serverless inference model.

**Describe alternatives you've considered**
I've considerered creating the endpoint configuration manually, but given that we have the `deploy` function, it would be faster by doing it directly from there

**Additional context**
By looking at the code of the `deploy` function, the `production_variant` is created inside the function. By making the `production_variant` as an optional argument (or at least the arguments to create the `production_variant`) it could solve the problem

**Comment by ShwetaSingh801** [comment]
Shweta

**Comment by ShwetaSingh801** [comment]
Hi @diegoxfx,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request to our backlog and may consider putting it into future SDK versions. I will go ahead and close the issue now. Please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta

**Comment by brifordwylie** [comment]
We have clients that specifically want serverless for their pipeline models, can we please reopen this ticket?
