### ISSUE TITLE
the extra "new" word in doc cause error

### ISSUE THREAD

**Issue by myprogrammerpersonality** [aws/sagemaker-python-sdk#2919]
**Describe the bug**
The [SageMaker Asynchronous Inference](https://sagemaker.readthedocs.io/en/stable/overview.html#id8) and [SageMaker Serverless Inference](https://sagemaker.readthedocs.io/en/stable/overview.html#id9) part of the docs contain a weird "new" word in their example codes that cause an error if users copy the code. It should be removed.

**Expected behavior**
delete the "new"

**Comment by martinRenou** [comment]
Thank you for opening an issue. The links you point to seem to be outdated and not point to the issue you are mentioning? I cannot find references to the `new` word you mention. 

Closing for triaging, but feel free to reopen if you think it is still an issue.
