### ISSUE TITLE
82 symbols length constraint error for a pipeline name while creating a new pipeline

### ISSUE THREAD

**Issue by morelen17** [aws/sagemaker-python-sdk#2933]
**Describe the bug**
I get this error when building and creating an arbitrary pipeline.
```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: [string "<pipeline-name>" is too long (length: <xxx>, maximum allowed: 82)]
```

Apparently, it is somehow related with `PipelineExecutionDisplayName` length constraint (from the [docs](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_PipelineExecution.html): `Minimum length of 1. Maximum length of 82.`). `PipelineName` in fact has the [following](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreatePipeline.html#sagemaker-CreatePipeline-request-PipelineName) constraint: `Minimum length of 1. Maximum length of 256.`.

**To reproduce**
Create any pipeline:
```python
from sagemaker.workflow.pipeline import Pipeline


a_long_pipeline_name = '...'  # len(a_long_pipeline_name) > 82 - magic number?
buggy_sm_pipeline = Pipeline(
    name=a_long_pipeline_name,
    steps=[...],
)
buggy_sm_pipeline.upsert(role_arn='...')
```

**Expected behavior**
The pipeline is created / updated w/o any errors even if its name length is greater than **82**. It must not be in any way tied to `PipelineExecutionDisplayName` (if this is indeed the case, which I suspect it is).

**Screenshots or logs**
```
Traceback (most recent call last):
  ...
  File "<>/python3.8/site-packages/sagemaker/workflow/pipeline.py", line 219, in upsert
    response = self.create(role_arn, description, tags, parallelism_config)
  File "<>/python3.8/site-packages/sagemaker/workflow/pipeline.py", line 121, in create
    return self.sagemaker_session.sagemaker_client.create_pipeline(**kwargs)
  File "<>/python3.8/site-packages/botocore/client.py", line 391, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "<>/python3.8/site-packages/botocore/client.py", line 719, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the CreatePipeline operation: [string "<pipeline-name>" is too long (length: <xxx>, maximum allowed: 82)]
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.73.0 (also 2.59.8)
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: -
- **Framework version**: -
- **Python version**: 3.8 (3.8.12)
- **CPU or GPU**: -
- **Custom Docker image (Y/N)**: N

**Additional context**
\-

**Comment by staubhp** [comment]
Sorry for the inconvenience, this is a bug caused by the backend. I'll comment on this issue when it's resolved.

**Comment by morelen17** [comment]
@staubhp hello! Any updates on the issue? Has the backend been fixed?
