### ISSUE TITLE
environment collection is specified for the Estimator passed to the HyperparameterTuner.

### ISSUE THREAD

**Issue by patrick-239** [aws/sagemaker-python-sdk#2934]
**Describe the feature you'd like**
Unfortunately, the Environment collection is not yet supported in the training job definition of an HPO job. If you use environment variables in a training script you could use HPO. 

**How would this feature be used? Please describe.**
Ability to use environment variables defined in an estimator within HPO jobs. 

**Describe alternatives you've considered**
As a workaround you could use the hyperparameter collection to pass a value accessible from the container, and then define the corresponding environment variable in the script if needed. But this solution look strange and lead to miss use of hyperparameter collection. 

**Additional context**

**Comment by DougTrajano** [comment]
Hi folks, a workaround solution for that is to use the `hyperparameters` instead of `environment` in the Estimator API.

To don't change my estimator implementation, I added the code below in the hyperparameters code.

```python
for k, v in estimator.environment.items():
    estimator._hyperparameters[k] = v
```

In the `entry_point` script, I added all unexpected arguments as environment variables

```python
if len(remaining_args) > 0:
    for arg in range(len(remaining_args)):
        if remaining_args[arg].startswith("--"):
            os.environ[remaining_args[arg].strip("--")] = remaining_args[arg+1]
```

**Comment by lorenzwalthert** [comment]
I think we can close this as per https://github.com/aws/sagemaker-python-sdk/pull/3614.

**Comment by akrishna1995** [comment]
Thanks for raising this issue to us. Closing as per above comment. Please re-open this issue if the issue remains with the latest sagemaker. Thank you.
