### ISSUE TITLE
GAN model supports in Sagemaker Tensorflow

### ISSUE THREAD

**Issue by chinazm** [aws/sagemaker-python-sdk#295]
Sagemaker is using estimator (train_and_evaluate) for its tensorflow model training, I am thing is there a way to train the GAN models in sagemaker tensorflow. It would be difficult to use current estimator to train the GAN models...

**Comment by dennis-ec** [comment]
Sagemaker gives you the possibility to run your own docker container with custom code. Using this way you're much more flexible. [This example](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own) is a good place to start. If you want to use a gpu you have to build your docker with [nvidia docker](https://github.com/NVIDIA/nvidia-docker).

**Comment by yangaws** [comment]
Hi @chinazm ,

Just as @dennis-ec said, you could always build your own container for any customization you want to do on sagemaker.

 If you think a specific feature will be widely used by developers and it's not efficient for everybody to develop their own on same thing, you are always welcome to submit feature request here.
