### ISSUE TITLE
Model Error due to index out of range in self

### ISSUE THREAD

**Issue by bommavj** [aws/sagemaker-python-sdk#2955]
[ERROR] ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "
{
    "code": 400,
    "type": "InternalServerException",
    "message": "index out of range in self"
}

". See https://us-xxxx-1.console.aws.amazon.com/cloudwatch/home?region=us-xxxx-1#logEventViewer:group=/aws/sagemaker/Endpoints/uxxxxx in account xxxx for more information.
Traceback (most recent call last):
  File "/var/task/myPythonCode.py", line 23, in lambda_handler
    response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,
  File "/var/runtime/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
[ERROR] ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received client error (400) from primary with message "{ "code": 400, "type": "InternalServerException", "message": "index out of range in self" } ". See https://us-xxxx-1.console.aws.amazon.com/cloudwatch/home?region=us-xxxx-1#logEventViewer:group=/aws/sagemaker/Endpoints/xxxxx in account xxxxx for more information. Traceback (most recent call last):   File "/var/task/myPythonCode.py", line 23, in lambda_handler     response = runtime.invoke_endpoint(EndpointName=ENDPOINT_NAME,   File "/var/runtime/botocore/client.py", line 386, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/runtime/botocore/client.py", line 705, in _make_api_call     raise error_class(parsed_response, operation_name)

Total length of the payload = 2788

payload like below is erroring with index out of range:

{"inputs":["613 chars" , "2157 chars"]}

when we do with the below payload, it is successful

{"inputs":["613 chars" , "2155 chars"]}

can you please let us know in limiting the payload.

**Comment by bommavj** [comment]
the max chars it is taking is 2155 for each. please investigate and let us know if this can be fixed

**Comment by bommavj** [comment]
we are using the boto3 version as 1.18.55 version, it is accepting 2155 chars length

when we upgraded to boto3 version as 1.20.46 version, it is accepting 2487 chars length. But we have some description more than 2487 chars and our nlp results are degarded due to this description size.

**Comment by alvinlee123** [comment]
hi were you able to solve this? I'm running into this issue now

**Comment by akrishna1995** [comment]
Hi @bommavj @alvinlee123 

Are you still facing this issue? Can you please share more details on how to reproduce this issue ?

**Comment by akrishna1995** [comment]
Closing this issue as non reproducible for now. Please feel free to reopen if this issue still persists. Thanks
