### ISSUE TITLE
The TensorFlow container saves the exported models in Ascending order

### ISSUE THREAD

**Issue by chinazm** [aws/sagemaker-python-sdk#296]
We found that there is a bug in sagemaker to export the model:

sagemaker first exported checkpoints as exported models in the output folder and after training there will be a final model zipped and exported. We found sagemaker exported and zipped the models on ascending order not the most recent model exported.

**Comment by andremoeller** [comment]
Hi @chinazm ,

Thanks for the report! You're right that this isn't the expected behavior -- we'll investigate and comment on this ticket when we have updates.

Thanks again!

**Comment by andremoeller** [comment]
@chinazm 

That fix has been merged in. Thanks for the report!
