### ISSUE TITLE
Support to override model_data when calling Estimator.create_model

### ISSUE THREAD

**Issue by jonsnowseven** [aws/sagemaker-python-sdk#2988]
**Describe the feature you'd like**
Support to override a model data S3 URI when creating a model: https://github.com/aws/sagemaker-python-sdk/blob/34cb1c7b24dd0870877bb1bca6343ecd15d0fee5/src/sagemaker/estimator.py#L2419-L2421

**How would this feature be used? Please describe.**
It is useful to call `create_model` from an estimator, when we are using a tuner job, **specially** for SageMaker Pipelines.

```python
...
estimator = ...
tuner = ...
step_tuning = ...

model = estimator.create_model(
    model_data=step_tuning.get_top_model_s3_uri(
            top_k=0,
            s3_bucket=default_bucket,
            prefix=prefix,
    ),
    ...
)
```

instead of

```python
...
estimator = ...
tuner = ...
step_tuning = ...

model_class = <specific estimator model class (e.g., TensorFlowModel)>

model = model_class(
    model_data=step_tuning.get_top_model_s3_uri(
            top_k=0,
            s3_bucket=default_bucket,
            prefix=prefix,
    ),
    ...
)
```

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
