### ISSUE TITLE
AttributeError: 'LocalSagemakerClient' object has no attribute 'create_pipeline'

### ISSUE THREAD

**Issue by neilmcguigan** [aws/sagemaker-python-sdk#2990]
**Describe the bug**
SageMaker Python SDK model building pipelines does not work in Local Mode

**To reproduce**

```

sagemaker_session = LocalSession()
sagemaker_session.config = {'local': {'local_code': True}}

processor = SKLearnProcessor(
    base_job_name = "processingjob",
    role = cfg.role_arn,
    framework_version = cfg.sklearn_version,
    instance_count = cfg.instance_count,
    instance_type = "local",
    sagemaker_session=sagemaker_session
)

processing_step = ProcessingStep(
    name="processing",
    processor=processor,
    code = "code/preprocessor.py"
)

pipeline = Pipeline(
    name = "mypipeline",
    steps = [processing_step],
    sagemaker_session = sagemaker_session
)

pipeline.upsert(role_arn = cfg.role_arn)
pipeline.start()
```

**Expected behavior**
SageMaker model building pipelines should work in Local Mode for faster development

**Screenshots or logs**
AttributeError: 'LocalSagemakerClient' object has no attribute 'create_pipeline'

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.78.0
- **Python version**: 3.8
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by staubhp** [comment]
Hi @neilmcguigan, you're correct that local mode jobs won't work today in a pipeline. For that to happen, pipelines needs its own version of local mode that recreates the server-side orchestration logic. This is on the team's radar.

**Comment by ycrouin** [comment]
Hello, the cold-start time of SageMaker pipelines is really a pain.
This feature would be great to tackle this issue! Is there an ETA?

**Comment by knoam** [comment]
This would be very useful.

**Comment by jerrypeng7773** [comment]
we are diligently working on this. =)

**Comment by cirofdo** [comment]
Good to know, for now I'll keep testing locally each step at a time.

**Comment by cirofdo** [comment]
It seems to be avaiable now https://docs.aws.amazon.com/sagemaker/latest/dg/pipelines-local-mode.html

**Comment by ShwetaSingh801** [comment]
Closing this tkt since the requested feature is now available in SageMaker Python SDK.
