### ISSUE TITLE
Enable Python 3.10 support 

### ISSUE THREAD

**Issue by ahsan-z-khan** [aws/sagemaker-python-sdk#2999]
Describe the feature you'd like

With [Python 3.10.0](https://www.python.org/downloads/release/python-3100/), the first maintenance release of Python 3.10, out, more of the ecosystem has declared support for the Python version (e.g. [attrs](https://pypi.org/project/attrs/), [boto3](https://pypi.org/project/boto3/), etc.). Including support for Python 3.10 keeps the SageMaker Python SDK up-to-date.

How would this feature be used? Please describe.

As the last of the dependencies declare support for Python 3.10, anyone in a Python 3.10 environment could use the SageMaker Python SDK with confidence.

Describe alternatives you've considered

N/A

Additional context

N/A

**Comment by navinsoni** [comment]
we have added support for python 3.10 in https://github.com/aws/sagemaker-python-sdk/pull/3327

**Comment by ahsan-z-khan** [comment]
Thank you team! 🎉
