### ISSUE TITLE
modify CreateFeatureGroup API call to accept _both_ KmsKeyId and KmsKeyId_ARN. 

### ISSUE THREAD

**Issue by sermolin** [aws/sagemaker-python-sdk#3057]
**Describe the feature you'd like**
In CreateFeatureGroup, the parameter "KmsKeyId" expects KMS Key ID ARN, instead of the KmsKeyId value. This behavior is different from other API calls. This is _not_ just a documentation issue. This inconsistency becomes a serious problem when someone tries to pass KMS Key to all SageMaker API calls either via either AWS Systems Manager Parameter Store or by encapsulating KMS Key in a SageMaker *SuperSession* object. 

**How would this feature be used? Please describe.**
To preserve backwards compatibility, modify CreateFeatureGroup API call to accept _both_ KmsKeyId and KmsKeyId_ARN. 

**Describe alternatives you've considered**
This seems to be the best solution

**Additional context**
https://t.corp.amazon.com/V408655442/communication

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
