### ISSUE TITLE
SKLearn Version bump

### ISSUE THREAD

**Issue by jperuggia** [aws/sagemaker-python-sdk#3061]
**Describe the feature you'd like**
The team that maintains the scikit learn container merged in and approved a PR for an image for `sklearn==1.0.2`  as seen [here](https://github.com/aws/sagemaker-scikit-learn-container/pull/107)

**How would this feature be used? Please describe.**
Run training and model hosting using the SKLearn estimator class as well as Processing jobs. 

**Describe alternatives you've considered**
Custom containers being used currently with Bring your own container.

**Comment by lorenzwalthert** [comment]
I think this is closed with #3110
