### ISSUE TITLE
ProcessingStep does not accept Processor.process() argument, "arguments", as a parameter

### ISSUE THREAD

**Issue by lkev** [aws/sagemaker-python-sdk#3069]
**Describe the bug**
The `ProcessingStep` object is supposed to accept any arguments that are in `Processor.run()`. However, it does not accept `arguments`, which is a valid argument from `Processor.run()`. Instead it accepts the deprecated `job_arguments`.

**To reproduce**
The following:
```python
from sagemaker.workflow.steps import ProcessingStep
from sagemaker.processing import Processor

arbitrary_processor = Processor(
        image_uri="any_uri",
        role="any_role",
        instance_count=1,
        instance_type="ml.c5.18xlarge",
)

# raises no error
processing_step = ProcessingStep(
        name="process_step",
        processor=arbitrary_processor,
        job_arguments=["--argument-one", "argval"]
)

# raises error
processing_step = ProcessingStep(
        name="process_step",
        processor=arbitrary_processor,
        arguments=["--argument-one", "argval"]
)
```
gives:
```python
Traceback (most recent call last):
~/example.py in <module>
     17 
     18 # raises error
---> 19 processing_step = ProcessingStep(
     20         name="process_step",
     21         processor=arbitrary_processor,

TypeError: __init__() got an unexpected keyword argument 'arguments'
```

**Expected behavior**
It should accept `arguments` instead of `job_arguments`, as per the documentation. Note the `ProcessingStep` documentation refers to `Processor.process()` as opposed to `Processor.run()`.

**Screenshots or logs**
N/A

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.72.3
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.9.6
- **CPU or GPU**: N/A
- **Custom Docker image (Y/N)**: N

**Additional context**
N/A

**Comment by staubhp** [comment]
You'll need to use the [get_run_args](https://sagemaker.readthedocs.io/en/stable/api/training/processing.html#sagemaker.processing.ScriptProcessor.get_run_args) method of the processor to generate the arguments to ProcessingStep. Example:

```
run_args = pyspark_processor.get_run_args(
    "preprocess.py",
    inputs=[
      ProcessingInput(source=<input_data>, destination="/opt/ml/processing/input"),
    ],
    outputs=[
        ProcessingOutput(output_name="train", source="/opt/ml/processing/train"),
        ProcessingOutput(output_name="validation", source="/opt/ml/processing/validation"),
        ProcessingOutput(output_name="test", source="/opt/ml/processing/test")
    ],
    arguments=None
)

step_process = ProcessingStep(
    name="AbaloneProcess",
    processor=pyspark_processor,
    inputs=run_args.inputs,
    outputs=run_args.outputs,
    job_arguments=run_args.arguments,
    code=run_args.code
)
```

The reason for this is Processor subclasses take a variety of different arguments which need to be normalized for ProcessingStep. `get_run_args` does that normalization.

Open to suggestions on how this can be made clearer in the documentation.

**Comment by lkev** [comment]
Hey @staubhp, apologies for delay just seen this reply now.

The method you suggested does not work for the basic `Processor`, i.e. [there is no](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.steps.ProcessingStep) `Processor.get_run_args()` method. In my example above, running `arbitrary_processor.get_run_args()` gives `AttributeError: 'Processor' object has no attribute 'get_runs_args'`.

In terms of making it clearer in the docs, currently in the docs it explicitly says on [the page](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.steps.ProcessingStep) for `ProcessingStep`:

> In addition to the Processor instance, the other arguments are those that are supplied to the process method of the sagemaker.processing.Processor.

So the documentation is incorrect - at least the `job_arguments` argument differs from `sagemaker.processing.Processor`. So it seems like maybe the `get_run_args` method needs to be added to `Processor` and/or the documentation needs to be updated?
