### ISSUE TITLE
SageMaker Bring Your Own Container - on local mode - connection to S3

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3084]
**Describe the feature you'd like**
During implementation of SageMaker BYOC with local mode with Python SDK, we notice that it connects to S3 (to Sagemaker object's - default bucket), places all of the artifacts in there, and then downloading it again into the local container. We thought that local mode means that no external connections are done, but that's not the case in our implementation.

**How would this feature be used? Please describe.**
We want local mode to be able to be completely local. So if we want to, we can indicate to it to fully work without the need to connect to web at all.

**Additional context**
We used this code as a reference: https://github.com/aws-samples/amazon-sagemaker-local-mode/blob/main/scikit_learn_bring_your_own_container_local_processing/scikit_learn_bring_your_own_container_local_processing.py

**Comment by mufaddal-rohawala** [comment]
Fix released. Should be fixed in release >= [v2.89.0](https://github.com/aws/sagemaker-python-sdk/commit/0b8bd8d92087b994a3f18c61b0152c39ba22ba51)

**Comment by clausagerskov** [comment]
@mufaddal-rohawala this is not fixed

**Comment by clausagerskov** [comment]
this bug fix listed in the release was to change a required "s3:ListAllMyBuckets" to a required "s3:ListBucket". 
that does not at all address the issue here, which is fully local development

**Comment by clausagerskov** [comment]
@shreyapandit

**Comment by fahran-wallace** [comment]
I'm experiencing the same I think, using `sagemaker[local]==2.222.0`.

A code snippet extracted from this example: https://github.com/aws-samples/amazon-sagemaker-local-mode/blob/main/xgboost_script_mode_local_training_and_serving/xgboost_script_mode_local_training_and_serving.py

```python
from sagemaker import TrainingInput
from sagemaker.xgboost import XGBoost, XGBoostModel
from sagemaker.local import LocalSession

DUMMY_IAM_ROLE = 'arn:aws:iam::111111111111:role/service-role/AmazonSageMaker-ExecutionRole-20200101T000001'
LOCAL_SESSION = LocalSession()
LOCAL_SESSION.config = {'local': {'local_code': True}}  # Ensure full code locality, see: https://sagemaker.readthedocs.io/en/stable/overview.html#local-mode
FRAMEWORK_VERSION = "1.7-1"

def main():
    xgb_inference_model = XGBoostModel(
        model_data="./tests/resources/models/fake/model.json",
        role=DUMMY_IAM_ROLE,
        entry_point="inference.py",
        source_dir="./src",
        framework_version=FRAMEWORK_VERSION,
        sagemaker_session=LOCAL_SESSION
    )

    print('Deploying endpoint in local mode')
    predictor = xgb_inference_model.deploy(
        initial_instance_count=1,
        instance_type="local",
    )

def test_inference_endpoint():
    main()
```

Expected behaviour: Model repacked locally
Actual behaviour: Failure when creating an S3 bucket during the deploy job. I...really do not want my code being uploaded to random S3 buckets! 

```self = <botocore.client.S3 object at 0x16c38eaf0>
operation_name = 'CreateBucket'
api_params = {'Bucket': 'sagemaker-eu-west-1-xxxxxxxxxxxx', 'CreateBucketConfiguration': {'LocationConstraint': 'eu-west-1'}}```

**Comment by clausagerskov** [comment]
so is this fixed then?
