### ISSUE TITLE
Create Model Step fails when when we pass the URL as a Pipeline Parameter for model_data

### ISSUE THREAD

**Issue by rohangpatil** [aws/sagemaker-python-sdk#3091]
**Describe the bug**

**To reproduce**
The below code works
```python
model = XGBoostModel(
      model_data="s3://<...>/model.tar.gz",
      role=role,
      sagemaker_session=sagemaker_session,
      entry_point="inference_entrypoint.py",
      framework_version="1.5-1",
    )
```
This doesnt work.
```python
model_url = ParameterString(name="ModelURL")
model = XGBoostModel(
      model_data=model_url,
      role=role,
      sagemaker_session=sagemaker_session,
      entry_point="inference_entrypoint.py",
      framework_version="1.5-1",
    )
```

**Expected behavior**

**Screenshots or logs**
This is not what is expected.
<img width="1438" alt="Screen Shot 2022-05-03 at 11 28 49 AM" src="https://user-images.githubusercontent.com/1222850/166410377-db53e87b-ccb6-4fe4-892a-d3e90ea27734.png">
This is expected 
<img width="1438" alt="Screen Shot 2022-05-03 at 11 30 04 AM" src="https://user-images.githubusercontent.com/1222850/166410409-2a1fef5d-9490-44b5-95f9-9e31d5143bec.png">

**System information**
A description of your system. Please provide:

SageMaker Python SDK version: 2.87.0
Framework name (eg. PyTorch) or algorithm (eg. KMeans): XGBoost
Framework version: 1.5-1
Python version: 3.7.10
CPU or GPU: CPU
Custom Docker image (Y/N): N

**Additional context**

**Comment by jessieweiyi** [comment]
This issue is similar to #3078.

**Comment by rohangpatil** [comment]
> We have a PR under review to fix this, as a workaround, you can give the parameter a default value like this
> 
> `model_url = ParameterString(name="ModelURL", default="my-model")`
> 
> and then override this parameter to the actual value while starting the pipeline execution.
> 
> Sorry for the inconvenience.

Thanks! Some how this workaround works.

**Comment by qidewenwhen** [comment]
@rohangpatil The fix has been released. Could you check if it works for you?
Closing this issue and feel free to reopen if you have any questions.
