### ISSUE TITLE
no metrics showing in the sagemaker pipeline UI as well as in the Experiments and trails UI

### ISSUE THREAD

**Issue by hannahHe20** [aws/sagemaker-python-sdk#3092]
**Describe the bug**
I'm looking into the sagemaker experiment tracking functionality to run my project based on my own docker image. But I cannot see the metrics in the sagemaker pipeline UI and Experiments & trails UI. 

**To reproduce**
I used the sagemaker studio and the default "MLOps template for model building, training and deployment" template to initiate my project. And then modified the code in the pipeline.py under abalone(the code has been attached).
The pipeline has run successfully but I'm not able to see the metrics on both sagemaker pipeline UI and experiment trails UI. 

**Expected behavior**
it supposed to show the "Top 10 Combinations Based on Score" and also it's value which captured by regrex as I defined in the estimator. 

**Screenshots or logs**
logs in cloudwatch  training group and I'm using regex to get this sentence to get the value: "top 10 combinations based on score: [0, 1, 2, 5, 6, 9, 19, 30, 57, 58, 3497.034612758378]" and based on my regex, it can locate to the sentence and get the values as shown:

<img width="1671" alt="logs in cloudwatch training group" src="https://user-images.githubusercontent.com/74689853/166620186-56a6fb92-aaed-4fb1-b0ee-db9ff40da27c.png">
<img width="860" alt="Screenshot 2022-05-03 at 8 52 27 PM" src="https://user-images.githubusercontent.com/74689853/166620947-d76052b7-767e-40ba-9ff0-b065c0a2fe25.png">

<img width="1337" alt="no metrics in pipeline ui" src="https://user-images.githubusercontent.com/74689853/166427415-c16b596c-8937-4841-aa6e-fc763be1dc62.png">

<img width="812" alt="no metrics in experiment ui" src="https://user-images.githubusercontent.com/74689853/166427431-a6557ba3-d798-4ecb-93d4-0df200cafaf3.png">

<img width="845" alt="my customized estimator" src="https://user-images.githubusercontent.com/74689853/166427450-727fbc24-9e37-4f6c-80cb-4d73bd29dfc7.png">

<img width="930" alt="code for customized estimator" src="https://user-images.githubusercontent.com/74689853/166427464-d513b4f6-8e4b-4f87-bb01-db1208688ba0.png">

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: Downloading sagemaker-2.88.2.tar.gz (529 kB) 
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: no
- **Framework version**: no 
- **Python version**: python 3.6
- **CPU or GPU**: both
- **Custom Docker image (Y/N)**:  Y

**Additional context**

**Comment by hannahHe20** [comment]
problem solved.

**Comment by wickeat** [comment]
@hannahHe20 How did you solve this problem?

**Comment by marrrcin** [comment]
@hannahHe20 could you please describe how did you manage to solve this problem?
