### ISSUE TITLE
AWS CDK v2 incompatibility

### ISSUE THREAD

**Issue by lsli8888** [aws/sagemaker-python-sdk#3096]
pip is failing for me due to conflicts between sagemaker and aws-cdk-lib, both of which are dependencies in my project.  Specifically, it's due to the attrs dependency.  Pip spits out the following error noting the conflict:

`The conflict is caused by:
    sagemaker 2.88.3 depends on attrs==20.3.0
    jsii 1.57.0 depends on attrs~=21.2
`
aws-cdk-lib depends on jsii >= 1.57.0, < 2.0.0.  jsii in turn depends on attrs ~= 21.2.  The problem is that sagemaker has a hard dependency on attrs version 20.3.0.  Is this a hard dependency, or can you modify the dependency to be something like attrs>=20.3.0?

**Comment by lsli8888** [comment]
I had to downgrade to sagemaker 2.75.1 to make it work.

**Comment by acere** [comment]
+1

**Comment by l3ku** [comment]
I am also experiencing the same issue, had to downgrade to sagemaker 2.75.1. Would love to use more recently added features so I'm also wondering whether the hard dependency on `attrs==20.3.0` is required?

**Comment by navinsoni** [comment]
@lsli8888, @l3ku: We have upgraded attrs to 22.1.0 in https://github.com/aws/sagemaker-python-sdk/pull/3374.
Can you please check if it works for you.

**Comment by l3ku** [comment]
Works for me. Thanks!

**Comment by knikure** [comment]
We have provided the fix for this dependency issue in sagemaker>=[v2.111.0](https://github.com/aws/sagemaker-python-sdk/releases/tag/v2.111.0). Please feel free to open this issue if there are any concerns.
