### ISSUE TITLE
[Feature Request] Checkpoints in local mode

### ISSUE THREAD

**Issue by austinmw** [aws/sagemaker-python-sdk#3099]
**Describe the feature you'd like**
Is there any possibility that a way could be found to enable `checkpoint_s3_uri` in local mode?

https://github.com/aws/sagemaker-python-sdk/blob/5b8eb10bfddcb54fb65c8b28f923697619672120/src/sagemaker/estimator.py#L1897

**How would this feature be used? Please describe.**
Realtime streaming to S3 of selected files would add a useful feature to local mode by itself, but it would also enable using local mode as a debugging environment when setting up checkpointing, since currently the iteration speed of doing this is not ideal.

**Describe alternatives you've considered**
I'm not aware of any good alternatives

**Additional context**
Maybe this feature would require the additional input of `region`?

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
