### ISSUE TITLE
How to save model?

### ISSUE THREAD

**Issue by meownoid** [aws/sagemaker-python-sdk#31]
How can I save model after the `model.fit()`so next time I could load and deploy it using `model.deploy()`?

**Comment by andremoeller** [comment]
Hi @meownoid ,

Model artifacts from a training job are uploaded to S3 when training completes, so the model is already saved. You can use `attach()` with the training job name from `fit()` to deploy this model:

https://github.com/aws/sagemaker-python-sdk/blob/157d8670977243f7f77327175d40364c885482b3/src/sagemaker/estimator.py#L531

Does this answer your question?

**Comment by yangaws** [comment]
@meownoid

 I will close the issue now. Feel free to reply if you have any further questions.

**Comment by giggle0312** [comment]
The trained model can be deployed on the other platform without dependency of sagemaker or aws service?

**Comment by ricoms** [comment]
@andremoeller, that is true if you did the training on the SageMaker, but in my example, I did not. I train everything in EC2 instances, then saved the architecture file in json format and the weights in h5 format.

Is there any way that I can deploy and estimator to SageMaker from this files?

I'm following this material: https://github.com/samir-souza/ai-workshop/blob/master/lab/03_ImageClassification/ImageClassificationFashionMNIST.ipynb my problem is similar.

**Comment by KobaKhit** [comment]
Follow up here. What format does sagemaker save models in? To be more precise, after you unzip the `model.tar.gz` what is the resulting format of the model file. It does not seem to be mleap. Was wondering if its possible to load the `model.tar.gz` produced by sagemaker training job using an mleap like library.

**Comment by laurenyu** [comment]
@KobaKhit the format of the model depends on how you trained the image, e.g. if you use TensorFlow, then the model is saved in the format specified by your training script.
