### ISSUE TITLE
PyTorch estimatore searches for entry_point in source_dir

### ISSUE THREAD

**Issue by jendrikjoe** [aws/sagemaker-python-sdk#312]
### System Information
- **PyTorch**:
- **0.4.0**:
- **3.6**:
- **GPU**:
- **3.6**:
- **No**:

### Describe the problem
Hey there everyone,

I am currently utilizing the PyTorch version of the SageMaker estimator and need to add additional files for it.
For that I used the source_dir option in the Estimator. However, different to what the documentation states, the entry_point has to reside in the source_dir. Is it possible to change that? Otherwise, I have to keep lots of files around ;) 

### Minimal repro / logs
    estimator = PyTorch(entry_point="PredictionSageMaker.py",
                        source_dir='/path/to/source_dir_sagemaker',
                        role='aws role',
                        framework_version='0.4.0',
                        train_instance_count=1,
                        train_instance_type='ml.p2.xlarge',
                        hyperparameters={'epochs': 50, 'model': 'SimpleRNNNet', 'batch-size': 2048, 
                                     'learning-rate': 1e-5, 'mode': 'day'})

    Traceback (most recent call last):
      File "(*deleted*)/launchSageMaker.py", line 28, in <module>
        estimator.fit({'train': '(*deleted*)', 'test': '(*deleted*)'})
      File "(*deleted*)/anaconda3/lib/python3.6/site-packages/sagemaker/estimator.py", line 176, in fit
        self._prepare_for_training(job_name=job_name)
      File "(*deleted*)/anaconda3/lib/python3.6/site-packages/sagemaker/estimator.py", line 542, in _prepare_for_training
        validate_source_dir(self.entry_point, self.source_dir)
      File "(*deleted*)/anaconda3/lib/python3.6/site-packages/sagemaker/fw_utils.py", line 87, in validate_source_dir
        raise ValueError('No file named "{}" was found in directory "{}".'.format(script, directory))
    ValueError: No file named "PredictionSageMaker.py" was found in directory "(*deleted*)/source_dir_sagemaker".

**Comment by yangaws** [comment]
Hi @jendrikjoe ,

Thanks for bringing this. This is a doc error. The entry_point file has to be in the source_dir if source_dir is used.
