### ISSUE TITLE
Support retaining current desired instance count when updating endpoint

### ISSUE THREAD

**Issue by torsjonas** [aws/sagemaker-python-sdk#3126]
**Describe the feature you'd like**
The default behaviour of SageMaker Python SDK when updating an inference endpoint is to throw away whatever value for desired instance count there is currently at runtime for the endpoint (according the endpoint autoscaling policy). Please add support for the SageMaker UpdateEndpoint API boolean parameter `RetainAllVariantProperties` as a way to solve this issue, see https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_UpdateEndpoint.html#API_UpdateEndpoint_RequestSyntax

**How would this feature be used? Please describe.**
I would provide RetainAllVariantProperties=True to update an endpoint while retaining whatever is the current runtime autoscaling policy desired instance count.

**Describe alternatives you've considered**
Use boto3 as a workaround

**Additional context**

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
