### ISSUE TITLE
Cannot get code location from training job step

### ISSUE THREAD

**Issue by jonathanhillwebsite** [aws/sagemaker-python-sdk#3127]
**Describe the bug**
I cannot pass the `source_dir` (sagemaker_submit_directory) outputted from a sagemaker training job to an evaluation processing step because I don't know where this output is on S3 until after the training job finishes.

* A timestamp is automatically generated when the training job is executed, and I cannot retrieve this timestamp.
* This means it's impossible to get the code_location path before executing the pipeline.
* As this path is created while the pipeline is running, there's no way of pass it to the next step.

I've tried looking through the training step's object attributes but could not find this. I found the `sagemaker_submit_directory` string (which is the path I'm looking for), but cannot pass this string to the step's inputs.

<img width="753" alt="image" src="https://user-images.githubusercontent.com/24596396/169877851-1e097f5e-f7c4-45a7-9cbc-40c5cac16250.png">

Above is the code being passed into the training estimator, and then the training job will add a timestamp to that path like the below:

<img width="987" alt="image" src="https://user-images.githubusercontent.com/24596396/169878105-818345ad-3f03-47d3-9f80-591eed79d0ed.png">

However.. There's no way of getting that timestamp, and the function I used above (_get_or_create_name) will create a new timestamp every time it's called.

I hope there's something super obvious I'm missing here. I couldn't find any documentation explaining how to get these step information dynamically between steps which makes sagemaker pipelines very hard to convince others to use.

my attempts of accessing the code_location so far:
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/24596396/169879626-70ce3719-1c34-453f-b45c-a1f210de2fe0.png">

**To reproduce**
Run a training step and try to access the code_location (source_dir.tar.gz file) in a processing step.

**Expected behavior**
The path to the code location s3 URI to be easily accessible (same as the model.tar.gz file as shown above)

**Screenshots or logs**
Some screenshots shown above, can provide more if necessary.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.86.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Tensorflow
- **Framework version**: 2.5
- **Python version**: 3.6 (I'm using the conda_amazonei_tensorflow2_p36 environment)
- **CPU or GPU**: both
- **Custom Docker image (Y/N)**: N

**Additional context**
I'm relatively new to SageMaker Pipelines. Looks promising but I'm struggling using it for anything more advanced than the basic tutorial.

**Comment by jerrypeng7773** [comment]
@jonathanhillwebsite you should be able to get it by referring this:

`training_step.properties.HyperParameters["sagemaker_submit_directory"]`

Also, if you update the latest SDK version, you will be able to enjoy a far better experience of constructing the training and processing step.

```
from sagemaker.workflow.pipeline_context import PipelineSession

session = PipelineSession()

estimator = Tensorflow(..., sagemaker_session=session)

train_step_args = estimator.fit(...)

step_train = TrainingStep(name="MyTrainingStep", step_args=train_step_args)

processor = FrameworkProcessor(..., sagemaker_session=session)

process_step_args = processor.run(inputs=..., source_dir="...")

step_sklearn = ProcessingStep(
    name="MyProcessingStep",
    step_args=step_args,
)
```

In summary, we introduced the PipelineSession. This special session does not trigger a processing job immediately when you call processor.run , instead, it captures the request arguments required to run a processing job, and delegate it to the processing step to start the job later during pipeline execution. 

This works for transformer, and tuner too.

**Comment by jerrypeng7773** [comment]
@jonathanhillwebsite sure, can you try this

```
from sagemaker.workflow.functions import Join

ProcessingInput(source=Join(on="/", values=[
   training_step.properties.HyperParameters["sagemaker_submit_directory"],
  "source/souredir.tar.gz",
]))
```

**Comment by jerrypeng7773** [comment]
Hey @jonathanhillwebsite we just realized that we are putting additional quotation marks to the training job `HyperParameters`. We are discussing this internally. @navinsoni @shreyapandit @navaj0

**Comment by jerrypeng7773** [comment]
@jonathanhillwebsite just re-read your description, if I understand it correctly, it looks like you are trying to access the `source.tar.gz` from the processing job. I assume you already have source files locally, which training job would upload to s3 on your behalf; at the same time, processing job can do the same. 

For estimator, `code_location` is the S3 prefix URI where local custom code is uploaded, `source_dir` is where you local custom code is. For processor, you can give the below as one of the processing inputs,

```
ProcessingInput(source="/my-local-source", destination="/opt/ml/processing/input/")
```

The source which pointing to a local dir will automatically be uploaded to S3 under `s3://<default-bucket-name>/<job-name>/input/<input-name>`, and it will be automatically downloaded to the processing job container under dir `/opt/ml/processing/input/`, where you will be able to read it.

**Comment by quwei913** [comment]
@jerrypeng7773  @jonathanhillwebsite  any update on this? I am running into the same issue. We need some way to remove the double quotation marks from training_step.properties.HyperParameters["sagemaker_submit_directory"] and training_step.properties.HyperParameters["sagemaker_program"].

**Comment by jerrypeng7773** [comment]
The hyperparameter values of reserved keys like `sagemaker_submit_directory` and `sagemaker_program` are used in our algorithm container images, the quotation mark is deliberately added to differentiate strings from other types like integer in str format. Removing the quotation mark will break many existing containers, and causing backward incompatibility. This means removing the quotation marks from the training job HyperParameters dictionary reserved key value is not an option. 

The major issue here is that, as you mentioned, the `job_name` is automatically populated. Here is a temporarily workaround

```
from sagemaker.workflow.pipeline_context import PipelineSession

sess = PipelineSession()
step_args = estimator.fit(..., job_name="my-job-name")
```
In this way, the `code_location` will become `s3://< default-bucket-name >/my-job-name/input/< input-name >`. However, note that during pipeline execution, we will automatically generate a new job name for the training job (to avoid naming collision during repeat pipeline execution) the `job_name=my-job-name` given above won't be honored.

This is a bit confusing, and we are working on an improvement (and it might break this workaround)

**Comment by qidewenwhen** [comment]
Closing this issue as no new requests coming in the past month. Feel free to reopen if you have any further questions.

**Comment by qidewenwhen** [comment]
Update: the cache improvement we've launched by end of 2022 has broken the workaround provided above https://github.com/aws/sagemaker-python-sdk/issues/3127#issuecomment-1156697695.

As files in `sagemaker_submit_directory` are actually some local build time resources, to be uploaded to the TrainingStep, we'd recommend users to avoid such usage `training_step.properties.HyperParameters["sagemaker_submit_directory"]`. Instead, please try assigning the SDK generated local path directly to the next step's input if possible.

The SDK generated source dir can be retrieved via `estimator.uploaded_code.s3_prefix`.
Rationale: given the SDK source code below, the `estimator.uploaded_code.s3_prefix` is the `sagemaker_submit_directory` sending to the Training step/job.

https://github.com/aws/sagemaker-python-sdk/blob/3cafa5325c8ae256e8aff71a1c73fe9d8df87855/src/sagemaker/estimator.py#L892-L914C28
