### ISSUE TITLE
RegisterModel Pipeline Step Documentation is Broken

### ISSUE THREAD

**Issue by quasimik** [aws/sagemaker-python-sdk#3129]
**What did you find confusing? Please describe.**

I was following instructions from this [blogpost](https://aws.amazon.com/blogs/machine-learning/automate-model-retraining-with-amazon-sagemaker-pipelines-when-drift-is-detected/) and one step was creating a RegisterModel Pipeline step.

However, the [documentation](https://sagemaker.readthedocs.io/en/v2.91.1/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.step_collections.RegisterModel) for the latest version (v2.91.1) simply says:

> alias of `sagemaker.deprecations.deprecated_class.<locals>.DeprecatedClass`

**Describe how documentation can be improved**

Fix the docstring, or tell me why it was deprecated.

**Additional context**

The latest version for which the docstring makes sense is [v2.89.0](https://sagemaker.readthedocs.io/en/v2.89.0/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.step_collections.RegisterModel). From the next version [v2.90.0](https://sagemaker.readthedocs.io/en/v2.90.0/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.step_collections.RegisterModel) onwards, the docstring is the above.

The [v2.90.0 changelog](https://github.com/aws/sagemaker-python-sdk/blob/master/CHANGELOG.md#v2900-2022-05-16) in this repo states:

> Features:
>     * Add ModelStep for SageMaker Model Building Pipeline

Perhaps it's related.

**Comment by qidewenwhen** [comment]
Hi @quasimik, sorry for the inconvenience caused and we have opened a PR to fix this: https://github.com/aws/sagemaker-python-sdk/pull/3137

**Comment by quasimik** [comment]
Thanks!
