### ISSUE TITLE
documentation: the estimator.fit method does not have docstring

### ISSUE THREAD

**Issue by mchoi8739** [aws/sagemaker-python-sdk#3131]
**What did you find confusing? Please describe.**

The most used class method of Estimator for training, `Estimator.fit`, is not documented properly.
https://sagemaker.readthedocs.io/en/stable/api/training/estimators.html#sagemaker.estimator.Estimator.fit

**Describe how documentation can be improved**
- Add docstring to the fit classmethod.
- Add a complete list of kwd args for the fit method, such as `inputs` for training data channels, etc.

**Comment by jerrypeng7773** [comment]
The change to fix it has been merged.

https://github.com/aws/sagemaker-python-sdk/commit/8c93f923c6a0485d2d1cdf87ce8128a8eb6a13aa
