### ISSUE TITLE
TypeError: can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by DanielRZapataS** [aws/sagemaker-python-sdk#3160]
This error appears when you run the ScriptProcessor.run(). The script its at thew same level of my notebook in pagemaker Studio. It doesn't change if I add input, and output. I'm using a custom image on ECR. I also tried to save my script on s3 and pass the s3 path.

```
from sagemaker.processing import Processor
processor = ScriptProcessor(role=role,
                      image_uri=processing_image_uri,
                      instance_count=processing_instance_count,
                      instance_type=processing_instance_type,
                      base_job_name=base_job_name,
                      sagemaker_session = sagemaker_session,
                      command="python3") 
code = 'main.py'
processor.run(
        code = code
) 

```

**Screenshots or logs**

![Screen Shot 2022-06-06 at 10 18 04 PM](https://user-images.githubusercontent.com/25508560/172288392-9b17bd16-74ff-4122-a3bf-02c52bce278d.png)

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.88.1 and 2.93.1
- **Python version**:3.x

**Additional context**

**Comment by nhm-7** [comment]
Hi! You should use `command=["python3"]`


![image](https://user-images.githubusercontent.com/83786684/173409750-84e833be-6bb7-489d-b231-f8be8323365c.png)

**Comment by trungleduc** [comment]
Closing as answered

**Comment by martinRenou** [comment]
@jesusaurus can you comment on what you've tried and which error you are getting?
