### ISSUE TITLE
Feature Group Athena Query allow setting the Athena workgroup, currently it only running in Primary workgroup of Athena

### ISSUE THREAD

**Issue by rahulsing** [aws/sagemaker-python-sdk#3176]
**Describe the feature you'd like**
Not able to set workgroup for Athena query running on feature group.
If I try to set: 
identity_query.run(query_string=query_string, output_location='s3://'+default_s3_bucket_name+'/query_results/',workgroup='non-primaty')
Getting the below error: 
TypeError: run() got an unexpected keyword argument 'workgroup'

**How would this feature be used? Please describe.**
This will allow Athena query to run with project specific workgroup instead of running all the query in primary. 

**Describe alternatives you've considered**
Non for now, only boto3 is any option to use for querying by setting the workgroup

**Additional context**
Athena start_query_execution has this capability. 
![image](https://user-images.githubusercontent.com/3228347/174193703-34ea7fbf-6de7-452d-9661-4b986eeb9023.png)
But missing in SageMaker SDK: 
![image](https://user-images.githubusercontent.com/3228347/174193757-ba33ccc6-fd0e-4c5c-9d8e-5f741b1ddbf6.png)

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.

**Comment by johnrc90** [comment]
Is this in the backlog yet? Im trying to use the V3 in Sagemaker Unified Studio and each project has access to its own workgrup, so the DatasetBuilder dont work without being able to choose the workgroup.
