### ISSUE TITLE
Not able to provide `extra_args` to S3Uploader.upload()

### ISSUE THREAD

**Issue by spaskalaydzhiyski** [aws/sagemaker-python-sdk#3197]
**Describe the bug**
Not able to provide `extra_args` to S3Uploader.upload()

**To reproduce**
Try calling `sagemaker.s3.S3Uploader.upload()`
<img width="700" alt="image" src="https://user-images.githubusercontent.com/106966418/175954247-82367b11-2c05-4e25-b113-83badf667262.png">
 for an s3 bucket encrypted with **AES256**

The `upload()` function internally calls `sagemaker_session.upload_data()` which takes `extra_args` as param, but unfortunately we have no means of passing extra_args from `S3Uploader.upload()`
<img width="764" alt="image" src="https://user-images.githubusercontent.com/106966418/175954179-40f89137-2cf5-44d7-9ef1-0ca84dc72b5a.png">

Because of this line:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/106966418/175956039-381acc4d-ad48-4dd9-a4d9-539156f2ab2f.png">

When called the function results in AccessDenied error.
<img width="487" alt="image" src="https://user-images.githubusercontent.com/106966418/175954641-c050253c-3af3-42c3-bcab-61300b789c47.png">

**Expected behavior**
I would expect to be able to call `S3Uploader.upload(local_file_path, s3_destination_path, extra_args={'ServerSideEncryption': 'AES256'})`.

**IMPORTANT**
This problem also breaks the demos in SageMaker Studio (in case you are using AES256 encrypted S3 buckets) since both `Processor` and `ScriptProcessor` use `S3Uploader` internally to communicate with S3.
The fix is very straight forward (although laborious) and only requires to add `extra_args` to all the places where `S3Uploader.upload` is called from **including all upstream function calls that are supposed to pass `extra_args` down to S3Uploader.upload.**
<img width="989" alt="image" src="https://user-images.githubusercontent.com/106966418/176168054-04aab4b7-f25e-4b79-87d0-e3b0a9779cc7.png">

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:2.96.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:3.9
- **CPU or GPU**:CPU
- **Custom Docker image (Y/N)**:N

**Additional context**
I can write the fix myself, but since `S3Uploader.upload()` is quite a common function and is used all throughout the codebase - I would rather not touch other modules in sagemaker a part from `S3Uploader`. The full solution would include adding the option to pass `extra_args` to **all calls** of `S3Uploader.upload()`

**Comment by spaskalaydzhiyski** [comment]
P.S. Please find the proposed patch below:

[patch-add-extra_args-everywhere.diff.txt](https://github.com/aws/sagemaker-python-sdk/files/9001826/patch-add-extra_args-everywhere.diff.txt)
(remove the **.txt** extension) and you can **apply** it to the latest version of the master branch.

**Comment by spaskalaydzhiyski** [comment]
Found a work around.

**Comment by nicornk** [comment]
@spaskalaydzhiyski I am running into the same issue. Our Service Control Policies require me to always send the `s3:x-amz-server-side-encryption` with value `AES256`.

Can you share your workaround?
