### ISSUE TITLE
Using Sagemaker Autopilot with Pipelines

### ISSUE THREAD

**Issue by uwaisiqbal** [aws/sagemaker-python-sdk#3207]
Is it possible to use Sagemaker Autopilot as a TrainingStep in a Pipeline?

I've been looking through the documentation but couldn't find an example of how it can be implemented

**Comment by uwaisiqbal** [comment]
Hey - thanks for the response. Is there any idea of an ETA for when this could be worked on and included? I'm happy to contribute to this feature as I need it for a project I'm actively working on.

**Comment by qidewenwhen** [comment]
Hi @uwaisiqbal, sorry that I'm not able to give an ETA for it but will let you know if we have any updates.
Thanks for trying to help us to improve SageMaker Pipeline!

**Comment by qidewenwhen** [comment]
Hi @uwaisiqbal, sorry for the late response. We have launched the AutoMLStep at the end of 2022 to integrate Autopilot with SageMaker Pipeline.
See sample notebook: https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-pipelines/tabular/automl-step/sagemaker_autopilot_pipelines_native_auto_ml_step.ipynb

Can you check if it works in your case? Thanks

**Comment by qidewenwhen** [comment]
Closing the issue. Feel free to reopen if you have further questions.
