### ISSUE TITLE
Automatically infer `Framework` and `FrameworkVersion` from `FrameworkModel` when calling the `register()` method  

### ISSUE THREAD

**Issue by acere** [aws/sagemaker-python-sdk#3218]
**Describe the feature you'd like**
When I register a model created with any of the [Framework Models](https://sagemaker.readthedocs.io/en/stable/api/inference/model.html#sagemaker.model.FrameworkModel) I don't need to repeat the framework and version (necessary to enable inference recommender) in the arguments of [`model.create()`](https://sagemaker.readthedocs.io/en/stable/frameworks/pytorch/sagemaker.pytorch.html#sagemaker.pytorch.model.PyTorchModel.register)

**How would this feature be used? Please describe.**
This feature will reduce the number of argument necessary to register a model in SageMaker Model Registry, making inference recommender more accessible.

**Describe alternatives you've considered**
The current alternative is to maintain the current method signature, providing little differentiation between the SDK and boto3

**Comment by qidewenwhen** [comment]
Hi @acere, the fix has been released in [v2.101.0](https://github.com/aws/sagemaker-python-sdk/releases/tag/v2.101.0). Please check if it works for you.
