### ISSUE TITLE
Support for Python 3.10 

### ISSUE THREAD

**Issue by mufaddal-rohawala** [aws/sagemaker-python-sdk#3226]
**Describe the feature you'd like**
Python 3.10 is [a currently supported version of Python ](https://devguide.python.org/versions/#versions). The issue is to track Python 3.10 support for the package `sagemaker-python-sdk`.

**How would this feature be used? Please describe.**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by martinRenou** [comment]
Closing as fixed by https://github.com/aws/sagemaker-python-sdk/pull/3327
