### ISSUE TITLE
Model monitor job intermittently fails

### ISSUE THREAD

**Issue by arvgram** [aws/sagemaker-python-sdk#3233]
When monitoring an endpoint that is utilizing a decision tree model on Iris dataset the monitor sometimes executes a monitor job successfully, sometimes it crashes with the exit message:
`Command 'bin/spark-submit --master yarn --deploy-mode client --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.serializer=org.apache.spark.serializer.KryoSerializer /opt/amazon/sagemaker-data-analyzer-1.0-jar-with-dependencies.jar --analytics_input /tmp/spark_job_config.json' died with <Signals.SIGKILL: 9>`. 

**To reproduce**
-  Upload a model to an endpoint:
```
# Create a model object from the pretrained model. 

model_uri = string with the uri for the s3 bucket where model i stored. 
model_name = f"my-decision-tree-model"

model = SKLearnModel(model_data= model_uri,
                             role=role,
                             entry_point= "Scripts/serve.py",
                             framework_version="0.23-1")
print('Model name: ' + model_name)
```
The `serve`-function we are using is defined as:

```
%%writefile Scripts/serve.py

# The methods below are for model serving, which will be called by the SageMaker serving endpoint automatically:
#  model_fn()
#  input_fn()
#  predict_fn()
#  output_fn()

import os
import joblib
import json
import pandas as pd
import numpy as np
from io import StringIO 

"""
Deserialize fitted model
"""
def model_fn(model_dir):
    model = joblib.load(os.path.join(model_dir, "model.joblib"))
    return model

"""
input_fn
    request_body: The body of the request sent to the model.
    request_content_type: (string) specifies the format/variable type of the request
"""
def input_fn(request_body, request_content_type):
    if request_content_type == 'application/json':
        request_body = json.loads(request_body)
        inpVar = request_body['Input']
        return inpVar
    elif request_content_type == 'text/csv':
        df = pd.read_csv(StringIO(request_body),header=None)
        return df.values.tolist()
    else:
        raise ValueError("This model only supports text/csv or application/json input")
        
"""
predict_fn
    input_data: returned array from input_fn above
    model (sklearn model) returned model loaded from model_fn above
"""
def predict_fn(input_data, model):
    return model.predict(input_data)

"""
output_fn
    prediction: the returned value from predict_fn above
    content_type: the content type the endpoint expects to be returned. Ex: JSON, string
"""

def output_fn(prediction, content_type):
    if content_type == 'application/json':
        res = prediction.tolist()
        respJSON = {'Output': res}
        return respJSON
    elif content_type == 'text/csv':
        s = StringIO()
        np.savetxt(s, prediction, fmt='%d', delimiter=',', newline='\n')
        return s.getvalue()
    else:
        raise ValueError("This model only supports text/csv or application/json input") 

```
- Upload model to endpoint with endpoint data capture enabled:

```
endpoint_name = "model-endpoint" 
print("Endpoint name (endpoint_name) =", endpoint_name)

data_capture_config = DataCaptureConfig(
    enable_capture = True, 
    sampling_percentage = 100, 
    destination_s3_uri = endpoint_data_uri,
    csv_content_types = ['text/csv', 'text/html']
)

predictor = model.deploy(
    initial_instance_count=1,
    instance_type="ml.t2.medium",
    endpoint_name=endpoint_name,
    data_capture_config=data_capture_config,
)
```
-  Create a model monitor object and set an hourly schedule. 
```
my_model_monitor = DefaultModelMonitor(
    role=role,
    instance_count=1,
    instance_type="ml.t3.medium",
    volume_size_in_gb=20,
    max_runtime_in_seconds=1800,
    sagemaker_session=session,
)

mon_schedule_name = my_monitor_schedule

my_model_monitor.create_monitoring_schedule(
    monitor_schedule_name=mon_schedule_name,
    endpoint_input=endpoint_name,
    output_s3_uri = s3_report_path,
    statistics = statistics_uri, #we point at uploaded statistics in s3
    constraints = constraints_uri, #we point at uploaded constraints in s3
    schedule_cron_expression=CronExpressionGenerator.hourly(),
    enable_cloudwatch_metrics=True,
)

```
- Send some data to endpoint. I have made a loop that sends randomized input with features that are similar to the Iris dataset, mixed with input from the actual Iris dataset and see if it catches any drift etc. 

```
def invoke_csv_iris(output = False):
    import numpy as np
    
    content_type = "text/csv"
    
    sepal_length = 3 + np.random.rand()*5
    sepal_width = 2 + np.random.rand()*2
    petal_length = 1 + np.random.rand()*5
    petal_width = np.random.rand()*3

    random_iris_string = str(sepal_length) + "," + str(sepal_width) + "," + str(petal_length) + "," + str(petal_width)

    response = client.invoke_endpoint(
        EndpointName=endpoint_name, 
        ContentType=content_type,
        Accept=content_type,
        Body=random_iris_string)
    r = response['Body'].read().decode()
    if output:
        print(type(r))
        print(r)
```

```
content_type = "text/csv"
count = 0
stop_count = 7
with open("dataset_for_monitor.csv", "r") as csv_file:
    for row in csv_file:
        body = row[:-3]  # without the target
        if count%4 == 0: #send a random iris every fourth 
            invoke_csv_iris(output = False)
            count += 1
            if count > stop_count:
                break
        
        response = client.invoke_endpoint(
            EndpointName=endpoint_name, 
            ContentType=content_type,
            Accept=content_type,
            Body=body)
        time.sleep(1)
        count += 1
        if count > stop_count:
            break
    print(f'Processed {count} predictions.')
```

```
def inspect_monitor_executions(monitor_object):
    monitoring_executions = monitor_object.list_executions()
    print("The executions the monitor has made are: ")
    for execution in monitoring_executions:
        print(20*"-")
        print("Latest execution status: {}".format(execution.describe()["ProcessingJobStatus"]))
        print("Latest execution exit message: {}".format(execution.describe()["ExitMessage"]))
        print("Process start time: {}. ".format(execution.describe()["ProcessingStartTime"]))
        print("Process end time: {}. ".format(execution.describe()["ProcessingEndTime"]))
```

`inspect_monitor_executions(fresh_start_friday_parallel_monitor)`

- Sometimes this performs successful executions and sometimes it crashes. I have tried to send only "real" data from dataset or only "artificial" data from randomized loop, without being able to conclude the reason for the crash. I have also sent different  batch size of input data, and there might be a problem with larger requests. However, these are about 10 invocations per minute, which with the four feature data should not too much of a computational load. 

**Expected behavior**
I expect the monitor to complete a successful execution every time. It is weird that it is crashing some of the times and executing successfully some of the time. 

**Screenshots or logs**
The exit message for the crash is:
`Command 'bin/spark-submit --master yarn --deploy-mode client --conf spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider --conf spark.serializer=org.apache.spark.serializer.KryoSerializer /opt/amazon/sagemaker-data-analyzer-1.0-jar-with-dependencies.jar --analytics_input /tmp/spark_job_config.json' died with <Signals.SIGKILL: 9>.`

**System information**
A description of your system. Please provide:
- SageMaker Python SDK version: 2.98.0
- Framework name (eg. PyTorch) or algorithm (eg. KMeans): ScikitLearn decision tree
- Framework version:
- Python version 3.8.12. 
- CPU or GPU: CPU
- Custom Docker image (Y/N): No.

**Additional context**

**Comment by Aditya369nair** [comment]
+1, I an facing the exact same issue.  There is no indication on when and under what condition the model monitor job fails . I have triggered the same request and sometimes it runs  and other time it crashes 

Also is there a way to manually trigger the model monitor job. Currently the minimum schedule period is 1 hour which makes it really difficult to debug this

**Comment by staubhp** [comment]
I haven't had time to fully repro this yet, but one of the things that could cause the process to be killed like that is an out of memory exception. That might align with the intermittency of the failure; the job is succeeding or failing based on the amount of captured endpoint data.

Some questions:

* Do the executions pass when you stop sending test data to the endpoint?
* Do the executions start passing if you change the instance type to, say, `ml.t3.large`?

As for @Aditya369nair 's question, those monitoring executions are simply processing jobs using a SageMaker-provided container. You can run a one-off execution like this:

```
import sagemaker
from sagemaker.processing import Processor, ProcessingInput, ProcessingOutput
from sagemaker.model_monitor.model_monitoring import DefaultModelMonitor
from sagemaker import get_execution_role, session
from datetime import datetime

sm_session = sagemaker.Session()
role = get_execution_role()

endpoint_name = "my-endpoint-name"
monitoring_schedule_name = "my-monitoring-schedule-name"

# Variables below determine start and end time of captured data being analyzed
start_year="2022"
start_month="07"
start_day="29"
start_hour="18"

end_year="2022"
end_month="07"
end_day="29"
end_hour="19"

my_processor = Processor(
    role=role,
    image_uri=DefaultModelMonitor._get_default_image_uri(sm_session.boto_region_name),
    instance_count=1,
    instance_type="ml.m5.xlarge",
    base_job_name="OneOffModelMonitorRun",
    env={
        "baseline_constraints": "/opt/ml/processing/baseline/constraints/constraints.json",
        "baseline_statistics": "/opt/ml/processing/baseline/stats/statistics.json",
        "dataset_format": "{\"sagemakerCaptureJson\":{\"captureIndexNames\":[\"endpointInput\",\"endpointOutput\"]}}",
        "dataset_source": "/opt/ml/processing/input/endpoint",
        "end_time": f"{end_year}-{end_month}-{end_day}T{end_hour}:00:00Z",
        "metric_time": f"{start_year}-{start_month}-{start_day}T{start_hour}:00:00Z",
        "output_path": "/opt/ml/processing/output",
        "post_analytics_processor_script": "/opt/ml/processing/code/postprocessing/postprocessor.py",
        "publish_cloudwatch_metrics": "Enabled",
        "sagemaker_endpoint_name": endpoint_name,
        "sagemaker_monitoring_schedule_name": monitoring_schedule_name,
        "start_time": f"{start_year}-{start_month}-{start_day}T{start_hour}:00:00Z"
    }
)

my_processor.run(
    inputs=[
        # Statistics file:
        ProcessingInput(source="s3://my-bucket/statistics.json", destination="/opt/ml/processing/baseline/stats"),
        # Constraints file:
        ProcessingInput(source="s3://my-bucket/constraints.json", destination="/opt/ml/processing/baseline/constraints"),
        # Captured endpoint data:
        ProcessingInput(source=f"s3://my-bucket/datacapture/{endpoint_name}/AllTraffic/{start_year}/{start_month}/{start_day}/{start_hour}", destination=f"/opt/ml/processing/input/endpoint/{endpoint_name}/AllTraffic/{start_year}/{start_month}/{start_day}/{start_hour}"),
        # Post-processing script (if any):
        ProcessingInput(source="s3://my-bucket/postprocessor.py", destination="/opt/ml/processing/code/postprocessing"),

    ],
    outputs=[
        ProcessingOutput(output_name="results", source="/opt/ml/processing/output", s3_upload_mode="Continuous"),
    ]
)
```

This is admittedly complicated. Official SDK or backend support for one-off executions may appear sometime in the future.

**Comment by arvgram** [comment]
The suggestion with a larger instance works! 
Out of curiosity: how come we need a greater than medium instance type when the requests we are handling are for example 10 rows of four feature tabular data? It should not be more than a couple of hundred bytes? 
Thank you for the help!

**Comment by staubhp** [comment]
The monitoring job is going to download all of the captured endpoint data for the time period defined by your schedule (for example, an hourly schedule will download all of the JSON files under the `s3://my-dir/sagemaker/<MONITOR_NAME>/datacapture/<ENDPOINT_NAME>/AllTraffic/<YEAR>/<MONTH>/<DAY>/<HOUR>/` prefix) and load it into a data frame. That data could exceed the ml.t3.medium's 4GB of memory depending on how many inference requests happened during that time.

You can see what data was actually processed by describing the processing job associated with that monitoring execution and looking at its inputs and the checking that S3 location(s). It might be more data than you expect.

That being said, we could do a better job of catching this and returning a useful error message. Feel free to create a support ticket with a reference to this issue and the ARN of your monitoring schedule so we can look at platform logs.
