### ISSUE TITLE
ClientError: An error occurred (ValidationException) when calling the DescribeTrainingJob operation:

### ISSUE THREAD

**Issue by mondor** [aws/sagemaker-python-sdk#326]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow 1.8.0 
- **Python Version**: Python 3.6.4
- **CPU or GPU**: CPU
- **Python SDK Version**: sagemaker 1.4.1
- **Are you using a custom image**: no

### Describe the problem
Just recently we are getting this error when describe a training job we trained earlier:

Jupyter Notebook:
training_job_name = '5b458b8fbaf3d-2018-07-11-05-04-28-959'
import sagemaker 
session = sagemaker.Session()
job = session.sagemaker_client.describe_training_job(TrainingJobName=training_job_name)

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
<ipython-input-9-2d67521b9ae5> in <module>()
----> 1 job = session.sagemaker_client.describe_training_job(TrainingJobName=training_job_name)

~/.local/lib/python3.6/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    312                     "%s() only accepts keyword arguments." % py_operation_name)
    313             # The "self" in this scope is referring to the BaseClient.
--> 314             return self._make_api_call(operation_name, kwargs)
    315 
    316         _api_call.__name__ = str(py_operation_name)

~/.local/lib/python3.6/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    610             error_code = parsed_response.get("Error", {}).get("Code")
    611             error_class = self.exceptions.from_code(error_code)
--> 612             raise error_class(parsed_response, operation_name)
    613         else:
    614             return parsed_response

ClientError: An error occurred (ValidationException) when calling the DescribeTrainingJob operation: Requested resource not found.

**Comment by mondor** [comment]
you are right @icywang86rui, there was some issue with my AWS credential, thanks for you help.

**Comment by imranparuk** [comment]
I'm getting this error randomly
