### ISSUE TITLE
New line causes ValidationException (potential race condition)

### ISSUE THREAD

**Issue by l1x** [aws/sagemaker-python-sdk#3295]
**Describe the bug**

The following code results in an exception:

```python
fg = FeatureGroup(
    name="hello", sagemaker_session=feature_store_session
)
fg.put_record([
    FeatureValue('id', '2'),
    FeatureValue('data', 'test\n'),
    FeatureValue('EventTime', '0.0')
])
```

The exception:

```
ClientError: An error occurred (ValidationException) when calling the PutRecord operation: 1 validation error detected: Value 'test
' at 'record.2.member.valueAsString' failed to satisfy constraint: Member must satisfy regular expression pattern: .*
```

**To reproduce**

See above.

**Expected behavior**

Probably have an exception saying new line characters are not allowed instead of saying a regexp check failed.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.100.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: NA
- **Framework version**: NA
- **Python version**: 3.10.5
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by psnilesh** [comment]
Regular expression included the message itself is the key to debugging such errors. According to python [docs](https://docs.python.org/3/library/re.html),
```
(Dot.) In the default mode, this matches any character except a newline. 
```

Could you please elaborate on the race condition issue is referring to ?

**Comment by akrishna1995** [comment]
Closing this issue as per the above comment, Please feel free to reopen if you have any more feedback. Thank you
