### ISSUE TITLE
Runtime error when importing model

### ISSUE THREAD

**Issue by mitchell-reid** [aws/sagemaker-python-sdk#3298]
I am trying to import a model for use with torcheia. I am using the following code: 

```python
import torch

def model_fn():
    model = torch.jit.load("cos_1.5.1.pt", map_location=torch.device('cpu'))
    if torch.__version__ == '1.5.1':
        import torcheia
        model = model.eval()
        model = torcheia.jit.attach_eia(model, 0)
    
    return model

model = model_fn()
```

This is resulting in the following error: `RuntimeError: class '__torch__.torch.nn.modules.conv.___torch_mangle_1.Conv2d' already defined.`
Full traceback as follows:
```
Traceback (most recent call last):
  File "main.py", line 50, in <module>
    model = model_fn()
  File "main.py", line 15, in model_fn
    model = torcheia.jit.attach_eia(model, 0)
  File "/home/ubuntu/.pyenv/versions/eia-testing/lib/python3.6/site-packages/torcheia/jit/__init__.py", line 5, in attach_eia
    newobj = _torch_eia._tag_eia_device(obj._c, device)
RuntimeError: class '__torch__.torch.nn.modules.conv.___torch_mangle_1.Conv2d' already defined.
```

Since the error is occuring within the compiled files I have no way of investigating further.

**Comment by martinRenou** [comment]
Thank you for opening an issue. Have you find how to resolve this?

You may have better luck opening this issue in the pytorch repository. It seems similar issues are have been reported here https://github.com/pytorch/pytorch/issues/52363

**Comment by mohanasudhan** [comment]
@mitchell-reid  Thanks for reporting this issue. Please refer to Elastic Inference document for recommendation https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html

Q: We currently use Amazon Elastic Inference (EI) accelerators. Will we be able to continue using them after April 15, 2023?

Yes, you will be able use Amazon EI accelerators. We recommend that you migrate your current ML Inference workloads running on Amazon EI to other hardware accelerator options at your earliest convenience.

Recommend going over the migration steps https://docs.aws.amazon.com/sagemaker/latest/dg/ei.html#ei-migration

Please reopen the issue if you see any issue with migration.
