### ISSUE TITLE
Default channel name is "training" not "train"

### ISSUE THREAD

**Issue by laurencer** [aws/sagemaker-python-sdk#332]
### Describe the problem
The documentation for implementing an MXNet estimator says that the default channel if nothing is specified in the `.fit(s3_path)` call (e.g. `mxnet_estimator.fit('s3://foo/bar')`) will be named `train`. 

See https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/mxnet/README.rst#calling-fit

However when I actually ran it the default channel was passed in as `training` instead.

Either the documentation should be updated or the default behaviour changed.

### Minimal repro / logs
I created an `MXNetEstimator` and associated script that simply logged the parameters:

```python

def train(hyperparameters,
          input_data_config,
          channel_input_dirs,
          output_data_dir,
          num_gpus,
          num_cpus,
          hosts,
          current_host):
    print("input_data_config: {}".format(input_data_config))
    print("channel_input_dirs: {}".format(channel_input_dirs))

```

and got the following output:

```
input_data_config: {'training': {'RecordWrapperType': 'None', 'S3DistributionType': 'FullyReplicated', 'TrainingInputMode': 'File'}}
channel_input_dirs: {'training': '/opt/ml/input/data/training'}
```

when I called it with:

```python
from sagemaker.mxnet import MXNet

mxnet_estimator = MXNet("experiment.py",
                        role=role,
                        py_version='py3',
                        source_dir=os.path.dirname(os.path.abspath(__file__)),
                        train_instance_type="ml.c5.9xlarge",
                        train_instance_count=1)

mxnet_estimator.fit('s3://my_bucket/my_data/')
```

**Comment by icywang86rui** [comment]
Hi @laurencer,

The default channel name is 'training' - https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/job.py#L78

The documentation is incorrect. Thanks for pointing this out. I will update the document.

**Comment by icywang86rui** [comment]
Documentation fix is merged. Thanks again!
