### ISSUE TITLE
Increase shared memory for local mode

### ISSUE THREAD

**Issue by bengruher** [aws/sagemaker-python-sdk#3331]
Currently, SageMaker local mode for model training does not allow for adjusting `smh-size`. Defaults to 64MB which is not enough for most use cases. Does not allow for model to be trained on custom hardware using SageMaker SDK.

**Comment by yinweisu** [comment]
Encountered this problem and modified the source code to make it work...

Basically you'll want to add `'shm_size': 'Xgb',` to the `host_config` dict linked below
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/image.py#L741-L749

Will plan to send a PR later. But if you got this problem and you have access to the source code. ^^should do the trick.
