### ISSUE TITLE
Getting ImportError when trying to retrieve 'forecasting-deepar' image_uri

### ISSUE THREAD

**Issue by taimaruuu** [aws/sagemaker-python-sdk#3353]
I'm currently trying to use AWS DeepAR to forecast the settlement price for some electricity pricing. When I try to import the image_uris from sagemaker as indicated [here](https://docs.aws.amazon.com/sagemaker/latest/dg/ecr-us-west-1.html#forecasting-deepar-us-west-1.title) I am getting the following import error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-41-173bbea7895a> in <module>
----> 1 from sagemaker import image_uris
      2 # image_uris.retrieve(framework='forecasting-deepar',region='us-east-2')

/opt/conda/lib/python3.7/site-packages/sagemaker/image_uris.py in <module>
     25 from sagemaker.jumpstart import artifacts
     26 from sagemaker.workflow import is_pipeline_variable
---> 27 from sagemaker.workflow.utilities import override_pipeline_parameter_var
     28 
     29 logger = logging.getLogger(__name__)

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/utilities.py in <module>
     24 
     25 from sagemaker.workflow.parameters import Parameter
---> 26 from sagemaker.workflow.pipeline_context import _StepArguments
     27 from sagemaker.workflow.entities import (
     28     Entity,

/opt/conda/lib/python3.7/site-packages/sagemaker/workflow/pipeline_context.py in <module>
     19 from typing import Dict, Optional
     20 
---> 21 from sagemaker.session import Session, SessionSettings
     22 from sagemaker.local import LocalSession
     23 

ImportError: cannot import name 'SessionSettings' from 'sagemaker.session' (/opt/conda/lib/python3.7/site-packages/sagemaker/session.py)

To recreate this issue, simply run the following command:
`from sagemaker import image_uris
`

For reference I am using sagemaker 2.108.0

**Comment by martinRenou** [comment]
Thank you for opening an issue. Were you able to fix it? It seems you may have had a broken installation of sagemaker at this point. Trying to update it with `pip install sagemaker -U` or `conda install -c conda-forge sagemaker` could have fixed it?

**Comment by akrishna1995** [comment]
Thanks for bringing this issue to our attention. Please feel free to reopen if this issue still persists with the latest version following martin's comment.
