### ISSUE TITLE
OOM when resuming training from checkpoint

### ISSUE THREAD

**Issue by renziver** [aws/sagemaker-python-sdk#3357]
**Describe the bug**
I'm encountering an OOM error while using the Hugging Face Estimator API while following the [Spot Instance training sample](https://github.com/huggingface/notebooks/blob/main/sagemaker/05_spot_instances/sagemaker-notebook.ipynb) which basically needs a way to resume training from checkpoints. 

I have a script that uses the Trainer API that then gets to be passed on to the Hugging Face estimator for training on the SageMaker environment.

```
trainer = Trainer(
        model=model,
        args=train_args,
        data_collator=data_collator,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
    )
    if train_from_checkpoint:
        last_checkpoint = get_last_checkpoint(checkpoint_dir)
        trainer.train(resume_from_checkpoint=last_checkpoint)
    else:
        trainer.train()
```

I have confirmed that without using the Hugging Face estimator API, the training script that I use could be successfully completed. This led me to the following [issue](https://github.com/huggingface/transformers/issues/3730) on Hugging Face where it is reported that there has been a memory leak issue in Hugging Face for training that is resumed from checkpoints which spot instance training heavily relies on.

**Screenshots or logs**
<img width="541" alt="Screen Shot 2022-09-13 at 4 33 35 PM" src="https://user-images.githubusercontent.com/13497174/189854730-1399f405-b76f-4416-97a2-869e9f563ee3.png">

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.108.0
- **Pytorch version**: 1.10.2
- **Hugging Face version**: 4.17.0 (maximum supported of SageMaker Hugging Face estimator
- **Python version**: 3.8
- GPU: ml.p3.2xlarge (1 V100 GPU)

**Comment by akrishna1995** [comment]
Hi @renziver - can you please confirm if you are still facing this issue? from the issue you linked - HF team has put out the fix : https://github.com/huggingface/transformers/issues/22123

**Comment by akrishna1995** [comment]
Closing this issue for now, please feel free to reopen if the issue still persists
