### ISSUE TITLE
FrameworkProcessor does not use output_kms_key when uploading the code artifact

### ISSUE THREAD

**Issue by szamarin** [aws/sagemaker-python-sdk#3389]
The Framework processor creates an Estimator when uploading the code artifact (sourcedir.tar.gz) to S3. However when instantiating the estimator, the output_kms_key is not passed to the constructor ([code](https://github.com/aws/sagemaker-python-sdk/blob/342f2187010f191e15f5c66b93f5a7f0335b7120/src/sagemaker/processing.py#L1741))

```
    def _upload_payload(
        self,
        entry_point: str,
        source_dir: Optional[str],
        dependencies: Optional[List[str]],
        git_config: Optional[Dict[str, str]],
        job_name: str,
    ) -> "sagemaker.estimator.Framework":  # type: ignore[name-defined]   # noqa: F821
        """Upload payload sourcedir.tar.gz to S3."""
        # A new estimator instance is required, because each call to ScriptProcessor.run() can
        # use different codes.
        estimator = self._create_estimator(
            entry_point=entry_point,
            source_dir=source_dir,
            dependencies=dependencies,
            git_config=git_config,
        )

        estimator._prepare_for_training(job_name=job_name)
        logger.info(
            "Uploaded %s to %s",
            estimator.source_dir,
            estimator._hyperparameters["sagemaker_submit_directory"],
        )

        return estimator
```
If a customer has a bucket policy that requires a SSE with KMS, they are unable to use the Frameworkprocessor.

**Comment by knikure** [comment]
Closing this issue as #3784 fixed it.

**Comment by szamarin** [comment]
Don't see how is this related to #3784 as that is for the Model not FrameworkProcessor. This issue is still not fixed and should be reopened. The fix is[ here](https://github.com/aws/sagemaker-python-sdk/pull/3390/commits/0d35b2ad60ffdcc8282ff9b004041eb4d90b06e1)
