### ISSUE TITLE
How to install warpctc_pytorch module for sagemaker pytorch estimator

### ISSUE THREAD

**Issue by Harathi123** [aws/sagemaker-python-sdk#340]
### System Information
- **Framework**: pytorch
- **Python Version**: 3.6
- **CPU or GPU**: GPU
Using custom training and inference code

### Describe the problem
I have a pytorch model which uses 'warpctc_pytorch' module https://github.com/SeanNaren/warp-ctc. In my local server, I cloned the git repository and installed it and used. Now i want to customize that model to sagemaker and deploy it. 

How to install that dependency for pytorch estimator. When I searched for this, i found that we need to add all the required dependencies to a 'requirements.txt' file. But it is not pip installable. Any suggestions on how to install this...

Thanks in advance,
Harathi

**Comment by jesterhazy** [comment]
If you need to install a dependency that can't be installed using pip, the best bet is to create your own custom container. We've published examples of how to do this for [scikit]( https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own) and [tensorflow](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/tensorflow_bring_your_own).

**Comment by Harathi123** [comment]
Thanks @jesterhazy, any examples for how to create custom pytorch container...

Thanks,
Harathi
