### ISSUE TITLE
Regression in terms of handling the code_location attribute in SM Pipelines

### ISSUE THREAD

**Issue by navaj0** [aws/sagemaker-python-sdk#3413]
**Describe the bug**

It worked before, but now breaks my code. It worked at least until 2.100.0 and I was kinda hoping it would be fixed without intervention, but it does not work in 2.104.0, 2.109.0 and 2.110.0.

I used to provide a string that ended in a ‘/’, like `f's3://{pipeline_session.default_bucket()}/pipeline-code/' ` But this now results in the below error message when attempting to run a Batch Transform. Please recognize the ‘//’ in the key.

```
ClientError: Failed to download model data(bucket: sagemaker-eu-west-1-426334991426, key: pipeline-code//pytorch-inference-2022-10-12-14-48-22-161/pipelines-otzuzj9grt59-lr-bow-RepackModel-0-bVEhzyl7Ih/output/model.tar.gz). NoSuchKey (HTTP StatusCode: 404)
```

aws s3 ls would still see the model tarball, but not the Batch Transform. Removing the slash from the code location “works” (as in does not create an error message), but then I have no separation between the pipeline prefix and the artifact name, e.g. `pipeline-codepytorchinference ...`

**To reproduce**

Example:

```
teacher_model = PyTorchModel(
    model_data=teacher_training_step.properties.ModelArtifacts.S3ModelArtifacts,
    **common_attributes,
    code_location=f's3://{pipeline_session.default_bucket()}/pipeline-code/',
    source_dir='.',
    entry_point='inference.py',
) 
```
In the first training job config in the pipeline json dump, you will find:
```
'OutputDataConfig': {'S3OutputPath': 's3://sagemaker-eu-west-1-426334991426/pipeline-code//pytorch-inference-2022-10-12-16-00-45-984'},
```

**Expected behavior**

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by marianokamp** [comment]
I tried with 2.115.0 and it works great now. Thanks a lot!
