### ISSUE TITLE
Accept pipeline parameters as estimator/processor roles

### ISSUE THREAD

**Issue by navaj0** [aws/sagemaker-python-sdk#3414]
**Describe the feature you'd like**

Accept pipeline parameters as estimator/processor roles

According to the SDK API doc, the role can’t be assigned to a pipeline parameter.
* image_uri ([str](https://docs.python.org/3/library/stdtypes.html#str) or [PipelineVariable](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.entities.PipelineVariable)) – The container image to use for training.
* role ([str](https://docs.python.org/3/library/stdtypes.html#str)) – An AWS IAM role (either name or full ARN). The Amazon SageMaker training jobs and APIs that create Amazon SageMaker endpoints use this role to access training data and model artifacts. After the endpoint is created, the inference code might use the IAM role, if it needs to access an AWS resource.
* instance_count ([int](https://docs.python.org/3/library/functions.html#int) or [PipelineVariable](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.entities.PipelineVariable)) – Number of Amazon EC2 instances to use for training. Required if instance_groups is not set.

The SDK must be doing some compile time verification over the role (existence etc.) that prevents it from accepting a pipeline parameter.

**How would this feature be used? Please describe.**

Some users are interested to use SageMaker pipelines for a multi-tenant application. As part of their solution they want to execute a SageMaker pipeline estimator for every tenant with a dedicated IAM role (i.e., the estimator only has access to a tenant-dedicated S3 bucket). 

**Describe alternatives you've considered**

**Additional context**

**Comment by ivannotes** [comment]
+1 to that request.

I have similar requirement. when I dump the pipeline definition, the estimator will always [expand the role](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/job.py#L70-L72), in the case a role is a pipeline parameter it will raise error. 

It will be great if the estimator can accept role as a pipeline parameter.

**Comment by qidewenwhen** [comment]
Thanks so much for @francescoalongi to work on https://github.com/aws/sagemaker-python-sdk/pull/3605 to fill in the gap on Processor regarding parameterized role

**Comment by ShwetaSingh801** [comment]
Hi @navaj0, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
