### ISSUE TITLE
SSH into a SageMaker instance for debugging purposes

### ISSUE THREAD

**Issue by mklissa** [aws/sagemaker-python-sdk#344]
I am trying to connect to a SageMaker instance through SSH with my local machine, but I cannot find a way to do it. This seems like an important functionnality, either for debugging (through PyCharm) or for uploading files with SCP. I am wondering if there is any way to do this?

**Comment by jesterhazy** [comment]
SageMaker doesn't support SSH access to running jobs or endpoints. There are a couple of ways to get files into your instances:

- add the files to the set of input data you specify when you launch your job (or add to model files for a hosting endpoint)
- modify your training (or inference) code to download the files when your code is run.

There's currently no way to do remote debugging of a training job. You might be able to do this by using a [customized container](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/scikit_bring_your_own/scikit_bring_your_own.ipynb) to run your job in [local mode](https://github.com/aws/sagemaker-python-sdk#local-mode).

**Comment by yonatanp** [comment]
If you have another instance that you can ssh into from both the instance and your local machine, then you can tunnel through and achieve ssh access. I'm using this for the same purpose of SCPing stuff in and out.

For example, assuming "bastion" is the additional middle instance:
```
# run this command from within a terminal on your notebook instance (New -> Terminal), pushes port 22 to bastion's locally accessible port 10022
sh-4.2$ ssh user@bastion -R 10022:localhost:22 -f -N

# run this command from you local machine, pulls port 10022 of the bastion to local machine port 10022
[you@yourmachine]$ ssh user@bastion -L 10022:localhost:10022 -f -N

# now you can ssh or scp as you'd like, using the localhost port 10022 as the target
[you@yourmachine]$ ssh localhost -p 10022 -l ec2-user
```

You'll of course have to take care of authentication in the right directions (e.g. create private keys and add to authorized_keys as applicable).

**Comment by elgalu** [comment]
Are you planning to implement this feature? how?

You could add a new IAM Allow Statement `sagemaker:CreateSSHTraining` that would permit ssh by using a new configuration option, e.g.

```
tf_estimator.fit(inputs=input, ssh_pub_key='~/.ssh/id_rsa.pub')
```

The `sagemaker` locally installed cli will take care of uploading the ssh public key by using current user's AWS credentials.

Then SageMaker should create proxy/endpoint that is automatically firewalled to the source IP from which the training was launched (e.g. current laptop). This endpoint (random sub-domain) purpose is only to expose port 22 (or other random port) for the current user.

It would finally print the randomly generated ssh endpoint into stdout so the user can copy paste to ssh into the training instance. The training instance could automatically pause before shutting down to give the user time to ssh into it but this can be made configurable, most likely the user will use the Python debugger to put a breakpoint anyways.

The link would expire once the user shuts down the training instance.

Perhaps this feature is worth a new resource type, instead of polluting the `Trainings` SM resource it would create a `SSHTrainings` resource.

**Comment by kot-behemoth** [comment]
@mklissa I know this is quite late, but it looks like AWS has thought about your particular use case: [Tutorial: Set Up PyCharm Professional with a Development Endpoint](https://docs.aws.amazon.com/glue/latest/dg/dev-endpoint-tutorial-pycharm.html). It looks like it only supports Py2.7 though.

**Comment by mariokostelac** [comment]
AWS does not natively support SSH-ing into SageMaker notebook instances, but nothing really prevents you from setting up SSH yourself.

The only problem is that these instances do not get a public IP address, which means you have to either create a reverse proxy (with ngrok for example) or connect to it via bastion box.

I've written about both solutions on https://biasandvariance.com/sagemaker-ssh-setup/. It's not that complicated, you can get it set up in 4min, but I definitely suggest giving it a read to understand what you're doing.

**Comment by daysm** [comment]
Thank you @mariokostelac! I used the most recent ngrok and needed to change two things:
- Change the command to `/ngrok authtoken <AUTHTOKEN>`.
- Keep ngrok in the foreground (writing to a log file did not work)

**Comment by elgalu** [comment]
This can also be solved via https://docs.aws.amazon.com/systems-manager/latest/userguide/managed_instances.html by setting the SageMaker machine as it if where an on-prem computer that AWS SSM can manage and then one can ssh/scp/tunnel into it.

**Comment by hanan-vian** [comment]
> This can also be solved via https://docs.aws.amazon.com/systems-manager/latest/userguide/managed_instances.html by setting the SageMaker machine as it if where an on-prem computer that AWS SSM can manage and then one can ssh/scp/tunnel into it.
> 
> ```
> laptop> $ aws ssm start-session --region=eu-central-1 --target i-083ee1e47a95416c3
> 
> Starting session with SessionId: lgallucci-0d662d7d50462b043
> 
> ec2> $ nvidia-smi
> Thu Nov 19 08:58:45 2020       
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Tesla M60           On   | 00000000:00:1E.0 Off |                    0 |
> | N/A   34C    P8    14W / 150W |      0MiB /  7618MiB |      0%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |  No running processes found                                                 |
> +-----------------------------------------------------------------------------+
> ```

How do I know my SageMaker Studio notebook target id?

**Comment by mariokostelac** [comment]
> This can also be solved via https://docs.aws.amazon.com/systems-manager/latest/userguide/managed_instances.html by setting the SageMaker machine as it if where an on-prem computer that AWS SSM can manage and then one can ssh/scp/tunnel into it.

This is great, thanks a lot for that information. I'll try to set it up soon. Do you know by any chance whether enabling SSH through SSM is something convoluted?

**Comment by elgalu** [comment]
@hanan-vian SM doesn't give you any target id, you have to do everything yourself as if it were some computer box in your basement (sort to say). It would be great if the SageMaker team realizes the potential of this use case and does the integration automatically, some day maybe.

**Comment by philschmid** [comment]
@elgalu if I understand you correctly I have to start en ec2 instance with a Deep Learning-AMI? 
I cannot use this together with `Estimator.fit()` using the `sdk`?

**Comment by elgalu** [comment]
@philschmid we are discussing SSH access in SageMaker Studio/Notebooks in this thread. With EC2 you can already ssh, it's solved there.

**Comment by moon-home** [comment]
I am using SM with custom Docker image, not prebuilt AMI, not notebook. I didn't find the instance id on the training job page. Did you find the instance id? @philschmid @elgalu

**Comment by ruslanmv** [comment]
I've found not being able to SSH to notebook instances too limiting so I've built a guide to set it up by using the bastion box.
[https://ruslanmv.com/blog/How-to-connect-to-Sagemaker-Notebook-via-SSH ](https://ruslanmv.com/blog/How-to-connect-to-Sagemaker-Notebook-via-SSH )
I hope this can be helpful.

**Comment by ivan-khvostishkov** [comment]
I know this thread is quite old, but developers keep bumping into this discussion when searching for SageMaker and SSH. 

Now there's an AWS repo with sample scripts to automate the SSH setup:
https://github.com/aws-samples/sagemaker-ssh-helper .

It uses managed instances capability of AWS Systems Manager (SSM), as suggested earlier by @elgalu .

As a result, the solution is secure, serverless, and supports not only connection into running jobs and endpoints with SSH/SSM, but also into SageMaker Studio containers, and allows integration with PyCharm and VSCode.

**Comment by julien-c** [comment]
really cool @ivan-khvostishkov, that's very helpful

**Comment by harrypawar** [comment]
For SageMaker inference endpoints you could now use SSM to get shell level access to the container https://docs.aws.amazon.com/sagemaker/latest/dg/ssm-access.html

**Comment by charleschenzc1** [comment]
https://docs.aws.amazon.com/sagemaker/latest/dg/ssm-access.html
Native solution seems available now.

**Comment by charleschenzc1** [comment]
There is a native solution by AWS SageMaker now https://docs.aws.amazon.com/sagemaker/latest/dg/train-remote-debugging.html
