### ISSUE TITLE
Serverless inference to be able to set idle time duration before tear down resources

### ISSUE THREAD

**Issue by rodrigofp-possiblefinance** [aws/sagemaker-python-sdk#3446]
**Describe the feature you'd like**
Currently serverless inference suffers from the known cold start problem, which can take up to some minutes to leverage resources. Thus the first requests usually take longer than expected. I perceived that whenever the instance enters in idle state for just a couple of seconds it tears down the resources. 
It would be nice to have way to configure the idle duration for an endpoint before tearing down resources.

**How would this feature be used? Please describe.**
A parameter at `CreateEndpointConfig.ProductionVariants.ServerlessConfig` to set the idle duration before tearing down resources.

**Describe alternatives you've considered**
An alternative would be a service to trigger dummy requests just to keep the endpoint alive for a bit longer.

**Additional context**
None

**Comment by tomaszdudek7** [comment]
While this feature would be nice, I think it will be denied.

In AWS Lambda you cannot control this behavior. AWS doesn't even tell you "how much time Lambda will be kept alive". People have seen that most Lambda containers die after ~5 minutes of inactivity, but that's not deterministic. Some die earlier, some later.

AWS probably has some kind of a "death timer" that resets whenever a given Lambda container gets an invocation and draws a number from Gaussian distribution `N(5, 0.5)`. 😄
