### ISSUE TITLE
Add support for Transformers v4.24.0 DLC

### ISSUE THREAD

**Issue by wildgeece96** [aws/sagemaker-python-sdk#3456]
**Describe the feature you'd like**
A clear and concise description of the functionality you want.

Add support for Transformers v4.24.  
https://github.com/huggingface/transformers/releases/tag/v4.24.0

**How would this feature be used? Please describe.**
A clear and concise description of the use case for this feature. Please provide an example, if possible.

Now SageMaker Python SDK supports HuggingFace Transformers v4.17 by this Pull Request.  
- https://github.com/aws/sagemaker-python-sdk/pull/3027/files  

Recently, we can use epoch-making models on Transformers such as whisper, ESMFold which cannot be used on v4.17.

**Describe alternatives you've considered**

Build and share the docker images for Transformers v4.24 on SageMaker like following pull request.
- https://github.com/aws/sagemaker-python-sdk/pull/3027/files

**Additional context**

**Comment by pirtlj** [comment]
Is there any progress on this?  In the last month alone there are several new powerful models that require v4.24

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
