### ISSUE TITLE
Allow json_path in JsonGet to take a Parameter as input

### ISSUE THREAD

**Issue by superlaut** [aws/sagemaker-python-sdk#3463]
**Describe the feature you'd like**
json_path in JsonGet must now be a string. Allow for it to be dynamic through a Pipeline Parameter (ParameterString).

**How would this feature be used? Please describe.**
I want to be able to dynamically configure the reference metric for a ConditionStep before a ModelStep. For this you use left=JsonGet(step_name=..., property_file=evaluation_report, **json_path=**). This json_path must be a string, else you obtain an "Exception: Object of type ParameterString is not JSON serializable".

**Describe alternatives you've considered**
Passing as an argument to the create_pipeline.py script works, but it is a string, not a pipeline parameter then.

**Comment by ShwetaSingh801** [comment]
Hi @superlaut,  

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
