### ISSUE TITLE
Support Neuron SDK model cache for Trainium training jobs

### ISSUE THREAD

**Issue by juliensimon** [aws/sagemaker-python-sdk#3481]
The Neuron SDK compiles models for the Trainium accelerator. The compiled model is then stored in a disk cache, which saves time for further training jobs.

With SageMaker, the model is recompiled every time, as the model cache is stored inside the training container and lost across jobs. It'd be great to be able to automatically save the model cache to an S3 bucket, in order to pass it to the Estimator for the next training job.

I guess this is doable today by adding bespoke code in the training script, but a built-in feature would be nicer.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
