### ISSUE TITLE
Extract Container ID when Using SageMaker Local Mode with ProcessingScript

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3488]
**Describe the feature you'd like**
We integrate SageMaker local mode on our ProcessingScripts into the project test suite. Now after the test suite finished to run in the local machine, the machine is left with all the steps containers of the pipeline object. 

**How would this feature be used? Please describe.**
After a test had finished execution successfully, we want a way to either extract the container id that was just used or that the SageMaker session itself will know to remove the used container by request (an API call).

**Describe alternatives you've considered**
Today we search for the docker compose file and extract the container id by the file name like this:
```python
Path(self.sagemaker_session.sagemaker_client._processing_jobs[step.processor.jobs[-1].describe()['ProcessingJobName']].container.container_root).stem
```

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
