### ISSUE TITLE
Accessing LambdaStep output

### ISSUE THREAD

**Issue by khalidbourhaba** [aws/sagemaker-python-sdk#3499]
**Describe the bug**

Following the [docs](https://github.com/aws/sagemaker-python-sdk/blob/v2.116.0/doc/amazon_sagemaker_model_building_pipeline.rst#lambdastep), I can't access LambdaStep output using :
`step_lambda.OutputParameters["model_arn"]`

I'm getting this error : 

`AttributeError: 'LambdaStep' object has no attribute 'OutputParameters'`

**To reproduce**
 Below my code : 
```
from sagemaker.workflow.lambda_step import (
    LambdaStep,
    LambdaOutput,
    LambdaOutputTypeEnum,
)
from sagemaker.lambda_helper import Lambda
from sagemaker.workflow.pipeline_context import PipelineSession

model_arn = LambdaOutput(output_name="model_arn", output_type=LambdaOutputTypeEnum.String)

step_lambda = LambdaStep(
    name="LambdaStepgGetLastModel",
    lambda_func=Lambda(
        function_arn="xx",
        session=PipelineSession()),
    inputs={
        "model_package_group": "xxx"
    },
    outputs=[model_arn],
)

step_lambda.OutputParameters["model_arn"]
```

**Expected behavior**
Return the output of lambda

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.118.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by jerrypeng7773** [comment]
thanks for catching this, the correct usage is

```
step_lambda.properties.Outputs["model_arn"]
```

we will update the doc.

**Comment by jerrypeng7773** [comment]
doc fix: https://github.com/aws/sagemaker-python-sdk/pull/3553
