### ISSUE TITLE
Allow user to specify default vpc_config, encryption, tag settings at the session level and apply these to any session call where not otherwise specified

### ISSUE THREAD

**Issue by apriceaws** [aws/sagemaker-python-sdk#3512]
**Describe the feature you'd like**
Allow user to specify default vpc_config, encryption, tag settings at the session level and apply these to any session call where not otherwise specified

**How would this feature be used? Please describe.**
Some compliance-minded organizations enforce specification of vpc_config, encrypt_inter_container_traffic, and certain tags through IAM policy. These currently need to be specified separately for every session call. If these parameters are not properly specified on each call, the user receives an opaque access denied error. The user should be able to specify these parameters as session defaults, which would be applied for any session call where they are not otherwise specified.

**Describe alternatives you've considered**
Alternative is the current approach of individually specifying these parameters for every session call. This is an unnecessary burden on the user.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
