### ISSUE TITLE
Support PyYAML 6

### ISSUE THREAD

**Issue by lukehsiao** [aws/sagemaker-python-sdk#3526]
**Describe the feature you'd like**

Support for docker-compose v2, and, consequently, PyYAML 6.

AFAIK, the current docker-compose requirement: https://github.com/aws/sagemaker-python-sdk/blob/fadc817c7557f5fea5e414d51b500a6b7cd02065/requirements/extras/local_requirements.txt#L2

is only here to ensure the tool is installed for calling via CLI. 

**How would this feature be used? Please describe.**

Sagemaker is a helpful python library, but when installed with the `local` extra, it imposes a PyYAML 5.4.1 requirement. Given PyYAML is such a popular library, and PyYAML 6 is commonly used, this frequently causes dependency conflicts.

**Describe alternatives you've considered**

Sagemaker could continue to use the deprecated, end-of-life docker-compose v1 Python package if they loosened their PyYAML requirement. But, since it's end-of-life, they will not be making changes and do not seem interested in doing so: https://github.com/docker/compose/issues/9114

**Comment by claytonparnell** [comment]
We've loosened requirements for PyYAML and removed docker-compose. docker-compose v2 will have to be installed separately, as pip install isn't supported.
