### ISSUE TITLE
Pinned packaging in v2.121.2 #3514 renders sagemaker uninstallable with other dependencies

### ISSUE THREAD

**Issue by jmahlik** [aws/sagemaker-python-sdk#3531]
**Describe the bug**

It looks like #3514 attempted to address packaging changing some exceptions in recent versions. `packaging` was also pinned in this PR to `packaging==20.9` in the `setup.py`. Packaging is quite a widely used dependency, so pinning it is making upgrading sagmaker not possible.

packaging 20.9 was released in January 2021, so many other dependencies are requiring a more recent version.

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

```
python -m pip install  'sagemaker>=2.121.1' 'statsmodels>=0.13.5'
...

The conflict is caused by:
    sagemaker 2.121.1 depends on packaging==20.9
    statsmodels 0.13.5 depends on packaging>=21.3
```

**Expected behavior**

Sagemaker is installable with other dependencies. `packaging` should ideally be un-pinned and the exceptions adjusted to account for newer versions. Potentially require at least a recent version of packaging? Maybe `>=22.0`. 

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.121.2, 2.121.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: n/a
- **Framework version**: n/a
- **Python version**: 3.11, 3.10, 3.9, 3.8
- **CPU or GPU**: n/a
- **Custom Docker image (Y/N)**: N

**Additional context**

**Comment by claytonparnell** [comment]
Fix is included in the most recent release [2.122.0](https://pypi.org/project/sagemaker/2.122.0/)
