### ISSUE TITLE
Add multi select list as parameter to Sagemaker's pipeline object 

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3548]
**Describe the feature you'd like**
We want that Sagemaker's pipeline object parameters' UI will be able to retrieve not just a scalar but also a list. 

**How would this feature be used? Please describe.**
Sagemaker's HyperparameterTuner Grid search strategy is receiving the search space as a categorical range of discrete values. The discrete values should be a Sagemaker's pipeline object parameter in its own right and not a bunch of parameters that were sent together. As of it a multi select list should be added as parameter to Sagemaker's pipeline object.

**Additional context**
[See this AWS blog post as reference](https://aws.amazon.com/blogs/machine-learning/amazon-sagemaker-automatic-model-tuning-now-supports-grid-search/)

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
