### ISSUE TITLE
Add range radio button as parameter to Sagemaker's pipeline object

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3549]
**Describe the feature you'd like**
We want that Sagemaker's pipeline object parameters' UI will be able to retrieve not just a scalar but also tuple of two number that represent max and min values.

**How would this feature be used? Please describe.**
As we sent to tuning jobs parameters to build range from, we provide min and max value. For example:
```python
hyperparameter_ranges = {
        "learningWindow__windowsize": IntegerParameter(1, 15)
}

tuner = HyperparameterTuner(
        estimator=estimator,
        objective_metric_name=objective_metric_name,
        metric_definitions=metric_definitions,
        objective_type="Maximize",
        hyperparameter_ranges=hyperparameter_ranges,
        strategy=search_type,
        max_jobs=search_iterations,
        max_parallel_jobs=n_jobs
    )
```
In order to enforce the user to select min and max from a certain range, and that the UI will enforce it even before the pipeline had start execution, we need a range radio button as this:
![image](https://user-images.githubusercontent.com/14873156/208291761-2d64e9e0-e378-49c3-ab8f-fe685c387cb4.png)
With the ability to choose what is the size of the step between values inside the range.

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
