### ISSUE TITLE
Add the ability to control a start point and an end point steps for Sagemaker's pipeline object

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3550]
**Describe the feature you'd like**
Research requires us to be flexible, and thus some situation will require us to run only certain steps in order to check hypnosis. 

**How would this feature be used? Please describe.**
We need the ability to choose step name as start point and a step name as end point for pipeline execution in the Sagemaker's pipeline object parameters' UI.

**Describe alternatives you've considered**
Today we change to the code and remove steps manually for an experiment.

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
