### ISSUE TITLE
Covert job_arguments of a processing step into string at the execution phase and not upsert phase of Sagemaker's pipeline object

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3551]
**Describe the feature you'd like**
As of today, most of our Sagemaker's pipeline object's parameters are ```StringParameter``` as other passed parameters into a processing step are convert to string when updating the pipeline object and thus the container getting a string representation of parameter object and not the value.

**How would this feature be used? Please describe.**
You'll be able to use any parameter from the package ```sagemaker.workflow.parameters``` as a value to an argument in job_arguments for processing step, and not just ```StringParameter```. The conversion of a parameter to string will be at the execution of the Sagemaker's pipeline, and thus the parameter will have value to be converted to.

**Describe alternatives you've considered**
We switched all of the parameters that go to a processing step to be ```StringParameter```.

**Comment by qidewenwhen** [comment]
Hi @idanmoradarthas, thanks for reaching out!

To make sure we get your request correctly: you hope to make the `job_arguments` in ProcessingStep (legacy usage)  **to support all Parameters types, e.g. `ParameterFloat`, `ParameterInteger` etc**. Though the Processing job requires the job arguments to be string type, you recommend to do the type casting during pipeline execution time. Am I correct?

Note: the `job_arguments` in legacy step usage corresponds to `arguments` in Processor in the new usage - i.e. passing args generated by `processor.run` directly to `ProcessingStep` under `PipelineSession`. See: https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html#processingstep

**Comment by idanmoradarthas** [comment]
Hi @qidewenwhen,
Thanks for responding.
I have talked on this subject with Abi (product manager in sagemaker) on 06-16-22.

What happens is that most of the sagemaker parameters are going insider our processor, and because not all the parameter types are supported, we have about 99% of our parameters as string and the UI does not enforce for us that parameters such as booting iterations should be integer and we need to do it in the step code.

Here is a generic step that we have, that we showed Abi:
![image](https://user-images.githubusercontent.com/14873156/209462471-698f0328-3574-4553-9cd5-05b719446e16.png)

About the legacy note, as I see in the documentation processing step is getting job_arguments: https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.steps.ProcessingStep

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta

**Comment by AdrianB-sovo** [comment]
Hi, it would be nice to document that `job_arguments` is legacy, at least in the docstring of `ProcessingStep`...
It's not nice to have something that don't work and learn here that it's supposed to be legacy.
