### ISSUE TITLE
Allow uploading custom, browsable charts to SageMaker Experiments

### ISSUE THREAD

**Issue by tomaszdudek7** [aws/sagemaker-python-sdk#3552]
**Describe the feature you'd like**
Freshly overhauled SageMaker Experiments only allow you to:
- `log_confusion_matrix`
- `log_roc_curve`
- `log_precision_recall`
- `log_metric`

which all generate some kind of browsable chart. However, there's no way to create a custom plot or to customize existing ones.

It would be great to allow us to upload **custom charts that would be displayed directly in the Experiments UI**. Plotly, png, matplotlib - literally anything.

**How would this feature be used? Please describe.**
`log_confusion_matrix`, `log_roc_curve`, `log_precision_recall` are too specific and `log_metric` is too inflexible (line chart only). You cannot plot a bar chart, a scatterplot or a histogram.

**Describe alternatives you've considered**
MLflow, Weights&Biases, Neptune.ai, ...

**Comment by dsradecki** [comment]
This would be greatly appreciated by our team since the lack of this feature is currently blocking us from moving to SageMaker Experiment Tracking. Currently, we produce an html file with custom plots and some of them cannot be expressed by the Experiments' features.

**Comment by Drwhit** [comment]
We also need this functionality to help us move from mlflow to sagemaker.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
