### ISSUE TITLE
TransformStep transforms files it should not

### ISSUE THREAD

**Issue by HarryPommier** [aws/sagemaker-python-sdk#3557]
**Describe the bug**
When using the output of a processing step as input to a transformation step (`step_process.properties.ProcessingOutputConfig.Outputs["test"].S3Output.S3Uri`), the transformation step transforms files from directories at the same level as the input directory (`test_small_sample_with_info`). It should not.

**To reproduce**
```
[...]
step_process_args = pyspark_processor.run(
    submit_app="source/preprocess.py",
    submit_py_files=["source/preprocess_utils.py",
                     "source/spark_utils.py"],
    outputs=[
        ProcessingOutput(
            output_name="train",
            source="/opt/ml/processing/output/train",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "train"]),
        ),
        ProcessingOutput(
            output_name="validation",
            source="/opt/ml/processing/output/validation",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "validation"]),
        ),
        ProcessingOutput(
            output_name="test",
            source="/opt/ml/processing/output/test",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "test"]),
        ),
        ProcessingOutput(
            output_name="test_small_sample",
            source="/opt/ml/processing/output/test_small_sample",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "test_small_sample"]),
        ),
        ProcessingOutput(
            output_name="train_with_info",
            source="/opt/ml/processing/output/train_with_info",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "train_with_info"]),
        ),
        ProcessingOutput(
            output_name="validation_with_info",
            source="/opt/ml/processing/output/validation_with_info",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "validation_with_info"]),
        ),
        ProcessingOutput(
            output_name="test_with_info",
            source="/opt/ml/processing/output/test_with_info",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "test_with_info"]),
        ),
        ProcessingOutput(
            output_name="test_small_sample_with_info",
            source="/opt/ml/processing/output/test_small_sample_with_info",
            destination=Join(on="/", values=[s3_training_pipeline_preprocess_output_path, "test_small_sample_with_info"]),
        ),
    ],
    arguments=[
        "--aws_account",
        aws_account,
        "--aws_env",
        aws_env,
        "--project_name",
        project_name,
        "--mode",
        "training",
    ],
)

step_process = ProcessingStep(
    name="PySparkPreprocessing", step_args=step_process_args,

[...]

transformer = Transformer(
    model_name=model_step.properties.ModelName,
    instance_count=transformer_instance_count,
    instance_type=transformer_instance_type,
    strategy="MultiRecord",
    assemble_with="Line",
    output_path=s3_training_pipeline_transform_output_path,
    accept="text/csv",
    max_concurrent_transforms=max_concurrent_transforms,
    max_payload=max_payload,
    sagemaker_session=pipeline_session,
    base_transform_job_name=[MASKED],
)

step_transform = TransformStep(
    name=[MASKED],
    transformer=transformer,
    inputs=TransformInput(
        data=step_process.properties.ProcessingOutputConfig.Outputs["test"].S3Output.S3Uri,
        content_type="text/csv",
        split_type="Line",
        input_filter="$[1:]",
    ),
    depends_on=[model_step],
    cache_config=cache_config,
)
```

**Expected behavior**
Transform only the csv file in the test dir.

**Screenshots or logs**
![image](https://user-images.githubusercontent.com/50177956/209127179-eebede85-76b3-499e-8ad1-501f161567c8.png)

`test_small_sample_with_info` should not be transformed.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.125.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**: 3.9.12
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Y

**Additional context**
A workaround consists in specifying the URI to the csv file like this :
`inputs=TransformInput(
        data=Join(
            on="/",
            values=[step_process.properties.ProcessingOutputConfig.Outputs["test"].S3Output.S3Uri, "data.csv"],
        ),
[...]
`
But it is not the way proposed in this example : [sagemaker-pipeline-model-monitor-clarify-steps](https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-pipelines/tabular/model-monitor-clarify-pipelines/sagemaker-pipeline-model-monitor-clarify-steps.ipynb)

**Comment by qidewenwhen** [comment]
Hi @HarryPommier, thanks for reaching out!

I've tired to reproduce with the supplied info but I'm NOT able to reproduce it.
Could you help to provide the following info to help us on further investigation? Thanks!
1. The TransformJob input data configuration displayed in the console:
  - The TransformStep would create a TransformJob, which will be surfaced to the AWS SageMaker console. 
  You'll be able to retrieve its input data by: 1) Log in to AWS SageMaker console -> 2) Click on the "Inference" drop down in the left panel -> 3) Click on the "Batch transform jobs" -> 4) Select the specific transform job -> 5) Check the "S3 URI" field in "Input data configuration" section
    - e.g. in my test case, it's displaying `s3://sagemaker-us-west-2-xxxx/.../.../test`, which is as expected and `test_small_sample_with_info` is not included.
2. [Optional] The `source/preprocess.py` and its dependent util files if possible.
  - This would help us to better reproduce the contents in `test_small_sample_with_info`

**Comment by qidewenwhen** [comment]
Closing this issue as no response received for over 3 months. Feel free to reopen if you have further questions. Thanks!

**Comment by zhenliu2012** [comment]
I'm experiencing the same issue: I follow the official aws examples: 
https://github.com/aws/amazon-sagemaker-examples/blob/main/sagemaker-pipelines/tabular/model-monitor-clarify-pipelines/sagemaker-pipeline-model-monitor-clarify-steps.ipynb
In the process step, it splits data into 3 files: train.csv, test.csv and validation.csv
In the transform step, it sets the transform input data to be 
`step_process.properties.ProcessingOutputConfig.Outputs["test"].S3Output.S3Uri`, which means it only needs to transform the test data. however, it performs the transform job on all 3 files (train.csv, test.csv and validation.csv) in the same folder and I received 3 prediction files rather than the specified test dataset. 
You can reproduce this by running the notebook.  
This is the same problem as the original post.
