### ISSUE TITLE
Lambda boto3 wrappers doesn't have all the option that we need to create a lambda 

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3563]
**Describe the feature you'd like**
We need that ```sagemaker.lambda_helper.Lambda``` will have more options like the ```aws lambda create-function``` cli command.
The missing options that we need are:
* environment
* vpc-config
* architectures

**How would this feature be used? Please describe.**
The class ```sagemaker.lambda_helper.Lambda``` will have the missing attributes.

**Describe alternatives you've considered**
What we do today is to create the lambda as part of the automation of our pipeline object upsert in codepipline, and we have a step in the pipeline for the same particular lambda in order it to be execute as part of the pipeline. 

**Additional context**
https://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html
https://sagemaker.readthedocs.io/en/stable/api/utility/lambda_helper.html

**Comment by dipanjank** [comment]
Hello! Interested in contributing this feature.
