### ISSUE TITLE
ParameterString should be able to be an empty string

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3564]
**Describe the feature you'd like**
```sagemaker.workflow.parameters.ParameterString``` should be able to be an empty string as a default value, and also be able to receive empty string as an input. In sagemaker local mode we are able to put empty string as parameter to the script processor, so it is unclear why in local mode it is working but in the cloud we will get an error.

**Describe alternatives you've considered**
We are putting the string "(empty)" to represent empty values, Seems redundant.

**Comment by qidewenwhen** [comment]
Hi @idanmoradarthas, thanks for reaching out!

I tried to reproduce but did not see any errors. So could you please provide us the following detailed info to help us do further investigation?
- The SageMaker Python SDK version you're using
- What is the error message you got
- The code sample with the following info:
  - how did you define the `ParameterString` with an empty string as a default value. Is it something like `ParameterString(name="MyString", default_value="")`?
  - where did you assign this `ParameterString` to, e.g. which step and which attribute?
  - Did you override the parameter when starting a pipeline execution by `pipeline.start(parameters={...})`?
