### ISSUE TITLE
Feature Request: ability to "rejoin" the pipeline flow after a ConditionStep

### ISSUE THREAD

**Issue by lodo1995** [aws/sagemaker-python-sdk#3565]
I would like my Sagemaker pipeline to do something akin to the following (imagine every function call to be a pipeline step):
```python3
if condition():
    foo()
bar()
baz()
```
Or the following:
```python3
if condition():
    foo_true()
else:
    foo_false()
bar()
baz()
```

That is, I have a conditional step, and I have other steps that must run *after* whatever branch of the conditional is taken has completed.

However, there is currently no way to achieve this, as far as I know. A condition step cannot be added as an explicit dependency in a subsequent step (pipeline creation will fail with an error if trying to do so). Adding the last step from each branch as a dependency does not work, as Sagemaker applies an `and` condition, and only starts a step when *all* its dependency have completed.

So every common step to be run after a conditional must be duplicated in both branches of the conditional, which makes it hard to understand the underlying logic and creates unnecessary duplication.

It is therefore necessary to provide a way to "rejoin" the two branches of the pipeline execution after a condition step.

This could be done by allowing a step to depend on a conditional step, which would be interpreted as waiting for the completion of either all steps in the true branch or all steps in the false branch, depending on how the condition evaluates.

Alternatively, explicit and general support could be provided for an `or` operator when having multiple explicit dependencies in a step. This would then allow users to manually specify that common subsequent steps depend on the steps from both branches.

**Comment by rragundez** [comment]
The request mentioned here is a very common pattern when using the concept of pipelines in other tech stack implementations. In our current company we also need this and there is quite an ugly work around of repeating all steps on each branch which in turn implies that there cannot be another conditional step further down the pipeline as a conditional inside a conditional is not supported.

**Comment by ShwetaSingh801** [comment]
Hi @lodo1995,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
