### ISSUE TITLE
Lambda helper doesn't update the lambda function code when using the function_arn parameter

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3568]
**Describe the bug**
We tested ```sagemaker.lambda_helper.Lambda``` with zipped_code_dir parameter and (and also with script parameter, but not together) using the parameter function_arn to identify the lambda function (as we created it outside of python code). We are using the Pipeline object from sagemaker but the function doesn't update the code when we upsert the pipeline code to sagemaker. 

A workaround is to use the update() function. If this is an expected behavior and you need to use the update() function when using the parameter function_arn, it should be written in the documentation here: https://sagemaker.readthedocs.io/en/stable/api/utility/lambda_helper.html

**To reproduce**
```python
func = Lambda(
    function_arn="arn:aws:lambda:[region]:[account_id]function:[function_name]",
    zipped_code_dir="lambda_helper.zip",
    handler="lambda_helper.lambda_handler",
    s3_bucket=sagemaker.Session().default_bucket()
)
```

The work around:
```python
f_update_response = func.update()
print(f_update_response)
```

**Expected behavior**
The function will update the code when using upsert of the Pipeline object.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.52.1. but the bug also reproduces on the latest sagemaker SDK Python version (2.126.0)
- **Python version**: 3.9
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Comment by rohangujarathi** [comment]
Thank you for using SageMaker. The fix has been deployed to SageMaker Python SDK version `v2.135.0`. The issue should be resolved after upgrade.
