### ISSUE TITLE
Support protobuf 4

### ISSUE THREAD

**Issue by hajapy** [aws/sagemaker-python-sdk#3592]
Is there any timeline for when support for protobuf 4 will arrive? [This upper bound](https://github.com/aws/sagemaker-python-sdk/blob/7faf9ce252a7694cac63be3a8ec8986776276708/setup.py#L54) prevents installing sagemaker sdk in environments with protobuf 4. Would this be blocked on [tensorflow supporting protobuf 4](https://github.com/tensorflow/tensorflow/issues/59221)?

**Comment by stephen37** [comment]
It is also a problem for us now as other dependencies we use require Protobuf 4 but Sagemaker doesn't support it. For example `google-ads` requires `protobuf>=4.0`

**Comment by andrusha** [comment]
This is breaking Flyte orchestration, as it recently migrated to v4.

**Comment by wardvandriessche-centrica** [comment]
Breaking our workflow as well. Any update?

**Comment by hajapy** [comment]
https://protobuf.dev/support/version-support/#python indicates that support for protobuf 3.20.x has ended as of 2023 Q2. 
Could [record_pb2.py](https://github.com/aws/sagemaker-python-sdk/blob/4c1c118bdb48edff7b6b44be34026129d92e2062/src/sagemaker/amazon/record_pb2.py)be regenerated for protobuf 4 and the dependency be updated?

**Comment by j-adamczyk** [comment]
This causes problems for our deployment as well, would be nice to fix this

**Comment by dresslife-nime** [comment]
This is also a problem for us.

**Comment by felipe-costa-compado** [comment]
This is also a problem for us too
