### ISSUE TITLE
Processing Step: Can't pass workflow.arguments as arguments (in processor.run

### ISSUE THREAD

**Issue by abd-shouman** [aws/sagemaker-python-sdk#3600]
Hello everyone,

I am trying to use workflow.parameters with a ProcessingStep for two things:

1. Use as an input for a ProcessingStep
2. Use as an argument for the same ProcessingStep 

However, I don't know if the SDK currently supports this.

For context, the parameters I am using are S3 parameters which allow me to run the pipeline multiple times with different s3 urls.
The parameters are defined as follows

```
s3_bucket = ParameterString(name="InputBucket", default_value="mybucket")
s3_prefix = ParameterString(name="InputPrefix", default_value="myprefix") 
s3_filename = ParameterString(name="InputFileName", default_value="myfile") 
```

So far, I was only able to pass workflow.parameters as input but not as arguments

# 1. Using workflow.parameters as ProcessingInput ##
### This works fine
```
from sagemaker.workflow.functions import Join
s3_full_address = Join(on="", values=[
    "s3://",
    s3_bucket,
    "/",
    s3_prefix,
    "/",
    s3_filename,
]
)
step_train_test_split = ProcessingStep(
    name="Train-Test-Preprocess-Household-Loadprediction-Data",
    processor=train_test_data_processor,
    inputs=[
        ProcessingInput(source=s3_full_address, destination="/opt/ml/processing/input"),
    ],
    outputs=[
        ProcessingOutput(output_name="raw", source="/opt/ml/processing/train"),
        ProcessingOutput(output_name="test", source="/opt/ml/processing/test"),
    ],
    code="generate_train_test_data.py",
)
```

# 2. Using workflow.parameters as ProcessingInput and parameters
### This Raises an error:  ```TypeError: Object of type ParameterString is not JSON serializable```

```
step_train_test_split = ProcessingStep(
   step_args=train_test_data_processor.run(
       inputs=[
            ProcessingInput(source=s3_full_address, destination="/opt/ml/processing/input"),
       ],
       outputs=[
        ProcessingOutput(output_name="raw", source="/opt/ml/processing/train"),
        ProcessingOutput(output_name="test", source="/opt/ml/processing/test"),
       ],
       code="generate_train_test_data.py",
       arguments=["--s3_prefix", s3_prefix]
   )
)
```
### Error explained
>#### The error is caused because in the ```arguments``` attribute, s3_prefix is a parameter string and it is not serializable.

## Approach 2.B
I tried to change it from `s3_prefix` to `s3_prefix.expr`, however, this has caused another error. 
_(Note: I am using .expr because I am assuming it will be evaluated at run_time. However, I am not sure if this is actually correct)_

### Error raised: ```TypeError: Object of type Join is not JSON serializable```
```
step_train_test_split = ProcessingStep(
   step_args=train_test_data_processor.run(
       inputs=[
            ProcessingInput(source=s3_full_address, destination="/opt/ml/processing/input"),
       ],
       outputs=[
        ProcessingOutput(output_name="raw", source="/opt/ml/processing/train"),
        ProcessingOutput(output_name="test", source="/opt/ml/processing/test"),
       ],
       code="generate_train_test_data.py",
       arguments=["--s3_prefix", s3_prefix.expr]
   )
)
```
### Error explained
>#### This error was raised because S3 was constructed using `.join` which is not json serializable

## Approach 2.C
I tried using the `.expr` again for the s3_full_address 
### Error raised: ```ParamValidationError: Parameter validation failed: Invalid type for parameter AppSpecification.ContainerArguments[1], value: {'Get': 'Parameters.InputPrefix'}, type: <class 'dict'>, valid types: <class 'str'>```
 
```s3_full_address = f's3://{s3_bucket.expr}/{s3_prefix.expr}/{s3_filename.expr}'
step_train_test_split = ProcessingStep(
   step_args=train_test_data_processor.run(
       inputs=[
            ProcessingInput(source=s3_full_address, destination="/opt/ml/processing/input"),
       ],
       outputs=[
        ProcessingOutput(output_name="raw", source="/opt/ml/processing/train"),
        ProcessingOutput(output_name="test", source="/opt/ml/processing/test"),
       ],
       code="generate_train_test_data.py",
       arguments=["--s3_prefix", s3_prefix.expr]
   )
)
```
### Error explained
>#### This is because s3_prefix.expr is evaluated as ```{'Get': 'Parameters.InputPrefix'}``` which is a dictionary

Note: I tried different combination of ```.expr``` and ```to_string``` to no avail
Would highly appreciate your feedback and help

**Comment by qidewenwhen** [comment]
Hi @abd-shouman, thanks for using SageMaker!
Could you share the code snippet on how you define the `train_test_data_processor`? Especially what kind of session did you use?

As you're using `train_test_data_processor.run` to get the `step_args`, which is the new step interfaced we introduced last year. **This new interface requires the session to be [`PipelineSession`](https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html#pipeline-session)**. Otherwise, it can cause the `TypeError: Object of type ParameterString is not JSON serializable` error you've seen

**Comment by qidewenwhen** [comment]
Closing this issue as there's no response for over a month. Feel free to reopen if you any further questions. Thanks!
