### ISSUE TITLE
Customizing the artifact output path.

### ISSUE THREAD

**Issue by ILikeNNs** [aws/sagemaker-python-sdk#3609]
**Describe the feature you'd like**
Before Experiments were integrated with the base sagemaker library, I could customize the path where the training artifacts are stored with Tracker, since the load method allowed for specifying the artifact bucket and the artifact prefix:

`Tracker.load(artifact_bucket='xxx',  artifact_prefix='yyy')`

The new, integrated sagemaker.experiments no longer allows it in load_run
https://github.com/aws/sagemaker-python-sdk/blob/5cb00a4d9042f96814582006161639527ebc1e15/src/sagemaker/experiments/run.py#L713-L717

I would like to be able to customize the path. At the moment the bucket and prefix sit in the _helper.py in the _ArtifactUploader class, the prefix seems to be hardcoded https://github.com/aws/sagemaker-python-sdk/blob/5cb00a4d9042f96814582006161639527ebc1e15/src/sagemaker/experiments/_helper.py#L31-L40

There does not seem to be a way to customize the output path for artifacts anymore, and that is something that has come extremely handy while using the old SDK.

**How would this feature be used? Please describe.**
Being able to define the bucket AND the prefix where the output artifacts would be stored.

**Describe alternatives you've considered**
The only alternative I have found is using the old SDK - if someone has another idea, please let me know.

**Comment by JanetMatsen** [comment]
I'd also love this, so we can put our modeling artifacts in an immutable bucket.  Thank you!

**Comment by rd-pong** [comment]
An alternative would be using `default_bucket` and `default_bucket_prefix` when initilizing a [sagemaker_session](https://sagemaker.readthedocs.io/en/stable/api/utility/session.html#sagemaker.session.Session).

Initialize a [sagemaker_session](https://sagemaker.readthedocs.io/en/stable/api/utility/session.html#sagemaker.session.Session) and specify `default_bucket` and `default_bucket_prefix` to be your desired artifact output location. Then, when initializing a new [Run](https://sagemaker.readthedocs.io/en/stable/experiments/sagemaker.experiments.html#sagemaker.experiments.Run), pass in the `sagemaker_session`: `Run(experiment_name="my-exp", run_name="my-run", sagemaker_session="my_session")`.
