### ISSUE TITLE
bump docker-compose dependency to avoid dependency hell

### ISSUE THREAD

**Issue by lorenzwalthert** [aws/sagemaker-python-sdk#3613]
**Describe the feature you'd like**

You depend on almost two year old [docker-compose](https://github.com/docker/compose/releases/tag/1.29.2) version (as an optional dependency). I.e. you depend on [1.29.2](https://github.com/aws/sagemaker-python-sdk/blob/5d5976726cb8e0cf7143d86b4abb4b665842fd14/requirements/extras/local_requirements.txt#L2), but there is 2.15.1 This old dependency itself has version constraints on other packages such as `jsonschema`. My project (and/or its dependencies) depend on newer versions of `jsonschema` and hence I can't resolve the dependencies in my project.

**How would this feature be used? Please describe.**

Make it easier for users to resolve their dependencies.

**Describe alternatives you've considered**

Not making docker-compose a requirement in my poetry setup and install ad-hoc with `pip install`. This may cause unexpected conflicts.

**Additional context**
The use of `docker-compose` seems [very limited](https://github.com/aws/sagemaker-python-sdk/search?q=compose_cmd) in this repo and hence an upgrade and potential adaption effort would be low.

**Comment by j-adamczyk** [comment]
+1, this is quite a problem for me, since we are using Docker Compose in modern version across all apps, and I would very much like to avoid using very old 1.X version just for SageMaker projects

**Comment by lorenzwalthert** [comment]
Right... I won't need the alias, but thanks.
