### ISSUE TITLE
Repack Model Step failed after upgrading to 2.125.0: ProfilerConfig is not allowed to have fields when disabled.

### ISSUE THREAD

**Issue by isunli** [aws/sagemaker-python-sdk#3620]
We recently updated our SDK version to 2.125.0, before updating, our sagemaker pipeline works fine but it will break at the model repack step after updating. 
The error message is `ProfilerConfig is not allowed to have fields when disabled.` which seems related to https://github.com/aws/sagemaker-python-sdk/issues/3555 and https://github.com/aws/sagemaker-python-sdk/commit/92358fe20b5f8a390edc81b0d17a013612f7245a#commitcomment-93687270. 
Is this bug fixed in the 2.130.0? 
Can we rollback the change if it can't be fixed in the next version? 
Thanks!

**Comment by qidewenwhen** [comment]
Synced up with @isunli offline and let him know that the issue seems to be fixed in https://github.com/aws/sagemaker-python-sdk/releases/tag/v2.126.0 so we're not able to reproduce this issue anymore with the latest SageMaker PySDK (> v2.126.0).
He may upgrade to verify the fix.
