### ISSUE TITLE
Container log level for Estimator expects python logging package number and not ENUM string – can’t be a readable pipeline parameter as such

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3634]
**Describe the feature you'd like**
container_log_level parameter in sagemaker.estimator.Estimator can only be either an int or Integer PipelineVariable. We want it to be a string or String PipelineVariable that is an Enum.

**How would this feature be used? Please describe.**
container_log_level parameter in sagemaker.estimator.Estimator will be able to receive a string from the following table: https://docs.python.org/3/library/logging.html#levels 
<html>
<body>

Level | Numeric value
-- | --
CRITICAL | 50
ERROR | 40
WARNING | 30
INFO | 20
DEBUG | 10
NOTSET | 0

</body>
</html>

**Describe alternatives you've considered**
We just added a long description to the PipelineVariable

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
