### ISSUE TITLE
Random Seed in HPO can’t be pipeline parameter

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3635]
**Describe the feature you'd like**
random_seed parameter in sagemaker.tuner.HyperparameterTuner can only be int. It should be a PipelineVariable also.

**How would this feature be used? Please describe.**
Random seed could be set from the pipeline object parameters.

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
