### ISSUE TITLE
ParameterInteger Could also get Enum values

### ISSUE THREAD

**Issue by idanmoradarthas** [aws/sagemaker-python-sdk#3647]
**Describe the feature you'd like**
We want ```sagemaker.workflow.parameters.ParameterInteger``` to be able to get enum value like ```sagemaker.workflow.parameters.ParameterString```

**How would this feature be used? Please describe.**
When using ```sagemaker.estimator.Estimator```, you need to pass a parameter named container_log_level based on integer values from https://docs.python.org/3/library/logging.html#levels . We extracted this parameter to a PipelineVariable. However, because it is a ```sagemaker.workflow.parameters.ParameterInteger``` we cannot enforce the user to only select valid values are defined in the Python logging module. Enabling ```sagemaker.workflow.parameters.ParameterInteger``` to have enum values will fix that.

**Describe alternatives you've considered**
Throwing exception in code we wrote for the estimator.

**Comment by ShwetaSingh801** [comment]
Hi @idanmoradarthas, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
