### ISSUE TITLE
[Feature - Hugging Face] Add new DLCs(transformers 4.26.0) to Image config

### ISSUE THREAD

**Issue by JingyaHuang** [aws/sagemaker-python-sdk#3669]
# Add Release Image to Image config for the Hugging Face DLCs

## huggingface_pytorch

**Training**
- [x] PyTorch 1.13 - Transformers 4.26.0 - GPU

**Inference**

- [x] PyTorch 1.13 - Transformers 4.26.0 - CPU
- [x] PyTorch 1.13 - Transformers 4.26.0 - GPU

## huggingface_tensorflow

**Training**

- [ ] TensorFlow 2.11.0 - Transformers 4.26.0 - GPU

**Inference**

- [ ] TensorFlow 2.11.0 - Transformers 4.26.0 - CPU
- [ ] TensorFlow 2.11.0 - Transformers 4.26.0 - GPU

cc @tejaschumbalkar @arjkesh

**Comment by rojamet** [comment]
@JingyaHuang your PR appears to not include a training image for transformers 4.26 with tensorflow, is it an oversight, or is the 4.26 tensorflow training version coming later?

**Comment by JingyaHuang** [comment]
Hi @rojamet, the training image will come later. You can track the progress of HF-TF training DLC for transformers 4.26 here: https://github.com/aws/deep-learning-containers/pull/2693 .

**Comment by rojamet** [comment]
@JingyaHuang Thank you very much for that quick answer! I'll be following that.

**Comment by JingyaHuang** [comment]
Hi @knikure, can you reopen the issue, as the TF training DLC is merged in the DLC repo but not yet released nor added to sagemaker SDK. Thanks.
