### ISSUE TITLE
Deprecate from Error to Warning: "KMS key is not supported for NVMe instance storage"

### ISSUE THREAD

**Issue by sermolin** [aws/sagemaker-python-sdk#3677]
**Describe the bug**
SDK issues and error and stops deployment if KMS key is specified for instances with NVMe hardware encryption (P4*, G5* etc).
Customer's Service Control Policies (SCPs) enforce KMS key in CreateEndpointConfig API call as they must for p2* and p3* instances. 

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
Add an SCP or IAM policy below and try any estimator.deploy() with P4* of G5* instance type
    {
      "Effect": "Deny",
      "Action": [
        "sagemaker:CreateAutoMLJob",
        "sagemaker:CreateLabelingJob",
        "sagemaker:CreateProcessingJob",
        "sagemaker:CreateTrainingJob",
        "sagemaker:CreateHyperParameterTuningJob",
        "sagemaker:CreateEndpointConfig",
        "sagemaker:CreateMonitoringSchedule",
        "sagemaker:UpdateMonitoringSchedule",
        "sagemaker:CreateNotebookInstance",
        "sagemaker:CreateTransformJob",
        "sagemaker:CreateDataQualityJobDefinition",
        "sagemaker:CreateDomain",
        "sagemaker:CreateModelBiasJobDefinition",
        "sagemaker:CreateModelExplainabilityJobDefinition",
        "sagemaker:CreateModelQualityJobDefinition"
      ],
      "Resource": "*",
      "Condition": {
        "Null": {
          "sagemaker:VolumeKmsKey": [
            "true"
          ]
        }
      }
    },

**Expected behavior**
SDK issues a Warning: KMS key is not supported for NVMe instance storage; these instances use built-in hardware-based encryption

**Screenshots or logs**

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
/tmp/ipykernel_9617/3613806716.py in <cell line: 1>()
----> 1 predictor = huggingface_estimator.deploy(1,"ml.p4d.24xlarge", kms_key=kms_key) #deploy on GPU
      2 #predictor = huggingface_estimator.deploy(1,"ml.p3.2xlarge", kms_key=kms_key) #deploy on GPU
      3 #predictor = huggingface_estimator.deploy(1,"ml.c5.4xlarge", kms_key=kms_key) #deploy on CPU

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/sagemaker/estimator.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, use_compiled_model, wait, model_name, kms_key, data_capture_config, tags, **kwargs)
    950         return debugger_rule_configs
    951 
--> 952     def _prepare_collection_configs(self):
    953         """De-duplicate configurations and save them in the debugger hook configuration."""
    954         # Create a set to de-duplicate CollectionConfigs.

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, **kwargs)
    725         tags,
    726     ):
--> 727         """Creates a request object for a packaging job.
    728 
    729         Args:

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/sagemaker/session.py in endpoint_from_production_variants(self, name, production_variants, tags, kms_key, wait, data_capture_config_dict)
   3515         self.sagemaker_client.delete_endpoint(EndpointName=endpoint_name)
   3516 
-> 3517     def delete_endpoint_config(self, endpoint_config_name):
   3518         """Delete an Amazon SageMaker endpoint configuration.
   3519 

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    528                 )
    529             # The "self" in this scope is referring to the BaseClient.
--> 530             return self._make_api_call(operation_name, kwargs)
    531 
    532         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/pytorch_p39/lib/python3.9/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    958             error_code = parsed_response.get("Error", {}).get("Code")
    959             error_class = self.exceptions.from_code(error_code)
--> 960             raise error_class(parsed_response, operation_name)
    961         else:
    962             return parsed_response

ClientError: An error occurred (ValidationException) when calling the CreateEndpointConfig operation: KMS key is not supported for NVMe instance storage. Remove the KMS key in the request or choose a different instance type.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.134.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Conda_PyTorch_p39
- **Framework version**:
- **Python version**:
- **CPU or GPU**: GPU
- **Custom Docker image (Y/N)**: NO

**Additional context**
Customer wants to deploy LLMs on P4DN and P4DNs, G5, but can't because of this issue.

**Comment by sermolin** [comment]
Suggested verbiage to replace the ERROR message: WARNING: KMS volume key is not supported for AWS compute instances with NVMe instance storage. The data on NVMe instance store volumes is encrypted using an XTS-AES-256 cipher, implemented on a hardware module on the instance. The keys used to encrypt data that's written to locally-attached NVMe storage devices are per-customer, and per volume. The keys are generated by, and only reside within, the hardware module, which is inaccessible to AWS personnel. The encryption keys are destroyed when the instance is stopped or terminated and cannot be recovered. You cannot disable this encryption and you cannot provide your own encryption key. The KMS volume encryption key you provided will not be used. Source: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/data-protection.html

**Comment by martinRenou** [comment]
Thank you for opening an issue and for your suggestion.

The current error message is quite clear on what to do to fix the error, stating "Remove the KMS key in the request or choose a different instance type".

Closing as won't fix, but we're happy to continue discuss it if you think otherwise.
