### ISSUE TITLE
Using the Bring Your Own Algorithm Config with Estimator , no way currently to pass VPC configs

### ISSUE THREAD

**Issue by whiletruelearn** [aws/sagemaker-python-sdk#369]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: BYO Algorithm
- **Framework Version**: NA
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.9.2
- **Are you using a custom image**: Yes

### Describe the problem
We use `sage.estimator.Estimator` for passing the training image and other details needed for training. Currently this API doesn't accept any vpc config.

### Minimal repro / logs

- **Exact command to reproduce**:

**Comment by nadiaya** [comment]
Thank you for creating a PR!

**Comment by nadiaya** [comment]
PR is merged. Closing the issue.
