### ISSUE TITLE
Adding tag support for Sagemaker pipeline

### ISSUE THREAD

**Issue by toytown** [aws/sagemaker-python-sdk#3733]
**Describe the feature you'd like**
Currently tags are not supported for creating  / listing or deleting pipelines by this SDK while other API like cloudformation supports this out of the box Sagemaker feature.  See https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsagemaker.html

```python
pipeline = Pipeline(
    name=pipeline_name,
    parameters=[instance_count, app_managed],
    steps=[step_sklearn],
    sagemaker_session=session,
   **tags= ??**
)
```

**How would this feature be used? Please describe.**
Without resource resource tagging feature there is not way to **restrict** the creation, update or deletion of pipelines from other teams. As we use Sagemaker studio with multiple teams , the pipelines from other teams are clearly visible.  So theoretically team-A can view and modify pipelines from other teams and this is potentially also a security risk.

**Describe alternatives you've considered**
Without resource tagging support for authorization it would be difficult to use Sagemaker pipelines. We have not considered any alternative yet

**Additional context**
Sagemaker Studio. Sagemaker pipelines.  A similar request has been raised for CreateModel API as well
https://github.com/aws/sagemaker-python-sdk/issues/3447

**Comment by qidewenwhen** [comment]
Hi @toytown, thanks for reaching out!

The SageMaker Pipeline does support tags, which is taken in the `pipeline.create()` method. See https://github.com/aws/sagemaker-python-sdk/blob/4884d18430248f870196328008893d6e39f4b862/src/sagemaker/workflow/pipeline.py#L114

Once adding the tags to the pipeline and setting up a proper tag-based policy, you'll be able to restrict the update or deletion of pipelines from other teams.

Can you check if this is what you asked for? Or did you see any issues when adding tags when creating a pipeline?

**Comment by qidewenwhen** [comment]
Closing the issue as no responses received for over 3 months. Feel free to reopen if you have any other questions. Thanks!
