### ISSUE TITLE
%pip install --upgrade pip sagemaker==2.140.1 fails with error 

### ISSUE THREAD

**Issue by teraiyam** [aws/sagemaker-python-sdk#3742]
**Describe the bug**
%pip install --upgrade pip sagemaker==2.140.1 fails wit  error: metadata-generation-failed
**To reproduce**
%pip install --upgrade pip sagemaker
A clear, step-by-step set of instructions to reproduce the bug.

**Expected behavior**
sagemaker version should be updated
**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.
![Screenshot 2023-03-22 at 11 07 08](https://user-images.githubusercontent.com/125926750/226869986-78b685e5-d4a3-4b8f-ae50-6fbfabd82023.png)

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**:
- **Python version**:
- **CPU or GPU**:
- **Custom Docker image (Y/N)**:

**Additional context**

**Comment by martinRenou** [comment]
Starting from the next release, a wheel will be provided on PyPi, preventing this kind of issues. Thank you for using the SDK.
