### ISSUE TITLE
DJLModel doesn't support ml.p4d.24xlarge for deployment

### ISSUE THREAD

**Issue by andjsmi** [aws/sagemaker-python-sdk#3748]
**Describe the bug**
The `ml.p4d.*` and `ml.p4de.*` instances are not supported for the DJLModel for deploying as they aren't included in allowed instance families.

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
Deploy a SageMaker Endpoint with an `ml.p4d.24xlarge` from a DJLModel.

**Expected behavior**
Endpoint deploys successfully as ml.p4d.24xlarge is sufficiently large enough.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.
![Screen Shot 2023-03-23 at 3 07 29 pm](https://user-images.githubusercontent.com/101757907/227100457-f78b7696-8544-4c12-9e97-7288ceb0c7d4.png)

**System information**
A description of your system. Please provide:

- **SageMaker Python SDK version**: 2.140.1
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Deep Java Library
- **Framework version**:
- **Python version**: 3.8.13
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**

**Comment by siddvenk** [comment]
Thanks for raising this issue - I have created a PR to fix this bug. I also noticed that some other instance families needed to be fixed, so now p3dn, p4d, and p4de instances should all work.
