### ISSUE TITLE
Parameter description update 

### ISSUE THREAD

**Issue by mwfongAWS** [aws/sagemaker-python-sdk#3777]
**What did you find confusing? Please describe.**
I tried to read the description for sagemaker.transformer.Transformer.transform() 

https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.TransformInput

**Describe how documentation can be improved**
Add parameter descriptions

**Additional context**
Here are some resources:
* readthedocs: https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html#sagemaker.inputs.TransformInput
* APIRef: https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_TransformInput.html
* GitHub: https://github.com/aws/sagemaker-python-sdk/blob/e917cb47c51041e168a09c472b19e07fdfeaf1af/doc/api/utility/inputs.rst

I wrote an attempted draft:

@attr.s
class TransformInput(object):
    """Create a class containing all the parameters.

    It can be used when calling ``sagemaker.transformer.Transformer.transform()``

    Parameters:
        data (str): The S3 location of the input data that the model can consume.
        data_type (str): elastic inference accelerator type.
           (default: ``'S3Prefix'``)
        content_type (str): The multipurpose internet mail extension (MIME) type of the data.
            (default: None)
        compression_type (str): If your transform data is compressed, specify the compression type.
            Valid values: ``'Gzip'``, ``None``
            (default: None)
        split_type (str): The method to use to split the transform job's data files into smaller 
        batches.
            Valid values: ``'Line'``, ``RecordIO``, ``'TFRecord'``, None
            (default: None)
        input_filter (str): 
            (default: None)
        output_filter (str): 
            (default: None)
        join_source (str): 
            (default: None)
        model_client_config (dict): 
            (default: None)
        batch_data_capture_config (dict): Specifies configuration related to batch transform job 
        data capture for use with Amazon SageMaker Model Monitoring.
            (default: None)
    """

    data: str = attr.ib()
    data_type: str = attr.ib(default="S3Prefix")
    content_type: str = attr.ib(default=None)
    compression_type: str = attr.ib(default=None)
    split_type: str = attr.ib(default=None)
    input_filter: str = attr.ib(default=None)
    output_filter: str = attr.ib(default=None)
    join_source: str = attr.ib(default=None)
    model_client_config: dict = attr.ib(default=None)
    batch_data_capture_config: dict = attr.ib(default=None)

**Comment by mufaddal-rohawala** [comment]
Thanks for reaching out to Sagemaker! I've forwarded the request to Sagemaker Documentation Team.

**Comment by mufaddal-rohawala** [comment]
https://t.corp.amazon.com/V878842617

**Comment by mufaddal-rohawala** [comment]
The documentation has been updated. Thank you!
