### ISSUE TITLE
Example code error in sagemaker.workflow.functions.Join doc

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-python-sdk#3778]
**What did you find confusing? Please describe.**

The current [example code](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#functions) for `sagemaker.workflow.functions.Join`:

```
TrainingInput(
    s3_data=Join(on='/', ['s3:/', bucket, ExecutionVariables.PIPELINE_EXECUTION_ID]),
    content_type="text/csv")
```

...raises an error because a positional argument (the list of components) cannot follow a keyword argument (`on='/'`) in Python

**Describe how documentation can be improved**

Update the docs to add `values=` on the second arg or remove the `on=` from the first.

**Additional context**

N/A

**Comment by claytonparnell** [comment]
Fixed by https://github.com/aws/sagemaker-python-sdk/pull/3807
