### ISSUE TITLE
cannot import name 'get_base_python_image_uri' from 'sagemaker.image_uris' (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/image_uris.py)

### ISSUE THREAD

**Issue by KraftZzz** [aws/sagemaker-python-sdk#3815]
I run this code in jupyternotebook:

!pip3 show sagemaker
from sagemaker.remote_function import remote

Name: sagemaker
Version: 2.150.0
Summary: Open source library for training and deploying models on Amazon SageMaker.
Home-page: https://github.com/aws/sagemaker-python-sdk/
Author: Amazon Web Services
Author-email: 
License: Apache License 2.0
Location: /home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages
Requires: attrs, boto3, cloudpickle, google-pasta, importlib-metadata, jsonschema, numpy, packaging, pandas, pathos, platformdirs, protobuf, protobuf3-to-dict, PyYAML, schema, smdebug-rulesconfig, tblib
Required-by: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[6], line 2
      1 get_ipython().system('pip3 show sagemaker')
----> 2 from sagemaker.remote_function import remote

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/remote_function/__init__.py:16
     13 """Defines classes and helper methods used in remote function executions."""
     14 from __future__ import absolute_import
---> 16 from sagemaker.remote_function.client import remote, RemoteExecutor  # noqa: F401

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/remote_function/client.py:38
     36 from sagemaker.session import Session
     37 from sagemaker.s3 import s3_path_join
---> 38 from sagemaker.remote_function.job import _JobSettings, _Job, _RunInfo
     39 from sagemaker.remote_function import logging_config
     40 from sagemaker.utils import name_from_base, base_from_name

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/remote_function/job.py:44
     42 from sagemaker.experiments._run_context import _RunContext
     43 from sagemaker.experiments.run import Run
---> 44 from sagemaker.image_uris import get_base_python_image_uri
     45 from sagemaker.session import get_execution_role, _logs_for_job, Session
     46 from sagemaker.utils import name_from_base, _tmpdir, resolve_value_from_config

ImportError: cannot import name 'get_base_python_image_uri' from 'sagemaker.image_uris' (/home/ec2-user/anaconda3/envs/python3/lib/python3.10/site-packages/sagemaker/image_uris.py)

I refer this blog: https://aws.amazon.com/cn/blogs/machine-learning/run-your-local-machine-learning-code-as-amazon-sagemaker-training-jobs-with-minimal-code-changes/, but is not work fine.

**Comment by dpatro** [comment]
@KraftZzz Can you share more details about how your are running your jupyternotebook?

Are you running a local JupyterServer? Or Are your running a jupyter notebook from inside an Python IDE like PyCharm, VSCode, etc and using the conda environment as the Jupyter Kernel?

In either case, can you try restarting the Kernel from the IDE and see if it helps? It is recommended to restart the kernel from an IDE after you install or upgrade any dependency package(s).

Thanks,

**Comment by KraftZzz** [comment]
Hey, dpatro, I run the jupyternotebook in sagemaker notebook instance and I tried to change the notebook kernel and restart kernel or re-create a new jupyternotebook, but not work. And I confirm that the sagemaker sdk package is in latest version.

**Comment by dpatro** [comment]
Thanks for sharing the details. I am unable to reproduce the problem at my end. I am looking for what might be causing the problem of import failure even when the package is updated.

Can you try following steps?

1/ splitting your first cell into two so that following are two different cells:
`!pip install sagemaker`

`from sagemaker.remote_function import remote`

2/ Execute the first cell with `pip install`.

3/ Restart the kernel: Top menu bar -> `Kernel` -> `Restart Kernel...`

4/ Execute the second cell with `from ... import`


====

In case it does not work, we have other options to try the remote function feature, e.g. you local development laptop or SageMaker Studio. Check out the "Set up your environment" in our developer guide : https://docs.aws.amazon.com/sagemaker/latest/dg/train-remote-decorator.html

**Comment by KraftZzz** [comment]
Amazing,  restart kernel will help. I can import this package, many thanks

**Comment by KraftZzz** [comment]
import sagemaker
from sagemaker.remote_function import remote

@remote(instance_type="ml.m5.xlarge")
def divide(x, y):
    return x / y
if __name__ == "__main__":
    print(divide(2, 3.0))

error log:
INFO: CONDA_PKGS_DIRS is set to '/opt/ml/sagemaker/warmpoolcache/sm_remotefunction_user_dependencies_cache/conda/pkgs'
--
INFO: PIP_CACHE_DIR is set to '/opt/ml/sagemaker/warmpoolcache/sm_remotefunction_user_dependencies_cache/pip'
INFO: Bootstraping runtime environment.
2023-04-27 03:53:18,575 sagemaker.remote_function INFO     Directory '/opt/ml/input/data/sm_rf_user_ws' does not exist. Assuming no dependencies to bootstrap.
INFO: No conda env provided. Invoking remote function
/usr/local/bin/python: Error while finding module specification for 'sagemaker.remote_function.invoke_function' (ModuleNotFoundError: No module named 'sagemaker')

**Comment by dpatro** [comment]
Awesome, glad it worked out.
