### ISSUE TITLE
lambda_helper Lambda Is Not Able to Create - Requires VpcConfig

### ISSUE THREAD

**Issue by hxrsmurf** [aws/sagemaker-python-sdk#3826]
**Describe the bug**
After https://github.com/aws/sagemaker-python-sdk/pull/3594 was merged, creating a Lambda Step for SageMaker Pipeline does not work when no values are specified. For example, if I do not want to include any values for VpcConfig.

This error does not occur in 2.150.0

**To reproduce**
```lambda_step = Lambda(
  function_name="My Function",
execution_role_arn=my_arn_here,
script="./myscript.py",
handler="myscript.lambda_handler",
session=sagemaker_sesion,
timeout=15
)
```

**Expected behavior**
Allow LambdaStep to be created

**Screenshots or logs**
```
Invalid type for parameter VpcConfig, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter Environment, value: None, type: <class 'NoneType'>, valid types: <class 'dict'>
Invalid type for parameter Architectures, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
Invalid type for parameter Layers, value: None, type: <class 'NoneType'>, valid types: <class 'list'>, <class 'tuple'>
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.151.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.10.11
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

**Additional context**
N/A

**Comment by hxrsmurf** [comment]
@dipanjank - Is there a way to catch NoneType for VpcConfig, Environment, Architectures, and Layers ?

**Comment by dipanjank** [comment]
> @dipanjank - Is there a way to catch NoneType for VpcConfig, Environment, Architectures, and Layers ?

Oops - will have a look.

**Comment by dipanjank** [comment]
@hxrsmurf - can you please have a look at the referenced PR?

**Comment by hxrsmurf** [comment]
@dipanjank  - Thanks for the quick response . LGTM.
