### ISSUE TITLE
Missing: Volume Encryption

### ISSUE THREAD

**Issue by kenstler** [aws/sagemaker-python-sdk#383]
### Describe the problem
Volume encryption missing from SDK.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by winstonaws** [comment]
Started working on this today, PR out soon hopefully.

**Comment by winstonaws** [comment]
Fixed in this release: https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.10.1
