### ISSUE TITLE
Issue in a creating a job with a name containing underscore

### ISSUE THREAD

**Issue by whiletruelearn** [aws/sagemaker-python-sdk#384]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Custom
- **Framework Version**: NA
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.9.2
- **Are you using a custom image**: Yes

### Describe the problem
When passing `base_job_name` to `sage.estimator.Estimator` , there is a client error failure due to a regex match. Job names which contain `_` have this issue.

### Minimal repro / logs
`ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: 1 validation error detected: Value 'health_and_personal_care_inter_title-2018-09-06-05-57-49-470' at 'trainingJobName' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9](-*[a-zA-Z0-9])*`

- **Exact command to reproduce**:

**Comment by iquintero** [comment]
Hi @whiletruelearn 

This is not a bug, the trainingJobName can't contain underscores. This is documented in the SageMaker API docs:

https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateTrainingJob.html

Feel free to re-open this issue if you have further questions.
