### ISSUE TITLE
Incorrect type-hint in ingest method for feature store

### ISSUE THREAD

**Issue by pbamotra** [aws/sagemaker-python-sdk#3850]
@ericpark3 the type-hint is incorrect in this line. 

https://github.com/aws/sagemaker-python-sdk/blame/1ae7ce938e9b94aeb421b7af1570c6a7c3ae4a6e/src/sagemaker/feature_store/feature_group.py#L280

**Comment by mufaddal-rohawala** [comment]
@pbamotra thanks for reaching out, can you create a bug request with the template in https://github.com/aws/sagemaker-python-sdk/issues/new/choose and provide as much information as possible to help reproduce and resolve.

Closing this issue and awaiting a detailed bug issue.
