### ISSUE TITLE
Object of type ParameterString is not JSON serializable

### ISSUE THREAD

**Issue by aravinddeveloper** [aws/sagemaker-python-sdk#3860]
Bug:
When passing parameters to pipeline processors, Exception "Object of type ParameterString is not JSON serializable" is received

To reproduce:
BASE_DIR = os.path.dirname(os.path.realpath(__file__))
BUCKET_NAME = <bucket_name>
PROCESSING_PATH = "/opt/ml/processing"
train_folder_name="train"
val_folder_name="val"
eval_folder_name="eval"
processing_instance_count = ParameterInteger(name="ProcessingInstanceCount", default_value=1)
processing_instance_type = ParameterString(
    name="ProcessingInstanceType", default_value="ml.m5.xlarge"
)
input_data_path = ParameterString(
        name="InputDataUrl",
        default_value=f"s3://{BUCKET_NAME}/input" )
    processed_data_path = ParameterString(
        name="OutputDataUrl",
        default_value=f"s3://{BUCKET_NAME}/processed" )
processor = PyTorchProcessor(role=role,
                             framework_version="1.8",
                             instance_type=processing_instance_type,
                             instance_count=processing_instance_count,
                             sagemaker_session=sagemaker_session)
proc_args = processor.run(inputs=[ProcessingInput(input_name="raw-data",
                                                  source=input_data_path,
                                                  destination=f"{PROCESSING_PATH}/input")],
                          code=os.path.join(BASE_DIR,"processing.py"),
                          outputs=[ProcessingOutput(output_name=train_folder_name,
                                                    source=f"{PROCESSING_PATH}/{train_folder_name}",
                                                    destination=Join(on="",values=[processed_data_path,"/",train_folder_name])),
                                   ProcessingOutput(output_name=val_folder_name,
                                                    source=f"{PROCESSING_PATH}/{val_folder_name}",
                                                    destination=Join(on="",values=[processed_data_path,"/",val_folder_name])),
                                   ProcessingOutput(output_name=eval_folder_name,
                                                    source=f"{PROCESSING_PATH}/{eval_folder_name}",
                                                    destination=Join(on="",values=[processed_data_path,"/",eval_folder_name]))],
                          arguments=["--train-test-split_ratio", 0.1, 
                                     "--process-input-folder","input",
                                     "--process-train-folder",train_folder_name,
                                     "--process-val-folder",val_folder_name,
                                     "--process-eval-folder",eval_folder_name])

- SageMaker Python SDK version:2.113.0
- Framework name (eg. PyTorch) or algorithm (eg. KMeans): pytorch
- Framework version:1.8
- Python version:3.8
- CPU or GPU:CPU
- Custom Docker image (Y/N):N

**Comment by navaj0** [comment]
> sagemaker_session=sagemaker_session

You should use PipelineSession in this line. With a normal Session object, the processor will try to start a processing job immediately, and will fail if it sees PipelineVariable passed in.
