### ISSUE TITLE
Customized model data download timeout is not supported in China region(cn-north-1&cn-northwest-1)

### ISSUE THREAD

**Issue by KraftZzz** [aws/sagemaker-python-sdk#3883]
from sagemaker.huggingface import HuggingFaceModel
import sagemaker

role = sagemaker.get_execution_role()
# Hub Model configuration. https://huggingface.co/models
hub = {
    'HF_MODEL_ID':'BelleGroup/BELLE-7B-0.2M',
    'HF_TASK':'text2text-generation',
    'HUGGINGFACE_ASSETS_CACHE':'/tmp'
}

# create Hugging Face Model Class
huggingface_model = HuggingFaceModel(
    transformers_version='4.17.0',
    pytorch_version='1.10.2',
    py_version='py38',
    env=hub,
    role=role, 
)

# deploy model to SageMaker Inference
predictor = huggingface_model.deploy(
    initial_instance_count=1, # number of instances
    instance_type='ml.m5.xlarge',
    model_data_download_timeout=3600,
    wait=False
)

predictor.predict({
    'inputs': "The answer to the universe is"
})

I use this huggingface demo in my sagemaker notebook instance jupyter notebook. and I encounter the error message as below:

---------------------------------------------------------------------------
ClientError                               Traceback (most recent call last)
/tmp/ipykernel_24542/2270592720.py in <cell line: 22>()
     20 
     21 # deploy model to SageMaker Inference
---> 22 predictor = huggingface_model.deploy(
     23     initial_instance_count=1, # number of instances
     24     instance_type='ml.m5.xlarge',

~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/huggingface/model.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, async_inference_config, serverless_inference_config, volume_size, model_data_download_timeout, container_startup_health_check_timeout, inference_recommendation_id, explainer_config, **kwargs)
    309             )
    310 
--> 311         return super(HuggingFaceModel, self).deploy(
    312             initial_instance_count,
    313             instance_type,

~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/model.py in deploy(self, initial_instance_count, instance_type, serializer, deserializer, accelerator_type, endpoint_name, tags, kms_key, wait, data_capture_config, async_inference_config, serverless_inference_config, volume_size, model_data_download_timeout, container_startup_health_check_timeout, inference_recommendation_id, explainer_config, **kwargs)
   1308             async_inference_config_dict = async_inference_config._to_request_dict()
   1309 
-> 1310         explainer_config_dict = None
   1311         if is_explainer_enabled:
   1312             explainer_config_dict = explainer_config._to_request_dict()

~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/sagemaker/session.py in endpoint_from_production_variants(self, name, production_variants, tags, kms_key, wait, data_capture_config_dict, async_inference_config_dict, explainer_config_dict)
   4506         Returns:
   4507             str: The name of the created ``Endpoint``.
-> 4508         """
   4509         update_list_of_dicts_with_values_from_config(
   4510             production_variants,

~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    528                 )
    529             # The "self" in this scope is referring to the BaseClient.
--> 530             return self._make_api_call(operation_name, kwargs)
    531 
    532         _api_call.__name__ = str(py_operation_name)

~/anaconda3/envs/tensorflow2_p310/lib/python3.10/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    962             error_code = parsed_response.get("Error", {}).get("Code")
    963             error_class = self.exceptions.from_code(error_code)
--> 964             raise error_class(parsed_response, operation_name)
    965         else:
    966             return parsed_response

ClientError: An error occurred (ValidationException) when calling the CreateEndpointConfig operation: Customized model data download timeout is not supported.

Please help me to check whether this feature is available in China Region

**Comment by akrishna1995** [comment]
From the error message I believe this is not supported in those regions, can you please try a different region and confirm if it fails with the latest sagemaker version? Closing this issue for now feel free to reopen if you have further questions. Thanks
