### ISSUE TITLE
Add transformers v4.29.0 compatibility to sagemaker.huggingface

### ISSUE THREAD

**Issue by phall1** [aws/sagemaker-python-sdk#3896]
**Describe the feature you'd like**
Add compatibility with transformers v4.29.0

**How would this feature be used? Please describe.**
It would unblock usage of transformers v4.29.0 with the 

**Describe alternatives you've considered**
-

**Additional context**
What inspired me to make this issue is that BitsAndBytesConfig was added in transformers v 4.29.0

https://github.com/huggingface/transformers/pull/21579

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
