### ISSUE TITLE
Running the example results in TypeError missing argument "role"

### ISSUE THREAD

**Issue by neuront** [aws/sagemaker-python-sdk#392]
### System Information

* Ubuntu 18.04 with Python 3.6
* sagemaker version: 1.10.0

Installed packages

    boto3==1.9.5
    botocore==1.12.5
    docutils==0.14
    jmespath==0.9.3
    numpy==1.15.1
    pandas==0.23.4
    pkg-resources==0.0.0
    protobuf==3.6.1
    protobuf3-to-dict==0.1.5
    python-dateutil==2.7.3
    pytz==2018.5
    PyYAML==3.13
    s3transfer==0.1.13
    sagemaker==1.10.0
    scipy==1.1.0
    six==1.11.0
    urllib3==1.23

### Describe the problem / Steps to reproduce

Running the first example in your README results in `TypeError`. (Named as `main.py`)

    from sagemaker.mxnet import MXNet

    # Configure an MXNet Estimator (no training happens yet)
    mxnet_estimator = MXNet('train.py',
                        train_instance_type='ml.p2.xlarge',
                        train_instance_count=1)

The traceback is like (when running from a virtualenv on Ubuntu OS)

    Traceback (most recent call last):
      File "main.py", line 6, in <module>
        train_instance_count=1)
      File "/xxx/.venv/lib/python3.6/site-packages/sagemaker/mxnet/estimator.py", line 64, in __init__
        image_name=image_name, **kwargs)
      File "/xxx/.venv/lib/python3.6/site-packages/sagemaker/estimator.py", line 575, in __init__
        super(Framework, self).__init__(**kwargs)
    TypeError: __init__() missing 1 required positional argument: 'role'

It seems that the constructors of [`MXNet`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/mxnet/estimator.py#L26) class and its direct parent [`Framework`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L560) don't require the `role` argument, while the constructor of `Framework`'s parent [`EstimatorBase`](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L48) does.

Btw, how am I supposed to obtain a `role` object or a `session` object if I'm testing it in my local environment? Can you give some examples?

**Comment by mvsusp** [comment]
Hi @neuront,

You can find documentation about the MXNet estimator here https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/mxnet/README.rst

The role is mandatory because it is required to train using SageMaker. For local training, the role is mandatory but it is not validated.

Thanks for reporting this issue, I changed the example to include the missing parameters.

Please, let me know if you have any questions.

**Comment by neuront** [comment]
@mvsusp Thanks for your reply. Let me add more details to the pull request.

**Comment by mvsusp** [comment]
Happy to help.

Thanks for using SageMaker!
