### ISSUE TITLE
Support for RetryPolicy in LambdaStep

### ISSUE THREAD

**Issue by stiebels** [aws/sagemaker-python-sdk#3922]
**Describe the feature you'd like**

- **Component**: `LambdaStep`
- **Problem**: In contrast to most other steps, `LambdaStep` does not offer support for a `RetryPolicy`. This may be an issue for common transient errors such as temporarily exceeding the concurrency limit of Lambda in an account. The Lambda invocation would fail with a transient error, making the entire SageMaker Pipeline fail. Support for a `RetryPolicy` would be a very convenient way to handle this case.

**How would this feature be used? Please describe.**
Add support for `RetryPolicy` to `LambdaStep`, resulting in a repeated execution of the corresponding action on/of the targeted (or to-be-created) Lambda in case of failure of invocation, the Lambda execution itself or the Lambda's creation (if applicable).

**Describe alternatives you've considered**
An alternative would be to _not_ use `LambdaStep` but implement the logic e.g. in a `ProcessingStep` that creates/invokes the Lambda via `boto3` and handles any errors as desired.

**Comment by ShwetaSingh801** [comment]
Hi @stiebels, 

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions. 

Best,
Shweta
