### ISSUE TITLE
Unable to upgrade to new sagemaker version due to PyYAML conflict

### ISSUE THREAD

**Issue by brianloyal** [aws/sagemaker-python-sdk#3928]
**Describe the bug**
Running the command`%pip install sagemaker==2.165 --upgrade` from within a SageMaker Studio notebook (Data Science Image + Python 3 kernel) results in an error due to the inability to uninstall PyYAML

**To reproduce**
Run `pip install --upgrade sagemaker with an existing installed version (2.145 in my case)

**Expected behavior**
For pip to successfully install version 2.165 (or whatever is most recent).

**Screenshots or logs**
"""
Collecting sagemaker==2.165
  Using cached sagemaker-2.165.0-py2.py3-none-any.whl
Collecting attrs<24,>=23.1.0 (from sagemaker==2.165)
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting boto3<2.0,>=1.26.131 (from sagemaker==2.165)
  Using cached boto3-1.26.153-py3-none-any.whl (135 kB)
Requirement already satisfied: cloudpickle==2.2.1 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (2.2.1)
Requirement already satisfied: google-pasta in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (0.2.0)
Requirement already satisfied: numpy<2.0,>=1.9.0 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (1.18.1)
Requirement already satisfied: protobuf<4.0,>=3.1 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (3.20.3)
Requirement already satisfied: protobuf3-to-dict<1.0,>=0.1.5 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (0.1.5)
Requirement already satisfied: smdebug-rulesconfig==1.0.1 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (1.0.1)
Requirement already satisfied: importlib-metadata<5.0,>=1.4.0 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (23.1)
Requirement already satisfied: pandas in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (1.3.5)
Requirement already satisfied: pathos in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (0.3.0)
Requirement already satisfied: schema in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (0.7.5)
Collecting PyYAML==6.0 (from sagemaker==2.165)
  Using cached PyYAML-6.0-cp37-cp37m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (596 kB)
Requirement already satisfied: jsonschema in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (3.2.0)
Requirement already satisfied: platformdirs in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (3.2.0)
Requirement already satisfied: tblib==1.7.0 in /opt/conda/lib/python3.7/site-packages (from sagemaker==2.165) (1.7.0)
Collecting botocore<1.30.0,>=1.29.153 (from boto3<2.0,>=1.26.131->sagemaker==2.165)
  Using cached botocore-1.29.153-py3-none-any.whl (10.9 MB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.7/site-packages (from boto3<2.0,>=1.26.131->sagemaker==2.165) (1.0.1)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in /opt/conda/lib/python3.7/site-packages (from boto3<2.0,>=1.26.131->sagemaker==2.165) (0.6.0)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.7/site-packages (from importlib-metadata<5.0,>=1.4.0->sagemaker==2.165) (2.2.0)
Requirement already satisfied: six in /opt/conda/lib/python3.7/site-packages (from protobuf3-to-dict<1.0,>=0.1.5->sagemaker==2.165) (1.14.0)
Requirement already satisfied: pyrsistent>=0.14.0 in /opt/conda/lib/python3.7/site-packages (from jsonschema->sagemaker==2.165) (0.15.7)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.7/site-packages (from jsonschema->sagemaker==2.165) (45.2.0.post20200210)
Requirement already satisfied: python-dateutil>=2.7.3 in /opt/conda/lib/python3.7/site-packages (from pandas->sagemaker==2.165) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /opt/conda/lib/python3.7/site-packages (from pandas->sagemaker==2.165) (2019.3)
Requirement already satisfied: ppft>=1.7.6.6 in /opt/conda/lib/python3.7/site-packages (from pathos->sagemaker==2.165) (1.7.6.6)
Requirement already satisfied: dill>=0.3.6 in /opt/conda/lib/python3.7/site-packages (from pathos->sagemaker==2.165) (0.3.6)
Requirement already satisfied: pox>=0.3.2 in /opt/conda/lib/python3.7/site-packages (from pathos->sagemaker==2.165) (0.3.2)
Requirement already satisfied: multiprocess>=0.70.14 in /opt/conda/lib/python3.7/site-packages (from pathos->sagemaker==2.165) (0.70.14)
Requirement already satisfied: typing-extensions>=4.5 in /opt/conda/lib/python3.7/site-packages (from platformdirs->sagemaker==2.165) (4.5.0)
Requirement already satisfied: contextlib2>=0.5.5 in /opt/conda/lib/python3.7/site-packages (from schema->sagemaker==2.165) (0.6.0.post1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /opt/conda/lib/python3.7/site-packages (from botocore<1.30.0,>=1.29.153->boto3<2.0,>=1.26.131->sagemaker==2.165) (1.26.15)
Installing collected packages: PyYAML, botocore, attrs, boto3, sagemaker
  Attempting uninstall: PyYAML
    Found existing installation: PyYAML 5.3
ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
Note: you may need to restart the kernel to use updated packages.
"""

**System information**
A description of your system. Please provide:
- **SageMaker 2.145**:
- **SageMaker Studio Data Science Image + Python 3 kernel**:
- **CPU**:
- **N**:

**Additional context**

**Comment by trungleduc** [comment]
I can not reproduce the issue on both SageMaker Studio notebook and my local machine. Please feel free to reopen if you still have this issue.
