### ISSUE TITLE
Use logger and remove print statements

### ISSUE THREAD

**Issue by anjali-chadha** [aws/sagemaker-python-sdk#3938]
**Describe the feature you'd like**
Request to convert print statements to logger. This conversion will provide better control over the logs in the application.
Eg: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/fw_utils.py#L475-L477

There was a previous pull request (PR #3591) that addressed this issue, but some print statements still exist in the codebase.

**Comment by akrishna1995** [comment]
PR has been merged : https://github.com/aws/sagemaker-python-sdk/pull/4133. Feel free to reopen if you have any issues - Thank you
