### ISSUE TITLE
Support for huggingface-llm latest version on a faster cadence

### ISSUE THREAD

**Issue by hlo-world** [aws/sagemaker-python-sdk#3975]
**Describe the feature you'd like**
Support for huggingface-llm latest version on a faster cadence, as there seems to be a significant time delay in updating the version in sagemaker-python-sdk.

**Comment by krumetoft** [comment]
Meanwhile on version 0.9.1. Support would be much appreciated.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
