### ISSUE TITLE
Error creating pipeline with TransformStep when use_custom_job_prefix = True

### ISSUE THREAD

**Issue by svpino** [aws/sagemaker-python-sdk#3991]
SageMaker SDK Version: 2.171.0

Trying to create a pipeline that includes a TransformStep and uses `PipelineDefinitionConfig(use_custom_job_prefix=True)` raises an exception: 

```
TypeError: expected string or bytes-like object
```

The exception happens here: https://github.com/aws/sagemaker-python-sdk/blob/baf96cd540dd9c46ee72e730f9904623184d2844/src/sagemaker/utils.py#L140

You can reproduce the issue with this code:

```python
from sagemaker.workflow.utilities import trim_request_dict

sagemaker_session = sagemaker.session.Session()

class Config:
    pipeline_definition_config = None

config = Config()
config.pipeline_definition_config = pipeline_definition_config

request_dict = sagemaker_session._get_transform_request(
    job_name=None,
    model_name="",
    strategy="",
    max_concurrent_transforms="",
    max_payload="",
    env="",
    input_config="",
    output_config="",
    resource_config="",
    experiment_config="",
    tags="",
    data_processing="")

request_dict["TransformJobName"] = base_from_name(request_dict["TransformJobName"]) 
```

Notice how I'm passing `None` as the job name. That's what the SDK is doing here: https://github.com/aws/sagemaker-python-sdk/blob/baf96cd540dd9c46ee72e730f9904623184d2844/src/sagemaker/transformer.py#L665

It uses the current job name, which is initialized with `None`, and it only changes inside the execution of the `tranform()` function.

The workaround is to manually set `_current_job_name` as I'm doing below:

```python
transformer = Transformer(
    model_name=create_model_step.properties.ModelName,
    base_transform_job_name="transform",
    instance_type="ml.c5.xlarge",
    instance_count=1,
    accept="application/json",
    strategy="SingleRecord",
    assemble_with="Line",
    output_path="...",
)
transformer._current_job_name = "transform"
```

**Comment by svia3** [comment]
Hi @svpino,

Looks like there may be a gap between setting the base_job_name via a transformer and manually tuning it when building the api request. A couple of follow up questions
- Does this issue only persist for your TrainingJobs? 
- I see that you are using a SageMaker session -- the expectation when using and creating a pipeline is that we initialize a PipelineSession object, indicating that the returned args of your job instances, i.e.  `Transformer`, will be passed into their corresponding step, i.e., TransformStep. Try using a `PipelineSession` and let me know if this fixes the issue. [[PipelineSession in the SageMaker python-sdk]](https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.pipeline_context.PipelineSession)

Looks like you've also found a quick workaround. In the meantime, can you also try calling the `.transform` method to produce the arguments for the training job? The current critical path assumes that this is to be used when generating the job arguments for a pipeline step, and in the process, initialize this` _current_job_name` field correctly.

https://github.com/aws/sagemaker-python-sdk/blob/baf96cd540dd9c46ee72e730f9904623184d2844/src/sagemaker/transformer.py#L252-L261

Thanks!

**Comment by svpino** [comment]
Hey @svia3!

Thanks for getting back to me!

* This issue is only happening when using a TransformStep. This doesn't happen with a Training Job.
* The SageMaker session is only on the small script I created to understand the problem. My pipeline uses a PipelineSession wherever is required.

I'm not sure I understand how can I call the `.transform()` method when defining the pipeline. Remember, I'm setting up a Transformer that will be used as part of a pipeline (a TransformStep) so `.transform()` will be automatically called when the pipeline runs.

Does that make sense?

**Comment by svpino** [comment]
Never mind. I now understand what you meant. I had to use the new [PipelineSession based-syntax](https://sagemaker.readthedocs.io/en/stable/amazon_sagemaker_model_building_pipeline.html), and everything works.,

**Comment by svia3** [comment]
Awesome!! That is correct, using a `PipelineSession` directly fixes this issue. Seems you answered your own question before I could reply. 😄 Glad you are unblocked.
