### ISSUE TITLE
AutoML Job V2

### ISSUE THREAD

**Issue by shayan1897** [aws/sagemaker-python-sdk#3995]
**Describe the feature you'd like**
Enabling creation of automl v2 job and possibly with backward compatibility with V1 to help with migration.

**How would this feature be used? Please describe.**
As AWS moving and recommending to use automl v2. 

**Describe alternatives you've considered**
it would only be boto3

**Additional context** N/A

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
