### ISSUE TITLE
Asynchronous fit

### ISSUE THREAD

**Issue by defreez** [aws/sagemaker-python-sdk#4]
My first use for SageMaker involved async submission of KMeans jobs. EstimatorBase.fit raises NotImplemented('Asynchronous fit not available') if the wait parameter is set to false.

Is fit() necessarily synchronous, or is it just not implemented _yet_?

**Comment by winstonaws** [comment]
Hey, thanks for trying out SageMaker!

We're going to support async fit, it just didn't make the cut for launch. This is on our backlog, and we'll give you an update when we have an ETA.

**Comment by defreez** [comment]
That's great to hear. Thanks!

**Comment by iquintero** [comment]
This is already implemented in master. However its not released to pypi yet. I will reopen this issue to track it and close it once this feature lands in pypi. Anyone interested in using it now can install the sdk from source.

**Comment by iquintero** [comment]
This was just released in v1.1.0 to PyPI
