### ISSUE TITLE
Fine-tuning Tensorflow object detection algorithm on custom data error related to 'transfer_learning.py'

### ISSUE THREAD

**Issue by yangwu-hpa** [aws/sagemaker-python-sdk#4006]
**Describe the bug**

When fine-tuning a pre-trained model on a custom dataset, we get a bbox invalid exception from 'transfer_learning.py' (stack trace below).

**To reproduce**

The notebook we are following is [here](https://github.com/aws/amazon-sagemaker-examples/blob/main/introduction_to_amazon_algorithms/object_detection_tensorflow/Amazon_Tensorflow_Object_Detection.ipynb). The only difference is we are using a custom dataset with the same directory structure.

```
input_directory
    |--images
        |--abc.png
        |--def.png
    |--annotations.json
```

**Screenshots or logs**

Here are the Cloudwatch logs:

```
Traceback (most recent call last):
  File "/opt/ml/code/transfer_learning.py", line 246, in <module>

run_with_args(args)
  File "/opt/ml/code/transfer_learning.py", line 201, in run_with_args

train_and_save_model(
  File "/opt/ml/code/train.py", line 124, in train_and_save_model

total_loss += train_step_fn(image_tensors, gt_box_tensors, gt_classes_one_hot_tensors).numpy()
  File "/usr/local/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/tmp/__autograph_generated_file9lo6kym6.py", line 35, in tf__train_step_fn
    losses_dict = ag__.converted_call(ag__.ld(model).loss, (ag__.ld(prediction_dict), ag__.ld(shapes)), None, fscope)
  File "/tmp/__autograph_generated_filegbnxvrom.py", line 86, in tf__loss
    (batch_cls_targets, batch_cls_weights, batch_reg_targets, batch_reg_weights, batch_match) = ag__.converted_call(ag__.ld(self)._assign_targets, (ag__.converted_call(ag__.ld(self).groundtruth_lists, (ag__.ld(fields).BoxListFields.boxes,), None, fscope), ag__.converted_call(ag__.ld(self).groundtruth_lists, (ag__.ld(fields).BoxListFields.classes,), None, fscope), ag__.ld(keypoints), ag__.ld(weights), ag__.ld(confidences)), None, fscope)
  File "/tmp/__autograph_generated_file158xlg1v.py", line 48, in tf___assign_targets

groundtruth_boxlists = [ag__.converted_call(ag__.ld(box_list).BoxList, (ag__.ld(boxes),), None, fscope) for boxes in ag__.ld(groundtruth_boxes_list)]
  File "/tmp/__autograph_generated_file158xlg1v.py", line 48, in <listcomp>
    groundtruth_boxlists = [ag__.converted_call(ag__.ld(box_list).BoxList, (ag__.ld(boxes),), None, fscope) for boxes in ag__.ld(groundtruth_boxes_list)]
  File "/opt/ml/code/object_detection/core/box_list.py", line 55, in __init__
    raise ValueError("Invalid dimensions for box data: {}".format(boxes.shape))

ValueError: in user code:
    File "/opt/ml/code/train.py", line 56, in train_step_fn  *
        losses_dict = model.loss(prediction_dict, shapes)
    File "/opt/ml/code/object_detection/meta_architectures/ssd_meta_arch.py", line 818, in loss  *
        (
    File "/opt/ml/code/object_detection/meta_architectures/ssd_meta_arch.py", line 1013, in _assign_targets  *
        groundtruth_boxlists = [box_list.BoxList(boxes) for boxes in groundtruth_boxes_list]
    File "/opt/ml/code/object_detection/core/box_list.py", line 55, in __init__  **
        raise ValueError("Invalid dimensions for box data: {}".format(boxes.shape))
    ValueError: Invalid dimensions for box data: (0,)
```

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.173.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: Tensorflow
- **Training image**: `763104351884.dkr.ecr.us-east-1.amazonaws.com/tensorflow-training:2.11.0-gpu-py39`
- **Training script**: `s3://jumpstart-cache-prod-us-east-1/source-directory-tarballs/tensorflow/transfer_learning/od1/v1.1.0/sourcedir.tar.gz`
- **CPU or GPU**: GPU
- **Custom Docker image (Y/N)**: N

**Additional context**

There are related issues [here](https://github.com/tensorflow/models/issues/10953) and [here](https://github.com/aws/amazon-sagemaker-examples/issues/3852). Here is an excerpt from these issue:

---
When fine tuning, the notebook states (section 3 of the above link):

The annotations.json file should have information for bounding_boxes and their class labels. It should have a dictionary with keys "images" and "annotations". Value for the "images" key should be a list of entries, one for each image of the form {"file_name": image_name, "height": height, "width": width, "id": image_id}. Value of the 'annotations' key should be a list of entries, one for each bounding box of the form {"image_id": image_id, "bbox": [xmin, ymin, xmax, ymax], "category_id": bbox_label}.

If someone is familiar on this topic, one could rapidly guess that what you are asking here is to use the COCO annotation format (as I did) but if we look closer, specifically at the bbox key, what is asked to be filled is:

"bbox": [xmin, ymin, xmax, ymax]

but the [COCO annotation format for object detection](https://cocodataset.org/#format-data) specifies:

"bbox": [x,y,width,height]

So how do they map each other? at least for me is not clear that:

xmin => x ( min? )
xmax => width (first one will be the width of the image, while the second one is the absolute coordinate)

but then again, if you deep dive into this, and [download any](https://s3.console.aws.amazon.com/s3/buckets/jumpstart-cache-prod-us-east-1?prefix=training-datasets/PennFudanPed_COCO_format/&region=us-east-1) of the pedestrian examples images proposed in the notebook, and you take the corresponding annotation, and plot their corresponding bbox (like, manually on paint for instance), you'll see that what is being used on the pedestrian dataset is:

"bbox": [xmin, ymin, xmax, ymax]

As only the absolute coordinates creates the correct bbox.

---

We suspect the the issue lies with bbox format. As we do not have insights into how the `transfer_learning.py` works, the examples and documentation have not been enough for us to efficiently identify what exactly is wrong and how to best proceed with correcting the annotations. We would appreciate some help on this.

Thanks.

**Comment by vivekmadan2** [comment]
@yangwu-hpa Are you using the COCO format for the dataset? As stated above, expected dataset format for TF OD algorithm is different and there is mapping inside the algorithm. 

If you would like to inspect the code, you can download the  training script by awscli as 
aws s3 cp s3://jumpstart-cache-prod-us-east-1/source-directory-tarballs/tensorflow/transfer_learning/od1/v1.1.0/sourcedir.tar.gz .

**Comment by YangWu1227** [comment]
@vivekmadan2 Upon looking into the mapping in the script, I was able to find the error and subsequently fixed it. Thanks.
