### ISSUE TITLE
Support for setting artifact bucket and prefix via PipelineExperimentConfig

### ISSUE THREAD

**Issue by maltelorbach** [aws/sagemaker-python-sdk#4022]
Feature request: there was a recent addition (https://github.com/aws/sagemaker-python-sdk/pull/3965) to the `experiment.Run` class allowing customizing the output path of logged artifacts. In order to make this feature available for Pipelines, the `PipelineExperimentConfig` should support setting the artifact bucket and prefix as well.

https://github.com/aws/sagemaker-python-sdk/blob/219ad245238c94a31e0960a9ede0470a6b075b56/src/sagemaker/workflow/pipeline_experiment_config.py#L27-L35

https://github.com/aws/sagemaker-python-sdk/blob/219ad245238c94a31e0960a9ede0470a6b075b56/src/sagemaker/experiments/run.py#L91-L105

**Comment by ShwetaSingh801** [comment]
Hi @maltelorbach,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
