### ISSUE TITLE
Docker compose v2 support in local mode

### ISSUE THREAD

**Issue by sateeshmannar** [aws/sagemaker-python-sdk#4038]
**Describe the bug**
Local mode execution currently just uses "docker-compose" and dosen't use the newer  "docker compose".
The _compose function @ image,py should attempt to find both docker compose executables and use the one thats available with v2 (docker compose) being the first option.

relevant code to change:
https://github.com/aws/sagemaker-python-sdk/blob/6a7002ebe50de51316dbedf8e083839f2b408c02/src/sagemaker/local/image.py#L96-L103

https://github.com/aws/sagemaker-python-sdk/blob/6a7002ebe50de51316dbedf8e083839f2b408c02/src/sagemaker/local/image.py#L712-L730

**To reproduce**
Install the latest version of SageMaker SDK and attempt to run a processing or training task in local mode.
- Run local mode WITHOUT installing package "docker-compose" (docker-compose 1.29.2)

**Expected behavior**
local mode execution should attempt to find both docker compose executables ("docker compose" , "docker-compose" in the listed order) and use the one thats available. "docker compose" the newer version should be the preferred option if both executables are found in the runtime environment. 

**System information**
- **SageMaker Python SDK version**: 2.173.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: SageMaker Processing
- **Python version**: 3.11.4
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Yes

**Additional context**
The custom docker image was working in local mode until the dependency package (docker-compose 1.29.2) was removed local requirements as part of release [v2.164.0](https://github.com/aws/sagemaker-python-sdk/releases/tag/v2.164.0)

**Comment by lorenzwalthert** [comment]
Also see https://github.com/aws/sagemaker-python-sdk/issues/3613.

**Comment by Ce11an** [comment]
Any movement on this? I have tried several different methods in my CI pipeline to no avail.

**Comment by jmahlik** [comment]
> Any movement on this? I have tried several different methods in my CI pipeline to no avail.

What kind of issues are you running in to? Do you have a traceback? Did you add a shim in to map compose to `docker-compose` or [directly download the binary](https://sagemaker.readthedocs.io/en/stable/overview.html?highlight=local%20mode#local-mode)?
