### ISSUE TITLE
Sagemaker with Dockerfile

### ISSUE THREAD

**Issue by celsofranssa** [aws/sagemaker-python-sdk#4071]
I am trying to automatize [AWS Sagemaker][1] as a base for a large series of deep-learning experiments. 

My current approach uses the [Estimators][2] as the code snippet shows:

```python
import hydra
from omegaconf import omegaconf
from sagemaker.pytorch.estimator import PyTorch


@hydra.main(config_path="setting/", config_name="setting.yaml", version_base=None)
def run_on_sagemaker(params):
    role = "<your sagemaker arn role>"
    estimator = PyTorch(
        entry_point=params.sagemaker.entry_point,
        role=role,
        framework_version=params.sagemaker.framework_version,
        py_version=params.sagemaker.py_version,
        instance_type=params.sagemaker.instance_type,
        instance_count=params.sagemaker.instance_count,
        volume_size=params.sagemaker.volume_size,
        hyperparameters=omegaconf.OmegaConf.to_container(params, resolve=True, throw_on_missing=True)
    )
    estimator.fit()


if __name__ == '__main__':
    run_on_sagemaker()

```

However, when building the indicated [Pytorch docker image][3], it seems that Sagemaker is not able to install all the dependencies correctly. 

Therefore, would it be possible to explicitly declare (through a Dockerfile, for instance) how to create the Docker image?

  [1]: https://sagemaker.readthedocs.io/en/stable/index.html
  [2]: https://sagemaker.readthedocs.io/en/stable/api/training/estimators.html
  [3]: https://hub.docker.com/layers/pytorch/pytorch/2.0.0-cuda11.7-cudnn8-devel/images/sha256-96ccb2997a131f2455d70fb78dbb284bafe4529aaf265e344bae932c8b32b2a4?context=explore

**Comment by j-adamczyk** [comment]
You can use ECR to run anything in SageMaker with your own Docker image. You have to create images and push to ECR yourself, however.

**Comment by celsofranssa** [comment]
Awesome. Once the container is started, is it possible to run some kind of script before the Python entry point (bash commands, for example)?

**Comment by celsofranssa** [comment]
> You can use ECR to run anything in SageMaker with your own Docker image. You have to create images and push to ECR yourself, however.

What should be in the Docker image? Just the configured environment  (based on requirements.txt, for instance), or should it contain all the source code, training, prediction, and evaluation data?

**Comment by j-adamczyk** [comment]
Just the environment, the source code and data will be copied by SageMaker. See "Bring Your Own Container (BYOC)" sections in SageMaker docs and examples for this.

**Comment by celsofranssa** [comment]
I've added the image URI (from AWS ECR). However, the estimator is tucked on:

```python
[2023-08-18 19:44:20,190][botocore.credentials][INFO] - Found credentials in shared credentials file: ~/.aws/credentials
```
