### ISSUE TITLE
Allow non-py files to be uploaded to sagemaker remote jobs when include_local_workdir is enabled

### ISSUE THREAD

**Issue by DJanyavula** [aws/sagemaker-python-sdk#4094]
**Describe the feature you'd like**
Currently the remote decorator job settings allow only files with .py extension to be uploaded because of below filter applied:
https://github.com/aws/sagemaker-python-sdk/blob/dd4be4c9f77c6b8bde7c2d62aa3980285a821451/src/sagemaker/remote_function/job.py#L896

**How would this feature be used? Please describe.**
This can be removed because in certain usecases, teams wants to upload their non-py files as well as for their remote job execution. An example would be conf files either in yaml/conf format that are needed for remote job execution.

**Describe alternatives you've considered**
Renaming the .conf/.yaml file as .py as a dirty hack and it works fine.

**Additional context**

**Comment by diegodebrito** [comment]
I am also struggling with the same issue. Maybe a flag "python_files_only=True" by default?
