### ISSUE TITLE
Support larger memory instance types for RepackModelStep

### ISSUE THREAD

**Issue by michael-lum** [aws/sagemaker-python-sdk#4098]
**Describe the feature you'd like**
Please either provide a larger default memory instance type or allow for configuration for the instance type of the RepackModelStep. This step is currently added automatically for the CreateModel step if custom code is provided but does not allow configuration of instance type.

**How would this feature be used? Please describe.**
For Large Language Models, model sizes can be larger than 30MB. This would allow providing custom code for model artifacts of large sizes with an automated repackaging step.

**Describe alternatives you've considered**
The only other alternative is to manually package the inference and loading code directly into the model zip or implementing the packaging logic ourself.

**Additional context**
[Code Link](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/workflow/_utils.py#L45)

**Comment by ShwetaSingh801** [comment]
Hi @michael-lum,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
