### ISSUE TITLE
Support local source for `TrainingInput`

### ISSUE THREAD

**Issue by lorenzwalthert** [aws/sagemaker-python-sdk#4119]
**Describe the feature you'd like**
While `ProcessingInput` supports a local path as a source, [TrainingInput](https://sagemaker.readthedocs.io/en/stable/api/utility/inputs.html) does only support S3. Since the two Input helpers are very similar in many ways, I'd expect feature parity here.

This is a bit inconvenient when you want to add inputs to training that are not yet on S3, because you have to think of a path where to store them, upload them, and then pass the location information to `TrainingInput()`.

**How would this feature be used? Please describe.**

Avoid boilerplate code to upload files to S3.

**Describe alternatives you've considered**

Uploading manually.

**Additional context**

I think it would be quite simple to implement as it should just follow the logic / code in `ProcessingInput`.

**Comment by ShwetaSingh801** [comment]
Hi @lorenzwalthert,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
