### ISSUE TITLE
SageMaker Model Cards UI doesn't show Model Cards created using model package details

### ISSUE THREAD

**Issue by l-m-j** [aws/sagemaker-python-sdk#4120]
**Describe the bug**
When creating a model card using model package details, the model card is created and visible from the CLI but is not visible in the Model Cards section of the UI.

**To reproduce**
Create a model package details object like below. The code was obtained from the following [AWS article](https://aws.amazon.com/blogs/machine-learning/integrate-amazon-sagemaker-model-cards-with-the-model-registry/).
```
mp = ModelPackage.from_model_package_arn(
    model_package_arn="arn:aws:sagemaker:us-east-2:000000000000:model-package/test-model-cards/7"
)

mc = ModelCard(
    name="test-model-card-from-model-package", 
    model_package_details=mp
)

mc.create()
```

The output from the create function returns the ARN of the newly created model card i.e. arn:aws:sagemaker:us-east-2:000000000000:model-card/test-model-card-from-model-package' but does not show in the UI.

**Expected behavior**
The model card should be visible under Governance -> Model cards section of the SageMaker management console UI.

**Screenshots or logs**
Model card not visible after creation in the UI.
![sagemaker_model_cards_ui](https://github.com/aws/sagemaker-python-sdk/assets/56968429/647bd57a-31be-4328-94d1-8a350923c301)

Model card can be found using CLI command `aws sagemaker list-model-cards`
![list_model_cards_output](https://github.com/aws/sagemaker-python-sdk/assets/56968429/e6658439-5ddb-4e73-85b2-2e089ee79eb5)

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.184.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:  SKLearn
- **Framework version**: 0.23-1
- **Python version**: 3.10
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: N

It should also be noted that we are experiencing this issue with custom algorithms deployed as ECR images.

**Additional context**

**Comment by mohanasudhan** [comment]
Thanks for bringing the issue to our attention. We have created an internal ticket to track it, as it is not PySDK-related. For future reference, please use this tracking ticket - https://tt.amazon.com/P109747960

**Comment by vermavarun** [comment]
We are experiencing the same issue any update on it? @mohanasudhan

**Comment by vermavarun** [comment]
@mohanasudhan @HessTaha @l-m-j @martinRenou 
Model card is already there but not visible. 
To view:

1. Go to Filter models or status by property or value
2. type model card name: {name of your model card}

and then you will be able to see

<img width="592" alt="image" src="https://github.com/aws/sagemaker-python-sdk/assets/8264476/b4d6e3ec-6420-4cf1-8752-215b74668733">
<hr/>
<img width="402" alt="image" src="https://github.com/aws/sagemaker-python-sdk/assets/8264476/a62a0f68-13c0-4a05-83c8-45def1027570">
