### ISSUE TITLE
JumpstartEstimator doesn't recognize trn1 instance types

### ISSUE THREAD

**Issue by mstfldmr** [aws/sagemaker-python-sdk#4166]
**Describe the bug**
I try creating a training job on a trn1 instance with Jumpstart estimator, I get error: 

> Unsupported processor: trn. You may need to upgrade your SDK version (pip install -U sagemaker) for newer processors. Supported processor(s): cpu, gpu.

**To reproduce**
```
from sagemaker.jumpstart.estimator import JumpStartEstimator

estimator = JumpStartEstimator(
    model_id=model_id,
    environment={"accept_eula": "true"},
    disable_output_compression=True,      
    instance_type = 'ml.trn1.2xlarge'
)

estimator.set_hyperparameters(instruction_tuned="True", epoch="10")
estimator.fit({"training": train_data_location})
```

> Unsupported processor: trn. You may need to upgrade your SDK version (pip install -U sagemaker) for newer processors. Supported processor(s): cpu, gpu.

**Expected behavior**
Start a training job with a ml.trn1.2xlarge instance.
I get the same error for ml.trn1.32xlarge instance type.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.189.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: PyTorch 1.12 Python 3.8 CPU Optimized kernel on Sagemaker Studio
- **Python version**: 3.8
- **CPU or GPU**:
- **Custom Docker image (Y/N)**: N

**Additional Context**
I have a service quota for ml.trn1.2xlarge Training Jobs

**Comment by evakravi** [comment]
Which model id is this? If it's for Llama, this instance type is not supported

**Comment by mstfldmr** [comment]
yes, it was Llama2. I am looking forward to see it being supported.
