### ISSUE TITLE
HuggingFace Estimator requires `py_version` when `image_uri` is specified

### ISSUE THREAD

**Issue by j-adamczyk** [aws/sagemaker-python-sdk#4179]
**Describe the bug**

As [per documentation](https://sagemaker.readthedocs.io/en/stable/frameworks/huggingface/sagemaker.huggingface.html), HuggingFace Estimator requires providing `py_version` argument when `image_uri` argument is specified. It should not, since when I point to a specific image, this argument doesn't matter. Curiously, `transformers_version` and `pytorch_version` are, properly, not required then.

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
