### ISSUE TITLE
Accept `hyperparameters` in `yaml` format

### ISSUE THREAD

**Issue by celsofranssa** [aws/sagemaker-python-sdk#4197]
Sagemaker Estimators could accept `hyperparameters` in yaml format such as provide from [Hydra](https://hydra.cc/) and [OmegaConf](https://omegaconf.readthedocs.io/en/2.3_branch/).

**Comment by akrishna1995** [comment]
We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback.
