### ISSUE TITLE
Sagemaker train documentation has a bug

### ISSUE THREAD

**Issue by matthewchung74** [aws/sagemaker-python-sdk#4199]
**What did you find confusing? Please describe.**

Here: 
https://huggingface.co/docs/sagemaker/train
there is this line
> If you are running a TrainingJob locally, define instance_type='local' or instance_type='local-gpu' for GPU usage. Note that this will not work with SageMaker Studio.

in this bug, @dosatos pointed out to me that
https://github.com/aws/sagemaker-python-sdk/issues/4198#issuecomment-1764746321

local-gpu should be local_gpu

**Comment by celsofranssa** [comment]
> **What did you find confusing? Please describe.**
> 
> Here: https://huggingface.co/docs/sagemaker/train there is this line
> 
> > If you are running a TrainingJob locally, define instance_type='local' or instance_type='local-gpu' for GPU usage. Note that this will not work with SageMaker Studio.
> 
> in this bug, @dosatos pointed out to me that [#4198 (comment)](https://github.com/aws/sagemaker-python-sdk/issues/4198#issuecomment-1764746321)
> 
> local-gpu should be local_gpu

I've posted a related issue #4196.

**Comment by akrishna1995** [comment]
Thank you for your input. The training documentation has since been updated to `local_gpu` here: https://huggingface.co/docs/sagemaker/train. Please reopen this issue if there are any more concerns.
