### ISSUE TITLE
Support processing datasets from S3 directly which have already been processed in the desired format

### ISSUE THREAD

**Issue by ragavvenkatesan** [aws/sagemaker-python-sdk#42]
Hi,

We are trying to support SM algorithms, where the user has multiple channels of processed data in S3 that is ready. The plan is to create a ``AmazonS3BaseEstimator`` class that will inherit from ``AmazonBaseEstimator`` class and will overwrite the ``record_set`` method. In this method, we will return a list of ``RecordSet`` objects. The ``_TrainingJob`` class already works with a dictionary of multiple channels of data. Therefore, we will overwrite the ``fit`` method in our class with ``data`` element being a dictionary of multiple channels of ``record`` objects. 

User will have to supply in their ``fit`` call, a list of S3 uri's. 

Thanks,
R

**Comment by ragavvenkatesan** [comment]
CC: @mvsusp @owen-t @orchidmajumder @vrkhare

**Comment by owen-t** [comment]
Hi Ragav,

I'd be happy to help here - it's not clear what your question is.

Please arrange a call or meeting with me.

Thanks,

Owen.
