### ISSUE TITLE
LinearLearner local mode - ShardedByS3Key is not currently supported in Local Mode

### ISSUE THREAD

**Issue by russau** [aws/sagemaker-python-sdk#420]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: LinearLearner
- **Framework Version**: sagemaker==1.11.0
- **Python Version**: 3.6.5
- **CPU or GPU**: CPU
- **Python SDK Version**: sagemaker==1.11.0
- **Are you using a custom image**: no

### Describe the problem

Attempting to use the LinearLearner estimator in local mode throws the exception:

```
RuntimeError: DataDistribution: ShardedByS3Key is not currently supported in Local Mode
```

### Minimal repro / logs

To repro I'm just taking the [multiclass classifiers](https://aws.amazon.com/blogs/machine-learning/build-multiclass-classifiers-with-amazon-sagemaker-linear-learner/) example and switching it use to local mode.

```
multiclass_estimator = sagemaker.LinearLearner(role=sagemaker.get_execution_role(),
                                               train_instance_count=1,
                                               train_instance_type='local',
                                               predictor_type='multiclass_classifier',
                                               num_classes=7)
```

Digging thru the code I see that [amazon_estimator.py](https://github.com/aws/sagemaker-python-sdk/blob/dbbe9a4083405fe23393ec9a2218c04d68f17a50/src/sagemaker/amazon/amazon_estimator.py#L220) sets the `s3_input` to `distribution='ShardedByS3Key'`.

Is there a way to create a FullyReplicated recordset and get local mode working?

**Comment by iquintero** [comment]
Hi @russau 

Linear Learner is not supported in Local Mode (none of the Amazon 1P Algorithms are). These containers are not public and can't be pulled into your local environment.

**Comment by laurenyu** [comment]
Added documentation in #575 - going to close this issue now. Feel free to reopen if necessary.
