### ISSUE TITLE
Adding PyTorch 2.1.0 SM Training DLC to `UNSUPPORTED_DLC_IMAGE_FOR_SM_PARALLELISM` list

### ISSUE THREAD

**Issue by sirutBuasai** [aws/sagemaker-python-sdk#4241]
Hi, we have recently released [PyTorch 2.1.0 SM Training DLC](https://github.com/aws/deep-learning-containers/releases/tag/v1.0-pt-sagemaker-2.1.0-tr-py310). However, this release does not yet contain support for SMModelParallel and SMDataParallel. Please consider adding the PT2.1 SM Training DLCs into the unsupported list declared [here](https://github.com/aws/sagemaker-python-sdk/blob/d355d5b01b892c7baa314c1ce0c1243b850653b9/src/sagemaker/estimator.py#L3209)

**Comment by mohanasudhan** [comment]
@sirutBuasai  can you please cut a PR for the same?
