### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'Mapping'

### ISSUE THREAD

**Issue by nectario** [aws/sagemaker-python-sdk#4245]
**Describe the bug**
When using the API I get: AttributeError: module 'collections' has no attribute 'Mapping'

**To reproduce**
Just use the above module

**Expected behavior**
The sdk is using a deprecated package and the imports must change in the code to the new one. 

**Screenshots or logs**

```

Traceback (most recent call last): File "/usr/local/bin/train", line 5, in <module> from sagemaker_containers.cli.train import main
File "/usr/local/lib/python3.10/dist-packages/sagemaker_containers/cli/train.py", line 14, in <module> from 
sagemaker_containers.beta.framework import trainer File "/usr/local/lib/python3.10/dist-
packages/sagemaker_containers/beta/framework/__init__.py", line 21, in <module> from sagemaker_containers import _env as
 env File "/usr/local/lib/python3.10/dist-packages/sagemaker_containers/_env.py", line 29, in <module> from 
sagemaker_containers import _content_types, _logging, _mapping, _params File "/usr/local/lib/python3.10/dist-
packages/sagemaker_containers/_mapping.py", line 151, in <module> class MappingMixin(collections.Mapping):

--
  | AttributeError: module 'collections' has no attribute 'Mapping'

```
</body>
</html>

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**:
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**:
- **Framework version**: latest
- **Python version**: 3.10
- **CPU or GPU**:GPU
- **Custom Docker image (Y/N)**:Y

**Additional context**

**Comment by trungleduc** [comment]
Hi, could you provide a minimal reproduction code? From the error message, it looks like you are using the `sagemaker_containers` package and not the `sagemaker-python-sdk`
