### ISSUE TITLE
LambdaStep does not call update_function_configuration

### ISSUE THREAD

**Issue by DRKolev-code** [aws/sagemaker-python-sdk#4251]
**Describe the bug**
On an Update the LambdaStep does not call `boto3` `update_function_configuration`.

**To reproduce**
It is missing from `def update` in `class Lambda` in `src/sagemaker/lambda_helper.py`. Only `response = lambda_client.update_function_code` is called.

**Expected behavior**
We should be able to update the configuration of the underlying lambda. Currently, we have to write custom code for that.

**Comment by ShwetaSingh801** [comment]
Hi @DRKolev-code,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta

**Comment by fjpa121197** [comment]
@ShwetaSingh801  is there any estimated time when this will get fixed? Is a PR already open for this? I might be able to contribute to this.

**Comment by fjpa121197** [comment]
Hi @DRKolev-code, is it possible to share your approach of updating the function configuration? I'm currently having the same problem, and I don't see any response from development team. Thanks in advance
