### ISSUE TITLE
Support the pipeline step `RegisterModel` in local mode

### ISSUE THREAD

**Issue by lorenzwalthert** [aws/sagemaker-python-sdk#4253]
**Describe the feature you'd like**
Support the pipeline step `RegisterModel` in local mode. Or at least add the restriction to the docs. There are other pending issues such as #826  or #4095 related to local execution that signficantly hinder local development. Back to this issue, I get 
```
botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the start_pipeline_execution operation: Step type RegisterModel is not supported in local mode.
```

**How would this feature be used? Please describe.**

Enhance producticity of debugging a sagemaker pipeline locally.

**Describe alternatives you've considered**

* Use AWS infrastructure for execution, which is much slower.
* Leverage warm pools for training to make feedback loop faster.

**Additional context**

**Comment by ShwetaSingh801** [comment]
Hi @lorenzwalthert,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request it to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
