### ISSUE TITLE
Update fastapi dependency version > 0.100 for pydantic v2 support

### ISSUE THREAD

**Issue by wickeat** [aws/sagemaker-python-sdk#4295]
**Describe the feature you'd like**
Update the `fastapi` pinned version in `setup.py` to > 0.100, so that [pydantic](https://github.com/pydantic/pydantic) v2 is supported. 

**How would this feature be used? Please describe.**
As active developement on pydantic v1 is officially stopped with the introduction of pydantic v2, the [pinned `fastapi` version of 0.95.2](https://github.com/aws/sagemaker-python-sdk/blob/57fd632a1b4b3859dd2565c6b01d2666a3ad4570/setup.py#L69C15-L69C21) should be updated to allow for pydantic v2 support.

**Comment by jmahlik** [comment]
I just noticed in #4361 that these deps don't appear to be used in the codebase. I can't tell why they were added. Submitting a PR to remove them.

**Comment by Ce11an** [comment]
This is stopping us from upgrading. Thank you for this 🙏🏻  Hope it gets merged ASAP.

**Comment by j-adamczyk** [comment]
+1. Why is this even included if it's not used?
