### ISSUE TITLE
creating estimator with role name fails if role is default sagemaker service role

### ISSUE THREAD

**Issue by jesterhazy** [aws/sagemaker-python-sdk#43]
if you pass a role name (instead of full ARN) to estimator constructor, and you are using default role created by SageMaker, training job will fail with "unable to assume the role" ClientError:

`sagemaker-mxnet-py2-cpu-2018-01-14-15-35-12-859: Failed Reason: ClientError: SageMaker was unable to assume the role 'arn:aws:iam::<ACCOUNT>:role/AmazonSageMaker-ExecutionRole-20180114T073202'`

error message shows the sdk converted role name to ARN without the 'service-role' prefix. running the same job with corrected full ARN works:

`arn:aws:iam::<ACCOUNT>:role/service-role/AmazonSageMaker-ExecutionRole-20180114T075260`

i encountered this error starting a training job, but I assume it would impact endpoint creation in same way.

**Comment by owen-t** [comment]
Thanks for bringing this issue to our attention. We're looking into it and will post correspondence here when we have an update. 

Thanks -- Owen
