### ISSUE TITLE
Not able to deploy Serverless Endpoint with requirements.txt

### ISSUE THREAD

**Issue by sid8491** [aws/sagemaker-python-sdk#4310]
**Describe the bug**
I am trying to deploy a serverless endpoint on sagemaker with inference script and requirements.txt

`
from sagemaker.tensorflow import TensorFlowModel
from sagemaker import get_execution_role
from sagemaker import Session
import boto3
from sagemaker.serverless import ServerlessInferenceConfig
print('starting ...')

model_data = "s3://datascience--sagemaker/model_repository/project_name/model.tar.gz"

role = get_execution_role()
sess = Session()
bucket = sess.default_bucket()
region = boto3.Session().region_name

tf_framework_version = '2.0.0'

sm_model = TensorFlowModel(
    model_data = model_data,
    framework_version = tf_framework_version,
    role=role,
    container_log_level=10,
    source_dir='code',
    entry_point='inference.py'
)

predictor = sm_model.deploy(
    endpoint_name = 'classifier-serverless',
    serverless_inference_config = ServerlessInferenceConfig(
        memory_size_in_mb= 2048,
        max_concurrency= 1,
    )
)
`
Inference script and requirements are placed at the correct place.

While deploying the model, package is downloaded but not installed due to error:

`2023-12-06 05:20:37.931396: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:202] Restoring SavedModel bundle.
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/14/32/d3fa649ad7ec0b82737b92fefd3c4dd376b0bb23730715124569f38f3a08/numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8MB)
Collecting Pillow
  Downloading https://files.pythonhosted.org/packages/ea/0f/2fa195c2d8c6fe0b3dc2df5fc6ac6b8dbd005ea30aaa0fa43eca88b8c664/Pillow-8.4.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1MB)
Installing collected packages: numpy, Pillow
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/dist-packages/numpy'
Consider using the `--user` option or check the permissions.
WARNING: You are using pip version 19.3.1; however, version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR:__main__:failed to install required packages, exiting.
INFO:__main__:stopping services
Traceback (most recent call last):
  File "/sagemaker/serve.py", line 212, in _setup_gunicorn
    subprocess.check_call(pip_install_cmd.split())
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['pip3', 'install', '-r', '/opt/ml/model/code/requirements.txt']' returned non-zero exit status 1.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/sagemaker/serve.py", line 388, in <module>
    ServiceManager().start()
  File "/sagemaker/serve.py", line 355, in start
    self._setup_gunicorn()
  File "/sagemaker/serve.py", line 215, in _setup_gunicorn
    self._stop()
  File "/sagemaker/serve.py", line 303, in _stop
    os.kill(self._nginx.pid, signal.SIGQUIT)
AttributeError: 'NoneType' object has no attribute 'pid'
Traceback (most recent call last):
  File "/usr/local/bin/dockerd-entrypoint.py", line 24, in <module>
    subprocess.check_call(shlex.split(' '.join(sys.argv[1:])))
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['serve']' returned non-zero exit status 1.`

On the other hand, if I try to deploy the same model in real-time endpoint, it is getting deployed successfully without any errors.

**Comment by trungleduc** [comment]
Hi @sid8491, could you provide a fully reproducible code (including external script, data...). 
I tried to reproduce your issue with [this example](https://github.com/aws/amazon-sagemaker-examples/blob/9c1e9b4cfc56c2789470c343ae4070aabfbc4f14/sagemaker-python-sdk/scikit_learn_iris/scikit_learn_estimator_example_with_batch_transform_outputs.ipynb) but my serverless deployment can install dependencies in the `requirements.txt` file without any issue.

```python
...
predictor = model.deploy(
    initial_instance_count=1,
    instance_type=instance_type,
    serializer=JSONSerializer(),
    deserializer=JSONDeserializer(),
    serverless_inference_config=ServerlessInferenceConfig(memory_size_in_mb= 2048, max_concurrency= 1),
    endpoint_logging=True
)
```

```
Defaulting to user installation because normal site-packages is not writeable
--
Collecting cosapp
Downloading cosapp-0.12.2-py3-none-any.whl (1.0 MB)
Requirement already satisfied: typing in /opt/conda/lib/python3.6/site-packages (from cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (3.6.4)
Requirement already satisfied: pandas in /opt/conda/lib/python3.6/site-packages (from cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (0.25.0)
Collecting jsonschema
Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Requirement already satisfied: numpy>=1.12 in /opt/conda/lib/python3.6/site-packages (from cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (1.16.4)
Collecting wrapt
Downloading wrapt-1.16.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)
Requirement already satisfied: scipy in /opt/conda/lib/python3.6/site-packages (from cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.6/site-packages (from jsonschema->cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (49.6.0.post20210108)
Collecting pyrsistent>=0.14.0
Downloading pyrsistent-0.18.0-cp36-cp36m-manylinux1_x86_64.whl (117 kB)
Collecting attrs>=17.4.0
Downloading attrs-22.2.0-py3-none-any.whl (60 kB)
Collecting importlib-metadata
Downloading importlib_metadata-4.8.3-py3-none-any.whl (17 kB)
Requirement already satisfied: six>=1.11.0 in /opt/conda/lib/python3.6/site-packages (from jsonschema->cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (1.15.0)
Collecting typing-extensions>=3.6.4
Downloading typing_extensions-4.1.1-py3-none-any.whl (26 kB)
Collecting zipp>=0.5
Downloading zipp-3.6.0-py3-none-any.whl (5.3 kB)
Requirement already satisfied: pytz>=2017.2 in /opt/conda/lib/python3.6/site-packages (from pandas->cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (2021.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /opt/conda/lib/python3.6/site-packages (from pandas->cosapp->-r /opt/ml/model/code/requirements.txt (line 1)) (2.8.1)
Installing collected packages: zipp, typing-extensions, pyrsistent, importlib-metadata, attrs, wrapt, jsonschema, cosapp
WARNING: The script jsonschema is installed in '/home/sbx_user1051/.local/bin' which is not on PATH.
Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed attrs-22.2.0 cosapp-0.12.2 importlib-metadata-4.8.3 jsonschema-3.2.0 pyrsistent-0.18.0 typing-extensions-4.1.1 wrapt-1.16.0 zipp-3.6.0

```

**Comment by sid8491** [comment]
Hi @trungleduc, I think it's an issue with TensorFlowModel.
When I used the base Model class, i.e., from sagemaker.model import Model, it worked.

**Comment by trungleduc** [comment]
If you could give me a fully reproducible code, I can work on fixing this issue.

**Comment by sid8491** [comment]
how do i provide the model file? its 250 mb.

**Comment by martinRenou** [comment]
Maybe the important part to reproduce is your `requirements.txt` file, what does it contain?

**Comment by sid8491** [comment]
> Maybe the important part to reproduce is your `requirements.txt` file, what does it contain?

It was due to Tensorflow image that I was using.
It's working with version 2.0.4 and above, but not working for version 2.0.0 for some reason.
And internally in sagemaker, 2.0 points to 2.0.4

**Comment by martinRenou** [comment]
Thank you for reporting back!
