### ISSUE TITLE
Environment variables not passed when deploying Sagemaker Estimator

### ISSUE THREAD

**Issue by clay-jona** [aws/sagemaker-python-sdk#4322]
**Describe the bug**
Environment variables aren't correctly passed when running `deploy` method on `sagemaker.estimator.Estimator` class.

**To reproduce**
`src/train`
```
#!/usr/bin/env python
from os import environ

print("During training ENV:", environ["TEST_ENV"])

with open("/opt/ml/model/model.pkl", "wb") as f:
    f.write(b"model")
```

`src/serve`
```
#!/usr/bin/env python
from os import environ

print("During serving ENV:", environ["TEST_ENV"])

with open("/opt/ml/model/model.pkl", "rb") as f:
    print(f.read())
```

`Dockerfile`
```
# Dockerfile

FROM python:3.11-bookworm

RUN mkdir /opt/app

COPY src/ /opt/app/src/

ENV PYTHONUNBUFFERED=TRUE
ENV PYTHONDONTWRITEBYTECODE=TRUE
ENV PATH="/opt/app/src:${PATH}"

WORKDIR /opt/app/src
```
Then the docker container is pushed to ECR. 

In the Sagemaker notebook,
```
import boto3
import sagemaker

model = sagemaker.estimator.Estimator(
    image_uri=IMAGE_URI,
    role=sagemaker.get_execution_role(),
    instance_count=1,
    instance_type="ml.m4.xlarge",
    output_path=OUTPUT_PATH,
    sagemaker_session=sagemaker.Session(),
    environment={"TEST_ENV": "TEST"}
)

model.fit()
```

```
print(model.environment)
# prints {'TEST_ENV': 'TEST'}
```

And I can also confirm in CloudWatch that 

`"During training ENV: TEST"` is printed out.

Now the deployment
```
predictor = model.deploy(
    initial_instance_count=1, 
    instance_type="ml.m4.xlarge",
)
```
, which runs forever. And I get a `KeyError: 'TEST_ENV'` upon checking CloudWatch.

**Expected behavior**
`"During serving ENV: TEST"` should be printed out.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.192.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: 
- **Framework version**:
- **Python version**: 3.10.6
- **CPU or GPU**: CPU
- **Custom Docker image (Y/N)**: Y

**Additional context**
I am aware of a workaround using `hyperparameters` as suggested in #2618 , but [the documentation](https://sagemaker.readthedocs.io/en/stable/api/training/estimators.html#sagemaker.jumpstart.estimator.JumpStartEstimator) prohibits including security-sensitive information, which is what I need.

**Comment by clay-jona** [comment]
Two things I figured:
1. `Model` class takes `env` as an argument, which we can pass as `**kwargs` when calling `.deploy()` method ([ref](https://sagemaker.readthedocs.io/en/stable/api/inference/model.html#sagemaker.model.Model)).
2. AWS Secrets Manager can be used ([ref](https://aws.amazon.com/secrets-manager/)).

**Comment by aarushgarg1110** [comment]
Has there been a fix for this? I would like to implement my pipeline as a CI/CD project, and for that to happen, i can't pass in the env variable to the deploy method. Is there a fix for directly saving the environment variable with the model when deployed?
