### ISSUE TITLE
Support PEP-396: sagemaker.__version__ doesn't work

### ISSUE THREAD

**Issue by leopd** [aws/sagemaker-python-sdk#434]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: all
- **Framework Version**: n/a
- **Python Version**: 3.6.3
- **CPU or GPU**: CPU
- **Python SDK Version**:  well that's the funny thing...  (pip freeze says 1.11.3)
- **Are you using a custom image**:  n/a

### Describe the problem
I'd like to be able to know which version of the sagemaker python SDK I'm using, so I naturally try what's recommended by PEP-396, and it doesn't work.

### Minimal repro / logs
```
>>> sagemaker.__version__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-6450e5659cf0> in <module>()
----> 1 sagemaker.__version__

AttributeError: module 'sagemaker' has no attribute '__version__'
```

- **Exact command to reproduce**:

`sagemaker.__version__`

**Comment by jesterhazy** [comment]
fixed by https://github.com/aws/sagemaker-python-sdk/pull/435

**Comment by jesterhazy** [comment]
this will ship in our next release
