### ISSUE TITLE
[feature request] requirements.txt on MXNET models

### ISSUE THREAD

**Issue by yifeim** [aws/sagemaker-python-sdk#436]
Now that it has been almost a year since the initial appearance. I hope people have time to look at some practicality aspects. One thing is that the original `pip install` for 3rd party python libraries is a pain. Could we instead support `requirements.txt` on MXNET models?

This is the desired protocol:

https://github.com/aws/sagemaker-python-sdk/blame/master/src/sagemaker/tensorflow/README.rst#L408

Speaking of convenience, I am also confused about this warning:

https://github.com/aws/sagemaker-python-sdk/blame/master/src/sagemaker/mxnet/README.rst#L37

Will `train, save, model_fn, transform_fn` still be the reserved keywords or are you planning to drop backward-compatibility for very important reasons?

Thanks.

**Comment by laurenyu** [comment]
@yifeim about the warning - `train` and `save` will no longer be reserved keywords, but it should be relatively straightforward to take a script using those two methods and convert it to be compatible with the new format. (More explanation can be found [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/mxnet/README.rst#updating-your-mxnet-training-script).) This new format is intended to allow for greater flexibility with training models.

on the other hand, the interface for inference will remain the same, so `model_fn` and `transform_fn` will function as they did before.

**Comment by yifeim** [comment]
Thanks for the extra explanations.
