### ISSUE TITLE
can't find libcuda.so.1 when deploying trained model with self-built tensorflow container

### ISSUE THREAD

**Issue by vbvg2008** [aws/sagemaker-python-sdk#440]
Hi , I used the docker image here https://github.com/aws/sagemaker-tensorflow-container/blob/master/docker/1.11.0/final/py2/Dockerfile.gpu 
Then follow the instructions here https://github.com/aws/sagemaker-tensorflow-container#building-your-image to build a tensorflow 1.11.0 gpu images and successfully trained a model.  But When I am trying to deploy the model by 

predictor = estimator.deploy(initial_instance_count=1, instance_type='ml.m4.xlarge')

it shows the error < The primary container for production variant AllTraffic did not pass the ping health check.>  Then in cloud watch, it shows that  <ImportError: libcuda.so.1: cannot open shared object file: No such file or directory>

It seems like the cuda is not recognized in deployment environment (even though I am not using gpu for inference).   Is there any way to work around it?

**Comment by mvsusp** [comment]
Hi @vbvg2008 

You should use the Dockerfile.cpu image in CPU instances because tensorflow-gpu requires NVIDIA CUDA drivers.

I believe this is solve your question.

I will close the ticket for now, please feel free to reopen it.

Thanks for using SageMaker!

**Comment by vbvg2008** [comment]
@mvsusp But I need the gpu docker image for training.  After training, when I use the 
```
predictor = estimator.deploy(....)
```
Sagemaker will use the same image for deployment, that's the issue.    

Is there a place where I can specify different docker image for training and deployment?

**Comment by mvsusp** [comment]
I understand better now @vbvg2008, thanks for clarifying.

You can use a [TensorFlow Model](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/README.rst#deploying-directly-from-model-artifacts) instead:

```python
from sagemaker.tensorflow import TensorFlowModel

tf_model = TensorFlowModel(model_data='s3://mybucket/model.tar.gz',
                           image_name='...',
                           role='MySageMakerRole',
                           entry_point='entry.py',
                           source_dir='my_src', # directory which contains entry_point script and requirements file
                           name='model_name',
                           env={'SAGEMAKER_REQUIREMENTS': 'requirements.txt'}) # path relative to source_dir

predictor = tf_model.deploy(initial_instance_count=1, instance_type='ml.c4.xlarge')
```

Please, let me know if you have more question.

**Comment by vbvg2008** [comment]
@mvsusp Thank you very much! your workaround is working.  

 One last thing that I didn't understand: before your workaround, I also tried to deploy my gpu docker image to ml.p3.2xlarge, but encountered the same error.   I mean, gpu instance should have CUDA installed already right?

**Comment by mvsusp** [comment]
Did you install the tensorflow-gpu version?
