### ISSUE TITLE
Documentation of @step decorator

### ISSUE THREAD

**Issue by JurijGass** [aws/sagemaker-python-sdk#4416]
Hi, I'm trying to implement a pipeline with @step decorator. So I was following descriptions on this side:
https://docs.aws.amazon.com/sagemaker/latest/dg/pipelines-step-decorator-create-pipeline.html

Paragraph: Define custom dependencies
Code Line: get_step(step_train_result).add_depends_on(step_process_result)
Problem: Function 'add_depends_on' needs a list. 
Correct version would be: get_step(step_train_result).add_depends_on([step_process_result])

No description of the function 'add_depends_on' in sdk docs: https://sagemaker.readthedocs.io/en/stable/workflows/pipelines/sagemaker.workflow.pipelines.html#sagemaker.workflow.steps.Step
Found definition in the code: https://github.com/aws/sagemaker-python-sdk/blob/87d661a8caff9c0671bce183000be6133d9103b9/src/sagemaker/workflow/steps.py#L158

**Comment by nmadan** [comment]
Hi @JurijGass, thanks for your feedback. We are currently working on getting this fixed!

**Comment by nmadan** [comment]
Documentation has been fixed: https://docs.aws.amazon.com/sagemaker/latest/dg/pipelines-step-decorator-create-pipeline.html#pipelines-step-decorator-run-pipeline-link-custom
