### ISSUE TITLE
Estimator.delete_endpoint does not delete the Model or Endpoint Configuration

### ISSUE THREAD

**Issue by mvsusp** [aws/sagemaker-python-sdk#447]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
Any Framework Container
- **Python Version**:
2 and 3
- **Python SDK Version**:
1.12

### Describe the problem
Issue found by @andrewcking here https://github.com/aws/sagemaker-python-sdk/issues/402

In SageMaker Hosting, the process to create an endpoint requires to [create an model, an endpoint configuration, and an endpoint](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-hosting.html).

SageMaker Python SDK abstract these 3 layers for you. These are the [lines where this process happens](https://github.com/aws/sagemaker-python-sdk/blob/dd44d25247927abe409f7bf9e5c4561f7e55585e/src/sagemaker/model.py#L105)

```python
        container_def = self.prepare_container_def(instance_type)
        self.name = self.name or name_from_image(container_def['Image'])
        self.sagemaker_session.create_model(self.name, self.role, container_def, vpc_config=self.vpc_config)
        production_variant = sagemaker.production_variant(self.name, instance_type, initial_instance_count)
        self.endpoint_name = endpoint_name or self.name
        self.sagemaker_session.endpoint_from_production_variants(self.endpoint_name, [production_variant], tags)
```

To be able to use Python SDK to create an endpoint with the same name, you will have to delete the model, the endpoint_config, and the endpoint. SageMaker Python SDK [delete_endpoint()](https://github.com/aws/sagemaker-python-sdk/blob/dd44d25247927abe409f7bf9e5c4561f7e55585e/src/sagemaker/estimator.py#L330) only deletes the endpoint, which is why the issue is happening.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:
```python
from sagemaker.pytorch import PyTorch

# create estimator
estimator = PyTorch(entry_point='train.py', 
                    role='SageMakerRole', 
                    framework_version='0.4.0', 
                    train_instance_count=1, 
                    train_instance_type='ml.c5.xlarge', 
                    source_dir='source', 
                    hyperparameters={'epochs': 6,})

# fit estimator
estimator.fit('s3://sagemaker-sample-data-us-west-2/spark/mnist/train/')

# deploy estimator (except it doesn't deploy your new estimator if a previously used endpoint name is specified)
estimator.deploy(instance_type='ml.c5.xlarge'', initial_instance_count=1)

# delete endpoint
estimator.delete_endpoint()

# deploy again
estimator.deploy(instance_type='ml.c5.xlarge'', initial_instance_count=1, endpoint_name=estimator.last_training_job.name)
```

**Comment by ChoiByungWook** [comment]
These features are being worked on in the following PRs:

- https://github.com/aws/sagemaker-python-sdk/pull/630
- https://github.com/aws/sagemaker-python-sdk/pull/638

The ability to delete endpoint configurations has been merged.

**Comment by ChuyangDeng** [comment]
The change has been merged, waiting on release.
