### ISSUE TITLE
The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint.

### ISSUE THREAD

**Issue by jos0mat** [aws/sagemaker-python-sdk#452]
Trying to implement kmeans algorithm on MNIST dataset using scikit learn in sagemaker using the following code.

import io
import os
import time
import gzip
import json
import pickle
import mxnet as mx
import numpy as np
import urllib.request
import sklearn.cluster
import boto3
from sagemaker import get_execution_role

urllib.request.urlretrieve("http://deeplearning.net/data/mnist/mnist.pkl.gz", "mnist.pkl.gz")
with gzip.open('mnist.pkl.gz', 'rb') as f:
    train_set, valid_set, test_set = pickle.load(f, encoding='latin1')

kmeans=sklearn.cluster.KMeans(n_clusters=10).fit(train_set[0])
centroids=mx.ndarray.array(kmeans.cluster_centers_)

mx.ndarray.save('kmeans-model',[centroids])
!tar czvf model.tar.gz kmeans-model

bucket='demobkts'
prefix='kmeansmxnet/model'
s3=boto3.Session().resource('s3')
current_bkt=s3.Bucket(bucket).Object(os.path.join(prefix,'model.tar.gz'))
current_bkt.upload_file('model.tar.gz')

kmeans_model= 'kmeans-scikit-' + time.strftime('%Y-%m-%d-%H-%M-%S', time.gmtime())
sm=boto3.client('sagemaker')
from sagemaker.amazon.amazon_estimator import get_image_uri
container = get_image_uri(boto3.Session().region_name, 'kmeans')
role=get_execution_role()

create_model_response = sm.create_model(
    ModelName=kmeans_model,
    ExecutionRoleArn=role,
    PrimaryContainer={
        'Image': container,
        'ModelDataUrl': 's3://{}/{}/model.tar.gz'.format(bucket, prefix)
                     }
                                       )
kmeans_endpoint_config='kmeans-endpoint-config-' + time.strftime('%Y-%m-%d-%H-%M-%S', time.gmtime())

create_endpoint_config_response = sm.create_endpoint_config(
    EndpointConfigName = kmeans_endpoint_config,
    ProductionVariants = [{
        'InstanceType':'ml.m4.xlarge',
        'InitialInstanceCount':1,
        'ModelName':kmeans_model,
        'VariantName':'AllTraffic'
                        }])

kmeans_endpoint='kmeans-endpoint-'+ time.strftime('%Y-%m-%d-%H-%M-%S', time.gmtime())

create_endpoint_response = sm.create_endpoint(
    EndpointName = kmeans_endpoint,
    EndpointConfigName = kmeans_endpoint_config)

try:
    sm.get_waiter('endpoint_in_service').wait(EndpointName=kmeans_endpoint)
finally:
    resp = sm.describe_endpoint(EndpointName=kmeans_endpoint)
    status = resp['EndpointStatus']
    print("Arn: " + resp['EndpointArn'])
    print("Create endpoint ended with status: " + status)

if status != 'InService':
        message = sm.describe_endpoint(EndpointName=kmeans_endpoint)['FailureReason']
        print('Training failed with the following error: {}'.format(message))
        raise Exception('Endpoint creation did not succeed')

**When the above code is executed, It returns the following error.**

Create endpoint ended with status: Failed
Training failed with the following error:  The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint.
---------------------------------------------------------------------------
WaiterError                               Traceback (most recent call last)
<ipython-input-26-a6f70df2e78e> in <module>()
      1 try:
----> 2     sm.get_waiter('endpoint_in_service').wait(EndpointName=kmeans_endpoint)
      3 finally:

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/botocore/waiter.py in wait(self, **kwargs)
     52     def wait(self, **kwargs):
---> 53         Waiter.wait(self, **kwargs)
     54 

~/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/botocore/waiter.py in wait(self, **kwargs)
    322                     reason='Waiter encountered a terminal failure state',
--> 323                     last_response=response,
    324                 )

WaiterError: Waiter EndpointInService failed: Waiter encountered a terminal failure state

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-26-a6f70df2e78e> in <module>()
     10         message = sm.describe_endpoint(EndpointName=kmeans_endpoint)['FailureReason']
     11         print('Training failed with the following error: {}'.format(message))
---> 12         raise Exception('Endpoint creation did not succeed')

Exception: Endpoint creation did not succeed

**Comment by nadiaya** [comment]
Hi, the error you are getting doesn't seem to be related to SageMaker Python SDK.

I am going to reassign this issue to the team who owns kmeans image.

**Comment by asadoughi** [comment]
Hi @jos0mat, thanks for trying out SageMaker k-means! As shown in this [example notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/kmeans_bring_your_own_model/kmeans_bring_your_own_model.ipynb),  the name of the model file should be `model_algo-1`. In this case, replace `kmeans-model` in the code you shared with `model_algo-1`.

**Comment by jos0mat** [comment]
Thanks @asadoughi .
Can you tell me why are we specifying that specific name (model_algo-1) ? I thought it is just a file name.

**Comment by asadoughi** [comment]
Sorry, I do not have further information to elaborate on the file name. `model-algo_1` is the expected file name of the current implementation. We will consider having more flexibility around the filename in future implementations. Thank you for your feedback.

**Comment by RaiAbhishek** [comment]
hey @asadoughi, @jos0mat, I tried to name the model as stated in the notebook, but it is failing to satisfy 'modelName' constraint. so I could not create the model with that name. can you please let me know if there is any workaround for this? Thanks.
