### ISSUE TITLE
Runtime dependency on setuptools from importing distutils

### ISSUE THREAD

**Issue by jmahlik** [aws/sagemaker-python-sdk#4534]
**Describe the bug**
Distutils was removed from the standard library in python 3.12. Environments created under 3.12 no longer contain setuptools by default.  Distutils itself is also [deprecated](https://setuptools.pypa.io/en/latest/deprecated/distutils-legacy.html). 

There's a few usages of distutils in the sagemaker python sdk. They are easily replaced by shutil. I do see a comment in `sagemaker.workflow._repack_model` about not wanting to use shutil. But with the [`dirs_exist_ok=True` parameter added in python 3.8](https://docs.python.org/3/library/shutil.html#shutil.copytree), it wouldn't fail on existing directories. So all supported python versions now have an alternative. 

https://github.com/aws/sagemaker-python-sdk/blob/e163807110924fc0c63ca236848507702fd30ded/src/sagemaker/workflow/_repack_model.py#L30-L35

```bash
git grep -e distutils
.pylintrc:ignored-modules=distutils
src/sagemaker/local/image.py:from distutils.spawn import find_executable
src/sagemaker/local/utils.py:from distutils.dir_util import copy_tree
src/sagemaker/local/utils.py:    """A wrapper around distutils.dir_util.copy_tree.
src/sagemaker/workflow/_repack_model.py:# distutils.dir_util.copy_tree works way better than the half-baked
src/sagemaker/workflow/_repack_model.py:from distutils.dir_util import copy_tree
tests/data/_repack_model.py:# distutils.dir_util.copy_tree works way better than the half-baked
tests/data/_repack_model.py:from distutils.dir_util import copy_tree
tests/unit/test_chainer.py:from distutils.util import strtobool
```

I'll submit a PR to remove the deprecated calls in the source.

**To reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
The provided code need to be **complete** and **runnable**, if additional data is needed, please include them in the issue.

```bash
# No setuptools installed by default
python3.12 -m venv
# or virtualenv venv --py 3.12
. venv/bin/activate
# Install from current master
python -m pip install -e .[local]
python -c 'import sagemaker.local.image'
...
    from distutils.spawn import find_executable
  ModuleNotFoundError: No module named 'distutils'

```

**Expected behavior**
Imports do not fail.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: master
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: n/a
- **Framework version**: n/a
- **Python version**: 3.12
- **CPU or GPU**: cpu
- **Custom Docker image (Y/N)**: n

**Additional context**

**Comment by HWiese1980** [comment]
Python 3.12 has been out for a couple months now, why is this still open? I'm currently running into exactly this problem. Python 3.12 is also already available as Lambda Runtime in AWS, so SageMaker SDK should follow as soon as possible.
