### ISSUE TITLE
Upstream package not pinned in setuptools config (schema)

### ISSUE THREAD

**Issue by venky-bharadwaj** [aws/sagemaker-python-sdk#4538]
**Describe the bug**

The schema package just did a release on 0.7.6 an hour ago. This package does not pin the version. This results in an import error when SageMaker package is imported.

**To reproduce**

OS is Amazon Linux 2
Python 3.10

`pip install --no-cache-dir sagemaker`. 

Open a python REPL

`import sagemaker`

Results in 

`ModuleNotFoundError: No module named schema`

Pinning `schema==0.7.5` solved this bug for me.  

**Expected behavior**

With this bug, I was unable to import the SageMaker python sdk.

**Comment by CallumAtCarter** [comment]
[schema 0.7.6](https://pypi.org/project/schema/0.7.6/) has now been yanked from PyPI.

**Comment by venky-bharadwaj** [comment]
In my haste- forgot to mark the latest sagemaker version as a note.

v2.214.0 is the latest sagemaker release tag at this time.

**Comment by zhaoqizqwang** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/4540 Created this pr to pin the package version to 0.7.5

**Comment by zhaoqizqwang** [comment]
resolved the issue
