### ISSUE TITLE
Trailing Slash in `create_dataset` output_path causes issues with joining results

### ISSUE THREAD

**Issue by mkkatica** [aws/sagemaker-python-sdk#4569]
**Describe the bug**
When using a pandas dataframe as the base for a Feature Store dataset, having a trailing slash in the `output_path` parameter causes objects to be uploaded to s3 with a double slash in their path. This conflicts with the definition of the temp table, which uses the correct location without the double-slash.

**To reproduce**
Try to create a dataset with code similar to:
```python
df = feature_store.create_dataset(
    base=base_df,
    output_path="s3://sagemaker-us-east-1-<aact num>/fs-output/", #<--------
    event_time_identifier_feature_name="index_dt",
    record_identifier_feature_name="id"
).with_feature_group(
    feature_group, "id", ["my_feature_1"]
    ).to_dataframe()
```
The returned dataset is empty, regardless of whether there is a valid inner join target for rows of the base dataframe.

**Expected behavior**
The returned dataset includes all the values that matched the inner join. Ideally, the s3 upload will not include the trailing slash if specified.

**Screenshots or logs**
<img width="1572" alt="Screenshot 2024-04-09 at 5 07 09 PM" src="https://github.com/aws/sagemaker-python-sdk/assets/56774886/4d9461c8-d8d5-4a39-a2d0-f6090c6f133e">
<img width="1585" alt="Screenshot 2024-04-09 at 5 07 26 PM" src="https://github.com/aws/sagemaker-python-sdk/assets/56774886/7a77abb7-38cc-40a8-a4b4-10994486ab95">
<img width="1903" alt="Screenshot 2024-04-09 at 5 07 51 PM" src="https://github.com/aws/sagemaker-python-sdk/assets/56774886/ea9dc7b1-ca18-4c84-b60c-2e7cff6d8bb7">

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.214.3
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: 3.11.6
- **CPU or GPU**: Apple M2
- **Custom Docker image (Y/N)**: N/A

**Additional context**
I'll submit a fix PR, just opening an issue to track.

**Comment by mufaddal-rohawala** [comment]
Hey @mkkatica , Thanks for reaching out to SageMaker. We are triaging the request internally and will be fixing this bug. Thanks. Hoping this is not a blocking issue for you though.
