### ISSUE TITLE
why version constraint on the urllib3 dependency?

### ISSUE THREAD

**Issue by vgod-dbx** [aws/sagemaker-python-sdk#457]
Hi,

I was wondering why there's a version constraint on `urllib3`'s version? Is it possible to relax the upper bound so we can use the latest version of `urllib3` with SageMaker?

Ref: https://github.com/aws/sagemaker-python-sdk/blob/868f81b78b9b6907030944e4f1fdbe04832de956/setup.py#L57

Thanks!

**Comment by nadiaya** [comment]
We had to do it as part of nvidia-docker2 support in local mode: https://github.com/aws/sagemaker-python-sdk/pull/426 because of some of the docker-compose dependencies. 

We should be able to unfreeze when new version of docker-compose is released.
