### ISSUE TITLE
SageMaker Timeseries Explainability: Timewise bug

### ISSUE THREAD

**Issue by Alex-Wenner-FHR** [aws/sagemaker-python-sdk#4641]
**Describe the bug**
When using the TSX feature, there appears to be a bug in the `timewise` granularity.

I see the following error **not** specifying static covariate baselines in the `AsymmetricShapleyValueConfig` instantiation:
`ValueError: Baseline for static_covariates must be set.`

When I **do** specify static covariate baselines in the `AsymmetricShapleyValueConfig` instantiation, I see the following: 
`ValueError: Baseline for static_covariates is only supported for fine_grained. Used granularity: timewise.`

**To reproduce**
Try to use the `AsymmetricShapleyValueConfig` instantiation with and without baselines for the static covariates.

**Expected behavior**
I would expect either specifying or not specifying the static covariate baselines to function with timewise granularity.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.217.0
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A (TSX)
- **Framework version**: N/A (TSX)
- **Python version**: 3.9 on the Processing Job, 3.10 on the notebook launching the job.
- **CPU or GPU**: GPU & CPU
- **Custom Docker image (Y/N)**: N

**Comment by rvasahu-amazon** [comment]
Hi Alex,

Thanks for reaching out. This looks like an bug on our end. We're working on a fix and release for this. For now please use `fine_grained` explanations instead. We'll include an update here when a fix is released.

**Comment by rvasahu-amazon** [comment]
Hi, this issue has been resolved and a new release has since been made. It should now be possible to omit a static covariates baseline when selecting a timewise explanation granularity. Please reach out to the team if there are any other issues.
