### ISSUE TITLE
Latest update [2.232.2] introduces MLFlow

### ISSUE THREAD

**Issue by mathcass** [aws/sagemaker-python-sdk#4885]
**Describe the bug**
The latest update to the SageMaker SDK introduces sagemaker-mlflow which then brings in a constellation of dependencies that users might not need. This is a minor change (https://github.com/aws/sagemaker-python-sdk/compare/v2.232.1...v2.232.2) that leads to installing 30 new dependencies.

**To reproduce**
Install the latest update, `pip install sagemaker==2.232.2`. 

**Expected behavior**
I would have liked if this release had been included via Python "extras" where you can specify an additional set of installation requirements. For example, rather than installing `sagemaker-mlflow` automatically, only install it if someone specifies `pip install "sagemaker[mlflow]>=2.232.2".

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**System information**
A description of your system. Please provide:
- **SageMaker Python SDK version**: 2.232.2
- **Framework name (eg. PyTorch) or algorithm (eg. KMeans)**: N/A
- **Framework version**: N/A
- **Python version**: N/A
- **CPU or GPU**: N/A
- **Custom Docker image (Y/N)**: N

**Additional context**
The package could be more usable and leaner if it implemented this as a Python "extra".

**Comment by jgangelBLNG** [comment]
I also ran into this when a deploy failed unexpectedly. Looks like there was a request to make it optional that wasn't addressed before merge - https://github.com/aws/sagemaker-python-sdk/pull/4880#discussion_r1784907626

**Comment by ryansteakley** [comment]
https://github.com/aws/sagemaker-python-sdk/pull/4903 open for review

**Comment by benieric** [comment]
Hi @mathcass, thanks for reaching out about this. We have merged the fix in this PR - https://github.com/aws/sagemaker-python-sdk/pull/4903

Should hopefully be resolved on next release

**Comment by benieric** [comment]
Closing since has been resolved in this PR - https://github.com/aws/sagemaker-python-sdk/pull/4903

**Comment by mathcass** [comment]
I saw this but I'm late to coming back to comment on it. Thank you so much for addressing and responding to the issue @ryansteakley & @benieric. I appreciate you.
