### ISSUE TITLE
Using MXNet LSTM with SageMaker

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [aws/sagemaker-python-sdk#51]
Going off of the [MNIST Example for MXNet](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_gluon_mnist/mnist.py#L91), I need to have a function like,

```python
def save(net, model_dir):
    # save the model
    y = net(mx.sym.var('data'))
    y.save('%s/model.json' % model_dir)
    net.collect_params().save('%s/model.params' % model_dir)
```

But, if I try this with an LSTM I get an error. The minimal code to reproduce the bug is,

```python
import mxnet as mx
from mxnet import gluon

net = gluon.rnn.LSTM(100)
net(mx.sym.var('dats'))
```

which gives,
```
$ python shape_error.py 
Traceback (most recent call last):
  File "shape_error.py", line 5, in <module>
    net(mx.sym.var('dats'))
  File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/block.py", line 304, in __call__
    return self.forward(*args)
  File "/usr/local/lib/python3.6/site-packages/mxnet/gluon/rnn/rnn_layer.py", line 173, in forward
    batch_size = inputs.shape[self._layout.find('N')]
AttributeError: 'Symbol' object has no attribute 'shape'
```

How do I solve this?

**Comment by jesterhazy** [comment]
@aidan-plenert-macdonald this is more of an mxnet usage issue than a SageMaker one. I've updated your [mxnet issue](https://github.com/apache/incubator-mxnet/issues/9501) with a suggested workaround and will close this ticket.
