### ISSUE TITLE
Is there a more comprehensive example for doing Inference Pipeline?

### ISSUE THREAD

**Issue by mshseek** [aws/sagemaker-python-sdk#517]
Is there a more comprehensive example of use SageMaker's Inference Pipeline feature?

I find the one on [github](https://github.com/aws/sagemaker-python-sdk#inference-pipelines) too brief and not reproducible.

**Comment by icywang86rui** [comment]
@mshseek 
You can find a bit more information here: 
* https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipeline-real-time.html

The following example notebooks demonstrates how to uese Inference Pipeline as well:
* https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/inference_pipeline_sparkml_xgboost_abalone/inference_pipeline_sparkml_xgboost_abalone.ipynb 
* https://github.com/awslabs/amazon-sagemaker-examples/blob/master/advanced_functionality/inference_pipeline_sparkml_blazingtext_dbpedia/inference_pipeline_sparkml_blazingtext_dbpedia.ipynb

I will add those as references to the github doc as well. Please let me know if you the examples are helpful.

**Comment by icywang86rui** [comment]
PR to add notebook references - https://github.com/aws/sagemaker-python-sdk/pull/519

**Comment by icywang86rui** [comment]
@mshseek glad to see that the notebooks are helpful. Closing this issue. Please don't hesitate to ask if you have any follow up questions.
