### ISSUE TITLE
PyTorch support

### ISSUE THREAD

**Issue by slevental** [aws/sagemaker-python-sdk#53]
Wondering if there are any plans for supporting pytorch framework in the nearest future. It's clear how to configure it myself, but if it's on a roadmap - I would rather wait for it. Thanks

**Comment by ChoiByungWook** [comment]
Hello,
   
Thank you for using Amazon SageMaker.  We have been actively watching the development of PyTorch and agree that it is an exciting technology.
 
Your feedback is important to us, and we are always reprioritizing our roadmap based on customer inputs.
   
Let us know if there is anything else we can assist with.
 
Thanks!

**Comment by edmondja** [comment]
Yes plz add pytorch, it would be very useful to me too instead of TF

**Comment by yardenhochman** [comment]
pytorch support is critical for the future of the sagemaker service

**Comment by leemengtaiwan** [comment]
Need this features!

**Comment by nakamura41** [comment]
I need it too!!

**Comment by Sarunas-Girdenas** [comment]
Totally agree, PyTorch support is needed and I would most certainly use it!

**Comment by rljonesiii** [comment]
Well, it’s there now. 👍🏻

**Comment by edmondjak** [comment]
Natively ?

**Comment by leemengtaiwan** [comment]
To the moment of this comment (2018/06/05), there seems no specific pytorch example notebooks available in the "SageMaker Python SDK" section on a Notebook instance.

![image](https://user-images.githubusercontent.com/3454980/40960548-04f8e580-68db-11e8-8dbf-12a1d7b4bc51.png)


Although there do exist Conda environment for pytorch:

![image](https://user-images.githubusercontent.com/3454980/40960564-131e803e-68db-11e8-83f1-ffcd93a99b51.png)

I think we have to wrap our pytorch environment into a container according to official announcement, but haven't tried it yet.

**Comment by edmondjak** [comment]
Ok so its not native, like here... 
https://medium.com/@julsimon/training-with-pytorch-on-amazon-sagemaker-58fca8c69987

**Comment by Sarunas-Girdenas** [comment]
Yes, that's what I've meant about the PyTorch support, that it is not native and needs (as @edmondjak mentioned) custom Docker container building. Are there any news when PyTorch could be natively supported?

**Comment by rljonesiii** [comment]
Yes, I’m using it now. You just install it with conda. 

Rob

**Comment by rljonesiii** [comment]
Let me know if you have issues @Sarunas-Girdenas. I invoked this from a newly created notebook:

!(conda install pytorch torchvision -c pytorch -y)

You an also install from the Terminal. 

I’m not sure what the "not natively supported" issue means in this case. But it’s working well for me, so far. ;)

**Comment by nadiaya** [comment]
Support for PyTorch framework has been released.

**Comment by rljonesiii** [comment]
Awesome! Thank you.
