### ISSUE TITLE
TF estimator not honoring "model_dir" argument, trying to create default bucket

### ISSUE THREAD

**Issue by maccam912** [aws/sagemaker-python-sdk#531]
A quick note on why this is an issue for me: my IAM role can only use existing buckets, but cannot create any. I am trying to use a bucket that exists. When doing hyperparameter tuning on a built in amazon estimator it seems to work for me.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow
- **Framework Version**: 1.11.0
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.16.1.post1
- **Are you using a custom image**: No

### Describe the problem
Tensorflow estimator doesn't seem to honor "model_dir" argument, tries to create default bucket.

### Minimal repro / logs

```
/mnt/miniconda/lib/python3.6/site-packages/sagemaker/tensorflow/estimator.py in fit_super()
    293 
    294         def fit_super():
--> 295             super(TensorFlow, self).fit(inputs, wait, logs, job_name)
    296 
    297         if run_tensorboard_locally and wait is False:

/mnt/miniconda/lib/python3.6/site-packages/sagemaker/estimator.py in fit(self, inputs, wait, logs, job_name)
    228                 based on the training image name and current timestamp.
    229         """
--> 230         self._prepare_for_training(job_name=job_name)
    231 
    232         self.latest_training_job = _TrainingJob.start_new(self, inputs)

/mnt/miniconda/lib/python3.6/site-packages/sagemaker/estimator.py in _prepare_for_training(self, job_name)
    800                 using the base name given to the constructor if applicable.
    801         """
--> 802         super(Framework, self)._prepare_for_training(job_name=job_name)
    803 
    804         # validate source dir will raise a ValueError if there is something wrong with the

/mnt/miniconda/lib/python3.6/site-packages/sagemaker/estimator.py in _prepare_for_training(self, job_name)
    198                 self.output_path = ''
    199             else:
--> 200                 self.output_path = 's3://{}/'.format(self.sagemaker_session.default_bucket())
    201 
    202     def fit(self, inputs=None, wait=True, logs=True, job_name=None):
```

- **Exact command to reproduce**:

```
from sagemaker.tensorflow import TensorFlow

estimator = TensorFlow(entry_point='cifar10_cnn.py',
                       role=role,
                       framework_version='1.11.0',
                       hyperparameters={'learning_rate': 1e-4, 'decay':1e-6},
                       training_steps=1000, evaluation_steps=100,
                       base_job_name='mattaba8a29e',
                       model_dir='s3://{}/{}/output'.format(bucket, prefix),
                       train_instance_count=1, train_instance_type='ml.c4.xlarge')

estimator.fit(inputs)
```

Is that something that should be sent through fit_super() call to estimator.fit()? Is there a way to fix this I'm just not seeing?

**Comment by jesterhazy** [comment]
`model_dir` is the S3 location for checkpoint during training. There is another parameter `output_path` that controls where the final model gets saved once training has finished. The missing `output_path` is what's causing the job to use the default bucket in your example.

If you do provide `output_path`, and don't provide a `model_dir`, then the checkpoints will be stored in a subdirectory within the `output_path` location.

Sorry the documentation for this isn't clear enough. We'll work on that.
