### ISSUE TITLE
AttributeError in sagemaker.local.image

### ISSUE THREAD

**Issue by tyrion** [aws/sagemaker-python-sdk#554]
On [line 316 of `sagemaker.local.image`][code] there is a reference to `sagemaker.rl.estimator` but the module is not imported. Therefore we get an error:
```
AttributeError: module 'sagemaker' has no attribute 'rl'
```
The fix is also not trivial, because if you try adding the needed import at the top of the file you incur in an import loop.

To trigger this code I created an estimator, passing to it an `output_path` starting with `"file://"` and then called its `fit` method. 

[code]: https://github.com/aws/sagemaker-python-sdk/blob/4bac1856926ed9446f160d0b2e5554dac7bfb6a0/src/sagemaker/local/image.py#L316

**Comment by ChoiByungWook** [comment]
Hello @tyrion,

Can you please provide a minimal repro for us to try?

The image or dataset doesn't have to be provided.

Thanks!

**Comment by tyrion** [comment]
Hello @ChoiByungWook,
here you go:
```python
from sagemaker import get_execution_role
from sagemaker.estimator import Estimator
from sagemaker.local import LocalSession

role = get_execution_role()

session = LocalSession()
session.config = {'local': {'local_code': True,}}

est = Estimator(
    image_name='nope',
    output_path=f"file:///anything",
    train_instance_type='local',
    train_instance_count=1,
    role=role,
    sagemaker_session=session,
)

est.fit()
```

**Comment by ChoiByungWook** [comment]
@tyrion,

Thank you so much for bringing this to our attention. We made our fix here: https://github.com/aws/sagemaker-python-sdk/pull/560

Please let us know if this solves your issue.

**Comment by tyrion** [comment]
The issue seems fixed to me

Thank you @ChoiByungWook
