### ISSUE TITLE
Wrong quotes used in estimator.py and model.py

### ISSUE THREAD

**Issue by sermolin** [aws/sagemaker-python-sdk#557]
Please fill out the form below.

### System Information
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L249
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model.py#L162

### Describe the problem
The quotes around 'data', 'var1', 'var2' are incorrect. they should be of " ' " type. Instead they are of " ` " type.
Eg: the line from https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/estimator.py#L249 below.
dictionary form, for example: {‘data’:[1,3,1024,1024]}, or {‘var1’: [1,1,28,28], ‘var2’:[1,1,28,28]}

### Minimal repro / logs
N/A

- **Exact command to reproduce**:
N/A

**Comment by sermolin** [comment]
SageMaker Engineering team, please, provide ETA on the fix.

**Comment by ChoiByungWook** [comment]
Hello,

Thank you for bringing this to our attention.

I have put out a PR with the corrections here: https://github.com/aws/sagemaker-python-sdk/pull/562

SageMaker is open source and always open to suggestions and contributions!

Thanks!

**Comment by ChoiByungWook** [comment]
The PR has been merged in.
