### ISSUE TITLE
documentation. sagemaker.tensorflow.TensorFlow: clarify the meaning of 'training_steps' and 'evaluation_steps'.

### ISSUE THREAD

**Issue by sermolin** [aws/sagemaker-python-sdk#561]
Please fill out the form below.

### System Information
N/A

### Describe the problem
a) please, define 'training_steps' and 'evaluation_steps' in terms of number of epochs and batch size, which are more commonly used parameters. 
b) in the case when the dataset is not split into "train_data" and "eval_data" as in this example (https://docs.aws.amazon.com/sagemaker/latest/dg/tf-example1-train.html), how is "evaluation_steps" parameter used?

### Minimal repro / logs
N/A

- **Exact command to reproduce**:
N/A

**Comment by ChoiByungWook** [comment]
Hello @sermolin,

Thank you for bringing this to our attention.

I believe that training_steps and evaluation_steps are being phased out in the new ["script mode"](https://github.com/aws/sagemaker-python-sdk/tree/master/src/sagemaker/tensorflow#tensorflow-sagemaker-estimators-and-models) being introduced. Which was introduced with SageMaker TensorFlow 1.11.

It also difficult to define training and evaluation steps in terms of epochs and batch sizes, as we use the same definition as stated in the TensorFlow documentation.

- [training_steps](https://www.tensorflow.org/api_docs/python/tf/estimator/TrainSpec)
- [evaluation_steps](https://www.tensorflow.org/api_docs/python/tf/estimator/EvalSpec)

Our non-script mode SageMaker predefined TensorFlow containers utilize TensorFlow's estimator for handling training, which require train and eval specs.

- https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/trainer.py#L119
- https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/trainer.py#L139

I don't think we can translate these steps in terms of epochs and batch size, however we should link to the TensorFlow documentation.

Please let me know if there is anything I can clarify.

**Comment by laurenyu** [comment]
All of our TF documentation has now been updated for describing how to use the script mode images, which as @ChoiByungWook mentioned, don't use the two args in question. Closing this issue.
