### ISSUE TITLE
Very minor question about tags.

### ISSUE THREAD

**Issue by ryanpeach** [aws/sagemaker-python-sdk#569]
I've seen this in a lot of aws documentation, and maybe you just want compatibility or something, but I'd just like to ask.

Why do we tag this way:

```python
tags=[{'Key': 'example', 'Value': 'True'}, ...]
```

Instead of the much more pythonic and intuitive:

```python
tags={'example': 'True'}
```

These could easily be supported with the following transformation:

```python
if isinstance(tags, dict):
    tags=[{'Key': str(k), 'Value': str(v)} for k, v in tags.items()]
```

Sorry if this has been brought up before, feel free to close.

**Comment by laurenyu** [comment]
hi @ryanpeach, good question! I think the original reason was to match how tags are defined with the regular AWS SDK, but you raise a good point about there being a more Pythonic way to do it in this SDK. It might be a little trickier to implement now while preserving backward-compatibility, but certainly not impossible.

I'll leave this open as a feature request; we're always reprioritizing our backlog based on customer feedback. Thanks!

**Comment by ryanpeach** [comment]
The example code I wrote should maintain backwards compatibility. Thanks!
