### ISSUE TITLE
Importing existing PyTorch model and deploying it to production

### ISSUE THREAD

**Issue by KeepingItClassy** [aws/sagemaker-python-sdk#579]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: PyTorch
- **Framework Version**: 1.0
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem
I have an already trained PyTorch image captioning model, a Python script that uses it to make predictions, and a Flask API to serve the prediction model that's currently running on Heroku. I'd like to migrate it to SageMaker to save serving costs and potentially get better performance. However, there's absolutely no documentation on how to import an existing model; all of the examples involve training the model in SageMaker. It seems like bringing an existing model would be a frequent use case, so there should be documentation for it.

**Comment by laurenyu** [comment]
hi @KeepingItClassy, thanks for your interest in SageMaker!

Apologies that there isn't a specific example of bringing an existing PyTorch model to SageMaker. There is a sample notebook that shows how to do this with an MXNet model: [mxnet_onnx.ipynb](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/mxnet_onnx_superresolution/mxnet_onnx.ipynb). You can do something similar with the [PyTorchModel class](https://sagemaker.readthedocs.io/en/stable/sagemaker.pytorch.html#pytorch-model) to deploy your model.

Hope that helps!

**Comment by codevinz** [comment]
Have you deployed your pytorch model to flask? I have the same problem but I only want it in flask.

**Comment by yang0110** [comment]
Why torch can not be import directly in sagemaker?

**Comment by laurenyu** [comment]
@yang0110 can you open a new issue and include more context to your question? thanks!
