### ISSUE TITLE
estimator hyperparameters with empty string value not passed to instance.

### ISSUE THREAD

**Issue by seanv507** [aws/sagemaker-python-sdk#582]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: NA
- **Framework Version**: NA
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**:1.16.3
- **Are you using a custom image**: YES

### Describe the problem
when using sagemaker.estimator.Estimator(...

hyperparameters  with value = empty string are not passed to  the instance
eg Hyperparameters = { "c": "" }
[I would expect all hyperparameters to be passed - whatever their value]
I can query the hyperparameters fine from the estimator object, just doesn't get to the training docker instance. [ I have printed the hyperparameters received on my instance to check]
### Minimal repro / logs

- **Exact command to reproduce**:

**Comment by martinRenou** [comment]
I've been able to reproduce this. Though I'm not sure it's an issue with the Python SDK.

If you inspect the request that is made to the sagemaker service by looking at the train message here: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/session.py#L959 you'd see that the empty hyperparameter **is there**.
