### ISSUE TITLE
List training jobs?

### ISSUE THREAD

**Issue by plynch-chewy** [aws/sagemaker-python-sdk#583]
The aws cli has a command to list training jobs via `aws sagemaker list-training-jobs`. Is there something similar with the sagemaker sdk?

**Comment by nadiaya** [comment]
SageMaker Python SDK is wrapper on top of boto3 that provides a more high level and convenient API, but it's not intended to fully duplicate all calls.

You can list training jobs in python code by using boto3 directly  https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker.html#SageMaker.Client.list_training_jobs
