### ISSUE TITLE
the model from sagemaker neo compilation can not be used in raspberry pi

### ISSUE THREAD

**Issue by fast4break** [aws/sagemaker-python-sdk#593]
Please fill out the form below.

### System Information
- **Framework (e.g. MXNET)**: MXNET
- **Framework Version**:lastest
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: latest
- **Are you using a custom image**: no

### Describe the problem
Following the steps in https://docs.aws.amazon.com/sagemaker/latest/dg/neo-job-compilation-cli.html to convert a MXNET resnet50 model to one for Raspberry pi 3B.  All steps passsed except the final rasp3pi model can not predict a meaningful result.
Original mnxet model: http://data.dmlc.ml/models/imagenet/resnet/50-layers/
Compilation scripts and testing code: https://aws.amazon.com/blogs/aws/amazon-sagemaker-neo-train-your-machine-learning-models-once-run-them-anywhere/
Testing image: /dlr-1.0-py2-armv7l/tests/dog.npy
[IF use resnet50 model under /dlr-1.0-py2-armv7l/models, the result is good.]

### Minimal repro / logs
The testing code output following log:
(1, 3, 224, 224)
/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py:26: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims)
Inference result: "tench, Tinca tinca" with probability nan.

- **Exact command to reproduce**:
follow steps in 
https://docs.aws.amazon.com/sagemaker/latest/dg/neo-job-compilation-cli.html
with models in http://data.dmlc.ml/models/imagenet/resnet/

**Comment by ChoiByungWook** [comment]
Hello @fast4break,

Apologies for the late response.

I have reached out to the SageMaker Neo team and they should respond as soon as possible.

Thank you for your patience.

**Comment by wweic** [comment]
Thanks for bringing up the issue, we are looking into it. Will update when we have some results.

**Comment by wweic** [comment]
@fast4break We are tracking the issue in DLR repo: https://github.com/neo-ai/neo-ai-dlr/issues/24 . We are able to produce an error(not exactly similar as yours), will update in the issue with further results. Do you mind me resolving this one and track there? Thanks.

**Comment by fast4break** [comment]
@wweic sure, I will follow
