### ISSUE TITLE
[Documentation] TensorFlowModel endpoints need the `export/Servo` folder structure, but this is not documented

### ISSUE THREAD

**Issue by zmjjmz** [aws/sagemaker-python-sdk#599]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow
- **Framework Version**: 1.12
- **Python Version**: 2.7
- **CPU or GPU**: n/a
- **Python SDK Version**: 1.17
- **Are you using a custom image**: no

### Describe the problem
When a 'Python' endpoint is created using the `sagemaker.tensorflow.TensorFlowModel` constructor, it downloads model artifacts from a given S3 URI, and then starts the endpoint. This endpoint then attempts to load the model from a serving location in `/opt/ml/model/export/Servo/{version}/saved_model.pb` -- which is undocumented, or at least not obvious from [this guide](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_python.rst). 

This wasn't / isn't an issue in 'legacy' mode, since the exporting was handled by SageMaker's framework code. However in the more hands-off 'script' mode, customers now have to ensure that they export their models to `os.path.join(os.environ.get('SM_MODEL_DIR'), 'export', 'Servo')`, which is a bit annoying (but not much else -- it works fine) and undocumented (as far as I can tell).

### Minimal repro / logs
It's a bit tedious to produce a script that reproduces this, but I can do so if absolutely necessary.

The log I get from the endpoint (that eventually fails the AllTraffic health check) contains the telling:

`2019-01-11 22:19:57.055333: E tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:369] FileSystemStoragePathSource encountered a file-system access error: Could not find base path /opt/ml/model/export/Servo for servable generic_model`

Inspecting the container shows that the model is at `/opt/ml/model`, but obviously this isn't where the serving entrypoint expects it.

It would be appreciated if the documentation was updated to reflect this behavior.

**Comment by mvsusp** [comment]
Hi @zmjjmz,

I updated the documentation like you suggested, the PR is under review at this moment.
I will consider adding some functionality to hosting the saved model without providing the versioning a feature request, okay?

Thanks for using SageMaker!

**Comment by manjunathsudheer666** [comment]
I am using the protobuff files of a locally trained models. Could someone help me explaining how to create the folder structure before making the tar file with the model files? I am planning to use 3 trained model files using the multi model endpoint approach provided here: https://aws.amazon.com/blogs/machine-learning/save-on-inference-costs-by-using-amazon-sagemaker-multi-model-endpoints/

**Comment by martinRenou** [comment]
Closed by https://github.com/aws/sagemaker-python-sdk/pull/567
