### ISSUE TITLE
Tensorflow used in SageMaker is not optimized for CPU 

### ISSUE THREAD

**Issue by slevental** [aws/sagemaker-python-sdk#60]
It makes sense to compile TF to let it use AVX2 instruction set - this should boost training on CPU c4 instances: 

Here is log output taken from training job which I ran on SageMaker:
```
2018-01-27 19:18:03.954899: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
```

**Comment by ChoiByungWook** [comment]
Thanks for bringing this issue to our attention. We're looking into it and will post correspondence here when we have an update.

**Comment by winstonaws** [comment]
Update: we are actively working on building new TensorFlow and MXNet images optimize them for different instance types. This will include enabling AVX2 for the C5 family of instances.

**Comment by mvsusp** [comment]
Closing this ticket given that the current TF CPU versions are optimized.
