### ISSUE TITLE
Pushing Hosted SageMaker Jupter Notebook Directory to GitHub

### ISSUE THREAD

**Issue by mohamami** [aws/sagemaker-python-sdk#61]
Hello everyone,

I'm not sure if this is the right place or not but here goes. I am using the hosted SageMaker notebook on AWS. How would I go about pushing the directory I made to GitHub? Hopefully, what I would like to be able to do is, whenever I make changes to any code in the directory, I would like to commit and push my changes to GitHub.

Right now, I don't see a way to download the whole hosted Jupyter directory (not the individual notebook). If there is a way to do that, I can simply download the whole directory and push it to GitHub.

I would highly appreciate it if someone could help me with this.

Thanks.

**Comment by laurenyu** [comment]
Hi,

Thanks for trying out SageMaker! We've reached out to the Notebook team, and they're aware of the desire for this feature. If you post in the [Amazon SageMaker forum](https://forums.aws.amazon.com/forum.jspa?forumID=285&start=0), they can provide more of an answer over there.

**Comment by laurenyu** [comment]
Small update - it looks like there's an existing thread on the forums about it already: https://forums.aws.amazon.com/thread.jspa?threadID=269586

As a workaround, you can also run shell commands in the notebook instance to use git.

Closing this issue as there's the forum thread, but feel free to reopen if necessary.
