### ISSUE TITLE
Unable to setup the content_type in Kmean Python SDK

### ISSUE THREAD

**Issue by snowlover173** [aws/sagemaker-python-sdk#619]
using the Kmean method:
https://sagemaker.readthedocs.io/en/stable/kmeans.html
It doesn't seem there is anyway to define the "content_type" for example as "text/csv"
using the common way of setting up sagemaker.session.s3_input() also doesn't work with Kmean.fit()

**Comment by laurenyu** [comment]
hi @snowlover173, thanks for bringing this to our attention. I've put this in our backlog, which we are always reprioritizing based on customer feedback.

In the meantime, are you able to convert your csv data to work with the `RecordSet` object? Here's an example notebook where we've done something like that: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/introduction_to_applying_machine_learning/US-census_population_segmentation_PCA_Kmeans/sagemaker-countycensusclustering.ipynb

**Comment by snowlover173** [comment]
Thanks @laurenyu, using the low level SDK helped with my problem.

**Comment by ShwetaSingh801** [comment]
Hi @snowlover173,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
