### ISSUE TITLE
Batch Transform not working with TensorFlow

### ISSUE THREAD

**Issue by zjost** [aws/sagemaker-python-sdk#635]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:  TensorFlow
- **Framework Version**: 1.11
- **Python Version**:  2.7
- **CPU or GPU**:  CPU
- **Python SDK Version**:    1.18.2
- **Are you using a custom image**:  No

### Describe the problem
Batch transform does not appear to create batches from input data.  This seems to cause the serving request to fail due to either timeout or resource exhaustion.

### Minimal repro / logs
```
[2019-02-08 21:13:46,043] ERROR in serving: <_Rendezvous of RPC that terminated with:
#011status = StatusCode.RESOURCE_EXHAUSTED
#011details = "Received message larger than max (170662612 vs. 4194304)"
#011debug_error_string = "
{
    "created": "@1549660426.041906580",
    "description": "Received message larger than max (170662612 vs. 4194304)",
    "file": "src/core/ext/filters/message_size/message_size_filter.cc",
    "file_line": 174,
    "grpc_status": 8
}
"
>
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 221, in _invoke
self.transformer.transform(content, input_content_type, requested_output_content_type)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 297, in transform
return self.transform_fn(data, content_type, accepts), accepts
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 224, in f
prediction = self.predict_fn(input)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 239, in predict_fn
return self.proxy_client.request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 82, in request
return request_fn(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 110, in predict
result = self.prediction_service_stub.Predict(request, self.request_timeout)
File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 550, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 467, in _end_unary_response_blocking
raise _Rendezvous(state, None, None, deadline)
```

- **Exact command to reproduce**:
```
t = estimator.transformer(
    1, 
    'ml.m5.4xlarge', 
    strategy='MultiRecord', 
    output_path='s3://<bucket>/<key>', 
    max_payload=1, 
    role='<role>', 
    env={'SAGEMAKER_TFS_GRPC_REQUEST_TIMEOUT': '300'}, 
    max_concurrent_transforms=1
)
t.transform(
    's3://<bucket>/<input_file.csv>', 
    content_type='text/csv', 
    split_type='Line', 
    job_name='<job_name>'
)
```
If I do not include the `env={'SAGEMAKER_TFS_GRPC_REQUEST_TIMEOUT': '300'}`, then I get a timeout error.  If I do include it, I get a `RESOURCE_EXHAUSTED` error.  

My `input_fn` looks like:
```
def input_fn(serialized_input, content_type):
    if content_type == 'text/csv':
        rows = list()
        csv_buff = StringIO(serialized_input)
        csv_to_parse = csv.reader(csv_buff, delimiter=',')
        for row in csv_to_parse:
            rows.append(row[0])
        data = {"input": rows}
        # Goes on to create predict_pb2.PredictRequest(), which works as intended with inference
```

I can confirm that this works when I manually invoke the endpoint with multiple records using `text/csv` and the csv_serializer.  

### Questions
1. Why is the message so large?  The entire file, uncompressed, is an 8.6 MB csv file.  I have requested a max payload size of 1 MB and 1 max concurrent transforms.  Why is TensorFlow serving reporting a message size of 170662612?  It seems like this message size is larger than my entire file.  My file is two columns: <str>,<int>, where <str> is model input and <int> is label.
2.  How does the transform service decide how to split a single input csv file into batches?

**Comment by zjost** [comment]
Update:
1. I tried with SingleRecord batch transform, and it completed after an hour.  If I bump max_concurrent_transforms to 100, it takes ~13 minutes.
2.  If I split the file into 100 sub-files, each of which are ~90kB, I just get a resource exhaustion error for each file, with message `details = "Received message larger than max (14669907 vs. 4194304)"`.  So, the message size dropped by a single order of magnitude, but the 8MB file was split by two orders of magnitude.  Surely a 90kB file isn't exhausting the resources of an ml.m5.4xlarge?

**Comment by ChoiByungWook** [comment]
Hello @zjost,

I apologize for the late correspondence.

I will begin by attempting to reproduce this issue.

Within your input_fn, can you by any chance print out the size of the tensor within the request being returned?

**Comment by zjost** [comment]
Closing this issue, as I have resolved the problem.  It is due to the response from the model exceeding the message size, not the input request.  This is because I was returning a vector from the model, not just the prediction score.  When I remove this from the model response, the error disappears and BatchTransform works as intended.

**Comment by Andreachen0707** [comment]
Hi,
I'm running into the same issue here. I saw the solution from @zjost is to remove the large response. However, my response is detection bounding boxes, which are for sure gonna be large response. Is there a way to solve the 'Timed out waiting for notification' issue?
