### ISSUE TITLE
local mode batch transform does not work with predefined SageMaker model

### ISSUE THREAD

**Issue by ChoiByungWook** [aws/sagemaker-python-sdk#649]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
- **Framework Version**:
- **Python Version**:  3.6
- **CPU or GPU**: cpu
- **Python SDK Version**: 1.18.1
- **Are you using a custom image**: no

### Describe the problem
Passing a LocalSession into a Transformer object with a model_name that already exists within SageMaker fails, as the _retrieve_image_name function call to sagemaker_client.describe_model is done within the local_session class, which doesn't account for models outside of local mode.

### Minimal repro / logs
ClientErrorTraceback (most recent call last)
<ipython-input-13-036761a38d08> in <module>()
     19     's3-input',
     20     content_type='text/csv',
---> 21     split_type='Line'
     22 )

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/transformer.pyc in transform(self, data, data_type, content_type, compression_type, split_type, job_name)
    104             self._current_job_name = job_name
    105         else:
--> 106             base_name = self.base_transform_job_name or base_name_from_image(self._retrieve_image_name())
    107             self._current_job_name = name_from_base(base_name)
    108 

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/transformer.pyc in _retrieve_image_name(self)
    114 
    115     def _retrieve_image_name(self):
--> 116         model_desc = self.sagemaker_session.sagemaker_client.describe_model(ModelName=self.model_name)
    117         return model_desc['PrimaryContainer']['Image']
    118 

/home/ec2-user/anaconda3/envs/tensorflow_p27/lib/python2.7/site-packages/sagemaker/local/local_session.pyc in describe_model(self, ModelName)
    116         if ModelName not in LocalSagemakerClient._models:
    117             error_response = {'Error': {'Code': 'ValidationException', 'Message': 'Could not find local model'}}
--> 118             raise ClientError(error_response, 'describe_model')
    119         else:
    120             return LocalSagemakerClient._models[ModelName].describe()

ClientError: An error occurred (ValidationException) when calling the describe_model operation: Could not find local model

- **Exact command to reproduce**:

from sagemaker.transformer import Transformer
from sagemaker.local import LocalSession

local_session = LocalSession()

t = Transformer(
    model_name='model-existing-in-sagemaker',
    instance_count=1,
    instance_type='ml.m5.4xlarge',
    strategy='MultiRecord',
    max_payload=1,
    env={'SAGEMAKER_TFS_GRPC_REQUEST_TIMEOUT': '300'},
    max_concurrent_transforms=1,
    sagemaker_session=local_session
)

t.transform(
    's3-input',
    content_type='text/csv',
    split_type='Line'
)

**Comment by mvsusp** [comment]
Hi @ChoiByungWook,

Local Mode Transformer currently does not support non local models. I added this bug to our roadmap.

Thanks for using SageMaker!

**Comment by nocedan** [comment]
I have found a way to do it without using the Transformer directly. It works for me.

`    boto_session = boto3.Session(
        aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key, region_name=aws_region_name
    )

    model_image = get_image_uri(boto_session.region_name, "forecasting-deepar", repo_version="latest")
    execution_role = config_aws_credentials["execution_role"]
    deepar_model = Model(
        model_data=model_name + "/output/model.tar.gz",
        image=model_image,
        sagemaker_session=Session(boto_session=boto_session),
        role=execution_role,
    )

    transformer = deepar_model.transformer(
        instance_count=1,
        instance_type="ml.m4.xlarge",
        strategy="SingleRecord",
        assemble_with="Line",
        output_path="s3://data-products-demand-forecast/outputs",
        env=dict(DEEPAR_INFERENCE_CONFIG='{ "num_samples": 200, "output_types": ["mean"] }'),
    )`
