### ISSUE TITLE
Can't attach an estimator that is instantiated without hyperparameters

### ISSUE THREAD

**Issue by BoecquaertJonas** [aws/sagemaker-python-sdk#657]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow / LSTM
- **Framework Version**: Latest
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: Latest

### Describe the problem
I'm trying to save and load an LSTM-network. I have 2 notebooks, in the first I instantiate the estimator and use `Estimator.fit()` to train and save it. Then in the second notebook, I try to load it again with `Estimator.attach()`. However when I try this I'm getting the following keyError:
![image](https://user-images.githubusercontent.com/29035046/53338420-ed464000-3903-11e9-814e-90e1784ded8d.png)

When initializing the estimator, I don't specify any hyperparameters:
![image](https://user-images.githubusercontent.com/29035046/53338715-aa389c80-3904-11e9-8339-d37b01df42a1.png)
When taking a look in the _init from the Estimator-class we can see that it defaults to None when no hyperparameters are specified:
![image](https://user-images.githubusercontent.com/29035046/53339128-bc670a80-3905-11e9-8b4e-45670dfc6b09.png)

But when taking a look in the response I get from .describe_training_job(), no key 'HyperParameters' is included. It seems that hyperparameters with an empty value don't get passed, resulting in this keyError I'm getting.
![image](https://user-images.githubusercontent.com/29035046/53339585-161c0480-3907-11e9-9f8b-2dfc50887af7.png)

Is there a way when instantiating an estimator to give it 'fake' hyperparameters so that at least something gets passed along, skipping the keyError.

**Comment by mvsusp** [comment]
Hey @BoecquaertJonas 

Thanks for pointing out the bug! We are in the process to review the code changes.
We will notify you when these code changes get merged. 

Thanks for using SageMaker!
