### ISSUE TITLE
Using "tensorflow-serving" with Batch Transform

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-python-sdk#668]
Please fill out the form below.

### System Information
* **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: N/A: TensorFlow Serving
* **Framework Version**: N/A
* **Python Version**: 3.5
* **CPU or GPU**: CPU
* **Python SDK Version**: 1.18.3
* **Are you using a custom image**: No

### Describe the problem
Is there a way to use the "tensorflow-serving" endpoint type for Batch (or a reason this can't or shouldn't be done)?

Would implementing this mostly be a matter of adding an endpoint_type parameter to def transform()?

Thanks!

**Comment by laurenyu** [comment]
Thanks for bringing this to our attention! Yes, I think the solution here would be adding an `endpoint_type` arg to `transformer()` to mimic what `TensorFlow.deploy()` does.

In the meantime, you should still be able to start Batch Transform jobs either with the `Transformer` class directly or through a [TensorFlow Serving Model object](https://sagemaker.readthedocs.io/en/stable/sagemaker.tensorflow.html#tensorflow-serving-model)

**Comment by andremoeller** [comment]
Closing, this was released in 1.32.0. Thanks!

https://github.com/aws/sagemaker-python-sdk/blob/91ea028c153fb1b618c73e3e92e7d6cf10712dfb/CHANGELOG.md#v1320-2019-07-02
