### ISSUE TITLE
TensorFlow Estimator allows S3 location for source_dir, but fails requirements_file validation

### ISSUE THREAD

**Issue by mmeidl** [aws/sagemaker-python-sdk#669]
Opening this issue on behalf of a SageMaker customer. The customer has pre-compressed and uploaded their `source_dir` to S3, and wants to set `requirements_file` to a relative path contained in the source.

The generic Frameworks Estimator allows `source_dir` to be an S3 location. In this case it skips validation/upload.
Skipping `source_dir` validation:
https://github.com/aws/sagemaker-python-sdk/blob/8b33a305110997e18b1f2f2a37b2d3cdd98b2f91/src/sagemaker/estimator.py#L830-L833
Skipping `source_dir` upload:
https://github.com/aws/sagemaker-python-sdk/blob/8b33a305110997e18b1f2f2a37b2d3cdd98b2f91/src/sagemaker/fw_utils.py#L143-L144

However the Tensorflow Estimator runs a validation for `requirements_file` which fails if the location `source_dir/requirements_file` is not a valid path on the local os: 
https://github.com/aws/sagemaker-python-sdk/blob/8b33a305110997e18b1f2f2a37b2d3cdd98b2f91/src/sagemaker/tensorflow/estimator.py#L273-L285

Seems like it would be easy to skip the local path validation if `source_dir` is an S3 location. Something like this could be added to `_validate_requirements_file`:
```
if source_dir.lower().startswith('s3://'):
  return
```

I know that support for `requirements.txt` files is limited between the "legacy" TensorFlow container and the newer "script mode" version. But this is a small bug in the SDK which could easily be fixed.

**Comment by nadiaya** [comment]
Thank you for reporting this. Marking as a bug.

**Comment by imujjwal96** [comment]
Close this?
