### ISSUE TITLE
Documentation error (output_fn)

### ISSUE THREAD

**Issue by cemsaz** [aws/sagemaker-python-sdk#670]
Please fill out the form below.

### System Information
- **Not algorithm specific**:
- **Not algorithm specific**:
- **Python 3**:
- **CPU**:
- ****:
- **No**:

This example has errors:
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_python.rst#overriding-output-postprocessing-with-an-output_fn

This section: **Overriding output postprocessing with an output_fn**
1st (possible) problem: request_content_type not defined in output_fn
2nd problem: np.dumps() -> Numpy doesn't have dumps, should be json.dumps() or something else ?

**Comment by nadiaya** [comment]
Thanks for reporting this.
For 2nd problem it should probably be:
https://docs.scipy.org/doc/numpy-1.16.1/reference/generated/numpy.ndarray.dumps.html
