### ISSUE TITLE
Unable to do batch transforms with tensor flow

### ISSUE THREAD

**Issue by rohitgmathews** [aws/sagemaker-python-sdk#672]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow
- **Framework Version**: 1.12.0
- **Python Version**: 2.7
- **CPU or GPU**: CPU
- **Python SDK Version**: 
- **Are you using a custom image**: No

### Describe the problem
Batch transform only returns a single result per input file passed in to it

### Minimal repro / logs
No errors are thrown, but, I get only a single prediction per file passed in, instead of prediction per row in the file. The result looks as follows (mildly edited for terseness):
```
{
  "modelSpec": {
    "version": "1551373308",
    "name": "generic_model",
    "signatureName": "serving_default"
  },
  "result": {
    "classifications": [
      {
        "classes": 
         [{"score": 0.9999710321426392, "label": "0"}, {"score": 2.890972791647073e-05,"label": "1"}]
      }
    ]
  }
}
```

- **Exact command to reproduce**:
The transformer is constructed as follows:
```
transformer = estimator.transformer(instance_count=1,
                                                              instance_type='ml.c5.xlarge',
                                                              strategy='MultiRecord')
```
and invoked as follows:
```
transformer.transform(f's3://{bucket_name}/{prefix}',
                              content_type='text/csv',
                              split_type='Line')
```
The serving_input_fn looks like this, which is where I suspect something is amiss
```
def serving_input_fn(params):
    feature_spec = {INPUT_TENSOR_NAME: tf.FixedLenFeature(dtype=tf.float32, shape=get_shape())}
    return tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()
```

**Expectation**:
The input has 5187 rows. The output file should have 5187 rows as well.

Ideally, I would love it if the only the scores for each class was present (in any format). Something like
```
{"score": 0.9999710321426392, "label": "0"}, {"score": 2.890972791647073e-05,"label": "1"}
{"score": 0.93, "label": "0"}, {"score":0.07,"label": "1"}
{"score": 0.81, "label": "0"}, {"score": 0.19,"label": "1"}
```
without other headers, but, I if that's not possible, just getting one prediction per input row would be ideal

**Comment by iquintero** [comment]
Hi @rohitgmathews 

thanks for using SageMaker.
I have asked our Batch team to take a look at this and get back to you :)

**Comment by andremoeller** [comment]
Hi @rohitgmathews ,

It seems likely that the container isn't handling multi-record batches. I tried this myself and got the same results: for each payload, I got one output back -- 25524 input records at 248MB with 6MB payloads got me 42 outputs.

The simplest solution would be to set strategy='SingleRecord'. If your records are small (smaller than 1MB), you might be able to transform faster with more max_concurrent_transforms.

I'd recommend this as your transformer:

```
transformer = estimator.transformer(instance_count=1,
                                                              instance_type='ml.c5.xlarge',
                                                              strategy='single_record',
                                                              assemble_with='Line',
                                                              max_payload=1,
                                                              max_concurrent_transforms=100)
```

assemble_with='Line' means the output will be joined by newline characters.

I tried this out and got 25524 outputs back, as I'd hoped.

As for only writing scores for each class:
You can post-process the output to just include the scores by putting an `output_fn` in your script:

https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_python.rst#overriding-output-postprocessing-with-an-output_fn

You'd have to load the JSON-formatted output, extract the scores and labels, and return the serialized output you want written for each record.

Hope this helps -- please let us know how things go, and don't hesitate to reach out if you have more questions or concerns.

**Comment by rohitgmathews** [comment]
Thanks @andremoeller

That workaround seems to have helped. At first glance, it *appears* to be much slower, but, at least it works :). So does your recommendation to provide an output_fn.

I am hitting some other errors while parsing the protobuf in output_fn, but, that's probably not related to the bug I filed. Thank you so much for your help.

**Comment by andremoeller** [comment]
No problem, glad I could help, @rohitgmathews .

You can refer to the default output_fn if it helps. This would be what your output_fn is replacing: https://github.com/aws/sagemaker-tensorflow-container/blob/master/src/tf_container/serve.py#L241-L248
