### ISSUE TITLE
Running the same Transformer with different entry_points: requires re-training?

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-python-sdk#690]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow
- **Framework Version**: 1.12.0
- **Python Version**: 3
- **CPU or GPU**: CPU
- **Python SDK Version**: sagemaker==1.16.3
- **Are you using a custom image**: No.

### Describe the problem

I want to run a Transform Job with a Transformer, then change my entry_point script, then run another transform job with that new entry_point script.

I ran tensorflow_batch_transform_mnist.ipynb. I changed my mnist.py, and ran another transform job. It ran against the old mnist.py, not the updated mnist.py. The only way I could figure out how to run against the new mnist.py was by retraining my Estimator, then making a new transformer. I couldn't pass in my entry_point into my Transformer.

How can I run TensorFlow Transform Jobs with different entry_points without retraining every time?

**Comment by nadiaya** [comment]
You should be able to this similar to how you would do a regular deployment of already existing model:
```
model = TensorFlowModel(model_data='s3://bucket/model.tar.gz', role='SageMakerRole',
                        entry_point='new_transform_script.py')

transformer = model.transformer(instance_count=1, instance_type='ml.m4.xlarge')

transformer.transform('s3://my-bucket/batch-transform-input')
```

Though we should probably mention it for Transform Jobs specifically in our documentation.
Also since creating a Transformer is a advertised way of running Batch Transform it should probably accept a new new entry_point and not force users to create a Model first. Adding feature request label.

**Comment by andremoeller** [comment]
This seems like a work-around. My Estimator knows where it put the model data, and what my role was, and so does the model (in SageMaker) referenced by this transformer.

I don't think it makes sense to have to create a TensorFlowModel (and resupply my role, model data) to create a Transformer (and resupply Transformer constructor arguments like strategy, env, accept, assemble_with, etc. that I supplied before). I think I should be able to run my Transformer with a different script -- would you mind keeping the 'enhancement' or 'feature request' label on?

**Comment by nadiaya** [comment]
I added those labels but after discussing the reasoning for the current behavior internally decided to remove them.
Right now batch transform behavior is consistent with hosting behavior: i.e. Transformer is similar in that way to a Predictor as it should be.
For both cases to run predictions against SageMaker when you just want to reuse trained model (but submit a new entry_point, etc.) using a Model class is a more consistent experience right now.

Though we are thinking about ways to improve Python SDK user experience, unfortunately we can't discuss it in more details right now.

**Comment by andremoeller** [comment]
OK,

I don't think a Transformer is like a Predictor. Transformer itself is much more like a Model, in my opinion, since Transformer and Model both create some SageMaker resource that takes a long time to create. A predictor just synchronously sends data to an already-created resource, but doesn't create anything itself.

Similar to how a TensorFlowModel can take an entry_point create an endpoint with `deploy`, then change its entry_point and create another endpoint with `deploy`, why shouldn't users be able to use a TensorFlowTransformer with one entry_point and call `transform` to create a Transform Job, then change its entry_point and create another transform job with `transform`?

**Comment by mvsusp** [comment]
Hi @andremoeller 

Thanks for your feature request. It seems that your suggestion would improve the customer experience for Transformer users. I will add your request to your roadmap.

Thanks for using SageMaker!
