### ISSUE TITLE
do you have factorization machines classification

### ISSUE THREAD

**Issue by Sandy4321** [aws/sagemaker-python-sdk#706]
your wrote in main page
 You can also train and deploy models with Amazon algorithms,
but where is the list of these algorithms 
is factorization machines classification is here?
according to this  
https://github.com/aws/sagemaker-python-sdk/issues/194

seems to be yes?

Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
- **Framework Version**:
- **Python Version**:
- **CPU or GPU**:
- **Python SDK Version**:
- **Are you using a custom image**:

### Describe the problem
Describe the problem or feature request clearly here.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by yangaws** [comment]
Hi @Sandy4321 ,

Yes, we have built-in factorization machines in SageMaker. The full list of supported algorithms is here: https://docs.aws.amazon.com/sagemaker/latest/dg/algos.html

Feel free to reopen the issue if you have more questions!

**Comment by Sandy4321** [comment]
I see thanks
can be sagemaker installed in my windows loptop to use offline without AWS ,
