### ISSUE TITLE
Pytorch PIPE mode

### ISSUE THREAD

**Issue by imranparuk** [aws/sagemaker-python-sdk#711]
Hi there, 

Where can I request a feature, specifically AWS sagemaker Pipe mode for pytorch?

**Comment by yangaws** [comment]
Hi @imranparuk ,

You can just make the feature request in this issue. Just make sure you provide enough details for your request. This will make the impact on the priority of this feature for us.

And before the feature is done, you can check this notebook (https://github.com/awslabs/amazon-sagemaker-examples/blob/80df7d61a4bf14a11f0442020e2003a7c1f78115/advanced_functionality/pipe_bring_your_own/train.py) for a way to write your own pipemode in the user script.
