### ISSUE TITLE
s3_input with "compression='Gzip', input_mode='Pipe'" fails with ValidationError

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-python-sdk#716]
Please fill out the form below.

### System Information
- **Python Version**: 3.6
- **Python SDK Version**: 1.18

### Describe the problem

I'm trying to fit with an Estimator on Gzipped data with Pipe mode. I don't have input_mode set on the Estimator, but I do have it set in the s3_input, which should override the Estimator's input_mode:

https://github.com/aws/sagemaker-python-sdk/blob/c2bac8fa23486469b6a27f5a82f1b4e4078a7efc/src/sagemaker/session.py#L1329-L1336

My `s3_input` is:

`training_s3_input = s3_input('s3://my_training_data', compression='Gzip', input_mode='Pipe', shuffle_config=ShuffleConfig(1))`

Trying to fit on an Estimator gives me back this ValidationError, even though I specify Pipe, not File:

`An error occurred (ValidationException) when calling the CreateTrainingJob operation: Invalid compression type for channel training: File mode only supports NONE, got Gzip instead`

Setting `input_mode='Pipe'` directly on the Estimator works as expected.

**Comment by laurenyu** [comment]
thanks for the bug report! it does seem like there's something smarter the code can do around this. I'll add it to our backlog.

**Comment by imujjwal96** [comment]
Hey @laurenyu ! I'd like to work on this issue

I was testing some stuff around this. 
I could notice that the CreateTrainingJob API call is made with the following request 

    {
         ....
         'InputDataConfig': [
             {
                 'CompressionType': 'Gzip', 
                 'ChannelName': 'training', 
                 'InputMode': 'Pipe', 
                 'DataSource': {
                      'S3DataSource': {
                           'S3DataType': 'S3Prefix', 
                           'S3DataDistributionType': 'FullyReplicated', 
                           'S3Uri': 's3://xxxxxx/data.tar.gz'
                      }
                 }, 
                 'ShuffleConfig': {'Seed': 1}
             }
         ], 
         'AlgorithmSpecification': {
             'TrainingInputMode': 'File', 
             'TrainingImage': 'xxxx'         
         }, 
        .....
     }

It seems that s3_input sets the `InputMode` but does not address the `TrainingInputMode` which is set to File by default. I guess the Exception is validating the `CompressionType` with TrainingInputMode. Is this expected?

**Comment by imujjwal96** [comment]
Close this?
