### ISSUE TITLE
TypeError: __new__() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by mrshanth** [aws/sagemaker-python-sdk#72]
`import sagemaker` gives the following error in an ubuntu machine:
`TypeError: __new__() got an unexpected keyword argument 'file'`

installation was tried by both:
`pip install sagemaker`
 or
`git clone https://github.com/aws/sagemaker-python-sdk.git
python setup.py sdist
pip install dist/sagemaker-1.0.3.tar.gz`

**Comment by iquintero** [comment]
Hello, thanks for reporting this issue. 

Can you post more of the stack trace you got to try and figure out where this error could be coming from?
