### ISSUE TITLE
CSR Serialization and Input format support

### ISSUE THREAD

**Issue by ericangelokim** [aws/sagemaker-python-sdk#724]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: All
- **Framework Version**: N/A
- **Python Version**: 3
- **CPU or GPU**: Either
- **Python SDK Version**: 1.18
- **Are you using a custom image**: No, this can be implemented outside of SDK but should be supported natively

### Describe the problem
Currently the SDK does not have native CSR support. 

Framework users will likely use sparse matrices for sparse, high-cardinality data strategies such as bag of words or one shot encoding.

The code for this is relatively simple:

Serializer:
```
def csr_serializer(data):
    buffer = io.BytesIO()
    save_npz(buffer,data)
    return buffer.getvalue()
```

It would also be nice if sagemaker-containers supported CSR as a format type so that Sagemaker users will not have to create their own input_fn, although this is probably more involved as for certain frameworks it would require a conversion to sparse tensor. The below code snippet worked for Scikit-learn.

Input_fn:
```
def input_fn(input_data, content_type):
    buffer = io.BytesIO(input_data)
    return load_npz(buffer)
```

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by ChuyangDeng** [comment]
Hi @ericaws, your request seems like a small change. I've marked this issue as contributions welcome, feel free to open a PR in this repo to add the feature.

**Comment by bveeramani** [comment]
Hi @ericangelokim, just wanted to let you know that we’ve added CSR support in v2 of the SageMaker Python SDK (#1739). Thank you for suggesting the feature.
