### ISSUE TITLE
MXNetModel.deploy() not returning until endpoint deployment complete

### ISSUE THREAD

**Issue by nemalipuri** [aws/sagemaker-python-sdk#731]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: MXNet
- **Framework Version**: 1.3.0
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.18.x
- **Are you using a custom image**: No

### Describe the problem
When creating a new endpoint using MXNetModel.deploy() it is not returning until deployment complete. 
I do not want to wait for the endpoint deployment to complete. deploy() is not accepting 'wait' argument. 
I need to execute deploy() from Lambda, so expecting deploy() to return response immediately.

### Minimal repro / logs
**_deploy() got an unexpected keyword argument 'wait'_**

- **Exact command to reproduce**:
`model.deploy(initial_instance_count=1,
                     instance_type='ml.p2.xlarge',
                    endpoint_name='p-sagemaker-endpoint-fm-t1', update_endpoint=False, wait=False)`

**Comment by nemalipuri** [comment]
I see below call is not passing 'wait' to session.create_endpoint.

https://github.com/aws/sagemaker-python-sdk/blob/1b9a26dc238c3d21875fcab814e09ccf309d5bee/src/sagemaker/model.py#L276

**Comment by jesterhazy** [comment]
@nemalipuri 

You're right, the `deploy` function doesn't take a `wait` argument the way `Estimator.fit(...)` does. I'll mark this as a feature request.

However, if you are intending to run this from lambda, you will run into another problem. The dependencies for this package are too large to fit in a lambda code archive. That means you would need to package them in a Lambda Layer, even after the missing `wait` feature is added.

If all you are doing in the lambda is starting the endpoint, I'd recommend that you avoid both issues by using the plain boto3 sdk to deploy the endpoint.

**Comment by nemalipuri** [comment]
@jesterhazy 

I agree, thought of using boto3 but I preferred using mxnet api because deploy() creates Model, endpoint config and hosting endpoint in a single call.

Regarding package size limit, yes Layer did not take direct import of zip file since it's size is more than 50MB. I'd to place it in S3 and imported it there into Lambda layer.

When I'm planning to product-ionize my work I will use boto3.  
Thanks for marking this as a Feature Request.
