### ISSUE TITLE
Question: Adding Cost allocation tags

### ISSUE THREAD

**Issue by danmoore83** [aws/sagemaker-python-sdk#74]
Hi,
Can you add Tags to an estimator / predictor using the High level API?

I saw in the boto3 docs that there is a AddTags function, but I can't find any way of doing it using the High level api in a Jupytr notebook...

Cheers,
Dan

**Comment by mvsusp** [comment]
Hi @wildpixeldesign,


Thanks a lot for the input. sagemaker-python-sdk does not support this feature right now. The feedback is important to us, and we are always reprioritizing our roadmap based on customer inputs.

Thanks for using SageMaker!

**Comment by laurenyu** [comment]
@danmoore83 we now do support tags for training jobs, hyperparameter tuning jobs, and endpoints. Does this satisfy what you were looking for?

**Comment by danmoore83** [comment]
@laurenyu oh yes that is perfect. Thanks for implementing it!

**Comment by laurenyu** [comment]
great!
