### ISSUE TITLE
Tensorflow Model Invocation failure. 

### ISSUE THREAD

**Issue by AnyAndyAbhy** [aws/sagemaker-python-sdk#740]
Please fill out the form below.

### System Information
- **Framework Tensorflow Algorithm: Inception/Resnet
- **Framework Version**:  1.12.0
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Are you using a custom image**: No

### Describe the problem
I do not have much experience with tensorflow and sagemaker.
I am trying to deploy a previously trained tensorflow model I got from a colleague.
I have a folder called export with following structure:
```
export
└── Servo
    └── 1
        ├── saved_model.pb
        └── variables
            ├── variables.data-00000-of-00001
            └── variables.index
```

I uploaded the model using following code:
```
import tarfile
with tarfile.open('model.tar.gz', mode='w:gz') as archive:
    archive.add('export', recursive=True)

import sagemaker

sagemaker_session = sagemaker.Session()
inputs = sagemaker_session.upload_data(path='model.tar.gz', key_prefix='model')
```

I then created a file called train.py with following content.
```
import tensorflow as tf

def serving_input_fn(hyperparameters):
    feature_placeholders = {
        "image" : tf.placeholder(tf.string, [])
    }
    images = tf.decode_base64(feature_placeholders["image"])
    images = tf.image.decode_jpeg(images, channels=3)
    images = tf.expand_dims(images, 0)
    images = tf.image.resize_images(images, [399, 399])
    images = tf.identity(images, name="input_3")
    features = {
        "image" : images
    }
    return tf.estimator.export.ServingInputReceiver(features, feature_placeholders)
```

I used above created python file as entry_point to deploy using:
```
from sagemaker import get_execution_role

role = get_execution_role()
from sagemaker.tensorflow.model import TensorFlowModel
sagemaker_model = TensorFlowModel(model_data = 's3://' + sagemaker_session.default_bucket() + '/model/model.tar.gz',
                                  role = role,
                                  entry_point = 'train.py')
predictor = sagemaker_model.deploy(initial_instance_count=1,
                                   instance_type='ml.m4.xlarge')

```

The intention is to pass the binary image as input and it should get transformed a tensor of shape (1,399,399,3) and receive the output of the invocation when calling predictor.predict.

When I try to invoke the endpoint using following code I get 500 server error
```
import base64
b64 = base64.urlsafe_b64encode(open('test_image_1.jpg', 'rb').read()).decode('utf-8')
req = '{"inputs" : {"image" : "' + b64 + '"}}'
predictor.predict(req)
```

The cloudwatch logs suggests that the request signature might not be correct.

```
tf_container - {
"modelSpec": {
"version": "1",
"name": "generic_model"
},
"metadata": {
"signature_def": {
"@type": "type.googleapis.com/tensorflow.serving.SignatureDefMap",
"signatureDef": {
"serving_default": {
"inputs": {
"image": {
"dtype": "DT_FLOAT",
"name": "input_3:0",
"tensorShape": {
"dim": [
{
"size": "-1"
},
{
"size": "-1"
},
{
"size": "-1"
},
{
"size": "3"
}
]
}
}
},
"methodName": "tensorflow/serving/predict",
"outputs": {
"scores": {
"dtype": "DT_FLOAT",
"name": "dense_3/Softmax:0",
"tensorShape": {
"dim": [
{
"size": "-1"
},
{
"size": "2"
}
]
}
}
}
}
}
}
}
```

On calling predict we have following log :
```
ERROR in serving: Unable to convert value to TensorProto: {"inputs" : {"image" : "_9j...._9k="}}
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 221, in _invoke
self.transformer.transform(content, input_content_type, requested_output_content_type)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 297, in transform
return self.transform_fn(data, content_type, accepts), accepts
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 224, in f
prediction = self.predict_fn(input)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 239, in predict_fn
return self.proxy_client.request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 82, in request
return request_fn(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 109, in predict
request = self._create_predict_request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 124, in _create_predict_request
input_map = self._create_input_map(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 217, in _create_input_map
return {self.input_tensor_name: self._value_to_tensor(data)}
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 232, in _value_to_tensor
raise ValueError(msg.format(value))
```

I do not understand where exactly I am going wrong. Shouldn't the serving_input_fn take care of this? Is it even being used?

**Comment by AnyAndyAbhy** [comment]
I have also tried sending the image tensor like :

`

import cv2
import skimage.io as skio
import numpy as np
from keras.applications.inception_resnet_v2 import preprocess_input as irv2_preprocess

def preprocess(image):
        """
        Preprocess input data to forward pass with the model
        Args:
          input_data: list of one or more images for classification 
        """
        image = cv2.resize(image, (399,399))
        out = np.expand_dims(irv2_preprocess(image), axis=0) 
        return out


img = skio.imread('test_image_1.jpg')
print(img.shape)
img2 = preprocess(img)

import json
b65 = json.dumps(json.loads(json.dumps(img2.tolist()), parse_float=lambda x: round(float(x), 6)))
req = '{"inputs" : {"image" : "' + b65 + '"}}'

predictor.predict(req)
`

I still get the same 500 internal error and in logs:

`
ValueError: Unable to convert value to TensorProto: {"inputs" : {"image" : "[[[[-0.380392, -0.090196, 0.6], ...... [-0.380392, -0.090196, 0.6]]]]"}}. 

Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/container_support/serving.py", line 221, in _invoke
self.transformer.transform(content, input_content_type, requested_output_content_type)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 297, in transform
return self.transform_fn(data, content_type, accepts), accepts
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 224, in f
prediction = self.predict_fn(input)
File "/usr/local/lib/python2.7/dist-packages/tf_container/serve.py", line 239, in predict_fn
return self.proxy_client.request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 82, in request
return request_fn(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 109, in predict
request = self._create_predict_request(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 124, in _create_predict_request
input_map = self._create_input_map(data)
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 217, in _create_input_map
return {self.input_tensor_name: self._value_to_tensor(data)}
File "/usr/local/lib/python2.7/dist-packages/tf_container/proxy_client.py", line 232, in _value_to_tensor
raise ValueError(msg.format(value))
`

**Comment by AnyAndyAbhy** [comment]
Note that when I run it locally it runs fine:
```
import tensorflow as tf
export_dir = "model"
model_load_tag = "serve"
!export CUDA_VISIBLE_DEVICES=0
sess = tf.Session(graph=tf.Graph())
model = tf.saved_model.loader.load(sess, [model_load_tag], export_dir)
print("model load successful")
```

```
import cv2
import skimage.io as skio
import numpy as np
from keras.applications.inception_resnet_v2 import preprocess_input as irv2_preprocess

def preprocess(image):
        """
        Preprocess input data to forward pass with the model
        Args:
          input_data: list of one or more images for classification 
        """
        image = cv2.resize(image, (399,399))
        out = np.expand_dims(irv2_preprocess(image), axis=0) 
        return out
```

```
img = skio.imread('test_image_1.jpg')
print(img.shape)
img2 = preprocess(img)
print(img2.shape)
print(model.signature_def)
sess.run(["dense_3/Softmax:0"], feed_dict={"input_3:0" : img2})
```

with output

```
(1351, 1108, 3)
(1, 399, 399, 3)
{'serving_default': inputs {
  key: "image"
  value {
    name: "input_3:0"
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: -1
      }
      dim {
        size: -1
      }
      dim {
        size: 3
      }
    }
  }
}
outputs {
  key: "scores"
  value {
    name: "dense_3/Softmax:0"
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: 2
      }
    }
  }
}
method_name: "tensorflow/serving/predict"
}

[array([[0.84045094, 0.15954906]], dtype=float32)]
```

**Comment by jesterhazy** [comment]
@AnyAndyAbhy There's a lot going on here!

Your serving_input_fn and your predict call inputs look reasonable, but you are right, the serving_input_fn isn't being used. It needs to be included in the SavedModel bundle itself -- when you export it -- in order for TensorFlow Serving to use it. See TensorFlow's [Prepare serving inputs](https://www.tensorflow.org/guide/saved_model#prepare_serving_inputs) docs for more info on this. You can also see this in some of our examples notebooks, like [this keras one](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-python-sdk/tensorflow_keras_cifar10/tensorflow_keras_CIFAR10.ipynb).

The entry_point script can't be used to add a serving_input_fn to the SavedModel after the fact, but it does let you add custom pre- and post-processing functions to the endpoint. That means you could use a different entry point script to handle image input if you wanted. See our [Endpoint prediction request handling](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_python.rst#endpoint-prediction-request-handling) for more info about that solution. Since you are close to getting this to work with your serving_input_fn, I'd recommend you stick with that approach because it will be more performant.

The reason it works locally... here, you are preprocessing the image to a tensor before passing it to the model via your session. Again, there is no serving_input_fn being used, but here your tensor input matches the required model input.

**Comment by AnyAndyAbhy** [comment]
What will I have to do to use the same image tensor I created locally named img2 and use with the predictor.predict() as that results in an error where connection is closed before getting a response. I suspect this maybe due to the size limit of 5MB. ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by AnyAndyAbhy** [comment]
I am successfully able to call using

import json
import boto3
import numpy as np
import io
import sys
import os
os.environ['KERAS_BACKEND'] = 'tensorflow'
import cv2
import skimage.io as skio
from keras.applications.inception_resnet_v2 import preprocess_input as irv2_preprocess
from sagemaker.session import Session

def preprocess(image):
        """
        Preprocess input data to forward pass with the model
        Args:
          input_data: list of one or more images for classification 
        """
        image = cv2.resize(image, (399,399))
        out = np.expand_dims(irv2_preprocess(image), axis=0) 
        return out


img = skio.imread('test_image_1.jpg')
imgPreProcessed = preprocess(img)

imageTensorCompactJson = json.dumps(json.loads(json.dumps(imgPreProcessed.tolist()), parse_float=lambda x: round(float(x), 6)))

endpoint_name="sagemaker-tensorflow-****-**-**-**-**-**-***"
client = boto3.client('runtime.sagemaker', region_name='us-east-1')
startString = '{"image":'
endString = '}'
response = client.invoke_endpoint(EndpointName=endpoint_name, Body=startString + imageTensorCompactJson + endString)
response_body = response['Body']
print(response_body.read())

**Comment by AnyAndyAbhy** [comment]
ok finally able to call directly using predictor using predictor.predict({ "image" : json.loads(imageTensorCompactJson)})
