### ISSUE TITLE
Default Pytorch Python version does not match official build Dockerfile

### ISSUE THREAD

**Issue by plynch-chewy** [aws/sagemaker-python-sdk#743]
Please fill out the form below.

### System Information
- **Framework**: Pytorch
- **Framework Version**: 1.0.0.dev
- **Python Version**: 
- **CPU or GPU**: GPU
- **Python SDK Version**: sagemaker-containers 2.4.4.post2
- **Are you using a custom image**:

### Describe the problem
Official Pytorch image does not match build from [sagemaker-pytorch-containerl](https://github.com/aws/sagemaker-pytorch-container)

Current default `sagemaker.pytorch.PyTorch` image uses `3.5.2`, while "official build" from above repo uses 3.6.

See https://github.com/aws/sagemaker-pytorch-container/issues/89

**Comment by jesterhazy** [comment]
@plynch-chewy 

You are getting an out of date image because you are using an unmaintained pre-release version of our pytorch framework. Use `framework_version=1.0.0` instead of `1.0.0.dev`.
