### ISSUE TITLE
NCHW format not supported in c5.xlarge deployment

### ISSUE THREAD

**Issue by gautiese** [aws/sagemaker-python-sdk#771]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**:1.12
- **Python Version**:2.7
- **CPU or GPU**:CPU
- **Python SDK Version**:
- **Are you using a custom image**:No

### Describe the problem
Describe the problem or feature request clearly here.

We trained a model on Tensorflow which consumes images in the format of NCHW. The training was done on GPUs (I believe NCHW is only supported by GPUs or MKL capable Intel processors).

When I try to infer from the model using an endpoint which is ml.c5.xlarge, I get the following error:

E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:623] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.

#011 [[{{node Gs/cond/8x8/Conv0_up/conv2d_transpose}} = Conv2DBackpropInput[T=DT_FLOAT, _output_shapes=[[1,512,8,8]], data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Gs/cond/8x8/Conv0_up/conv2d_transpose/output_shape, Gs/cond/8x8/Conv0_up/AddN, Gs/cond/ToRGB_lod6/Conv2D/Switch:1)]]

Strangely, when I deploy the same on the local notebook instance (which is also ml.c5.xlarge) the model works just fine!

**Comment by jesterhazy** [comment]
Hi @gautiese, thanks for using SageMaker!

Yes, it looks like you are using a non-MKL build of TensorFlow in SageMaker, and an MKL build in EC2.

Which "framework_version" (or container image uri) are you using when you create the endpoint?

**Comment by gautiese** [comment]
I am using 1.13 as the framework version.
Not using a custom image.
Is the sagemaker tensorflow inference image a non-MKL build?

**Comment by jesterhazy** [comment]
We haven't released any tensorflow 1.13 container yet, are you sure that's the right version? The info in the original post says 1.12, so I'm going to assume that's still correct.

We have a couple of different inference containers for TensorFlow. For 1.12 and up, the default one is our "TensorFlow Serving" container, described [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst). Right now it doesn't have MKL, but we are working on adding it. It sounds like this is the container you are using.

The other container is the older python-based container (described [here](https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_python.rst)). That one has MKL support, but the programming model is a bit different -- you'll need to create a python inference script, and the code to deploy the endpoint it slightly different.

Until we add MKL support to the newer container, your options would be to a) change your model to accept NHWC input, or b) deploy to our python-based container.

I'm going to tag this as a feature request (for MKL support) and leave it open.

**Comment by gautiese** [comment]
You are right, I am on 1.12.
Will be waiting eagerly for the MKL containers!
Re training this model will be very expensive at this moment.

**Comment by gautiese** [comment]
If I was to create an MKL-DNN sagemaker tensorflow serving container myself... How would I go about it? I am being pressed to deploy my model on a CPU instance soon (budgets)

**Comment by martinRenou** [comment]
More recent containers now come with the MKL optimization. Closing as fixed.
