### ISSUE TITLE
InstallModuleError when deploying a Pytorch model on Sagemaker endpoint

### ISSUE THREAD

**Issue by msobroza** [aws/sagemaker-python-sdk#773]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Pytorch
- **Framework Version**: 1.0.0
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem
I'm trying to deploy an already trained Pytorch model on sagemaker. I have an error message when I run the script to deploy.

```
from sagemaker.predictor import RealTimePredictor, json_deserializer

class CoupleDocumentsPredictor(RealTimePredictor):
    def __init__(self, endpoint_name, sagemaker_session):
        super(CoupleDocumentsPredictor, self).__init__(endpoint_name, sagemaker_session, content_type='application/json')
```

Train my estimator

```
from sagemaker.pytorch import PyTorchModel
pytorch_estimator = PyTorchModel(model_data= 's3://' + sagemaker_session.default_bucket() + '/doctrinal_binary_model/doctrinal_binary_model.tar.gz',
                            entry_point='./doctrinal_binary/inference_binary.py',
                            role = role,
                            py_version='py3',
                            source_dir='sagemaker-inference/source',
                            predictor_cls=CoupleDocumentsPredictor,
                            framework_version='1.0.0')
```

Deploy my estimator to a SageMaker Endpoint and get a predictor

```
predictor = pytorch_estimator.deploy(instance_type='ml.c4.xlarge',
                                     initial_instance_count=1)
```

The code to the entry point:

```
def model_fn(model_dir):
    """
    Load the torch model. Called once when hosting service starts.
    :param: model_dir The directory where model files are stored.
    :return: a model
    """
    logger.info('model_fn')
    model = Model()
    with open(os.path.join(path, 'model.pth'), 'rb') as f:
        model.state_dict = torch.load(f)
    logger.info('model_loaded')
    return model

def input_fn(request_body, request_content_type):
    """
    Deserialize the Invoke request body into an object we can perform prediction on
    """
    """An input_fn that loads a pickled object"""
    logger.info('model_input')
    if request_content_type == "application/json":
        input_data = json.loads(request_body)
        u = torch.from_numpy(np.array(input_data['input_1']).reshape(-1)).type(torch.float32)
        v = torch.from_numpy(np.array(input_data['input_2'])).type(torch.float32)
        return (u, v)
    else:
        # Handle other content-types here or raise an Exception
        # if the content type is not supported.
        pass
    

def predict_fn(input_object, model):
    """
    Perform prediction on the deserialized object, with the loaded model
    """
    logger.info('predict_fn')
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    u, v = input_object
    model.to(device)
    model.eval()
    with torch.no_grad():
        output, _, _ = model(u.to(device).unsqueeze(-1).view(-1, model.vocab_size), v.to(device).unsqueeze(-1).view(-1, model.vocab_size))
        return output.numpy()
    return None

def output_fn(output, output_content_type):
    """
    Serialize the prediction result into the desired response content type
    """
    logger.info('output_fn')
    return json.dumps({'output':output.reshape(-1).tolist()}), output_content_type
```

### Minimal repro / logs

The logs of errors are:
`sagemaker_containers._errors.InstallModuleError: InstallModuleError:`

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_pytorch_container/serving.py", line 103, in main
user_module = modules.import_module(serving_env.module_dir, serving_env.module_name)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 244, in import_module
install(_env.code_dir)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 110, in install
_process.check_error(shlex.split(cmd), _errors.InstallModuleError, cwd=path, capture_error=capture_error)
File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_process.py", line 48, in check_error
raise error_class(return_code=return_code, cmd=' '.join(cmd), output=stderr)
```

- **Exact command to reproduce**:

Thank you very much for the help

**Comment by icywang86rui** [comment]
@msobroza 

Sorry that you run into this problem. Could you show me the full cloudwatch log from this failed deployment? Could you also double check that the entry_point script is on the correct path `./doctrinal_binary/inference_binary.py`?

**Comment by msobroza** [comment]
@icywang86rui 

Thank you for your answer. I double checked the entry_point script path

The full cloudwatch log is:

> 10.32.0.1 - - [15/May/2019:00:12:39 +0000] "GET /ping HTTP/1.1" 500 141 "-" "AHC/2.0"
> Failed to import the site module
> Traceback (most recent call last):
> File "/usr/lib/python3.6/site.py", line 570, in <module>
> main()
> File "/usr/lib/python3.6/site.py", line 557, in main
> known_paths = addsitepackages(known_paths)
> File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
> addsitedir(sitedir, known_paths)
> File "/usr/lib/python3.6/site.py", line 213, in addsitedir
> addpackage(sitedir, name, known_paths)
> File "/usr/lib/python3.6/site.py", line 169, in addpackage
> for n, line in enumerate(f):
> File "/usr/lib/python3.6/codecs.py", line 321, in decode
> (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> [2019-05-15 00:12:44 +0000] [24] [ERROR] Error handling request /ping
> Traceback (most recent call last):
> File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
> self.handle_request(listener_name, req, client, addr)
> File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
> addr)
> File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
> respiter = self.wsgi(environ, resp.start_response)
> File "/usr/local/lib/python3.6/dist-packages/sagemaker_pytorch_container/serving.py", line 103, in main
> user_module = modules.import_module(serving_env.module_dir, serving_env.module_name)
> File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 244, in import_module
> install(_env.code_dir)
> File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_modules.py", line 110, in install
> _process.check_error(shlex.split(cmd), _errors.InstallModuleError, cwd=path, capture_error=capture_error)
> File "/usr/local/lib/python3.6/dist-packages/sagemaker_containers/_process.py", line 48, in check_error
> raise error_class(return_code=return_code, cmd=' '.join(cmd), output=stderr)
> sagemaker_containers._errors.InstallModuleError: InstallModuleError:

**Comment by msobroza** [comment]
If I use PyTorch 0.4.0 instead of 1.0.0. I have the following messages of error

```
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 84, in wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/inference.py", line 52, in model_fn
with open(os.path.join(model_dir, 'model.pth'), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ml/model/model.pth'
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_pytorch_container/serving.py", line 107, in main
user_module_transformer.initialize()
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_transformer.py", line 157, in initialize
self._model = self._model_fn(_env.model_dir)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 86, in wrapper
six.reraise(error_class, error_class(e), sys.exc_info()[2])
File "/usr/local/lib/python3.5/dist-packages/six.py", line 692, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 84, in wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/inference.py", line 52, in model_fn
with open(os.path.join(model_dir, 'model.pth'), 'rb') as f
sagemaker_containers._errors.ClientError: [Errno 2] No such file or directory: '/opt/ml/model/model.pth'
Traceback (most recent call last):
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 56, in handle
self.handle_request(listener_name, req, client, addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request
addr)
File "/usr/local/lib/python3.5/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request
respiter = self.wsgi(environ, resp.start_response)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_pytorch_container/serving.py", line 107, in main
user_module_transformer.initialize()
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_transformer.py", line 157, in initialize
self._model = self._model_fn(_env.model_dir)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 86, in wrapper
six.reraise(error_class, error_class(e), sys.exc_info()[2])
File "/usr/local/lib/python3.5/dist-packages/six.py", line 692, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.5/dist-packages/sagemaker_containers/_functions.py", line 84, in wrapper
return fn(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/inference.py", line 52, in model_fn
with open(os.path.join(model_dir, 'model.pth'), 'rb') as f:
Failed to import the site module

```

**Comment by panfeng-hover** [comment]
@msobroza Sorry for bothering you. I previously use Tensorflow models to create an endpoint, and Tensorflow needs to export the checkpoint for serving, which used the `tf.saved_model` class, different from general `tf.train.Saver()` restore stuff.

```
builder = tf.saved_model.builder.SavedModelBuilder(export_path)
builder.add_meta_graph_and_variables(
      sess, [tf.saved_model.tag_constants.SERVING],
      signature_def_map={
           'predict_images':
               prediction_signature,
           signature_constants.DEFAULT_SERVING_SIGNATURE_DEF_KEY:
               classification_signature,
      },
      main_op=tf.tables_initializer())
```

I am wondering, if use Pytorch, for an arbitrary model, is there any similar way like in Tensorflow to export the model?

Thanks in advance!

**Comment by jesterhazy** [comment]
@panfeng-hover take a look at the pytorch docs on [saving and loading models](https://pytorch.org/tutorials/beginner/saving_loading_models.html).

**Comment by jesterhazy** [comment]
@msobroza based on the pytorch 0.4.0 stack trace, it looks like `model.pth` is not at the expected location. In your `doctrinal_binary_model.tar.gz` archive, is `model.pth ` located at the root or in a directory?

**Comment by msobroza** [comment]
Thank you very much @jesterhazy I put the serialized model in sagemaker-inference instead of sagemaker-inference/source and changed the version to Pytorch 0.4.0 and it worked perfectly !
