### ISSUE TITLE
upload_data

### ISSUE THREAD

**Issue by frdchang** [aws/sagemaker-python-sdk#774]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
- **Framework Version**: 
- **Python Version**: 3
- **CPU or GPU**: CPU
- **Python SDK Version**:
- **Are you using a custom image**: no

### Describe the problem
upload_data() under sessions.py can not upload to encrypted s3 buckets right now.  Fortunately, The boto3 function that upload_data() is based on, upload_file(), can accept 'ExtraArgs' as a parameter, in which the encryption key and such can be defined.  

For example, upload_data may look like the following, with ExtraArgs being passed to upload_file
upload_data(....,ExtraArgs = {'ServerSideEncryption':'aws:kms', 'SSEKMSKeyId':'alias/aws/s3'})

note that estimator uses a different format to pass in the KMSKEY info.  Perhaps there is a standard way of passing this info.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by jesterhazy** [comment]
Hi @frdchang, thanks for using SageMaker! 

Your request looks like a small change, I'll mark it as contributions welcome and you can submit a Pull Request.

**Comment by drajeshk** [comment]
Hi @frdchang , Is it ok if I submit a PR for this issue?

**Comment by drajeshk** [comment]
PR #836  submitted

**Comment by laurenyu** [comment]
change has been released in v1.26.0

**Comment by frdchang** [comment]
Hello,

thanks for looking into this!
Fred

**Comment by JoaoSilva02** [comment]
Try this (you need to copy the S3 bucket KMS encryption key):


bucket = 'BucketName'
prefix = 'Whatever'

test_location = session.upload_data(os.path.join(data_dir, 'test.csv'), key_prefix = prefix, bucket = bucket, extra_args = {"ServerSideEncryption": "aws:kms",  "SSEKMSKeyId": "xxxxxx-xxxxx-xxxxx"})
