### ISSUE TITLE
The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint. while I am using python3 not python2 for scikit_bring_your_own?

### ISSUE THREAD

**Issue by 19feridwaniky** [aws/sagemaker-python-sdk#787]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
- **Framework Version**:
- **Python Version**:
- **CPU or GPU**:
- **Python SDK Version**:
- **Are you using a custom image**:

### Describe the problem
Describe the problem or feature request clearly here.

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by jesterhazy** [comment]
Closing as duplicate of #793
