### ISSUE TITLE
endpoint failure with scikit BYO container

### ISSUE THREAD

**Issue by 19feridwaniky** [aws/sagemaker-python-sdk#793]
Hi,
 I have a problem while I am using python3 not python2 for scikit_bring_your_own?
The primary container for production variant AllTraffic did not pass the ping health check. Please check CloudWatch logs for this endpoint. while I am using python3 not python2 for scikit_bring_your_own?

**Comment by jesterhazy** [comment]
Thanks for using SageMaker!

We now provide a standard [scikit-learn container](https://github.com/aws/sagemaker-scikit-learn-container) that includes python 3 support. Try using that instead of creating a custom container.
