### ISSUE TITLE
Tensorflow 1.12 Python 3 Container

### ISSUE THREAD

**Issue by addiemalick** [aws/sagemaker-python-sdk#795]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: TensorFlow
- **Framework Version**: 1.12
- **Python Version**: 3.7
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.20.1
- **Are you using a custom image**: No

### Describe the problem
In local mode I am getting this error:

Error response from daemon: manifest for 520713654638.dkr.ecr.us-east-1.amazonaws.com/sagemaker-tensorflow:1.12-cpu-py3 not found

### Minimal repro / logs
    from sagemaker.tensorflow.model import TensorFlowModel
    sagemaker_model = TensorFlowModel(model_data = 's3://' + <bucket> + '/model/model.tar.gz',
                                    role =  role,
                                    entry_point='script.py',
                                    py_version='py3',
                                    framework_version = '1.12',
                                    predictor_cls=predictor)

    predictor = sagemaker_model.deploy(initial_instance_count=1,
                                    instance_type='local')

- **Exact command to reproduce**:

**Comment by icywang86rui** [comment]
@addiemalick 

TensorFlowModel supports the legacy mode TF containers which do not have py3 support. Your script has to be a python 2.7 script. This error message is not really informative I will make a note to fix it. If your script is py2 compatible you can remove `py_version='py3'` and the error should go away.

If you would like to use a python 3 script please look into our TensorFlow serving containers - https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst
This container originally only supports TensorFlow rest APIs and we have recently released a version to support python pre/post processing. The documentation hasn't been updated with information about the python interfaces yet. Please don't hesitate to ask if you have any questions.

**Comment by addiemalick** [comment]
@icywang86rui Thanks for the pointer to python 3 supported TensorFlow containers for serving. 

Regarding python pre/processing, can you let us know when the documentation will become available?

**Comment by addiemalick** [comment]
@icywang86rui did you have an update on above questions? Thanks.

**Comment by ChuyangDeng** [comment]
Hi, @addiemalick, we have updated the TensorFlow Serving container documentation for pre/post-post processing here: [TFS container pre/post-processing](https://github.com/aws/sagemaker-tensorflow-serving-container#prepost-processing). There's also documentation on how to package your script with model: [Packaging SageMaker Models for TensorFlow Serving](https://github.com/aws/sagemaker-tensorflow-serving-container#packaging-sagemaker-models-for-tensorflow-serving).

The pre/post-processing documentation on Python SDK side is still work in progress, but it should come soon.

**Comment by ChoiByungWook** [comment]
The documentation for pre/post processing in the TFS container has been merged in the Python SDK: https://github.com/aws/sagemaker-python-sdk/pull/807
