### ISSUE TITLE
Kernel dies when importing tensorflow in Sagemaker

### ISSUE THREAD

**Issue by jennings1716** [aws/sagemaker-python-sdk#809]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**: 
- **Python Version**:3 & 2
- **CPU or GPU**:
- **Python SDK Version**:
- **Are you using a custom image**:
- **Instance type**: ml.t2.medium

### Describe the problem

When I import tensorflow in AWS sagemaker jupyter notebook kernel dies immediatly but it is able to import other packages like numpy scipy.
![Screenshot (95)](https://user-images.githubusercontent.com/13369949/58069958-e2264780-7bb4-11e9-94d6-e593ea73fb8f.png)

**Comment by jaipreet-s** [comment]
Hi @jennings1716,

I'm able to import tensorflow on the kernel you're using without any hiccups so it may be related to the state of your Notebook Instance
![Screen Shot 2019-05-23 at 10 38 42 AM](https://user-images.githubusercontent.com/43826141/58274093-f5691c80-7d46-11e9-935d-6591255ec4cb.png)

Could you try 
1. Checking the logs in `/var/log/jupyter.log` and post the error message here
2. Stop and start your Notebook Instance to restore it to an health state.
