### ISSUE TITLE
AWS CLI commands not working in Tensorflow script mode

### ISSUE THREAD

**Issue by tigerhawkvok** [aws/sagemaker-python-sdk#817]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow
- **Framework Version**: 1.12.0
- **Python Version**: 3.6
- **CPU or GPU**: GPU
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem
The training itself behaves, but when I try to execute an AWS CLI command, it craps out with `aws: not found`.

Possibly not the end of the world, and in particular this was more of a "check it" thing, but nevertheless....

```
INFO:tensorflow:Froze 2 variables.
INFO:tensorflow:Converted 2 variables to const ops.
./launcher.sh: 2: ./launcher.sh: aws: not found
./launcher.sh: 3: ./launcher.sh: aws: not found
2019-05-24 19:48:34,534 sagemaker-containers ERROR    ExecuteUserScriptError: [...]
```

The model itself is correctly targz'd to my S3 bucket.

### Minimal repro / logs

Sending into the estimator, commands like

```sh
# works
python pkahn_uc/retrain.py --image_dir ${SM_CHANNEL_TRAIN} --output_graph ${SM_MODEL_DIR}/myModel_output_graph_sagemaker.pb --output_labels ${SM_MODEL_DIR}/myModel_output_labels_sagemaker.txt   --random_brightness 10 --flip_left_right True --random_scale 10 --random_crop 5 --how_many_training_steps 50

# fails
aws s3 cp ${SM_MODEL_DIR}/myModel_output_graph_sagemaker.pb s3://sagemaker-mybucket/myModel_output_graph_sagemaker1558725581.557754.pb
aws s3 cp ${SM_MODEL_DIR}/myModel_output_labels_sagemaker.txt s3://sagemaker-mybucket/myModel_output_labels_sagemaker1558725581.557754.txt
```

- **Exact command to reproduce**:

Any `aws` command from within a Tensorflow script mode shell script entry point

**Comment by ChuyangDeng** [comment]
Hi @tigerhawkvok, thank you for using SageMaker!

Your description shows that you don't have aws cli installed/configured correctly. Please see these instructions to install and configure your aws cli on the instance/container you are running the script:

https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-install.html
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
