### ISSUE TITLE
ClientError: No iterator has been registered for ContentType (u'csv', '1.0')

### ISSUE THREAD

**Issue by Neel8496oyo** [aws/sagemaker-python-sdk#819]
Hello,
I'm using Linear learner for my binary classification problem and have stored my CSV file in S3 folder. When I'm starting a training job with s3_input object...

from sagemaker.amazon.amazon_estimator import get_image_uri
container = get_image_uri(boto3.Session().region_name, 'linear-learner')

s3_input_train = sagemaker.s3_input(s3_data=my_s3_path, content_type='csv')
sess = sagemaker.Session()

linear = sagemaker.estimator.Estimator(container, role, train_instance_count=1, 
                                       train_instance_type='ml.m4.xlarge',
                                       output_path=outputpath,
                                       sagemaker_session=sess)

linear.set_hyperparameters(feature_dim=10,
                           predictor_type='binary_classifier',
                           mini_batch_size=200)

linear.fit({'train': s3_input_train})

I'm getting this error.
"ValueError: Error for Training job linear-learner-2019-05-27-07-06-15-644: Failed Reason: ClientError: No iterator has been registered for ContentType (u'csv', '1.0')"

Can someone guide me, how to use CSV file for the training job?

Thanks,

**Comment by ChoiByungWook** [comment]
Hello @Neel8496oyo,

Can you try running your training job again but with `content_type='text/csv'`.

Thanks!
