### ISSUE TITLE
I want env parameter for  fit method of estimators

### ISSUE THREAD

**Issue by xnaiman** [aws/sagemaker-python-sdk#845]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Scikit-Learn
- **Framework Version**: 0.20.0 (official sagemaker-scikit-learn-container)
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: 1.26.0
- **Are you using a custom image**: No

### Describe the problem
I'd like to send environment-variable(`http_proxy`) to docker container at the time of training, but there is no way. On the other hand, the env parameter is prepared for the transform method.

### Minimal repro / logs
- **Exact command to reproduce**:
```python
env = {'HTTP_PROXY': os.environ['HTTP_PROXY']}
 
sklearn = SKLearn(
    entry_point='scikit_learn_iris.py',
    train_instance_type="ml.c4.xlarge",
    role=role,
    sagemaker_session=sagemaker_session,
    hyperparameters={'max_leaf_nodes': 30}
    )

sklearn.fit({'train': train_input}, env=env)      # I want to input env paramater here

**Comment by mvsusp** [comment]
Hello @xnaiman,

SageMaker Training Service does not allow you to specify environment variables at this moment. You need to set this variable in your training script. Another alternative is to generate your own Dockerfile and set the variable there.

Thanks for using SageMaker!

**Comment by xnaiman** [comment]
@mvsusp   
In my company, I need to use a proxy that requires user authentication. Therefore, I would like to avoid directly defining environment variables.   
At first I will use the method you have taught, and try to make it correspond to hyperparameters argument.

**Comment by mvsusp** [comment]
Using the hyperparameters is a good alternative, @xnaiman.

**Comment by ShwetaSingh801** [comment]
Hi @xnaiman,

Thanks for using SageMaker and taking the time to suggest ways to improve SageMaker Python SDK. We have added your feature request to our backlog of feature requests and may consider putting it into future SDK versions. I will go ahead and close the issue now, please let me know if you have any more feedback. Let me know if you have any other questions.

Best,
Shweta
