### ISSUE TITLE
Location of files and folders relative to entry point script

### ISSUE THREAD

**Issue by AlexUP** [aws/sagemaker-python-sdk#848]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: SKLearn
- **Framework Version**: Latest
- **Python Version**: 3
- **CPU or GPU**: CPU
- **Python SDK Version**: Latest
- **Are you using a custom image**: No

### Describe the problem
I am training an stacked classifier model from base models I have trained in Sagemaker.
Each base model's model.jobllib is extracted from their respective tar.gz files from S3 and are stored in a directory along with the entry point script for the stacking model. An example folder view looks like this:
```
models
----AdaBoostClassifier
-------model.joblib
----BernoulliNB
-------model.joblib
ensemble_training.py
```
The ensemble_training.py creates a feature matrix from input X matrix by using the base models probability predictions (in this case Adaboost and BernoulliNB). It locates the directory of where ensemble_training is called and extracts the model artefacts from there.

Locally, the script works fine. But I'm having trouble locating the "models" folder as the ensemble_training.py is called from (according to CloudWatch Logs):
```
'/usr/local/lib/python3.5/dist-packages/models'
```
and the folder "models" is not in the same directory. Where does the sagemaker container extract the source.tar.gz specified in the SKLearn object?

### Minimal repro / logs
```
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/models
```

- **Exact command to reproduce**:
```
sklearn = SKLearn.attach(training_job_name)

    predictor = sklearn.deploy(
        instance_type = instance_type,
        initial_instance_count = initial_instance_count,
        endpoint_name = project_name + '-' + model_name
    )
```
training_job_name is the name of the training job of the ensemble model. To train the ensemble model, the following is called:
```
sklearn = SKLearn(
        entry_point = ensemble_train.py,
        source_dir = "s3://" + ENTRY_POINT_BUCKET + '/' + "source.tar.gz",
        train_instance_type = some instance type,
        role = sagemaker role,
        py_version = "py3",
        hyperparameters = {
            'model_name': model_name
        }
    )

    sklearn.fit({'train': data_path})
```
with the file structure of source.tar.gz described as above.

**Comment by AlexUP** [comment]
I have tried inserting:
```
import os
module_path = os.path.abspath('/opt/ml/code')
if module_path not in sys.path:
    sys.path.append(module_path)
```
as suggested in https://github.com/aws/sagemaker-python-sdk/issues/648, but it doesn't work.

**Comment by AlexUP** [comment]
Fix it by appending the module_path to models:
```
os.listdir(os.path.join(module_path, "models"))
```

**Comment by mvsusp** [comment]
Hi @AlexUP,

The original files are stored under the `/opt/ml/code` directory.  I'm adding a feature request in the roadmap to add `/opt/ml/code` to __PYTHONPATH__ as well.

In the meanwhile, I believe you already found a solution for that issue.

Thanks for using SageMaker.
