### ISSUE TITLE
Batch transform on ndarray

### ISSUE THREAD

**Issue by tigerhawkvok** [aws/sagemaker-python-sdk#853]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Tensorflow / Batch Inference
- **Framework Version**: 1.12.0
- **Python Version**: 3
- **CPU or GPU**:
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem

I have a model that correctly serves as an endpoint from which I can generate [single predictions](https://sagemaker.readthedocs.io/en/stable/predictors.html). However, I'd like to classify many things at once. 

The [docs](https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipeline-batch.html) [suggest](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-batch.html) [batch](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-batch-transform.html) [transforms](https://docs.aws.amazon.com/sagemaker/latest/dg/API_TransformInput.html), and I can certainly make a [Transformer object](https://sagemaker.readthedocs.io/en/stable/model.html#sagemaker.model.Model.transformer) from my `model_data`, but as I'm doing image prediction my data are numpy arrays of shape `(299, 299, 3)`. 

For the predictor, I needed to provide a serializer after I got the image tensor out:

```python
def read_tensor_from_image_file(file_name, input_height=299, input_width=299, input_mean=128, input_std=128):
    """
    Code from v1.6.0 of Tensorflow's label_image.py example
    """
    #pylint: disable= W0621
    input_name = "file_reader"
    file_reader = tf.read_file(file_name, input_name)
    if file_name.endswith(".png"):
        image_reader = tf.image.decode_png(file_reader, channels=3, name="png_reader")
    elif file_name.endswith(".gif"):
        image_reader = tf.squeeze(tf.image.decode_gif(file_reader, name="gif_reader"))
    elif file_name.endswith(".bmp"):
        image_reader = tf.image.decode_bmp(file_reader, name="bmp_reader")
    else:
        image_reader = tf.image.decode_jpeg(file_reader, channels=3, name="jpeg_reader")
    float_caster = tf.cast(image_reader, tf.float32)
    dims_expander = tf.expand_dims(float_caster, 0)
    resized = tf.image.resize_bilinear(dims_expander, [input_height, input_width])
    normalized = tf.divide(tf.subtract(resized, [input_mean]), [input_std])
    sess = tf.Session()
    result = sess.run(normalized)
    return result
```

And I have a batch loop set up to dump `*.npy` files of pre-encoded tensors:

```python
# Prep it
numpyList = list()
chunkedPaths = list(chunks(fileList, 100))
print(f"Going to work on {len(fileList)} files over {len(chunkedPaths)} chunks...")
with timeit("Done in"):
    for chunk in chunkedPaths:
        alreadyEncoded = 0
        with timeit(f"Encoded {len(chunk)} images in"):
            for filen in chunk:
                fileNameBase = os.path.basename(filen).split(".")
                fileNameBase.pop()
                fileNameBase.append("npy")
                output = os.path.join(npyDir, ".".join(fileNameBase))
                numpyList.append(output)
                if os.path.exists(output):
                    alreadyEncoded += 1
                    continue
                npyTensor = read_tensor_from_image_file(filen)
                np.save(output, npyTensor, fix_imports= False)
        if alreadyEncoded > 0:
            print(f"\t... already had encoded {alreadyEncoded} images")
# Dump these onto S3
!aws s3 cp {npyDir} {bucketPath} --recursive --quiet
```

but it's not at all clear how to provide a serializer to the transform object so the transformer can ingest numpy ndarrays.

**Comment by mvsusp** [comment]
Hi @tigerhawkvok,

Are you using the TensorFlow or the TensorFlow Serving container? They both provide solutions to add pre and post processing steps to your inference calls. Would that be a good alternative to your problem?

**Comment by mvsusp** [comment]
Here are the links for the documentation on how to write pre and post processing steps:
- TFS container: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_tensorflow_serving.rst#how-to-implement-the-pre--andor-post-processing-handlers
- legacy TensorFlow container: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/tensorflow/deploying_python.rst#overriding-input-preprocessing-with-an-input_fn

Thanks for using SageMaker.

**Comment by tigerhawkvok** [comment]
@mvsusp No serving container, I was going to use the batch transformer: https://sagemaker.readthedocs.io/en/stable/model.html#sagemaker.model.Model.transformer

As I mentioned, 

> The [docs](https://docs.aws.amazon.com/sagemaker/latest/dg/inference-pipeline-batch.html) [suggest](https://docs.aws.amazon.com/sagemaker/latest/dg/how-it-works-batch.html) [batch](https://docs.aws.amazon.com/sagemaker/latest/dg/ex1-batch-transform.html) [transforms](https://docs.aws.amazon.com/sagemaker/latest/dg/API_TransformInput.html), and I can certainly make a [Transformer object](https://sagemaker.readthedocs.io/en/stable/model.html#sagemaker.model.Model.transformer) from my `model_data`, but as I'm doing image prediction my data are numpy arrays of shape `(299, 299, 3)`. 

I already have a fully functioning endpoint, I just want to test on ~20k images as a batch, and ultimately may run this on ~2.5M images.

**Comment by mvsusp** [comment]
@tigerhawkvok , thanks for your response. I need to know which specific container you are using to suggest you which pre and post processing functions you should use of the options mentioned above. You need to implement these functions in the container given that Batch transform does not allow you to provide a serializer.

**Comment by tigerhawkvok** [comment]
To be honest, @mvsusp I'm not sure what container I'm using for the transformer, so probably the default.

My code is set up to call

```python
# Create a Transformer for batch requests.
# https://sagemaker.readthedocs.io/en/stable/model.html#sagemaker.model.Model.transformer
t = model.transformer(instance_count= 1,
                           instance_type= COMPUTE_INSTANCE_TYPE,
                           strategy= "MULTI_RECORD",
                           splitType= "Line",
                           output_path= os.path.join(s3Bucket, f"{endpointName}_transformer_output"),
                           accept= "application/x-npy",
                           max_payload= 100)
t.transform(os.path.join(bucketPath, npyDir), content_type= "application/x-npy")
```

but I hadn't bothered trying to run it yet since I had no idea how to preprocess the information. I got as far as I mentioned in my original post -- precomputing the input tensor and dumping them to npy files -- but since I couldn't find how to provide a serializer/preparser I didn't go any further.

**Comment by mvsusp** [comment]
Do you mind sharing the code that is creating the model, @tigerhawkvok ?

**Comment by tigerhawkvok** [comment]
Solved it by just instancing the transformer off my model with an entry point
