### ISSUE TITLE
Fail to deploy custom Pytorch Model

### ISSUE THREAD

**Issue by dshahrokhian** [aws/sagemaker-python-sdk#854]
### System Information
- **Framework** Pytorch / Custom Model (BERT)
- **Framework Version**: 1.0.0
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: 3.6 PyTorchModel
- **Are you using a custom image**: Yes

### Describe the problem
I have been trying to deploy my own model for the last 3 days without success. I have a role with SageMakerFullAccess and my pytorch model is stored in S3. Right after I changed from the default Docker container to a custom one in order to be able to install dependencies, I have been getting the following error (even if I remove the option of `image` from the PytorchModel initialization).

### Minimal repro / logs
```
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 534, in run
    _stream_output(self.process)
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 594, in _stream_output
    raise RuntimeError("Process exited with code: %s" % exit_code)
RuntimeError: Process exited with code: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/sagemaker/local/image.py", line 539, in run
    raise RuntimeError(msg)
RuntimeError: Failed to run: ['docker-compose', '-f', '/tmp/tmpuc6hixqf/docker-compose.yaml', 'up', '--build', '--abort-on-container-exit'], Process exited with code: 1
```
- **Exact command to reproduce**:
This is what I have been using for deploying my already trained model:
```

import sagemaker
from sagemaker import get_execution_role

sagemaker_session = sagemaker.Session()
role = get_execution_role()
bucket = 'sagemodels'
path = 'models/finetuned_pytorch_model.bin'
model_location = 's3://{}/{}'.format(bucket, path)

from sagemaker.pytorch import PyTorchModel

pytorch_estimator = PyTorchModel(entry_point='dependencies/deploy.py',
                            model_data=model_location,
                            role=role,
                            framework_version='1.0.0',
                            source_dir='dependencies')

# Deploy trained model to an endpoint
predictor = pytorch_estimator.deploy(
        instance_type='local',
        initial_instance_count=1,
        endpoint_name='classifier'
)
```

**Comment by mvsusp** [comment]
Hello @dshahrokhian ,

The exception above is happening because the command:
```
docker-compose -f /tmp/tmpuc6hixqf/docker-compose.yaml up --build --abort-on-container-exit
```
is failing to run. Please ensure that `docker-compose` is working in your computer. You can execute the following command in your command line:

```
docker-compose -f /tmp/tmpuc6hixqf/docker-compose.yaml up --build --abort-on-container-exit
```

Please share with us the error that you get while running the command.

Thanks for using SageMaker!

**Comment by dshahrokhian** [comment]
Hi @mvsusp,

Thanks for the answer. I fixed the issue, it seems that the port was already taken.
