### ISSUE TITLE
Different requirements when deploying in 'local' vs 'ml.t2.medium'

### ISSUE THREAD

**Issue by dshahrokhian** [aws/sagemaker-python-sdk#867]
When deploying a model in local, `PyTorchModel` with `model_data` pointing at the S3 directory of my `.bin` model file does not seem to cause any trouble for loading, but as soon as I switch to `ml.t2.medium` instance_type, it complains that `model_data` is a directory, and I have to switch to the full path to the model, in which case now complains about the file not being `.tar.gz`, even though my `model_fn` definition handles the situation. Any clues?

Thanks,
Daniyal

**Comment by ChuyangDeng** [comment]
Hi @dshahrokhian, thank you for using SageMaker!

Can you provide more information on your usage of `PyTorchModel`? e.g. your serving script? your implementation of `model_fn`?

For `ml.t2.medium`, the `sagemaker_session` is this class: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/session.py; but for `local` mode, the `sagemaker_session` is a difference class: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/local/local_session.py

They have different ways to handle resources depending on the purpose of your methods.
