### ISSUE TITLE
`requirements.txt` not working for PytorchModel

### ISSUE THREAD

**Issue by dshahrokhian** [aws/sagemaker-python-sdk#868]
There is no way to install dependencies for `PytorchModel`, unless one uses the trick of installing within the python script using `subprocess`.

**Comment by ChuyangDeng** [comment]
Hi @dshahrokhian, thank you for using SageMaker! You can include you `requirements.txt` file into the `source_dir` here: https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/model.py#L506 to have your dependencies installed.

Example: 

`pytorch_model = PyTorchModel(source_dir='<put your requirements.txt in this source_dir>')`

**Comment by pinal-patel** [comment]
Hello @ChuyangDeng 

I am facing same issue. I want deploy already trained pytorch model (outside of sagemaker) on sagemaker. Below is my part of script

```
env={'SAGEMAKER_REQUIREMENTS': 'requirements.txt'}
model = sagemaker.pytorch.model.PyTorchModel(model_data=model_data,
                    entry_point='myentrypoint.py',
                    role=role,
                    py_version='py3',
                    env=env,
                    source_dir="src",
                    framework_version='1.2.0',
                    )
predictor = model.deploy(
        instance_type='ml.m4.xlarge',
        initial_instance_count=1,
        endpoint_name='my-end-point-name',
)
```

And src folder contain two file 
1. myentrypoint.py
2. requirements.txt

requirement file has following three library:
transformers==2.0.0
spacy==2.1.6
nltk==3.4
 
at time of request to endpoint, its throw an error of "ModuleNotFoundError: No module named 'transformers'"


please guide me, if is there any mistake or better way to handle this case.

**Comment by vlordier** [comment]
It seems the `dependencies=['your_file.py']` is also being ignored in the `PyTorchModel` call as well on image `1.3.1`

**Comment by laurenyu** [comment]
For PyTorch 1.2+, your model tar can include a requirements.txt file in the following structure:

```
model
  |- model files
code
  |- inference.py
  |- requirements.txt
```

**Comment by vlordier** [comment]
What about the dependency list ?

As in, inference.py contains an import
from model.py import SuperCoolModel

and this file model.py would be packaged as well ?

**Comment by laurenyu** [comment]
those files should also be able to go under `code/` in the model tar

**Comment by vlordier** [comment]
@laurenyu same question to pack pre-trained pytorch models, typically looked up in 
`.cache/torch` 
Should I build a custom `Dockerfile` with 
`COPY` to  `.cache/torch` ?
Is there another way to pack pre-trained model using `PytorchModel` than creating a `Dockerfile` from scratch ?

**Comment by laurenyu** [comment]
@vlordier can you open up a new issue? (your question sounds different enough and it's helpful to keep these issue threads about a single topic)

do you need to have the model saved at `.cache/torch` when serving predictions?

**Comment by vlordier** [comment]
https://github.com/aws/sagemaker-python-sdk/issues/1195#issue-542166444 👍

**Comment by morelen17** [comment]
I've run into the same problem described by @dshahrokhian. Passing directory that contains requirements file as `source_dir` to the `PyTorchModel` (as @pinal-patel suggested) does not help at all. Is there any alternative besides explicitly running package installation
```python
import subprocess
import sys

subprocess.check_call([sys.executable, "-m", "pip", "install", "some_required_package"])
```
within the entry point code?

I'm using `sagemaker==1.49.0`.

**Comment by vlordier** [comment]
Having requirements.txt in the /code directory with a pytorch image 1.3.1
works.

**Comment by morelen17** [comment]
@vlordier how `requirements.txt` can be stored there using only Sagemaker SDK with Sagemaker's default PyTorch image?
@vlordier, could you please provide an example of how to force `PyTorchModel` to consider `requirements.txt`? My code is pretty straightforward and repeats the stages described [here](https://sagemaker.readthedocs.io/en/stable/using_pytorch.html#deploy-pytorch-models).
@laurenyu 's suggestion of having `model.tar.gz` file of specific structure did not work as well.

**Comment by Serhiy-Shekhovtsov** [comment]
@laurenyu, it looks like we can't store anything under `/code` of model.tar since the entire directory tree under `code` is always removed during repacking:
https://github.com/aws/sagemaker-python-sdk/blob/master/src/sagemaker/utils.py#L518

The only way to get it working is to point `source_dir` to a folder containing `requirements.txt`. All the content inside `source_dir` is copied to `opt/ml/model/code` on target machine. The file specified as `entry_point` will also be coped there.

Another thing - since the entire content and structure of `source_dir` is packaged and copied to the container it doesn't make much sense to build the model tar manually every time and then create the model using `PyTorchModel.deploy`. Instead, you can store the model, requirements file and the code in a folder provided as `source_dir` and only run `PyTorchModel.deploy`.

**Comment by Serhiy-Shekhovtsov** [comment]
@morelen17 you probably stored `requirements.txt` in the folder specified in `source_dir`, not in `model.tar`, right?

**Comment by morelen17** [comment]
@Serhiy-Shekhovtsov right.

**Comment by mukeshyadav** [comment]
I have a pre-trained model, now trying to create an endpoint using Sagemaker, my folder structure like this
"model.tar.gz" looks like this:

model
  |- config.json
  |- pytorch_model.bin
  |- special_tokens_map.json
  |- spiece.model
  |- tokenizer_config.json
  |- training_args.bin
code
  |- inference.py
  |- requirements.txt

running following script to create endpoint:

`pytorch_model = PyTorchModel(
    model_data='s3://mck-dl-ai-studio/answer_card/answercard.tar.gz', 
    role=role, 
    entry_point='inference.py',
    framework_version="1.3.1")`

`predictor = pytorch_model.deploy(instance_type='ml.t2.medium', initial_instance_count=1)`

An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "No module named 'transformers'". See https://us-west-2.console.aws.amazon.com/cloudwatch/home?region=us-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/pytorch-inference-2020-07-20-16-45-51-564 in account 171739898504 for more information.

what I am missing here tried adding source_dir and py_version but no success

**Comment by touzariLiticia** [comment]
@mukeshyadav Hello, I'm facing the same issue, have you been able to fix it ?

**Comment by Ahtesham00** [comment]
@laurenyu @mukeshyadav
I am installing following packages using requirement.txt file in SageMaker training job

requirements.txt file is under code directory

```
numpy
rouge_score
fire
transformers>=4.26.1
torch
sentencepiece
tokenizers==0.12.1
wandb
git+https://github.com/zphang/transformers@llama_push
```

**Issue I am facing :** I am not able to access classes from this specific PR https://github.com/zphang/transformers@llama_push as this should also be installed as others are. I tested this requirements.txt file with my local python virtual env and it was working and installing all the packages including the Specific PR provided above.

What's the issue?

Is SageMaker training job does not install repos using git?

My estimator code is following

```
estimator = PyTorch(entry_point='train.py',
                    source_dir='code', 
                    role=role[0],
                    framework_version='1.9',
                    py_version='py38',
                    instance_count=1,
                    instance_type='ml.m5.large',
                    input_mode='File')
estimator.fit({'train': train_input})
```
Please help me regarding this.

**Comment by meg261995** [comment]
Same issue.. Can anyone tell me what was the final solution ?

**Comment by shakedlokits** [comment]
Same issue, still here in 2024 🌻

**Comment by rohit901** [comment]
any fix for this?
