### ISSUE TITLE
how to pass multiple S3 keys to Estimator.fit?

### ISSUE THREAD

**Issue by jmckib** [aws/sagemaker-python-sdk#87]
I have created my own algorithm container very similar to the [scikit_bring_your_own example](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/scikit_bring_your_own). I also have an S3 directory full of about 50 files, some of which I'd like to use for training and some for prediction. Right now, in order to use some subset of those files for training I actually have to create a new S3 directory and copy the training files into that directory, so I can pass the directory to `Estimator.fit`. Is there a better way of doing this that doesn't require me to touch my files in S3? Ideally I would like to be able to pass a list of S3 key prefixes to Estimator.fit, so that I can train on multiple files that do not share the same prefix. Shuffling the files around in S3 becomes especially impractical if I want to do something like k-folds cross validation. Thanks!

**Comment by andremoeller** [comment]
Hi,

Thanks for using Amazon SageMaker!

`fit` takes in an S3 prefix, so if your training files have the same prefix (like "train_"), you could do:

`estimator.fit("s3://my_bucket/my_training_data/train_")`

But if you want to train using a single training channel with the data at multiple S3 prefixes, like:
`estimator.fit(["s3://my_bucket/my_training_data/1_train", "s3://my_bucket/my_training_data/2_train"]`

Is this what you'd like to do? I don't believe there's a simple way at the moment to do that without renaming S3 prefixes in S3:
https://github.com/aws/sagemaker-python-sdk/blob/6b809eba605119ff274b39b3c8df3dd1163e784a/src/sagemaker/estimator.py#L332-L340

**Comment by jmckib** [comment]
> Is this what you'd like to do? I don't believe there's a simple way at the moment to do that without renaming S3 prefixes in S3:

@andremoeller Yes, that's what I'd like to do. It looks like I will have to rename S3 prefixes in order to do this. Thanks for the quick response!

**Comment by sinemetu1** [comment]
Is this a feature we could add? A common data warehouse pattern is to partition by date so users would need to copy files to a different bucket for training with 7 days for example instead of an entire months of data if paths are like:

```
s3://example/bucket/dt=2020-12-19
s3://example/bucket/dt=2020-12-20
s3://example/bucket/dt=2020-12-21
```

Currently `s3://example/bucket/dt=2020-12-` is the only way to pull in these buckets right?
