### ISSUE TITLE
The model data archive is too large. Please reduce the size of the model data archive or move to an instance type with more memory.

### ISSUE THREAD

**Issue by m4nuC** [aws/sagemaker-python-sdk#879]
### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: Gensim
- **Framework Version**: 3.7.3
- **Python Version**: 3.6
- **CPU or GPU**: CPU
- **Python SDK Version**: 
- **Are you using a custom image**: YES

### Describe the problem
I am using a custom image to load a Gensim model.

In a notebook `ml.m5.medium` instance, the model loads fine (it's not fully loaded to memory), but inside a Sagemaker instance, I need to use an `ml.m5.2xlarge` otherwise endpoint creation fails with this error:`The model data archive is too large. Please reduce the size of the model data archive or move to an instance type with more memory.` 

The model artifacts weigh 8Gb in tar ball. 

The image I am using is a "known-good" image, that I'd swear I've used to create `ml.m5.large` endpoints.

Are there been any recent changes in how model artifacts are handled?

**Comment by dshahrokhian** [comment]
Maybe you set the volme size higher than 5Gb (default) when creating the notebook instance? It is an option when you are creating the notebook under `Additional configuration`. Maybe try figuring out how to change the deployed volume size.

![screenshot](https://user-images.githubusercontent.com/8654460/60119168-15dd2a00-977e-11e9-9734-210faa39c149.png)

**Comment by m4nuC** [comment]
@dshahrokhian the model loads fine in the notebook. The problem seems to be around the transiting and extracting of the model artifacts

**Comment by m4nuC** [comment]
Turns out to be due to disk space restriction for instances: https://docs.aws.amazon.com/sagemaker/latest/dg/host-instance-storage.html

**Comment by lifinger** [comment]
Thanks for providing this link. I noticed the largest EBS volume is 30gb. In my case, my model.tar.gz file is 10gb, after uncompressing, it's larger than 30gb. It still throws me the error when I use multiple instances(each of them is 30gb). Are you able to deploy it in your case? Is there an argument like `train_volume_size` when we train the model? Or other methods?

**Comment by m4nuC** [comment]
@lifinger Sorry I dont know. I've ended up using EC2 to deploy my model

**Comment by seth814** [comment]
This is an issue with the instance memory. The instance needs to have enough memory to hold the uncompressed model. For a while I was reusing trained models and the endpoint config wasn't resetting to the new instance type I was putting in my code. Causing it to use my old ml.m5 instance. Using ml.r5 instances will let you get more memory over the ml.m5 instances. Once I deleted the old endpoint config and made sure I was working with 64 GB of memory for my ~10 GB compressed model.tar.gz it worked.

**Comment by seth814** [comment]
Ran more tests today. Upon looking at cloud watch metrics, it was likely insufficient disk space. My 10 GB model failed at ml.r5.xlarge but worked with ml.r5d.xlarge. Memory was under 50% with disk space being about 12%. Just put a d after the instance type you want and it will probably work.
