### ISSUE TITLE
Error running black-check locally

### ISSUE THREAD

**Issue by imujjwal96** [aws/sagemaker-python-sdk#896]
Getting the following trace:

    (tensorflow_p36) sh-4.2$ tox -e black-check
    GLOB sdist-make: /home/ec2-user/SageMaker/sagemaker-python-sdk/setup.py
    black-check create: /home/ec2-user/SageMaker/sagemaker-python-sdk/.tox/black-check
    black-check installdeps: black==19.3b0
    ERROR: invocation failed (exit code 1), logfile: /home/ec2-user/SageMaker/sagemaker-python-sdk/.tox/black-check/log/black-check-1.log
    ======================================================== log start ========================================================
    /home/ec2-user/SageMaker/sagemaker-python-sdk/.tox/black-check/bin/python: No module named pip

    ========================================================= log end =========================================================
    ERROR: could not install deps [black==19.3b0]; v = InvocationError('/home/ec2-user/SageMaker/sagemaker-python-sdk/.tox/black-check/bin/python -m pip install black==19.3b0', 1)
    _________________________________________________________ summary _________________________________________________________
    ERROR:   black-check: could not install deps [black==19.3b0]; v = InvocationError('/home/ec2-user/SageMaker/sagemaker-python-sdk/.tox/black-check/bin/python -m pip install black==19.3b0', 1)

 - on a SageMaker Notebook instance.
 - v1.31.1.dev0

**Comment by icywang86rui** [comment]
Not sure why would it complain about not having pip. I just tried running 'pip install black==19.3b0' on a SM notebook instance in the terminal. @imujjwal96 does running pip directly work for you? Did you modify the notebook instance at all?

**Comment by imujjwal96** [comment]
the pip install command worked via the terminal. Maybe something broke while installing tox. A fresh clone of the repository worked.
