### ISSUE TITLE
support requirements.txt in TF serving

### ISSUE THREAD

**Issue by chinazm** [aws/sagemaker-python-sdk#91]
Do you support customized packages (installing dependences) in serving mode?

**Comment by chinazm** [comment]
Sorry I may not make the question clear. When do the training, you can specify the requirements_file, in Tensorflow. However, when you deploy the model for serving, estimator.deploy(initial_instance_count=1, instance_type='ml.c4.xlarge'), I don't think there is a requirements.txt to be deployed in the endpoint container...

Thank you!

**Comment by andremoeller** [comment]
Hi @chinazm,

The `requirements.txt` file should work in this hosting case, but it seems from the other issue that it isn't working for your case. We're looking into this now. Thanks!

**Comment by JohnCalhoun** [comment]
i was able to get around this by adding this code before the relavent imports:

```python
try:
    from pip import main as pipmain
except:
    from pip._internal import main as pipmain
requirements=os.path.dirname(__file__)
pipmain(['install', "--upgrade", "pip"])
pipmain(['install', "-r","requirements"])
```
change `requirements` to point to your requirements file
