### ISSUE TITLE
Local mode(train and predict) for DeepAR model/

### ISSUE THREAD

**Issue by jguo16** [aws/sagemaker-python-sdk#913]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: DeepAR
- **Framework Version**:
- **Python Version**:
- **CPU or GPU**: CPU
- **Python SDK Version**:
- **Are you using a custom image**: No

### Describe the problem
I saw in the code there's 'local' mode for train, but when I try it, it still says that 

> 
ClientError: An error occurred (ValidationException) when calling the CreateTrainingJob operation: 1 validation error detected: Value 'local' at 'resourceConfig.instanceType' failed to satisfy constraint: Member must satisfy enum value set: [ml.p2.xlarge, ml.m5.4xlarge, ml.m4.16xlarge, ml.p3.16xlarge, ml.m5.large, ml.p2.16xlarge, ml.c4.2xlarge, ml.c5.2xlarge, ml.c4.4xlarge, ml.c5.4xlarge, ml.c4.8xlarge, ml.c5.9xlarge, ml.c5.xlarge, ml.c4.xlarge, ml.c5.18xlarge, ml.p3.2xlarge, ml.m5.xlarge, ml.m4.10xlarge, ml.m5.12xlarge, ml.m4.xlarge, ml.m5.24xlarge, ml.m4.2xlarge, ml.p2.8xlarge, ml.m5.2xlarge, ml.p3.8xlarge, ml.m4.4xlarge]
> 
So how can I totally train and predict locally?  I also found this instruction, https://aws.amazon.com/blogs/machine-learning/use-the-amazon-sagemaker-local-mode-to-train-on-your-notebook-instance/, so it shows the possibility to run locally? But for our case, what can goes wrong there? 

Thanks

### Minimal repro / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:

**Comment by ChuyangDeng** [comment]
Hi @jguo16,

Local mode is only supported for TensorFlow, MXNet, Chainer, PyTorch, and Scikit-Learn. For DeepAR, I don't think we have local mode support for that, please see the documentation here: https://sagemaker.readthedocs.io/en/stable/overview.html#local-mode

So unfortunately, you won't be able to use local mode for training in this case.
