### ISSUE TITLE
PipelineModel deploy method cannot find update_endpoint argument

### ISSUE THREAD

**Issue by markpurser** [aws/sagemaker-python-sdk#963]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**:
SKLearn with kNN
- **Framework Version**:
- **Python Version**:
Python 3
- **CPU or GPU**:
CPU
- **Python SDK Version**:
- **Are you using a custom image**:
No

### Describe the problem
I want to update an endpoint that already exists when deploying from a PipelineModel. The update_endpoint flag is supported on Estimators.deploy but not on PipelineModel.deploy

### Minimal repro / logs
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-116-1bc40bd315b2> in <module>()
     22                 instance_type='ml.t2.medium',
     23                 endpoint_name=endpoint_name,
---> 24                 update_endpoint=True)

TypeError: deploy() got an unexpected keyword argument 'update_endpoint'

- **Exact command to reproduce**:
model_name = 'inference-pipeline-' + timestamp_prefix
endpoint_name = 'sagemaker-ep'
sm_model = PipelineModel(
    name=model_name, 
    role=role, 
    models=[
        sklearn_preprocessor_model, 
        sklearn_estimator_model])

sm_model.deploy(initial_instance_count=1,
                instance_type='ml.t2.medium',
                endpoint_name=endpoint_name,
                update_endpoint=True)

**Comment by knakad** [comment]
@markpurser 
Hi Mark!
There was a separate issue blocking this, which I was able to resolve earlier this week.
Ujjwal beat me to the actual update_endpoint fix, which he pushed just a minute ago.
(Thanks Ujjwal!)

This'll be automatically released to PyPi within the next day or so (1.36.5) =)

**Comment by knakad** [comment]
I'm going to go ahead and keep this issue open until the release is available for consumption.

**Comment by knakad** [comment]
I triggered a release for this earlier this morning: https://github.com/aws/sagemaker-python-sdk/releases/tag/v1.37.0

Thanks again for reaching out and pointing this out to us!
