### ISSUE TITLE
SKLearn-based Estimator.fit() didn't pass the 'train' input to the Training instance

### ISSUE THREAD

**Issue by iamyaoxi** [aws/sagemaker-python-sdk#988]
Please fill out the form below.

### System Information
- **Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans)**: SKLearn
- **Framework Version**: SageMaker default (I think should be latest)
- **Python Version**: 3

### Describe the problem
SK-Learn based Estimator.fit() didn't pass the 'train' input to the Training instance.
[I've asked the question on StackOverflow](https://stackoverflow.com/questions/57522553/sagemaker-estimator-fit-didnt-pass-the-train-input-to-the-training-instance), do you think it might be a bug?

**Comment by ChoiByungWook** [comment]
Hello @iamyaoxi,

Thanks for bringing this up to our attention.

When running training jobs in SageMaker the S3 URL containing your training data provided ends up being copied into the docker container (aka training job) from the specified url. Thus the environment variable SM_CHANNEL_TRAIN is pointing to the local path of the training data that was copied from the S3 URL provided.

https://docs.aws.amazon.com/sagemaker/latest/dg/API_CreateTrainingJob.html#SageMaker-CreateTrainingJob-request-InputDataConfig

**Comment by iamyaoxi** [comment]
Thank you very much for clarification.
