### ISSUE TITLE
Misleading documentation for transformer accept parameter

### ISSUE THREAD

**Issue by vanoudh** [aws/sagemaker-python-sdk#994]
https://github.com/aws/sagemaker-python-sdk/blob/ee53bd47b54a8319d0619e2a28e51c914b123a8d/src/sagemaker/estimator.py#L688

Current documentation:

accept (str) – The content type accepted by the endpoint deployed during the transform job.

This is misleading, the accept header is passed in the request, to ask for a particular response format. Proposed documentation:

accept(str) - The accept header passed by the client to the inference endpoint. If it is supported by the endpoint it will be the format of the batch transform output.

**Comment by laurenyu** [comment]
@vanoudh thanks for the suggestion! I've opened a PR to address this: https://github.com/aws/sagemaker-python-sdk/pull/1017

**Comment by laurenyu** [comment]
released as part of v1.38.6.
