### ISSUE TITLE
Feature proposal: running multiple jobs / describing jobs

### ISSUE THREAD

**Issue by andremoeller** [aws/sagemaker-python-sdk#999]
Please fill out the form below.

### Describe the problem

Right now, there's no easy way to run multiple jobs, and then to wait for them, or to describe them during or once they're terminated.

For example: I can run a job, then run another job, and attach to the first job, but that ends up streaming logs from the first job, and I'll have to attach to the other job (creating another Estimator):
```
estimator.fit({'train': 's3://path/to/training/data'}, wait=False)
job_1 = estimator.latest_training_job
estimator.fit({'train': 's3://path/to/training/data'}, wait=False)
job_2 = estimator.latest_training_job
job_2.wait(logs=false)

# This currently always streams log and creates an estimator
Estimator.attach(job_1)

# Afterwards, I can't describe my jobs without using lower level constructs.
```

### Proposal for solution

My proposal is for `Estimator`, `Transformer`, and `HyperparameterTuner` to keep lists of jobs they've run, and for each job to be able to "Describe" which calls that job's `Describe` method, and returns a dictionary:

```
estimator.fit({'train': 's3://path/to/training/data'}, wait=False)
estimator.fit({'train': 's3://path/to/other/training/data'}, wait=False)
for job in estimator.training_jobs:
    job.wait(logs=False)
for job in estimator.training_jobs:
    print(job.describe())
```
This solves the problems above:
1. I can wait for multiple jobs to complete
2. I can get entire job state (such as status, time finished, input / output locations for reference later in code) from each job, during or after termination.
3. I don't end up creating another estimator to track completion
4. I don't inadvertently stream logs (from `attach` call)

This would requires two changes:

1. `describe` method added to `_TrainingJob`, etc.
2. `training_jobs`, `transform_jobs`, `tuning_jobs` members added to Estimator, etc. Whenever `fit` or `transform` are called, a job is appended to this list. When `Estimator.attach` is called, a new estimator is returned with just the latest training job in this list.

Thoughts / feedback on this proposal are welcome. Thanks!

**Comment by laurenyu** [comment]
this is now done.
